### ISSUE TITLE
Crash when start composing mail with account not fully created

### ISSUE THREAD

**Issue by totolanister** [thunderbird/thunderbird-android#4797] opened 2020-05-29 12:56 UTC
### Expected behavior
No crash and no ghost account

### Actual behavior
The app keep not fully created account, and this state could lead to crash

### Steps to reproduce
1. In screen Add account, enter the credentials and click next
2. Quit the app during creation
3. Reopen the app
4. Now there is a ghost account
5. Try to send a mail
=> crash

[k-9.txt](https://github.com/k9mail/k-9/files/4716411/k-9.txt)

I add a log at beggining of actionCompose method with parameters
As the exception is ActivityNotFoundException, I check that with account complete there is no crash.

### Environment
K-9 Mail version: 5.715 debug

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by GNUDimarik** [comment] 2020-09-22 12:10
That's exactly what I reproduced in [#4058](https://github.com/k9mail/k-9/issues/4058) after settings import but I didn't enter the password there because app didn't ask me

**Comment by cketti** [comment] 2021-02-22 13:06
This should be fixed in 5.730

**Closed by cketti** 2021-02-22 13:06 UTC
