### ISSUE TITLE
Unified Drafts folder

### ISSUE THREAD

**Issue by xandro0777** [thunderbird/thunderbird-android#6407] opened 2022-10-18 20:48 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.202

### Problem you are trying to solve

In my configuration there are 2-3 draft folders per account and of course several accounts. Happened to me recently that I "lost" a draft and found it two days later.

Also should be possible to find drafts in all accounts by search function but this does not seem to work?

### Suggested solution

Provide the option to show all drafts from all accounts in a unified folder. 

This seems to be a special case of https://github.com/thundernest/k-9/issues/4603 but may deserve special consideration.

**Comment by ivnmad** [comment] 2023-11-13 23:06
https://github.com/thunderbird/thunderbird-android/issues/6407

**Comment by cketti** [comment] 2024-06-17 10:00
We'll be tracking this as part of #6596.

Duplicate of #6596

**Closed by cketti** 2024-06-17 10:00 UTC
Labels: type: enhancement
