### ISSUE TITLE
Wrapped time periods do not work

### ISSUE THREAD

**Issue by ProfPh** [thunderbird/thunderbird-android#2572] opened 2017-06-07 21:40 UTC
### Expected behavior
Disable notifications checked in settings so notifications should be disabled during Quiet Time

### Actual behavior
Quiet Time set to an inclusive period like 02:00-01:59 (expected 23 hours 59 minutes of quiet time) does not disable notifications during this period

### Steps to reproduce
1. Set Quiet Time between 02:00-01:59

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

**Comment by philipwhiuk** [comment] 2017-06-08 08:10
I doubt we support wrapped time periods. We should probably look at that.

But if you just want to disable them all, Android has ways to do that.

**Comment by lbdroid** [comment] 2017-06-08 17:54
That's a non-feature anyway, since it can be accomplished through Android settings instead.
Go to system settings --> Sound --> Do not disturb --> Automatic rules, also Block visual disturbances.

**Comment by ProfPh** [comment] 2017-06-08 18:37
@philipwhiuk @lbdroid Yes, the issue is the wrapped time periods. I know I can disable it completely using Android but I gave an extreme example in place of a quiet time of 02:00-00:00 for example.

**Comment by philipwhiuk** [comment] 2017-06-10 14:40
Renamed issue to address what we should actually try and fix here.

**Comment by philipwhiuk** [comment] 2018-01-21 20:15
Huh, apparently this wasn't a regression @cketti.

Anyway closing, fixed in e9d90b1e75d14f4dc7c48da234287141e30e389e

**Closed by philipwhiuk** 2018-01-21 20:15 UTC
