### ISSUE TITLE
Automatically import existing email addresses / contacts from existing email folders  (like FairEmail does)

### ISSUE THREAD

**Issue by avatar1024** [thunderbird/thunderbird-android#7315] opened 2023-11-01 20:18 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

all

### Problem you are trying to solve

After a fresh install of K-9 Mail, K-9 Mail only finds email addresses from the phone contact (when typing the "To" field).

In comparison, FairEmail on a fresh install automatically finds any contact I have ever emailed (or received email from depending on the setting I choose) when I start writing a new email. I don't know how this is done, I guess it must scan my email folders and create a database of email addresses, but this is SO HELPFUL as it is very common not to have everyone you want to email as a phone contact.

This would solve a major usability issue (certainly why I stopped using K-9 Mail) and common complain people have about not able to import contact easily in K-9 Mail. Also a good stop gap until syncing Thunderbird contact to K-9 Mail is possible (although even when this is possible, it will only be useful for those who use thunderbird already).

### Suggested solution

Study how FairEmail does it, or ask the creator and reproduce the mechanism in K-9 Mail.

See below the settings in FairEmail related to this. Though just to be clear, it does add only contact you have emailed or received email from using the FairEmail app, but those already in your mail folders (inbox, sent, etc.).

![Screenshot_2023-11-01-20-24-18-57_208213728eb6a732b32bf625e881f060](https://github.com/thunderbird/thunderbird-android/assets/18719956/8c1a6011-b67f-4eb9-ba69-e91e4265ffc6)

**Comment by cketti** [comment] 2024-01-03 14:57
Duplicate of #1006

**Closed by cketti** 2024-01-03 14:57 UTC
Labels: enhancement, unconfirmed
