### ISSUE TITLE
Make star/favourite button easier to hit.

### ISSUE THREAD

**Issue by Glitchy-Tozier** [thunderbird/thunderbird-android#4942] opened 2020-09-11 09:28 UTC
**Describe the bug**
Currently, it's very common to accidentally scroll down when trying to star an email in the email-list. This is very annoying and could easily be prevented by either changing the scroll-bar-"hitbox" or by enlarging/moving the star-"hitbox"

**Expected behavior**
Make consistent staring and un-staring possible.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.717
 - Android version: 10
 - Device: Samsung Galaxy S9 (curved screen might play a role)

**Comment by cketti** [comment] 2020-09-11 13:40
Duplicate of #894

**Closed by cketti** 2020-09-11 13:40 UTC
