### ISSUE TITLE
Missing mails in Inbox of IMAP account

### ISSUE THREAD

**Issue by SinTan1729** [thunderbird/thunderbird-android#4631] opened 2020-03-27 19:31 UTC
My university's email used to work perfectly with K-9 but from this morning, many mails are missing. The mails appear perfectly on other mailing apps (FairEmail, BlueMail on Android, MailSpring on Linux).
I cannot find the missing mails on other folders either.

K-9 Mail version : 5.708 (beta)
Android version : 10
Account type : IMAP

**Comment by justinacolmena** [comment] 2020-03-27 22:20
I had that problem, too, with KDE mail --- it was this morning --- all the mail went missing from my POP account on KDE desktop, but I didn't notice anything on K-9 via IMAP.

KDE on my Linux laptop, after an upgrade, downloaded the mails from (my, in effect, personal) Dovecot server all over again, so nothing appears to have been lost permanently. I changed the password as a precaution, and also moved K-9 mail to the Samsung Secure Folder on my phone, as I use OpenKeychain app, which tends to be started up by malicious websites on Google Chrome, which I left out of the secure folder.

On March 27, 2020 11:32:20 AM AKDT, SinTan1729 <notifications@github.com> wrote:
>My university's email used to work perfectly with K-9 but from this
>morning, many mails are missing. The mails appear perfectly on other
>mailing apps (FairEmail, BlueMail on Android, MailSpring on Linux).
>I cannot find the missing mails on other folders either.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/4631

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by SinTan1729** [comment] 2020-03-28 06:43
If I may add, it also showed me duplicate folders in the left panel. There were two inboxes and two outboxes.

**Comment by cketti** [comment] 2020-03-31 12:51
Please record a debug log while trying to refresh the Inbox. See https://github.com/k9mail/k-9/wiki/LoggingErrors

Currently you'll have to manually refresh the list of folders if it changes on the server. Go to "manage folders", then select "refresh folder list" from the menu.

**Comment by Keefaetana** [comment] 2020-04-06 07:45
I'm not the OP, but I'm having similar issues. I can't seem to get K-9 to fetch my e-mails, even though I've triple checked my settings. Even tried un- and re-installing the app, but to no avail. Just now I caught the debug log (link in the bottom). There definitely seems to be an issue with the app itself.

The log was made using K-9 version 5.707.

https://pastebin.com/JK2XF0nh

**Comment by SinTan1729** [comment] 2020-04-06 11:38
> Please record a debug log while trying to refresh the Inbox. See https://github.com/k9mail/k-9/wiki/LoggingErrors
> 
> Currently you'll have to manually refresh the list of folders if it changes on the server. Go to "manage folders", then select "refresh folder list" from the menu.

Here is the requested log. Also, the duplicated folder issue is fixed after a reinstall.

[k9-log.txt](https://github.com/k9mail/k-9/files/4438093/k9-log.txt)

**Comment by cketti** [comment] 2020-04-06 16:24
The log doesn't contain any anomalies. Your K-9 Mail seems to be configured to download the 50 latest messages. For K-9 Mail "latest" refers to the order in which messages were added to that folder. So if you copy older messages to a folder they will be fetched before newer messages that have been in that folder for a longer time. Could this be what's happening in your case? In that case the missing messages will show up if you increase the message sync window (e.g. by clicking "Load up to X more").

**Comment by SinTan1729** [comment] 2020-04-06 16:35
> The log doesn't contain any anomalies. Your K-9 Mail seems to be configured to download the 50 latest messages. For K-9 Mail "latest" refers to the order in which messages were added to that folder. So if you copy older messages to a folder they will be fetched before newer messages that have been in that folder for a longer time. Could this be what's happening in your case? In that case the missing messages will show up if you increase the message sync window (e.g. by clicking "Load up to X more").

Maybe yes. Is it possible to sort them by date received/sent? That's the needed behaviour, I would presume. All other mail apps do it that way.

**Comment by cketti** [comment] 2020-04-06 16:53
> Is it possible to sort them by date received/sent?

Messages are properly sorted locally. It's just that the app is not using the date when deciding which messages to download. This is tracked as #1642.

Can you please close this issue if the unexpected behavior of K-9 Mail explains what you are seeing.

**Closed** 2020-04-06 17:12 UTC
Labels: status: needs information
