### ISSUE TITLE
Add option to open eml files from file managers

### ISSUE THREAD

**Issue by KopfKrieg** [thunderbird/thunderbird-android#7730] opened 2024-03-20 16:41 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.801

### Problem you are trying to solve

I sometimes get eml-files through other apps, sometimes as attachements from e-mails.

I'd like to be able to open them, especially from within file managers.

### Suggested solution

Implement eml viewer (I found a few issues for this, and it seems this is already implemented (?)), and add the option to open eml files through file managers (add link handlers)

**Comment by cketti** [comment] 2024-03-25 12:48
Duplicate of #733

**Closed by cketti** 2024-03-25 12:48 UTC
Labels: type: enhancement, unconfirmed
