### ISSUE TITLE
non-ASCII characters break link detection

### ISSUE THREAD

**Issue by Flexmaen** [thunderbird/thunderbird-android#3188] opened 2018-02-19 10:38 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Full link that appears in a text-only mail should be recognized.

### Actual behavior
Link will break with the umlaut "ö".

### Steps to reproduce
1.  Copy, paste and mail [this link](https://www.amazon.de/durchsichtige-abl%C3%B6sbare-Keysies-Aufkleber-Klavier-Keyboardtastatur/dp/B00XUDF6GW/ref=sr_1_6?rps=1&ie=UTF8&qid=1518650203&sr=8-6&keywords=keyboard+st%C3%A4nder&refinements=p_76%3A419122031).
2. Receive the mail and check link in K9
3. Link will be broken.

### Environment
K-9 Mail version: 5.403

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![k9-2](https://user-images.githubusercontent.com/6330276/36373739-5e3d95a2-1569-11e8-83c0-1f1732b21115.png)

**Comment by cketti** [comment] 2022-09-09 17:46
Duplicate of #3188

**Closed by cketti** 2022-09-09 17:46 UTC
Labels: type: enhancement
