### ISSUE TITLE
Add support for setting account images (avatar)

### ISSUE THREAD

**Issue by cketti** [thunderbird/thunderbird-android#5509] opened 2021-08-03 14:17 UTC
Some people add all of their email addresses to one system contact. And so all of their accounts in K-9 Mail show the same image.

To improve this situation we should allow users to pick what to display as the account image. I'm thinking we could have these options:
- contact picture (the current behavior)
- custom image (requires an image picker and probably a cropping tool; image should probably be included when settings are exported)
- no image (displays the placeholder image we currently use)

Especially the *custom image* option is probably quite a bit of work. So I suggest we start with just supporting the *contact picture* and *no image* option.

**Comment by protist** [comment] 2021-08-03 22:59
As per the linked closed issue, another option would be to use account colours as indicators, as per the [previous version of K-9](https://net2.com/wp-content/uploads/2020/06/word-image-147-768x667.jpeg).

@cketti what is the "no image" placeholder image? Presumably all accounts wouldn't still look identical?

**Comment by cketti** [comment] 2021-08-03 23:07
> what is the "no image" placeholder image?

<img src="https://user-images.githubusercontent.com/218061/128097427-787e477e-09ce-48c9-a58a-5e07c6a133d0.png" alt="k9mail_account_list_placeholder_images" width=300>

**Comment by protist** [comment] 2021-08-03 23:14
@cketti Ah okay, yes that would be a functional solution. Obviously a customisable picture would be best, but this seems totally workable.

It would also mean I don't have to see my ugly face every time I switch accounts! 😖 Thank you for writing up this issue and proposal.

**Comment by AndySchroder** [comment] 2021-08-05 03:39
Although I think https://github.com/k9mail/k-9/issues/5452 should definitely be fixed, this proposed enhancement does reduce the brainpower required to navigate around all the required new taps that https://github.com/k9mail/k-9/issues/5452 introduces to the user.

**Comment by seyfeb** [comment] 2022-11-10 15:07
I support manually setting avatars on a per account basis. I just can't remember which color I assigned which account. It might be somewhat better if I were able to set the account color to a Corporate Design theme color of an email provider, but such specific colors are obviously not available in the simple color picker for the account color.

**Comment by pserwylo** [comment] 2023-08-13 23:00
I would love to select a custom icon for each account. I had no desire for a profile photo to be shown, but rather wish for a company icon.

I realise everyone's usage is different, but for me - if I have three accounts, then it is because one is a personal account, and two are work accounts. Instead of having three different photos of my ugly face when I open the account selector, I'd much rather see a GMail icon for my personal GMail account, and the icon of each company for my work accounts.

After reading through the issue tracker, I now realise I can achieve this by creating separate contacts in my system and assign an appropriate avatar. With this setup I am much happier with the k9 user experience when switching accounts now, though it felt a little hacky.

**Comment by thomasmstein** [comment] 2024-01-08 01:20
While this issue has been around for a while, I still think it would be a great addition allowing to use an alternative image for an account especially useful if multiple email addresses are related to one contact. There is of course the workaround of creating multiple contacts for each email one. One could also add provider specific account images if preferred as @pserwylo mentioned.
Thanks

**Comment by sebbu2** [comment] 2024-11-07 11:13
There seems to be a regression in K-9 Mail 8, i don't see my avatar anymore when chhosing the email account, only the 2 letters

**Comment by Fmstrat** [comment] 2024-11-10 16:03
@cketti IMO this should be filed as a bug: "Account images lost after upgrade"

**Comment by kewisch** [comment] 2024-11-15 21:48
Duplicate of #8238 

While newer, we redesigned the drawer, so that issue contains more up to date screenshots.

**Closed by kewisch** 2024-11-15 21:48 UTC
Labels: type: enhancement
