### ISSUE TITLE
 an IllegalStateException 'Couldn't get domain from email address' in account setup

### ISSUE THREAD

**Issue by 2021QTester** [thunderbird/thunderbird-android#5374] opened 2021-06-30 13:09 UTC
**Describe the bug**
Sorry for my second issue, but I did find another crash caused by an IllegalStateException 'Couldn't get domain from email address'. As I used the automated testing tools, the value set to email account and password are random and I did not know them exactly. Immediately after I click on 'MANUAL SETUP' or 'NEXT' to continue, the error occured and the app crashed.

**To Reproduce**
1. Go to page 'Set up a new account'
2. Edit the email address and password, both are set to random values
3. Click 'MANUAL SETUP' and enter page 'Account type'
4. Click 'IMAP' and the app crashes

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android version: 6.0
 - Device: x86 Android emulator provided by Google
 - Account type: IMAP

**Logs**
06-26 20:26:47.430 24599 24599 E AndroidRuntime: FATAL EXCEPTION: main
06-26 20:26:47.430 24599 24599 E AndroidRuntime: Process: com.fsck.k9, PID: 24599
06-26 20:26:47.430 24599 24599 E AndroidRuntime: java.lang.IllegalStateException: Couldn't get domain from email address
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupAccountType.setupStoreAndSmtpTransport(AccountSetupAccountType.kt:66)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupAccountType.setupAccount(AccountSetupAccountType.kt:60)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupAccountType.setupPop3Account(AccountSetupAccountType.kt:52)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupAccountType.access$setupPop3Account(AccountSetupAccountType.kt:24)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.fsck.k9.activity.setup.AccountSetupAccountType$onCreate$1.onClick(AccountSetupAccountType.kt:39)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.view.View.performClick(View.java:5198)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.widget.TextView.performAccessibilityActionInternal(TextView.java:8999)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.view.View.performAccessibilityAction(View.java:8883)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.performAccessibilityActionUiThread(AccessibilityInteractionController.java:668)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.view.AccessibilityInteractionController.-wrap6(AccessibilityInteractionController.java)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.view.AccessibilityInteractionController$PrivateHandler.handleMessage(AccessibilityInteractionController.java:1194)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-26 20:26:47.430 24599 24599 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by cketti** [comment] 2021-06-30 14:27
Does your tool take the enabled state of buttons into account? The "Next" and "Manual setup" buttons in the "Set up a new account" screen should not be enabled unless a valid email address has been entered.

Have you been able to manually reproduce the error?

**Comment by 2021QTester** [comment] 2021-07-01 06:17
Yes, my tool can recognize that, and it cannot click on the Button "Next" and "Manual setup" when the password and email address are empty, or no '@' in email address.
I tried to reproduce the error, manually and via the testing framework 'uiautomator' my tool uses, but both of them failed. From this, I guess there may be a special app state where Button "Next" and "Manual setup" is enabled even though the inputs are illegal, however, I don't know how to get into this state.

**Comment by cketti** [comment] 2021-07-29 15:31
Closing because there are no instructions on how to reproduce the issue. You're welcome to open a new issue once you can provide the instructions.

**Closed by cketti** 2021-07-29 15:31 UTC
