### ISSUE TITLE
Confusing UI when “Reply after quoted text” enabled

### ISSUE THREAD

**Issue by shtrom** [thunderbird/thunderbird-android#6529] opened 2022-12-12 02:51 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

Stock Android 13

### Device model

Pixel 6a

### Steps to reproduce

1. In Settings/[Account]/Sending mail, set Reply after quoted text to true
2. In the Inbox, open an email, and Reply to it

### Expected behavior

The `Message text` input box is below the quoted message, and above the signature.

### Actual behavior

The `Message text` input box is displayed above the quoted message being replied to

Note that this is a UI-only problem. The contents of the input box is properly added below the quoted message when sending, as configured. However seeing response and quoted messages in a different order when composing the email is confusing (and I have more than once concluded an email with “Hi, how are you going?”).

### Logs

None relevant.

**Comment by ByteHamster** [comment] 2022-12-13 06:56
Duplicate of #2212

**Closed by ByteHamster** 2022-12-13 06:56 UTC
