### ISSUE TITLE
German umlaute in QR code are shown as � in TB for Android

### ISSUE THREAD

**Issue by nkgm-bs** [thunderbird/thunderbird-android#8472] opened 2024-11-02 09:23 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0, 8.0b5

### Where did you get the app from?

Other

### Android version

10

### Device model

Moto G8

### Steps to reproduce

- Have TB accounts with german umlaute in the display name
- Export to Mobile
- QR code scanned with a scanner app shows correct german umlaute
- Import into TB for Android, version 8.0 and 8.0b5

### Expected behavior

TB for Android should show german umlauts

### Actual behavior

TB for Android shows � instead of german umlauts
Might be related to issue #8468

**Comment by cketti** [comment] 2024-11-03 10:41
Duplicate of #8444

**Closed by cketti** 2024-11-03 10:41 UTC
