### ISSUE TITLE
§ in password not valid

### ISSUE THREAD

**Issue by droogi** [thunderbird/thunderbird-android#3532] opened 2018-07-27 06:27 UTC
### Expected behavior
After changing Password to new one containing §, Login is not possible anymore

### Actual behavior
wrong password

### Steps to reproduce
Change Password of existing account to new one containing Special sign  §

### Environment
K-9 Mail version:

Android version:

Outlook.office.com

**Comment by TJL73** [comment] 2019-05-16 07:21
Same error for:  à, è, é, ì, ò, ù  and/or  ^  in password.

**Comment by i-need-to-tell-you-something** [comment] 2019-08-27 15:03
Does it show an error when entering such symbols in password field with a popup or does it fail silently - i.e. just doesn't work without showing or saying anything?
I use a lot of special symbols in my passwords and don't know if any of them are causing a problem or if it is something else entirely. Thanks.

**Comment by i-need-to-tell-you-something** [comment] 2019-08-27 15:19
Duplicate of #1015

**Comment by schlagi123** [comment] 2019-12-15 15:52
I tryed to reproduce the bug, but I couldn't it.
I created a microsoft account and signs §, à, è, é, ì, ò and ù are not allowed for a password, so that I can not set a password with this signes. The ^ sign is allowed and I could use it with K9 successfully.
I also looked at Google accounts and Mailbox.org Accounts, but all of them do only support default ASCII signs or a subset of that for passwords, so that I had the same result.

In my opinion about this ticket is, that it is not reproducable and can be closed.

If I'm wrong correct me.

**Comment by i-need-to-tell-you-something** [comment] 2019-12-15 19:06
> In my opinion this ticket is not reproducible and can be closed.

I think before closing someone should *at least* verify a password working with `§`. But better if testing all of ` à è é ì ò ù ^`. The fact that Google and Microsoft don't permit those symbols doesn't mean the symbols shouldn't work elsewhere.

**Comment by schlagi123** [comment] 2019-12-15 20:18
I search long for a provider that allows these signs. With a web.de account I could set up the password `àèéìòù^Test` and it works.

**Closed** 2020-10-06 21:49 UTC
