### ISSUE TITLE
Failed synchronizing folder due to IllegalArgumentException: Unsupported character: �

### ISSUE THREAD

**Issue by mesonium** [thunderbird/thunderbird-android#6471] opened 2022-11-13 15:45 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

F-Droid

### Android version

Android 13 (CalyxOS)

### Device model

Google Pixel 6a

### Steps to reproduce

1. Have a mail account setup
2. Fetch mails

### Expected behavior

New mails are fetched and displayed.

### Actual behavior

No mails are fetched respectively displayed.

### Logs

```
(...)
16:34:16.753 V/RealImapConnection( 5526): conn104338777<<<#null# [2839, FETCH, [UID, 8210, FLAGS, [], INTERNALDATE, 13-Nov-2022 12:58:44 +0100, RFC822.SIZE, 37481, BODY, [HEADER.FIELDS, [DATE, SUBJECT, FROM, CONTENT-TYPE, TO, CC, REPLY-TO, MESSAGE-ID, REFERENCES, IN-REPLY-TO, LIST-UNSUBSCRIBE, X-K9MAIL-IDENTITY, CHAT-VERSION]], Date: Sun, 13 Nov 2022 11:58:42 +0000
16:34:16.753 V/RealImapConnection( 5526): From: "<snip> (no reply)" <snip>
16:34:16.753 V/RealImapConnection( 5526): To: <snip>
16:34:16.753 V/RealImapConnection( 5526): Message-ID: <snip>
16:34:16.753 V/RealImapConnection( 5526): Subject: <snip>
16:34:16.753 V/RealImapConnection( 5526): Content-Type: multipart/mixed; 
16:34:16.753 V/RealImapConnection( 5526):         boundary="----=_Part_10517616_1401553352.1668340722534"
16:34:16.753 V/RealImapConnection( 5526): 
16:34:16.753 V/RealImapConnection( 5526): ]]
16:34:16.754 V/RealImapConnection( 5526): conn104338777<<<#7# [OK, Fetch completed.]
16:34:16.754 D/ImapSync( 5526): SYNC: Synced unsynced messages for folder INBOX
16:34:16.754 D/ImapSync( 5526): SYNC: Have 49 large messages and 0 small messages out of 49 unsynced messages
16:34:16.754 D/ImapSync( 5526): SYNC: Fetching 0 small messages for folder INBOX
16:34:16.754 D/ImapSync( 5526): SYNC: Done fetching small messages for folder INBOX
16:34:16.754 D/ImapSync( 5526): SYNC: Fetching large messages for folder INBOX
16:34:16.754 V/RealImapConnection( 5526): conn104338777>>> 8 UID FETCH 8157,8159,8160,8161,8162,8163,8164,8166,8167,8168,8169,8170,8171,8173,8174,8175,8177,8178,8179,8180,8181,8182,8183,8184,8185,8186,8187,8188,8189,8190,8191,8192,8193,8194,8195,8196,8197,8198,8199,8201,8202,8203,8204,8205,8206,8207,8208,8209,8210 (UID BODYSTRUCTURE)
16:34:16.800 V/RealImapConnection( 5526): conn104338777<<<#null# [2788, FETCH, [UID, 8157, BODYSTRUCTURE, [[text, plain, [charset, ISO-8859-1], NIL, NIL, quoted-printable, 2064, 77, NIL, NIL, NIL, NIL], [application, pdf, [name, <snip>], NIL, NIL, base64, 101624, NIL, [attachment, [filename, <snip>]], NIL, NIL], [application, pdf, [name, <snip>], NIL, NIL, base64, 288258, NIL, [attachment, [filename, <snip>]], NIL, NIL], mixed, [boundary, ----=_Part_466_798310141.1667657720405], NIL, NIL, NIL]]]
16:34:16.801 E/ImapSync( 5526): synchronizeMailbox
16:34:16.801 E/ImapSync( 5526): java.lang.IllegalArgumentException: Unsupported character: �
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.mail.internet.MimeParameterEncoder.quoted(MimeParameterEncoder.kt:161)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:894)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.mail.store.imap.RealImapFolder.parseBodyStructure(RealImapFolder.kt:830)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.mail.store.imap.RealImapFolder.handleFetchResponse(RealImapFolder.kt:748)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.mail.store.imap.RealImapFolder.fetch(RealImapFolder.kt:599)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.backend.imap.ImapSync.downloadLargeMessages(ImapSync.kt:561)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.backend.imap.ImapSync.downloadMessages(ImapSync.kt:367)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:198)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:644)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:584)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:556)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:223)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:109)
16:34:16.801 E/ImapSync( 5526):   at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:164)
16:34:16.801 E/ImapSync( 5526):   at java.lang.Thread.run(Thread.java:1012)
16:34:16.807 E/ImapSync( 5526): Failed synchronizing folder <snip>:INBOX @ So. Nov. 13 16:34:16 MEZ 2022
16:34:16.808 I/MessagingController( 5526):  Command 'synchronizeMailbox' completed
16:34:16.808 I/MessagingController( 5526): Running command 'sendPendingMessages', seq = 51 (background priority)
16:34:16.811 I/MessagingController( 5526): Scanning Outbox folder for messages to send
16:34:16.811 V/MessagingController( 5526): Skipping sending message K9LOCAL:8feabc78-0442-434d-a2fc-aaefb44eec8d
16:34:16.814 I/MessagingController( 5526):  Command 'sendPendingMessages' completed
```

**Comment by cketti** [comment] 2022-11-13 22:02
Duplicate of #6291

**Closed by cketti** 2022-11-13 22:02 UTC
