### ISSUE TITLE
feature request: Please integrate support for S/MINE encryption and decryption

### ISSUE THREAD

**Issue by user4andre** [thunderbird/thunderbird-android#8133] opened 2024-09-10 17:11 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.804

### Problem you are trying to solve

no support now.

### Suggested solution

feature request: Please integrate support for S/MINE encryption and decryption

I cannot say whether this is already planned. I have searched for S/MINE in the issues, but found nothing.
The integrated PGP encryption is certainly the better or more free option for many people. However, many mail clients support S/MINE. Since S/MINE requires less preparatory initiative on the part of the recipient, a signed e-mail can be sent to practically anyone with S/MINE. I would therefore be very pleased if K9 Mail offered both encryption methods similar to Thunderbird for desktop computers.

### Screenshots / Drawings / Technical details

I consider signing, encryption and decryption as one feature, since only the entire package is usable together. Please split the tasks if this is useful for the implementation.

**Comment by mhf1998** [comment] 2024-09-17 17:00
Duplicate of https://github.com/thunderbird/thunderbird-android/issues/1003

**Comment by user4andre** [comment] 2024-10-11 21:21
yes it is.

**Closed** 2024-10-11 21:32 UTC
Labels: type: enhancement, unconfirmed
