### ISSUE TITLE
Screen flashes white

### ISSUE THREAD

**Issue by gitmatt19** [thunderbird/thunderbird-android#6057] opened 2022-05-03 02:04 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

F-Droid

### Android version

6

### Device model

Nexus 7

### Steps to reproduce

Start K9. IE touch the icon.

### Expected behavior

No flashing screen.

### Actual behavior

After upgrading to the latest version K9 started flashing a full white screen before bringing  up inbox.

Theme is set to Dark.

It looks like it starts to bring up a white theme, then stops before any messages come up and starts over and displays dark theme.

Has worked fine for years until this update.

**Comment by cketti** [comment] 2022-05-03 12:57
I can't reproduce this.

The startup animation is displayed by the system while the app is being launched. Android uses the "start theme" of the app for that. On Android versions prior to 9, K-9 Mail is using a theme with a black background as a start theme to avoid the situation you described.

Are you using a custom ROM that tries to do something clever regarding app themes?

**Comment by gitmatt19** [comment] 2022-05-04 02:01
Its rooted but no changes made to anything. Here is a poor video of it doing it

https://user-images.githubusercontent.com/17283802/166613920-e03e2643-09a5-4d79-8216-9e34c4187b5a.mp4

.

**Comment by johndoe71rus** [comment] 2022-06-06 10:25
can confirm behaviour
K-9 6.0000 (Playmarket)
Android 6.0.1
Asus Zenfone Max ZC550KL

**Comment by llevrel** [comment] 2022-08-24 16:56
Hi,

Sorry for the duplicate 6253. So: I confirm the behaviour in 6.301 from F-droid, on stock Android 8.1.0 (really stock, this is a noname device ;) ).

needs info : which?

**Comment by cketti** [comment] 2022-10-09 16:26
This was fixed in K-9 Mail 6.308

**Closed by cketti** 2022-10-09 16:26 UTC
Labels: status: needs information
