### ISSUE TITLE
opening message from widget broken (for non-first account)

### ISSUE THREAD

**Issue by JohaJung** [thunderbird/thunderbird-android#6535] opened 2022-12-21 15:16 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

7.0

### Device model

HUAWEI P9 lite (HWVNS-L31)

### Steps to reproduce

1. Configure at least three different mail accounts. On the main settings page, you can order them. In the following, I'll name them in this order: account 1, account 2, ..., account n.
2. Add the message list widget to the home screen.
3. Minimize the app while a message list of account X (X != 1) is open
4. From the widget, open a mail that belongs to account Y, where Y != X and Y != 1

### Expected behavior

The app opens showing the opened mail, after tapping the "back" button the messag list of this mail shows up and the list of account Y is visible in the sidebar.

### Actual behavior

The Inbox view of Account 1 shows up, with the sidebar listing the folders of account X.

### Logs

The log file was empty.

**Comment by cketti** [comment] 2023-01-19 12:15
Did you disable the Unified Inbox inside the app? *Settings → General settings → Display → Show Unified Inbox*

**Comment by JohaJung** [comment] 2023-01-19 13:20
> Did you disable the Unified Inbox inside the app? _Settings → General settings → Display → Show Unified Inbox_

Indeed, yes I have disabled this.

**Comment by cketti** [comment] 2023-01-19 13:59
The widget should work fine when that setting is enabled. 

Currently, it's not a high priority to make the widget work when *Show Unified Inbox* is disabled. 

Duplicate of #6590

**Closed by cketti** 2023-01-19 13:59 UTC
