### ISSUE TITLE
failed to import settings

### ISSUE THREAD

**Issue by ka223** [thunderbird/thunderbird-android#4022] opened 2019-04-16 08:50 UTC
I can not import my settings on K9 Mail (Version 5.6, gplay)

### Expected behavior
I can export my settings from version 5.6 and import them on version 5.6.

### Actual behavior
After selecting the account (import selection), an import failed message appears and nothing is imported. 

### Steps to reproduce
1. export backup from v5.6
2. import backup to v5.6
3. -> import failed message 

### Environment
K-9 Mail version:
Verson 5.6

Android version:
Export device: android 7.0
Import device: android 7.1

Account type: IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
... can not connect with adb now

**Comment by cketti** [comment] 2019-05-11 02:06
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ygoe** [comment] 2019-08-13 20:30
Same issue here. Getting the debug log is too complicated. Please just try yourself and you will see it doesn't work at all.

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment] 2020-04-16 15:10
### Expected behavior
Import settings and accounts successfully

### Actual behavior
Import failed

### Steps to reproduce
1. Select .k9s file in Android's DocumentsUI

### Environment
K-9 Mail version: 5.600

Android version: 10

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
```
[04-16 16:45:08.319 27548:27548 I/Accounts]
onActivityResult requestCode = 1, resultCode = -1, data = Intent { dat=content://com.android.externalstorage.documents/document/primary:Download/k9_settings_export_2020-04-16.k9s flg=0x1 }

[04-16 16:45:08.350 27548:27943 W/Accounts$ListImportCont]
Exception during export
com.fsck.k9.preferences.SettingsImportExportException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ﻿@1:2 in java.io.InputStreamReader@3c20502) 
	at com.fsck.k9.preferences.SettingsImporter.parseSettings(SettingsImporter.java:659)
	at com.fsck.k9.preferences.SettingsImporter.getImportStreamContents(SettingsImporter.java:116)
	at com.fsck.k9.activity.Accounts$ListImportContentsAsyncTask.doInBackground(Accounts.java:2124)
	at com.fsck.k9.activity.Accounts$ListImportContentsAsyncTask.doInBackground(Accounts.java:2101)
	at android.os.AsyncTask$3.call(AsyncTask.java:378)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:289)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ﻿@1:2 in java.io.InputStreamReader@3c20502) 
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:432)
	at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:313)
	at com.fsck.k9.preferences.SettingsImporter.parseSettings(SettingsImporter.java:650)
	... 9 more

[04-16 16:45:08.429 3501:22763 E/InputDispatcher]
Window handle Window{fdb043c u0 Importieren} has no registered input channel

[04-16 16:45:08.569 3501:3535 I/system_server]
NativeAlloc concurrent copying GC freed 368111(13MB) AllocSpace objects, 91(3452KB) LOS objects, 66% free, 21MB/65MB, paused 166us total 174.959ms

[04-16 16:45:08.585 3501:3537 W/System]
A resource failed to call release. 

[04-16 16:45:08.586 3501:3537 I/chatty]
uid=1000(system) FinalizerDaemon identical 4 lines

[04-16 16:45:08.586 3501:3537 W/System]
A resource failed to call release. 

[04-16 16:45:08.796 27920:27920 E/QTI_SDM_INFO]
[qti_rmnet_peripheral.c:758] qti_file_open():Could not open device file. Errno 2 error msg=No such file or directory
```

**Comment by cketti** [comment] 2020-04-16 15:21
@m54fjt6910tt3o948b1zi840oanas5uty4j3nq2 Can you attach the settings file here? Feel free to edit the file to redact information you don't want to share.

**Comment by m54fjt6910tt3o948b1zi840oanas5uty4j3nq2** [comment] 2020-04-20 09:29
@cketti I have exported the settings and accounts again, and I was able to successfully import them this time.

**Comment by cketti** [comment] 2020-04-20 09:34
Maybe there was a file corruption the first time. Closing this issue because it's not actionable.

**Closed by cketti** 2020-04-20 09:34 UTC
Labels: status: answered

**Comment by jimmiedave** [comment] 2026-01-13 23:05
Closed, and way old, I realize.

However, in forcing 5.6 to work on a new device, and having a similar problem, I found this:

lt/gt brackets in addresses in identities: `someguy <someguy@someaddress.com>` are allowed, work in k9, appear to export without complaint, and produces  validatable XML file. However, the lt/ft brackets read `&lt;` and `&gt;` in the file (instead of the proper `<` and `>`), and this causes the importer to choke and reject the entire account.

You can fix this problem by fixing the problematic identity lines in the .k9s file you exported. Open it with a text editor. Take out the plaintext name and the brackets. Save the file, and try and import again.

Hope this helps someone.
