### ISSUE TITLE
Version 5.800 crashes on Android 11, OnePlus 7T

### ISSUE THREAD

**Issue by Hoiss** [thunderbird/thunderbird-android#5442] opened 2021-07-25 19:27 UTC
Hi,

I have a problem after the new version 5.800 was automatically installed.
After the first start the database was updated and everything looked good, but I wanted to bring back the previous look by setting smaller font sizes.
So what I did was to set the font size for subjects to small I think. Afterwards nothing seemed to have changed and I quit K9 to start it again afterwards. It crashed and it now crashes every time I try to start it. (Even if I force quit from Android)
As soon as I press the icon I see the screen gets grey and disappears again.

Is there anything I can do to avoid the crash? I don't want to loose all the settings if i reinstall it completely...

**Comment by cketti** [comment] 2021-07-25 19:30
Reinstalling the app (and losing your data) is probably the fastest way to get it running again. You can record a debug log (see https://github.com/k9mail/k-9/wiki/LoggingErrors). That will give us a chance to find and fix the bug. But you won't be able to use the app before we release an update containing the fix.

**Comment by Hoiss** [comment] 2021-07-25 20:07
Yes the fastest way for sure, but it has some disadvantages.
I followed [https://k9mail.app/documentation/debugging.html](url) Step 3 and used adb on linux.
The output after using `./adb logcat -d --pid=xxxxx > k9-log.txt` is not much... Please see:

> --------- beginning of main
07-25 22:02:39.436 15878 15878 I libc    : SetHeapTaggingLevel: tag level set to 0
07-25 22:02:39.440 15878 15878 E com.fsck.k9: Unknown bits set in runtime_flags: 0x800000
07-25 22:02:39.445 15878 15878 E com.fsck.k9: Not starting debugger since process cannot load the jdwp agent.
07-25 22:02:39.462 15878 15878 D ApplicationLoaders: Returning zygote-cached class loader: /system/framework/android.test.base.jar
07-25 22:02:39.469 15878 15878 I Perf    : Connecting to perf service.
07-25 22:02:39.472 15878 15878 I com.fsck.k9: [GL_OOM] ClampGrowthLimit 536870912
07-25 22:02:39.473 15878 15878 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-25 22:02:39.473 15878 15878 D NetworkSecurityConfig: No Network Security Config specified, using platform default
07-25 22:02:39.491 15878 15878 E Config:Grabber:OnePlusFontConfig: Index 0 requested, with a size of 0
07-25 22:02:39.509 15878 15878 E sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
07-25 22:02:39.533 15878 15878 I TetheringManager: registerTetheringEventCallback:com.fsck.k9
07-25 22:02:39.536 15878 15900 E sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
07-25 22:02:39.538 15878 15900 I chatty  : uid=10250(com.fsck.k9) pool-6-thread-1 identical 1 line
07-25 22:02:39.541 15878 15900 E sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
07-25 22:02:39.560 15878 15903 E sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK

**Comment by cketti** [comment] 2021-07-25 20:15
Try leaving out the `--pid=xxxxx`.

**Comment by Hoiss** [comment] 2021-07-25 20:40
Oh wow, I just received the email notification of your reply in the android menu and clicked on that. Et voila, K9 opens the mail without crashing. And then I was able to go back and use K9 again!
Couldn't believe it and forced a quit via android, restarted, crashes again.
So I now maybe found a way to use K9 until the bug is fixed ;-)

For the attached output I started K9 and afterwards looked for the time I started it to give you the K9 relevant part of the huge log file.

[k9-logpart.txt](https://github.com/k9mail/k-9/files/6874527/k9-logpart.txt)

**Comment by cketti** [comment] 2021-07-25 20:54
Looks like your default account doesn't have a local Outbox folder set up. That shouldn't happen because the folder is created automatically when setting up an account. In this state you won't be able to send messages.

Did this account exist before the update? Were you able to send messages?

Duplicate of #5434

**Comment by Hoiss** [comment] 2021-07-25 21:03
Yes, it was fully functional before.
I now opened K9 again via the menu after receiving the mail, was able to go to options then and checked the server settings for the outbox - everything was fine. I confirmed the settings and also ensured it was marked as standard outbox. Now it seems it works again. Also after force quitting K9 it starts without crashing.

So this issue is really a duplicate of #5434.
And there seems to be a workaround as described ;-)

**Comment by cketti** [comment] 2021-07-25 21:13
You can't mark a folder as the Outbox. It's a special local folder that holds messages before they can be delivered to the outgoing mail server. Even though the app doesn't crash on startup anymore you probably won't be able to send messages. 

Chances are there's other settings that got corrupted. I highly recommend reinstalling the app and not using it in this half-broken state.

**Comment by Hoiss** [comment] 2021-07-25 21:40
No not a folder. I went to options -> the account I want to use -> general settings -> activate standard (send from this account).
I tried to send a message and it worked, doesn't even seem to be half-broken...
What do you think could happen? Something weird with the mails in the account maybe?
If just send and receive could not work I'd give it a try in this state (seems to work). 
A possible future bug-fix might give more details about the consequences.

**Closed** 2021-08-07 14:51 UTC
