### ISSUE TITLE
Inbox header does not scale properly if non default font size / display size are used

### ISSUE THREAD

**Issue by hiqua** [thunderbird/thunderbird-android#5279] opened 2021-04-27 15:48 UTC
**Describe the bug**

Font size: largest
Display size: smaller

The text of the email address of the account is not fully visible in the head while in the Inbox / Folders view, i.e. it doesn't scale properly with the display settings.

**To Reproduce**
1. Change Android settings: font size to largest, display size to smaller
2. Open k-9
3. open folder or Inbox
4. try to read email address from header

**Expected behavior**
The text should be fully visible.

**Screenshots**
![signal-2021-04-27-174129](https://user-images.githubusercontent.com/3812042/116271452-462def00-a780-11eb-9c20-9f1a1ed8cb2c.png)

**Environment (please complete the following information):**
 - K-9 Mail version: 5.600
 - Android version: 11
 - Device: LG G2
 - Account type: N/A

**Logs**
N/A

**Comment by cketti** [comment] 2021-04-27 17:10
Duplicate of #3997

See also: [How do I become a beta tester?](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68)

**Closed by cketti** 2021-04-27 17:10 UTC

**Comment by hiqua** [comment] 2021-04-27 18:45
Sincere apologies for the duplicate, "font size" does not return the corresponding issue, I should have looked further.

I installed the beta and indeed the bug is no longer relevant there (and the new interface looks pretty nice so congrats for this while I'm at it).
