### ISSUE TITLE
Can't set a key from Openkeychain to an account

### ISSUE THREAD

**Issue by ivanhercaz** [thunderbird/thunderbird-android#3689] opened 2018-10-31 11:39 UTC
I found some problems with [OpenKeychain](https://github.com/k9mail/k-9/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+openkeychain). One problem I found was #2601, very similar to this issue, but I prefer to open this issue to explain and show exactly what is happening. #3289 is similar too, but it is a solved bug, so it might be caused by a different reason.

I think it is a problem with K-9 because another applications in which I use a key from OpenKeychain, as [Password Store](https://github.com/zeapo/Android-Password-Store), works fine.

### Expected behavior
My intention is to add a key to an email account, but I can't. The expected behavior is to set without problems the key.

### Actual behavior
The system shows a notification telling me that OpenKeychain has crashed. After several times trying it, rebooting, uninstalling and reinstalling the app, I didn't achieve nothing and it keeps crashing.

### Steps to reproduce
Below there is an animated gif in which you can see what I am trying to do to configurate the key.

1. Set the OpenPGP provider in Global configuration > Encryption (excuse me if the items of the menu are not the same, I am translating it from the strings in Spanish, the language I use).
2. Then, try to set the key in Account configuration > Encryption > My key.
3. OpenKeychain crash.

![k9openkeychainissue](https://user-images.githubusercontent.com/8690921/47784818-a3a36b00-dcfe-11e8-9655-33da51726711.gif)

### Environment
- K-9 Mail version: 5.600 (downloaded from F-Droid)
- OpenKeychain version: 5.2 (downloaded from F-Droid)
- Android version: 7.1.1
- Smartphone: Moto X Play
- Account type (IMAP, POP3, WebDAV/Exchange): IMAP
----
Of course, I take the opportunity to thank you for the development of this awesome mail client, the one I like more. I wish we could solve this issue.

**Comment by ivanhercaz** [comment] 2018-11-04 10:54
@SergioFernandezCordero remember me that I have another smartphone where I can test it.

This issues **happens different** in the next environment:
- K-9 Mail version: 5.600 (downloaded from F-Droid)
- OpenKeychain version: 5.2 (downloaded from F-Droid)
- Android version: 7.1.2 (MIUI 9.6.5.0)
- Smartphone: Xiaomi Redmi 4X

In this case I show the window to generate a new key or to set an existing key, it is selected, but then, if I click in "My key", OpenKeychain crash.

**Comment by cvzi** [comment] 2019-01-04 13:03
Is there a workaround for this problem?

**Comment by cvzi** [comment] 2019-01-04 13:36
So, I just realized that when I set my phone to English, the problem does not appear and everything works as expected. Like the screencapture by @ivanhercaz  my phone is usually set to Spanish.

**Comment by SergioFernandezCordero** [comment] 2019-01-04 19:46
I confirm the behaviour indicated by @cvzi. Changing back to spanish crash again.

**Comment by chaos-prevails** [comment] 2019-03-06 09:02
I can confirm this bug on a Samsung Chromebook with 71.0.3578.127 64bit installed

Changing language from Spanish to English, and K9-Mail and openkeychain don't crash any more.

**Comment by elpasmo** [comment] 2019-05-02 06:55
I can confirm this bug on a Fairphone 2 with a Fairphone Open OS 7.1.2 19.02.1. Same versions of applications as @ivanhercaz 

Changing language from Spanish to English solved the problem.

**Comment by ivanhercaz** [comment] 2019-05-09 11:16
Thank you for your comments but in my case, I changed the language of K9 to English (as @elpasmo @chamonkey and @cvzi said) and the problem persists. I also try to set the key directly with "Applications" section of Openkeychain, the key is shown as allowed in the application, but the error mentioned above persists.

**Comment by elpasmo** [comment] 2019-05-09 11:18
> Thank you for your comments but in my case, I changed the language of K9 to English (as @elpasmo @chamonkey and @cvzi said) and the problem persists.

Sorry for the confusion but what I'd changed is the OS language, not the K9 setting.

**Comment by ivanhercaz** [comment] 2019-05-09 11:25
> @ivanhercaz Sorry for the confusion but what I'd changed is the OS language, not the K9 setting.

Oh, it works! Well... I will use English language until this error will be solved. Thank you @elpasmo!

**Comment by ivanhercaz** [comment] 2019-05-10 22:28
Today I get a new smartphone and I am having the same error using Spanish as operative system language. I haven't checked yet the behavior with English language. My new environment is:

  - K-9 Mail version: 5.600 (downloaded from F-Droid)
  - OpenKeychain version: 5.2 (downloaded from F-Droid)
  - Android version: 9 PKQ1.181021.001 (MIUI Global 10.2.4.0)
  - Smartphone: Xiaomi Redmi 7
  - Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by pwepwe973** [comment] 2019-12-06 17:42
I have a similar problem when I can not select a key at the moment. I selected openkeychain in: general settings> cryptography> opengpgp application> openkeychain.

but in the mail account> cryptography> no key selected is displayed.

I did the same procedure on monsamsung j5, it works very well, on the xioami redmi note 8 of my wife in the same way that it works, but on my xioami Mi 9 who does not want to add a key to the account of messaging

**Comment by Ost3rbaer** [comment] 2020-04-19 13:24
This seems really specific to Xiaomi.
My specs

- Xiaomi Redmi Note 8 Pro
- MIUI Global 11.0.3 | Stable
- Android PPR1.180610.011
- OpenKeyChain 5.5 (55000) installed from Google Play Store
- k9, versions 5.709 (from github) and 5.600 (from Google Play Store)
- tried German and English both as system language and k9 only

OpenKeyChain has loaded my key, I am able to decrypt and encrypt with it files on my phone. In k9 I have chosen OpenKeyChain as OpenPGP App (in global settings).

But when I go to account settings/cryptography I can't select a key, when I try to read an encrypted mail, I receive the error "decryption cancelled" (or the German translation thereof).

The language change trick did not help for me.

Is there any way I can gather more information to track down this issue? As all my mail is encrypted this limits the usefullness of my phone considerably. :(

No issues on my older Honor 7x - k9/OpenKeyChain works like a charm.

**Comment by cketti** [comment] 2020-10-06 22:16
Duplicate of #2601

**Closed by cketti** 2020-10-06 22:16 UTC
Labels: type: third-party integration
