### ISSUE TITLE
Make Threaded Actually Threaded

### ISSUE THREAD

**Issue by uniquePWD** [thunderbird/thunderbird-android#7883] opened 2024-05-29 10:10 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

Open an email that's part of a thread 

### Expected behavior

You can scroll up to read the entire thread

### Actual behavior

The actual behaviour is an abomination. You press the email and you're taken to a list of emails in the thread and once you open one, you have to horizontal scroll to see the next or previous and that's reversed anyway. But a horizontal scroll should take you to the next thread, not navigate within the same thread.

**Comment by ryanleesipes** [comment] 2024-05-31 12:44
I know this has been discussed, I believe there is a plan - through a conversation view - to enable this.

**Comment by cketti** [comment] 2024-06-08 17:37
Duplicate of #6197

**Closed by cketti** 2024-06-08 17:37 UTC
