### ISSUE TITLE
K9 deletes Text on Phone Flip

### ISSUE THREAD

**Issue by yooden** [thunderbird/thunderbird-android#1268] opened 2016-04-08 06:46 UTC
I just entered text in the sig area, flipped the phone from horizontal to verticsl, text was gone.

Version? No way to tell, latest from Play.

**Comment by philipwhiuk** [comment] 2016-04-08 20:44
Yep, confirmed in the latest version on F-Droid (5.008). Likely to exist in 5.010 because there wasn't much change here.

But this is fixed in the beta, I'm not sure where because the MessageCompose activity has seen a lot of work. I don't know if it's worth trying to workout where and why.

**Closed by philipwhiuk** 2016-04-08 20:44 UTC
