### ISSUE TITLE
Lag in applying dark theme at startup

### ISSUE THREAD

**Issue by entombedparty** [thunderbird/thunderbird-android#6253] opened 2022-08-24 16:32 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.301

### Where did you get the app from?

F-Droid

### Android version

8.1.0

### Device model

noname (echo Feeling)

### Steps to reproduce

Choose Dark theme.
Close the app.
Start the app.

### Expected behavior

When the app starts the background should immediately be dark.

### Actual behavior

For a few moments (1 or 2 seconds) the theme is Light. During this time only the header bar is displayed. The theme turns Dark at the same moment as the mail folder contents appears.

Enough time for my eyes to die XD

The problem appeared when I updated to 6.301, but I do not update apps very frequently. Last time was "a few months ago". Sorry for not being able to provide the working version I used before :-(

**Comment by cketti** [comment] 2022-08-24 16:44
Duplicate of #6057

**Closed by cketti** 2022-08-24 16:44 UTC
