### ISSUE TITLE
Certain emails are not displaying (All white)

### ISSUE THREAD

**Issue by garne2t** [thunderbird/thunderbird-android#854] opened 2015-10-20 17:49 UTC
I am signed up to get weekly emails from Goldstar.com with a list of discount events in my area. These emails are not properly displaying on K-9 and show up all white. At first the email may display but if I rotate my Samsung  Note 4 90 degrees, the email turns all white.   These emails use to display properly on k9.

**Comment by garne2t** [comment] 2015-10-20 17:59
After viewing the problem email, all other emails are now not readable and only show a white screen  in the content area. Note that the header displays but the message content is blank. Exiting and restarting k9 will allow other emails to be read but the problem is repeatable.

**Comment by cketti** [comment] 2015-10-23 02:56
I couldn't reproduce this using a Nexus device. Maybe it's an issue with Samsung's WebView. Without more information there is no way to know what's going wrong. Unfortunately, I can't think of a way you can provide that information (short of mailing me your device).
Chances are low that we are going to figure this one out. So I'm closing the issue until someone can provide enough information to fix the bug.

**Closed by cketti** 2015-10-23 02:56 UTC
Labels: status: needs information
