### ISSUE TITLE
ForegroundServiceStartNotAllowedException when PushService is restarted by Android

### ISSUE THREAD

**Issue by ryosoftware** [thunderbird/thunderbird-android#7416] opened 2023-12-06 08:34 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.7.12

### Where did you get the app from?

Other

### Android version

14

### Device model

Pixel 7 Pro

### Steps to reproduce

It occurs whiout user interaction

### Expected behavior

The app works without any FC

### Actual behavior

A FC occurs each time to time...

### Logs

type: crash
osVersion: google/cheetah/cheetah:14/UP1A.231105.003/2023112900:user/release-keys
package: com.fsck.k9:37012
process: com.fsck.k9
processUptime: 624 + 373 ms

```text
java.lang.RuntimeException: Unable to start service com.fsck.k9.controller.push.PushService@76c032 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4856)
at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2296)
at android.os.Handler.dispatchMessage(Handler.java:106)
at android.os.Looper.loopOnce(Looper.java:205)
at android.os.Looper.loop(Looper.java:294)
at android.app.ActivityThread.main(ActivityThread.java:8199)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ExecInit.main(ExecInit.java:49)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
at android.os.Parcel.readParcelable(Parcel.java:4872)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
at android.os.Parcel.createException(Parcel.java:3050)
at android.os.Parcel.readException(Parcel.java:3026)
at android.os.Parcel.readException(Parcel.java:2968)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6776)
at android.app.Service.startForeground(Service.java:862)
at com.fsck.k9.controller.push.PushService$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
at com.fsck.k9.controller.push.PushService.startForeground(PushService.kt:45)
at com.fsck.k9.controller.push.PushService.onStartCommand(PushService.kt:28)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4838)
... 11 more
```

**Comment by venumanas87** [comment] 2023-12-09 14:27
This force close occurs because Android 12/13 restricts service invocation while the app is in the background. For this reason, the worker should be replaced with a service. Would you like me to proceed with this solution?
@cketti

**Comment by robertoprubio** [comment] 2023-12-09 17:34
I can confirm the issue do not occurs anymore when I disable battery optimizations for this app

**Comment by cketti** [comment] 2023-12-10 01:03
@robertoprubio: What was the battery optimization value set to?

@venumanas87: `PushService` can't be replaced with a worker. We need a foreground service to ensure the app can keep the connection(s) to the server open. Maybe we're accidentally starting the service in situations where the app isn't allowed to do so.

**Comment by robertoprubio** [comment] 2023-12-10 06:02
> @robertoprubio: What was the battery optimization value set to?
> 

Do not optimize.

You need to use a ForegroundService and declare the type of the foregroundService.
According to Android docs (https://developer.android.com/guide/components/foreground-services?hl=es-419) apps for what the user has deactivated the battery optimizations can start foreground services anytime

**Comment by venumanas87** [comment] 2023-12-10 06:57
Yeah, that's already been implemented.

**Comment by robertoprubio** [comment] 2023-12-10 07:02
> Yeah, that's already been implemented.

Maybe you need to add a control to the app to check if battery optimization is disabled then disable if enabled. Like this;
Not all the users may knowhow to manually disable battery optimizations and also whats the cause of this FC

```
        private void checkBatteryOptimizationSetting()
        {
                if (Build.VERSION.SDK_INT >= 32)
                {
                        PowerManager power_manager = (PowerManager) getSystemService(POWER_SERVICE);
                        if (! power_manager.isIgnoringBatteryOptimizations(getPackageName())) {
                                ShowMessageDialog dialog = new ShowMessageDialog(this, getString(R.string.battery_optimization_android_12_disclaimer));
                                dialog.setTitle(R.string.information);
                                dialog.setButton(DialogInterface.BUTTON_POSITIVE, getString(R.string.accept_button), new DialogInterface.OnClickListener()
                                {
                                        public void onClick(DialogInterface dialog, int which)
                                        {
                                                Intent intent = new Intent();
                                                intent.setAction(Settings.ACTION_REQUEST_IGNORE_BATTERY_OPTIMIZATIONS);
                                                intent.setData(Uri.parse("package:" + getPackageName()));
                                                startActivity(intent);
                                        }
                                });
                                dialog.show();
                        }
                }
        }
```

**Comment by venumanas87** [comment] 2023-12-10 08:31
Yeah so should I proceed with implementing it in the MessageList Activity?

**Comment by robertoprubio** [comment] 2023-12-10 08:35
> Yeah so should I proceed with implementing it in the MessageList Activity (as it is the first screen displayed.)

Yes, this will be fantastic

**Comment by cketti** [comment] 2023-12-11 12:05
> > @robertoprubio: What was the battery optimization value set to?
> 
> Do not optimize.

Apologies for not being clearer. I wanted to know what battery optimization option was selected when the app was regularly crashing.

It's good to know that changing the battery optimization setting will avoid the crash. However, that's not fixing the actual problem. Let's focus on finding the root cause for this crash, so we can fix the bug.

Users should not have to change the battery optimization setting. Unless absolutely necessary, we won't prompt users to change it.

**Comment by robertoprubio** [comment] 2023-12-11 12:43
> > > @robertoprubio: What was the battery optimization value set to?
> > 
> > 
> > Do not optimize.
> 
> Apologies for not being clearer. I wanted to know what battery optimization option was selected when the app was regularly crashing.
> 
> It's good to know that changing the battery optimization setting will avoid the crash. However, that's not fixing the actual problem. Let's focus on finding the root cause for this crash, so we can fix the bug.
> 
> Users should not have to change the battery optimization setting. Unless absolutely necessary, we won't prompt users to change it.

The default one: optimize

**Comment by cketti** [comment] 2024-04-12 13:13
This seems to be caused by a bug in Android. See https://issuetracker.google.com/issues/307329994

The crash happens when the Push service is restarted after the app has been killed, e.g. because of low memory. But not reliably. So far I've only managed to reproduce the crash once, after hours of (automated) cycles of killing the app and it being automatically restarted by Android. That makes it very hard to test workarounds.

Avoiding the crash is rather easy. But doing only that would most likely lead to Push stopping to work at some point. Push would only restart once the app UI is manually launched or the device is rebooted.

**Comment by cketti** [comment] 2024-06-27 16:22
Ignoring `ForegroundServiceStartNotAllowedException` when the service is restarted seems to do the trick. It doesn't seem to lead to a `ForegroundServiceDidNotStartInTimeException` being thrown.

This change has been active in K-9 Mail 6.804 for a couple of weeks now. We haven't gotten any reports of Push stopping to work that could be traced back to this. I'm closing this bug until we see evidence our workaround didn't actually fix the problem.

**Closed by cketti** 2024-06-27 16:22 UTC
