### ISSUE TITLE
Permanently acoustic notifications probably by K-9 Mail/Thunderbird-Android, but in most cases no new emails in Inbox

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7379] opened 2023-11-24 18:15 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711

### Where did you get the app from?

F-Droid

### Android version

Android 10

### Device model

LG K50 s

### Steps to reproduce

When my smartphone generates acoustic notifications probably invoked by K-9 Mail/Thunderbird-Android, in most cases no visual notifications about new mails in the Inbox of K-9 Mail/Thunderbird-Android gets displayed on the Launcher Screen of my smartphone and no new mail has arrived in my main email account at my mailhoster, or such a visual notification gets displayed on the Launcher Screen for maximally one second and then disappears, but in fact a new email has arrived, but this time in the Inbox of the alias email account of my main email account at my mailhoster, and this new mail is displayed in the corresponding folder in by K-9 Mail/Thunderbird-Android and in the email program KMail on my laptop.

When I notice an acoustic notification by my smartphone, I first check the Launcher Screen if it displays a visual notification about a new email in K-9 Mail/Thunderbird-Android, and if the Launcher Screen does not display such a visual notification I check my main mail account at my mailhoster with its alias mail account in the email program "KMail" on my laptop, and in most cases in K-9 Mail/Thunderbird-Android, too. In most cases it appears that now new mail had arrived in my main email account at my mailhoster.

Sometimes in these situations as described above, the acoustic notifications are not fully generated regarding their length, i. e. they get abruptly stopped before they reach the end of their acoustic signal sound file.

How often does this behavior occur?

To give you an impression about how often this behavior occurs: This morning between 5 and 7 A.M. my smartphone generated 3 acoustic notifications, while in these three cases no new mail had arrived in the Inbox of my main mail and alias mail account.

While I am writing this bug report, my smartphone has generated appr. 10 times such a "ghost" acoustic notification until now. OK, I am a little bit slow in writing this report because my mother tongue is not English. I think it will take me two hours to write and finally save this bug report here.

Some days ago my smartphone generated more often these "ghost" acoustic notifications than compared to today's morning. Like every 20 minutes or so. Note that the version of K-9 Mail/Thunderbird-Android installed some days ago (6.6xx) was older than the version which is currently installed on my smartphone (6.711). Today I updated K-9 Mail/Thunderbird-Android to its newest available version in the F-DROID store.

Note that the behavior described above occurs at home. I did not take my smartphone out of my apartment since about two weeks. My smartphone uses Wi-Fi at home to be connected to the Internet via my router.

I think that the behavior described above started from the moment on when I had changed the Wi-Fi name of my router (its SSID) here at home. In the settings of my router I added the text string "_optout_nomap" at the end of the name of the SSID of my router, i. e. this way:

"<SSID>_optout_nomap"

According to Mike Kuketz, a German IT security and data protection specialist, this SSID name extension tells Microsoft, Google and other similar providers (location mapping services) not to process such SSID's for registering their location geo data, which are used to locate the positions of smartphones and other devices. This information can be found (in German) in chapter "WLAN-SSID: Opt-Out" here:

https://www.kuketz-blog.de/empfehlungsecke/

Note that I am using K-9 Mail/Thunderbird-Android in connection with OpenkeyChain on my smartphone, and that the adblocking app Adaway is running on my smartphone with several active ad blocking filters.

This afternoon I logged one of these "ghost" acoustic notifications on my smartphone using the logging/debugging functionality of K-9 Mail/Thunderbird-Android. This "ghost" acoustic notification which I logged occurred today at 14:58 o'clock German Winter Time.

This is what K-9 Mail/Thunderbird-Android has logged today at 14:58 o'clock German Winter Time:

[Note: Having uploaded this quote from the K-9 Mail log file, I noticed that it does not properly gets displayed here, although I used the "code" tags for that. I will upload the quote of the log file separately, just a moment, please.]

General description of how I set up K-9 Mail/Thunderbird-Android:

- K-9 Mail/Thunderbird-Android accesses one main email account at my mailhoster which has one alias email account which K-9 Mail/Thunderbird-Android accesses, too. Incoming mails in the main email address and in the alias email address are both shown in the the Unified Inbox.
- Access to these two mail addresses at my mailhoster via IMAP
- Push is not activated at all
- K-9 Mail/Thunderbird-Android retrieves (looks for new) mails every 15 minutes

I could upload the exported settings of my K-9 Mail/Thunderbird-Android setup, but I would do that first, if you think that there is something strange documented in the log information above.

### Expected behavior

K-9 Mail/Thunderbird-Android should only notify me with acoustic notifications about new emails in the Inboxes of my main email account and of the alias mail account. 

### Actual behavior

Refer to section "Steps to reproduce"

**Comment by ploxmox** [comment] 2023-11-24 18:20
[quote_from_k-9_mail_log_file.txt](https://github.com/thunderbird/thunderbird-android/files/13461603/quote_from_k-9_mail_log_file.txt)

**Comment by ploxmox** [comment] 2023-11-24 18:23
Quote from today's log file generated by K-9 Mail/Thunderbird-Android's debugging functionality. The quote contains all events logged today between 14:58 and 14:59 o'clock German Winter Time.

**Comment by cketti** [comment] 2023-11-24 18:53
It is unlikely that K-9 Mail is responsible for this. The log shows K-9 Mail hasn't created any notifications during the logging period. 

You could easily rule out K-9 Mail by disabling all notifications for K-9 Mail in Android's notification settings.

**Comment by ploxmox** [comment] 2023-11-24 19:01
OK, thanks for your analysis and response. I just have de-activated all notifications for K-9 Mail/Thunderbird-Android and will now wait for any new ghost notifications.

**Comment by ploxmox** [comment] 2023-11-24 20:35
Since I de-activated all notifications by K-9 Mail/Thunderbird-Android in my smartphone I received 3 acoustic notifications by my phone without any corresponding textual notification in the Launcher Screen. So another process must be the cause for these "ghost" notifications described in this issue report. 

I will close this issue report now. Thanks, @cketti

**Comment by ploxmox** [comment] 2023-11-24 20:37
Oh, something went wrong while trying to close this issue. Let me try once more ;-)

**Closed** 2023-11-24 20:37 UTC
