### ISSUE TITLE
Thunderbird fails to import via K9 app

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8211] opened 2024-10-01 13:23 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 7

### Steps to reproduce

1. Launch application (without any previously added accounts)
2. Select "Import Settings"
3. Select "Import from app"
4. Select the K9 Mail application (have accounts added)

### Expected behavior

The K9 application is selected and the import process continues without any issues.

### Actual behavior

Selected the K9 Mail application triggers the following error: "Failed to read settings file" and the process is halted.

### Logs

https://github.com/user-attachments/assets/af4c4ae1-c7b4-474f-ab13-b22c0f0c3406

[import app.txt](https://github.com/user-attachments/files/17210206/import.app.txt)

**Comment by cketti** [comment] 2024-10-01 13:28
Duplicate of #8138

**Closed by cketti** 2024-10-01 13:28 UTC
