### ISSUE TITLE
Put K-9 account list back the way that it was before you ruined it

### ISSUE THREAD

**Issue by leowankerddd** [thunderbird/thunderbird-android#8447] opened 2024-10-31 04:17 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b5

### Problem you are trying to solve

I've been an avid user of K-9 for many years and now the new thunderbird user interface has ruined it. I have 11 email accounts and now I don't know which one is which without scrolling through them every time one after the next this is terrible new design.

PLEASE let those of us who have been using the software for years continue to use it the way that we have been. Is there any way I can download the previous release that doesn't have this "new look".

I have 11 accounts and now all I can see are two letters and many of them are the same so now I need to come up with a color scheme and memorize the color scheme that is just I'm sorry to have to say it but dumb.

The user interface for selecting accounts that you want to look at by inbox has been ruined.

### Suggested solution

The solution is to take away the new look and put canine back the way that it was. Or, at least let those of us who have been canine users for the last 10 years use it the way that we have been accustomed to using it give us back the account UI.

**Comment by eroc1990** [comment] 2024-10-31 05:11
Glad someone brought this up. I use multiple addresses from the same base domain, so when Thunderbird does its truncation of my mail account names, everything under gmail.com just becomes GM in the sidebar with various accent colors. It's impossible to select the right account quickly without memorizing the order.

**Comment by docjochim** [comment] 2024-10-31 06:45
me too...
Changing the mail-accounts' order after clicking at one of them makes it impossible to look into all of them one after the other. Seems to be a déjà-vu remembering 80s alien-shooting-games.
My wife's smartphone just updated to the latest 8.0 (4?) an I never heard her scolding like this.

In addition: Why did the colour of marked mails change? It's nearly impossible to distinguish between marked and unread messages (light grey and just a little darker light grey...) Is there any possibily to change the colour of marked mails (e.g. in order to delete multiple mails) within the GUI, for example into a pink or something else distinguishable!?

Why the hell are you always trying to get users angry by changing GUI?

I still love my 5.6 :-))

**Comment by kewisch** [comment] 2024-10-31 09:48
I see you have found the issue where we've mentioned we're going to look into this and find a solution for the email account letters. I don't think it is very productive to simply remove all the code and make it look like it was before, but we're very open to making tweaks and improvements to make the new drawer more usable.

Regarding the color of emails, this is also a common point that has been brought up and a different issue. We've done some tweaks on this recently, but it is still an area of contention.

Duplicate of 8381

**Closed by kewisch** 2024-10-31 09:48 UTC
Labels: type: enhancement, unconfirmed

**Comment by 0verEngineer** [comment] 2024-11-12 15:24
@kewisch 
1. How can this be a duplicate of https://github.com/thunderbird/thunderbird-android/issues/8381 - 8381 is about the change of the name does not change the letters in the bubble.

2. If you don't think it is very productive to simply remove all the code and make it look like it was before then either make it usable and not suck or make a setting where users can change back to the old layout, i have 7 bubbles with the letters "HA" in it, do you find this simple and usable???

3. PLEASE reopen this issue because this is a real usability problem.

**Comment by DAveShillito** [comment] 2024-11-15 02:21
As a long time K-9 user, I have to add my support to the idea of putting back some way to see the entire email address.
The sliding in sidebar worked well in the past.
Trying to "fix" the new 2 letter code is only ever going to be a band-aid.
If it tastes bad it does not matter how much seasoning you add... you are eventually going to have to recook the meal.
