### ISSUE TITLE
Notification sound plays multiple times

### ISSUE THREAD

**Issue by mikhirev** [thunderbird/thunderbird-android#5022] opened 2020-10-22 18:47 UTC
I've recently updated to 5.721 from F-Droid (I'm unsure what version I used before, probably 5.600). After that notification sound began to repeat multiple times. E.g. I get 1 new message, it plays 2 times. If I get more messages, it plays even more times (somewhat about 1 time for each message + 1). Sometimes it bells even if there are no new messages (maybe because some message changed its state from "new" to "read"). It is very annoying.

**To Reproduce**
1. Enable notification sound.
2. Wait for new message.

**Expected behavior**
Notification sound should play exactly one time if one or several new messages received in a batch

 and should not play if no new messages received.

**Environment:**
 - K-9 Mail version: 5.721
 - Android version: 8
 - Device: Samsung Galaxy A5 (2017)
 - Account type: IMAP

**Additional context**
Build from F-Droid.

**Logs**
[k9-log.txt](https://github.com/k9mail/k-9/files/5425053/k9-log.txt) ­- 1 message received, sound played 2 times.

**Comment by pejakm** [comment] 2021-05-09 12:44
This is a duplicate of #4559 as far as I can see. I don't see any progress being made there.

**Comment by cketti** [comment] 2021-05-09 14:06
Duplicate of #4559

**Closed by cketti** 2021-05-09 14:06 UTC
