### ISSUE TITLE
fetching is slow

### ISSUE THREAD

**Issue by 532910** [thunderbird/thunderbird-android#5012] opened 2020-10-16 07:41 UTC
If I understand all correctly k9 fetches the whole letter and `Preview lines` only set how much lines to display.
Thus, it takes a very long time to fetch a mailbox with a lot of messages (like a maillist), especially on the cellular internet.
Yep, there is a message size limit to fetch, but it's not that I want. I'd like the same behaviour as on desktop thunderbird:
1. Only headers are download.
2. The full message is loaded that time it's opened.

**Comment by cketti** [comment] 2020-10-16 10:25
Duplicate of #2870

**Closed by cketti** 2020-10-16 10:25 UTC
