### ISSUE TITLE
When GPG Is enabled with OpenKeychain 6.0.0 trying to type a email crashes compose view

### ISSUE THREAD

**Issue by bill88t** [thunderbird/thunderbird-android#7629] opened 2024-02-12 16:24 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.715

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

Moto G32

### Steps to reproduce

1. Update OpenKeychain to 6.0.0
2. Enable gpg with a key
3. Open mail compose view
4. Write 2 characters in the "To" field.

### Expected behavior

Not implode.

### Actual behavior

Compose view crashes, throwing the user to k9 main screen.

### Logs

02-12 18:14:58.474 27200 27200 D VRI[PopupWindow:f61e83e]:   fl=NOT_FOCUSABLE NOT_TOUCHABLE LAYOUT_NO_LIMITS WATCH_OUTSIDE_TOUCH SPLIT_TOUCH HARDWARE_ACCELERATED FLAG_LAYOUT_ATTACHED_IN_DECOR
02-12 18:14:58.474 27200 27200 D VRI[PopupWindow:f61e83e]:   pfl=WILL_NOT_REPLACE_ON_RELAUNCH LAYOUT_CHILD_WINDOW_IN_PARENT_FRAME
02-12 18:14:58.474 27200 27200 D VRI[PopupWindow:f61e83e]:   bhv=DEFAULT
02-12 18:14:58.474 27200 27200 D VRI[PopupWindow:f61e83e]:   fitTypes=STATUS_BARS NAVIGATION_BARS CAPTION_BAR} by setLayoutParams
02-12 18:14:58.504 27200 27200 W OnBackInvokedCallback: OnBackInvokedCallback is not enabled for the application.
02-12 18:14:58.504 27200 27200 W OnBackInvokedCallback: Set 'android:enableOnBackInvokedCallback="true"' in the application manifest.
02-12 18:14:58.840 27200 27224 D Surface : Surface::disconnect
02-12 18:14:58.840 27200 27224 D BufferQueueProducer: [VRI[PopupWindow:f61e83e]#6(BLAST Consumer)6](id:6a4000000006,api:1,p:27200,c:27200) disconnect: api 1
02-12 18:14:58.841 27200 27224 D OpenGLRenderer: endAllActiveAnimators on 0xb4000075c69b31d0 (MenuPopupWindow$MenuDropDownListView) with handle 0xb4000074d694cb60
02-12 18:14:59.141 27200 27224 D Surface : Surface::disconnect
02-12 18:14:59.141 27200 27224 D BufferQueueProducer: [VRI[MessageCompose]#5(BLAST Consumer)5](id:6a4000000005,api:1,p:27200,c:27200) disconnect: api 1
02-12 18:15:00.736 27200 27200 D CompatibilityChangeReporter: Compat change id reported: 78294732; UID 10336; state: ENABLED
02-12 18:15:00.763 27200 27224 E OpenGLRenderer: Unable to match the desired swap behavior.
02-12 18:15:00.859 27200 27200 D TokenAutoComplete: Current completion text: [REDACTED, CORRECT],
02-12 18:15:00.886 27200 27387 E AndroidRuntime: FATAL EXCEPTION: ModernAsyncTask #2
02-12 18:15:00.886 27200 27387 E AndroidRuntime: Process: com.fsck.k9, PID: 27200
02-12 18:15:00.886 27200 27387 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:1012)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: Caused by: java.lang.NullPointerException: ResultSet returned null for UserPackets.sq:selectUserIdStatusByEmailLike
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3034)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:3012)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2995)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1219)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromCryptoProvider(RecipientLoader.java:230)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:200)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
02-12 18:15:00.886 27200 27387 E AndroidRuntime: 	... 3 more
02-12 18:15:00.922 27200 27200 E PhoneWindow: Circular progress bar not located in current window decor
02-12 18:15:00.944 27200 27387 I Process : Sending signal. PID: 27200 SIG: 9
02-12 18:15:01.066 27400 27400 I com.fsck.k9: Using CollectorTypeCC GC.

**Comment by cketti** [comment] 2024-02-12 16:34
Duplicate of #7622

**Closed by cketti** 2024-02-12 16:34 UTC
