### ISSUE TITLE
Error Decrypting Email

### ISSUE THREAD

**Issue by frojack** [thunderbird/thunderbird-android#1932] opened 2017-01-02 23:43 UTC
### Expected behavior
Expected decrypted email to show in cleartext

### Actual behavior
Error Eecrypting Email message shown with icon from OpenKeyChain

### Steps to reproduce
Send encrypted email to an account handled by K-9
Open email in k-9
Answer password request for decryption Key
See error message

### Environment
K-9 Mail version: 5.201

Android version: Android Version 6.0 - HTC M8 

Account type (IMAP, POP3, WebDAV/Exchange):
Sending Account was IMAP 
Receiving Account IMAP (gmail)

Both Public keys were imported from old AGP into OpenKeyChain.
Intentionally entering a wrong passphrase gives a different message: Wrong password.
Mail sent from either account to the other (encrypted) works in Thunderbird.  
Mail sent from Thunderbird also yields "Error Decrypting mail".

Process: com.fsck.k9, PID: 17677   <---- in Log
[k9-log-5.txt](https://github.com/k9mail/k-9/files/681499/k9-log-5.txt)

**Comment by philipwhiuk** [comment] 2017-01-03 00:08
Somehow callbackReturnResult is getting called twice. The second time around `queuedResult` is then null.

```
01-02 13:28:13.001 E/AndroidRuntime(17677): FATAL EXCEPTION: main
01-02 13:28:13.001 E/AndroidRuntime(17677): Process: com.fsck.k9, PID: 17677
01-02 13:28:13.001 E/AndroidRuntime(17677): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65916, result=0, data=null} to activity {com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.IllegalStateException: deliverResult() called with no result!
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3988)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4038)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.access$1400(ActivityThread.java:150)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.os.Looper.loop(Looper.java:168)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.main(ActivityThread.java:5845)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
01-02 13:28:13.001 E/AndroidRuntime(17677): Caused by: java.lang.IllegalStateException: deliverResult() called with no result!
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.deliverResult(MessageCryptoHelper.java:682)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.callbackReturnResult(MessageCryptoHelper.java:653)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.runSecondPassOrReturnResultToFragment(MessageCryptoHelper.java:602)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyNextPart(MessageCryptoHelper.java:192)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoFinished(MessageCryptoHelper.java:597)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationCanceled(MessageCryptoHelper.java:563)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onActivityResult(MessageCryptoHelper.java:536)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.activity.MessageLoaderHelper.onActivityResult(MessageLoaderHelper.java:168)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.messageview.MessageViewFragment.onPendingIntentResult(MessageViewFragment.java:393)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.activity.MessageList.onActivityResult(MessageList.java:1600)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.Activity.dispatchActivityResult(Activity.java:6439)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3984)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	... 9 more
```

Any ideas @Valodim ?

**Comment by frojack** [comment] 2017-01-03 05:51
I have multiple accounts (4) defined in K-9.Two of these have pgp keys defined in OpenKeychain.One additional account (gmail) has a key in openkeychain but is not defined in K-9.All of these accounts have the same Name.Each has a different Email Address (Obviously).    02.01.2017, 16:09, "Philip" <notifications@github.com>:Somehow callbackReturnResult is getting called twice. The second time around queuedResult is then null.
01-02 13:28:13.001 E/AndroidRuntime(17677): FATAL EXCEPTION: main
01-02 13:28:13.001 E/AndroidRuntime(17677): Process: com.fsck.k9, PID: 17677
01-02 13:28:13.001 E/AndroidRuntime(17677): java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65916, result=0, data=null} to activity {com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.IllegalStateException: deliverResult() called with no result!
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3988)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4038)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.access$1400(ActivityThread.java:150)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1443)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.os.Handler.dispatchMessage(Handler.java:102)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.os.Looper.loop(Looper.java:168)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.main(ActivityThread.java:5845)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at java.lang.reflect.Method.invoke(Native Method)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
01-02 13:28:13.001 E/AndroidRuntime(17677): Caused by: java.lang.IllegalStateException: deliverResult() called with no result!
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.deliverResult(MessageCryptoHelper.java:682)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.callbackReturnResult(MessageCryptoHelper.java:653)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.runSecondPassOrReturnResultToFragment(MessageCryptoHelper.java:602)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.decryptOrVerifyNextPart(MessageCryptoHelper.java:192)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoFinished(MessageCryptoHelper.java:597)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onCryptoOperationCanceled(MessageCryptoHelper.java:563)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.crypto.MessageCryptoHelper.onActivityResult(MessageCryptoHelper.java:536)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.activity.MessageLoaderHelper.onActivityResult(MessageLoaderHelper.java:168)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.ui.messageview.MessageViewFragment.onPendingIntentResult(MessageViewFragment.java:393)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at com.fsck.k9.activity.MessageList.onActivityResult(MessageList.java:1600)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.Activity.dispatchActivityResult(Activity.java:6439)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3984)
01-02 13:28:13.001 E/AndroidRuntime(17677): 	... 9 more

Any ideas @Valodim ?

**Comment by sophisticatedpenguin** [comment] 2017-01-05 18:41
I'm also receiving this error message. Is there a workaround? Thanks.

**Comment by jsamyth** [comment] 2017-01-05 23:53
Go to the Google Play store and update k9.
The update is out there last time I checked. (minutes ago)

**Comment by sophisticatedpenguin** [comment] 2017-01-05 23:59
Thanks - I have v5.202 though, and I'm not seeing an option to update.

On 5 January 2017 23:53:20 GMT+00:00, jsamyth <notifications@github.com> wrote:
>Go to the Google Play store and update k9.
>The update is out there last time I checked. (minutes ago)
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1932#issuecomment-270792464

-- 
Sent from my Android device with K-9 Mail. If you wish to send me an encrypted email, you can find my public key at http://pool.sks-keyservers.net/ by searching for my email address.

**Comment by cketti** [comment] 2017-01-06 00:05
The issue is still open which means the bug hasn't been fixed yet. 
We use this issue tracker to coordinate our development efforts. Please don't use it as support forum asking questions. We have a mailing list for that.

**Comment by sophisticatedpenguin** [comment] 2017-01-06 11:36
OK, then please could you tell me how to join the mailing list or where to find a support forum? I have searched for support but haven't been able to find it. I understand that the bug hasn't been fixed, but I hoped there might be a workaround as otherwise I can't read my emails (which is a significant issue!) Thank you, and I promise not to ask any more questions.

**Comment by frojack** [comment] 2017-02-06 20:40
Attached Requested Screen shot...
![screenshot_error-decrypting](https://cloud.githubusercontent.com/assets/7992119/22665367/5f54802e-ec69-11e6-8e5b-aaa7bc048e39.png)

**Comment by frojack** [comment] 2017-02-06 22:33
When requested to enter passphrase to decrypt a message, it asks with the User Name, and does not show the Email Account name.  This can be confusing when the same person has more than one email account.

![img_dialog-not-specific](https://cloud.githubusercontent.com/assets/7992119/22669386/2d33560a-ec79-11e6-9ec9-cc928e2cc305.jpg)

**Comment by Valodim** [comment] 2017-02-17 16:16
This error message also comes up with no further explanation when insecure ciphers are used or there is no MDC on an unsigned message. I'm currently working on error reporting, this will probably be solved along the way.

**Comment by Githubraum** [comment] 2017-10-04 21:47
I get the same error when I try to decrypt an incoming email. However, if I forward that email to myself the received copy will be decrypted without any problem.

K-9 Mail 5.208
OpenKeyChain Easy PGP v4.7

-----BEGIN PGP MESSAGE-----
Version: Cryptix OpenPGP 0.20050418
...

Do you need more information?

**Comment by Valodim** [comment] 2018-01-10 01:29
@Githubraum I don't think that's the same issue, please open a new issue about yours

**Comment by Valodim** [comment] 2018-01-10 01:31
As for the above stack trace, I still have no idea what caused that problem. If we're lucky, it might have been fixed along the way? Not sure.

**Comment by philipwhiuk** [comment] 2018-01-10 01:33
Let's close it then and 🤞

**Closed by philipwhiuk** 2018-01-10 01:33 UTC

**Comment by cgarciaq** [comment] 2019-12-02 12:28
Ey! I just found why I was getting a "Error decrypting" in my K9 + Openkeychain in a Xiaomi Android. Openkeychain did not have the permission to open in the background. Changed that "Android -> Settings -> Application --> Openkeychain --> Other permissions --> Open in background". Hope it helps someone.
