### ISSUE TITLE
Crashes on startup and then corrupts/loses accounts and settings

### ISSUE THREAD

**Issue by Wilm0r** [thunderbird/thunderbird-android#1452] opened 2016-06-09 12:10 UTC
### Expected behaviour

I get my inbox
### Actual behaviour

I get a crash, and on trying again to open K-9 e-mail I get the welcome screen asking me whether I want to import my settings from somewhere.
### Steps to reproduce

Sadly I don't know, but it's happened to me twice now. First time I don't have a backtrace of, but this time I caught it in time. There is some similarity with #1272 but that one doesn't happen at startup nor do I see a mention of settings getting lost.

This is the stacktrace, including the second attempt going straight to the welcome screen instead:

```
06-09 12:49:12.611  5440  6985 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[13,242][224,495] (has extras)} from uid 10031 on display 0
06-09 12:49:12.736  5440  3544 I ActivityManager: Start proc 1674:com.fsck.k9/u0a121 for activity com.fsck.k9/.activity.MessageList
06-09 12:49:13.057  1674  1674 E AndroidRuntime: FATAL EXCEPTION: main
06-09 12:49:13.057  1674  1674 E AndroidRuntime: Process: com.fsck.k9, PID: 1674
06-09 12:49:13.057  1674  1674 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fsck.k9.Account.getUuid()' on a null object reference
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread.-wrap11(ActivityThread.java)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5422)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-09 12:49:13.057  1674  1674 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.fsck.k9.Account.getUuid()' on a null object reference
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.decodeArguments(MessageListFragment.java:957)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.fsck.k9.fragment.MessageListFragment.onCreate(MessageListFragment.java:810)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.Fragment.performCreate(Fragment.java:2198)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:942)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1130)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.FragmentManagerImpl.dispatchCreate(FragmentManager.java:1948)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.FragmentController.dispatchCreate(FragmentController.java:141)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.Activity.onCreate(Activity.java:921)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.fsck.k9.activity.K9FragmentActivity.onCreate(K9FragmentActivity.java:19)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at com.fsck.k9.activity.MessageList.onCreate(MessageList.java:194)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.Activity.performCreate(Activity.java:6251)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
06-09 12:49:13.057  1674  1674 E AndroidRuntime:        ... 9 more
06-09 12:49:13.060  5440  6985 W ActivityManager:   Force finishing activity com.fsck.k9/.activity.MessageList
06-09 12:49:13.258  5440  6858 D ConnectivityService: updateNetworkScore for NetworkAgentInfo [WIFI () - 561] to 60
06-09 12:49:13.592  5440  5507 W ActivityManager: Activity pause timeout for ActivityRecord{8b20213 u0 com.fsck.k9/.activity.MessageList t2810 f}
06-09 12:49:14.346  5440 10803 W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@4ea8042 attribute=null, token = android.os.BinderProxy@10656c8
06-09 12:49:14.367  5440 10979 I ActivityManager: Process com.fsck.k9 (pid 1674) has died
06-09 12:49:14.545  5440  5553 W AppOps  : Finishing op nesting under-run: uid 1000 pkg android code 24 time=0 duration=0 nesting=0
06-09 12:49:14.876  5440  6987 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=com.fsck.k9/.activity.Accounts bnds=[13,242][224,495] (has extras)} from uid 10031 on display 0
06-09 12:49:14.924  5440  6429 I ActivityManager: Start proc 1705:com.fsck.k9/u0a121 for activity com.fsck.k9/.activity.Accounts
06-09 12:49:15.037  5440  3544 I ActivityManager: START u0 {cmp=com.fsck.k9/.activity.setup.WelcomeMessage} from uid 10121 on display 0
```
### Environment

K-9 Mail version: Version from Play Store which is currently 5.010.

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2016-06-09 13:07
The crash is most likely caused by the data already being gone rather than being the cause of the data disappearing.

The `Accounts` activity seems to be able to do its job. That suggests accounts can still be accessed at that point.

Did this happen after an app update?

**Comment by Wilm0r** [comment] 2016-06-09 13:20
Oh yes, that's a much more plausible theory indeed.

Did you push out a new version to the Play Store recently? I don't know how I can tell whether an update has happened recently - there's a notification about 5 updates having been installed but all different ones.

I have a 1.2MB backlog of adb logs, sadly first mention of k9 there is the exact crash above.

I'm trying to remember whether this was the first time I tried to use K9 today but don't know. My mailserver doesn't seem to log logins so I can't find out there either. :-/

**Comment by cketti** [comment] 2016-06-09 13:22
Not really. 5.010 was released in April. But failing database migrations are the only reason where we deliberately remove all data.

**Comment by Wilm0r** [comment] 2016-06-11 23:00
Strange, an upgrade seems unlikely this time then. I suppose there's not much else I can do to find useful info here then? I've restored my account now, hopefully this won't happen again too soon (last time was probably in April, likely around the upgrade then).

I've found Dovecot logs which showed one login from my phone around 11, an hour before this problem occured. Nothing logged about exact disconnect time, but this is probably not that interesting anyway.

**Comment by cketti** [comment] 2017-09-01 20:11
I just "lost" all accounts on my personal phone. The account databases still seem to be there, but the main database is empty except for these key/value pairs:

```
sqlite> select * from preferences_storage;
68639468-2847-40c4-ab4e-02536e6457af.description.0|Initial identity
68639468-2847-40c4-ab4e-02536e6457af.description.1|identity 2
68639468-2847-40c4-ab4e-02536e6457af.signatureUse.0|false
68639468-2847-40c4-ab4e-02536e6457af.signatureUse.1|false
68639468-2847-40c4-ab4e-02536e6457af.latestOldMessageSeenTime|1503484153000
68639468-2847-40c4-ab4e-02536e6457af.email.1|two@example.org
68639468-2847-40c4-ab4e-02536e6457af.email.0|one@example.org
68639468-2847-40c4-ab4e-02536e6457af.name.0|cketti
68639468-2847-40c4-ab4e-02536e6457af.signature.1|
68639468-2847-40c4-ab4e-02536e6457af.name.1|
68639468-2847-40c4-ab4e-02536e6457af.signature.0|-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
MailService.lastCheckEnd|1504226373375
```

It's unclear what caused this. I didn't see a crash dialog and couldn't find anything in the logs.

**Comment by philipwhiuk** [comment] 2017-09-01 21:36
I think maybe we should never delete the DB, just error madly.

**Comment by cketti** [comment] 2019-02-28 20:12
Duplicate of #750

**Closed by cketti** 2019-02-28 20:12 UTC
Labels: status: needs information
