### ISSUE TITLE
App crashes when cuting recepient email address

### ISSUE THREAD

**Issue by anzepintar** [thunderbird/thunderbird-android#7954] opened 2024-06-15 20:24 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

None

### Android version

14 - crdroid 10.5

### Device model

Poco X3 NFC

### Steps to reproduce

1. Open the compose email screen.
2. Write the recipient's email address.
3. Cut the email address before it is converted from text to a "box".
4. Repeat the previous step, as it only crashes the compose view the first time.

### Expected behavior

Not crashing

### Actual behavior

https://github.com/thunderbird/thunderbird-android/assets/46792251/3e227103-d082-4319-9335-22b7b14a8c9e

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/15854876/k9mail-logs.txt)

```
time: 1718479863451
msg: java.lang.IndexOutOfBoundsException: charAt: 0 >= length 0
stacktrace: java.lang.IndexOutOfBoundsException: charAt: 0 >= length 0
	at android.text.SpannableStringBuilder.charAt(SpannableStringBuilder.java:125)
	at android.text.CharSequenceCharacterIterator.current(CharSequenceCharacterIterator.java:58)
	at android.text.CharSequenceCharacterIterator.first(CharSequenceCharacterIterator.java:44)
	at android.icu.text.RuleBasedBreakIterator.CISetIndex32(RuleBasedBreakIterator.java:1052)
	at android.icu.text.RuleBasedBreakIterator.isBoundary(RuleBasedBreakIterator.java:549)
	at android.text.method.WordIterator.isBoundary(WordIterator.java:112)
	at android.widget.Editor$SelectionHandleView.positionAtCursorOffset(Editor.java:6297)
	at android.widget.Editor$HandleView.invalidate(Editor.java:5108)
	at android.widget.Editor$SelectionModifierCursorController.invalidateHandles(Editor.java:7177)
	at android.widget.Editor.invalidateHandlesAndActionMode(Editor.java:2331)
	at android.widget.TextView.setShadowLayer(TextView.java:5531)
	at com.tokenautocomplete.TokenCompleteTextView.api16Invalidate(TokenCompleteTextView.java:562)
	at com.tokenautocomplete.TokenCompleteTextView.invalidate(TokenCompleteTextView.java:571)
	at android.widget.TextView.updateAfterEdit(TextView.java:12614)
	at android.widget.TextView.handleTextChanged(TextView.java:12639)
	at android.widget.TextView$ChangeWatcher.onTextChanged(TextView.java:16071)
	at android.text.SpannableStringBuilder.sendTextChanged(SpannableStringBuilder.java:1268)
	at android.text.SpannableStringBuilder.replace(SpannableStringBuilder.java:577)
	at androidx.emoji2.text.SpannableBuilder.replace(SpannableBuilder.java:315)
	at android.text.SpannableStringBuilder.delete(SpannableStringBuilder.java:231)
	at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:337)
	at androidx.emoji2.text.SpannableBuilder.delete(SpannableBuilder.java:49)
	at android.widget.TextView.deleteText_internal(TextView.java:15565)
	at android.widget.TextView.onTextContextMenuItem(TextView.java:14778)
	at android.widget.EditText.onTextContextMenuItem(EditText.java:241)
	at android.widget.Editor$TextActionModeCallback.onActionItemClicked(Editor.java:4742)
	at com.android.internal.policy.DecorView$ActionModeCallback2Wrapper.onActionItemClicked(DecorView.java:2740)
	at com.android.internal.view.FloatingActionMode$3.onMenuItemSelected(FloatingActionMode.java:97)
	at com.android.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:788)
	at com.android.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:152)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:935)
	at com.android.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:925)
	at com.android.internal.view.FloatingActionMode.lambda$setFloatingToolbar$0(FloatingActionMode.java:122)
	at com.android.internal.view.FloatingActionMode.$r8$lambda$Y9Hq7gobR_VYnOvJY4KEpwtp1Qg(Unknown Source:0)
	at com.android.internal.view.FloatingActionMode$$ExternalSyntheticLambda0.onMenuItemClick(D8$$SyntheticClass:0)
	at com.android.internal.widget.floatingtoolbar.LocalFloatingToolbarPopup$2.onClick(LocalFloatingToolbarPopup.java:177)
	at android.view.View.performClick(View.java:7729)
	at android.view.View.performClickInternal(View.java:7706)
	at android.view.View.-$$Nest$mperformClickInternal(Unknown Source:0)
	at android.view.View$PerformClick.run(View.java:30486)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by mags0ft** [comment] 2024-06-17 20:54
I can confirm this: The bug does indeed crash the app, also resulting in Android opening a popup which tells you K-9 keeps crashing after repeating this another time.

**Comment by cketti** [comment] 2024-06-18 16:10
Duplicate of #3951

**Closed by cketti** 2024-06-18 16:10 UTC
