### ISSUE TITLE
Keyboard shortcuts are triggered while typing into search box

### ISSUE THREAD

**Issue by truh** [thunderbird/thunderbird-android#6196] opened 2022-07-27 15:55 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.201

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Galaxy S10+

### Steps to reproduce

1. Open inbox
2. Click on search icon
3. Start typing search term
4. Some of the time the search box will disappear and instead keyboard shortcuts are activated

### Expected behavior

Search box remains open and allows me to search my messages uninterrupted.

### Actual behavior

Search box is closed and already entered text is discarded

**Comment by truh** [comment] 2022-07-27 16:07
If I had to guess, I think the search box is closed when the messages are loaded into the view, the on-screen keyboard stays open and the shortcuts are triggered as I continue entering the search term.

Either it shouldn't be possible to open the search box before the messages are loaded or the the search box shouldn't be closed by the messages loading.

**Comment by cketti** [comment] 2022-09-26 09:49
Duplicate of #5967

**Closed by cketti** 2022-09-26 09:49 UTC
