### ISSUE TITLE
Cut and paste of Mailadresses not possible (eg from TO to CC)

### ISSUE THREAD

**Issue by githubandispensing** [thunderbird/thunderbird-android#7448] opened 2023-12-20 11:49 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Sony Xperia 5 II

### Steps to reproduce

1) press long on a mail address in the TO field
2) press cut
3) press long in the CC field
4) press insert
5) nothing happens

![Screenshot_20231220-114952_Kopie](https://github.com/thunderbird/thunderbird-android/assets/154430417/5ea9e22a-cf75-4793-98e5-b63e392aa561)

### Expected behavior

expected behavior: mail address is inserted

### Actual behavior

nothing happens

work around:
go in any text field: insert. mark mail address, cut or copy. insert Mail address in CC field.

**Comment by RafaelsRamos** [comment] 2023-12-21 14:19
After analysing the issue, I was able to replicate the bug.

On long-pressing on the whole edit text + pasting it on a non-recipient box, what we get is - `"<email_address>, "`. Evidence below:

https://github.com/thunderbird/thunderbird-android/assets/40279132/0b2efa66-2454-4de4-b4c5-948087b1321f

Because our EditText's input type is marked as `textEmailAddress|textMultiLine`, the box cannot process the comma, after the email address.

Given that these edit texts are handled internally by [splitwise's TokenAutoComplete](https://github.com/splitwise/TokenAutoComplete), I suggest we instead add a new cut icon to `recipient_alternate_item.xml`:

https://github.com/thunderbird/thunderbird-android/assets/40279132/2cee84d7-f2ae-4c50-b4f7-07cbc3d8a5b7

**Comment by cketti** [comment] 2024-01-02 21:00
Duplicate of #2961

**Closed by cketti** 2024-01-02 21:00 UTC
