### ISSUE TITLE
A crash of "got an activity result that wasn't meant for us"

### ISSUE THREAD

**Issue by 2021QTester** [thunderbird/thunderbird-android#5373] opened 2021-06-30 12:53 UTC
**Describe the bug**
I am doing some test on K9mail with automated testing tools just like Monkey. Several days ago, I found an error message for logcats, shown as follows. However, no suspicious actions I have found around the occurance of the bug. Would you please find the root cause and fix the bug?

**Environment (please complete the following information):**
 - K-9 Mail version: 5.734
 - Android version: 6.0
 - Device: x86 Android emulator provided by Google
 - Account type: IMAP

**Logs**
06-26 19:48:24.550 12504 12504 E AndroidRuntime: FATAL EXCEPTION: main
06-26 19:48:24.550 12504 12504 E AndroidRuntime: Process: com.fsck.k9, PID: 12504
06-26 19:48:24.550 12504 12504 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=49588908, result=0, data=null} to activity {com.fsck.k9/com.fsck.k9.activity.MessageList}: java.lang.IllegalStateException: got an activity result that wasn't meant for us. this is a bug!
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3699)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3742)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread.-wrap16(ActivityThread.java)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1393)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:148)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: Caused by: java.lang.IllegalStateException: got an activity result that wasn't meant for us. this is a bug!
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageCryptoPresenter.onActivityResult(MessageCryptoPresenter.java:127)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at com.fsck.k9.ui.messageview.MessageViewFragment.onPendingIntentResult(MessageViewFragment.java:448)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at com.fsck.k9.activity.MessageList.onActivityResult(MessageList.kt:1444)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.Activity.dispatchActivityResult(Activity.java:6428)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3695)
06-26 19:48:24.550 12504 12504 E AndroidRuntime: 	... 9 more

**Comment by cketti** [comment] 2021-06-30 12:55
Duplicate of #5302

**Closed by cketti** 2021-06-30 12:55 UTC
