### ISSUE TITLE
Duplicate notifications for new messages

### ISSUE THREAD

**Issue by gunterkoenigsmann** [thunderbird/thunderbird-android#6077] opened 2022-05-20 11:10 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Moto g10

### Steps to reproduce

Part of the trigger seems to be only closing the notifications about a few of the received mails and the  receiving more mails. More I didn't find out in the last months.

### Expected behavior

If n mails arrive I normally get notifications with all their title lines 

### Actual behavior

Rarely I get n notifications with the title lone of one of my mails instead

**Comment by gunterkoenigsmann** [comment] 2022-05-20 11:12
![Screenshot_20220519-111601](https://user-images.githubusercontent.com/5041537/169515974-17934db9-97d2-4509-8b59-b181aa1ade81.png)

I actually got 8 mails, bit only one was about wxMaxima

**Comment by FOSSilizedDaemon** [comment] 2022-06-30 16:05
Same problem. Driving me crazy!

**Comment by gunterkoenigsmann** [comment] 2022-07-09 10:29
Unfortunately that doesn't seem to be this specific Android11 bug:
![Screenshot_20220709-122821](https://user-images.githubusercontent.com/5041537/178101908-bfaec5a4-a424-4889-af1f-f24b9d0e46c2.png)

**Comment by gunterkoenigsmann** [comment] 2022-07-09 10:30
Unfortunately this time it seems not to be a bug in this specific Android11 feature:
![Screenshot_20220709-114305](https://user-images.githubusercontent.com/5041537/178101951-0a372527-ef71-4e59-9de7-02b366bcbd89.png)

**Comment by gunterkoenigsmann** [comment] 2022-07-09 10:31
Issue is still present in version 6.20

**Comment by gunterkoenigsmann** [comment] 2022-07-09 10:34
I have the impression that a trigger might be that a reply arrives to an unread message that is dropped out of the mails kept in K9 by the arrival of the new message.

**Comment by cketti** [comment] 2022-07-09 10:45
When this happens again, please try the following:

1. Force stop the app. This should also remove all notifications.
2. Do something that will start the app again. That will recreate the notifications from K-9 Mail's database. However, don't just open the app if this will open a message list view that contains the messages in the notifications (because that will lead to the notifications being removed). You could add a new "K-9 Unread" widget to the home screen. That process will launch the app, triggering the notifications to be recreated. But it won't display a message list that will lead to the notifications being removed.
3. Check if there are still duplicate notifications and report back.

**Comment by gunterkoenigsmann** [comment] 2022-07-10 06:15
We are lucky: Normally this triggers about once per week. Today I found two more puzzle pieces: I got 6 repeated notifications and one notification about a different mail.
And killing K9 and restarting it using the widget caused only the repeated notifications to reappear.
![Screenshot_20220710-080401](https://user-images.githubusercontent.com/5041537/178133664-633c0e43-0893-4811-b792-a4f3f2652134.png)

**Comment by cketti** [comment] 2022-07-10 13:56
That result is raising more questions than it is able to provide answers.

So you started out with 7 notifications, 6 of them for the same message? And you ended up with 3 notifications, all of them for the same message, the one that was repeated 6 times before the app restart?

What happened to the other message? Was it deleted, moved, or marked as read using another client?

**Comment by gunterkoenigsmann** [comment] 2022-07-10 14:21
Before I made the screenshot the 6 repeated Mails were still displayed in the notification drawer. I believed that the other mail that was no more shown might have been marked as read by tapping on the K9 widget. My kmail wasn't in a working order when I made this screenshot...

**Comment by cketti** [comment] 2022-07-10 16:50
Ok. So it sounds like all duplicate notifications are being restored. The database table that stores information about notifications doesn't allow more than one entry per internal message ID. That suggests that for K-9 Mail all of these entries are distinct messages.

When this happens again, please do the following:
1. Tap an individual notification to open the message. That should open the message view and remove the notification for that message.
2. Don't go back to the message list screen (because that would remove all notifications for messages in that folder). Leave the app using the home button.

Does that remove all duplicate notifications or just the one you tapped?

Repeat the process with the other notifications. Does tapping one of them remove more than one notification?

**Comment by gunterkoenigsmann** [comment] 2022-07-11 20:17
It removes only the duplicate I tried to remove. As if I get 10 duplicates that means I got 10 messages I guess that already made sense.

...but going back to the message list screen doesn't remove the duplicate notifications for me. As it often doesn't do so for non-duplicate messages that might possibly not mean anything, though...

**Comment by gunterkoenigsmann** [comment] 2022-07-16 14:04
Maybe the title is misleading now: I actually get one notification per message. But sometimes (very rarely) many of the notifications get the notification text from the same message.

**Comment by cketti** [comment] 2022-07-26 16:26
I was finally able to reproduce this issue.

Steps to reproduce:
- Receive 9 messages for which notifications are created
- Open the folder containing the messages by regularly opening the app (not through a notification)

When opening the folder, the app tries to remove all notifications belonging to messages in that folder. However, the code to remove notifications contains a bug. Combined with some other behavior this leads to 8 notifications showing the same message.

**Closed** 2022-07-27 20:11 UTC
