### ISSUE TITLE
Google Accounts do not work without turning off "Less secure app access"

### ISSUE THREAD

**Issue by Starcr0ss** [thunderbird/thunderbird-android#5066] opened 2020-12-07 01:11 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

If you are unsure whether or not you have found a bug please post to the support forum instead: https://forum.k9mail.app

**Describe the bug**
K9 mail is unable to sync Google/Gmail accounts unless "Less secure app access" is turned off in Google Account Settings
**To Reproduce**
1. Log into Gmail through K9
2. Get wall of errors
3. Remove account
4. Turn off "Less secure app access" in Google Account Settings
5. Log in again on K9
6. It now works

**Expected behavior**
Use Google's Single Sign On portal instead of logging into the account through K9
**Screenshots**
N/A

**Environment (please complete the following information):**
 - K-9 Mail version: 5.725
 - Android version: 10
 - Device: Samsung Galaxy Tab A 10.1 (2019)
 - Account type: Whatever Gmail uses, default settings

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:
The app already works and I don't want to undo the settings I changed. It tells me that it has a problem with incoming and outgoing until I turn off "Less secure app access". No emails appear until fixed.

**Comment by cketti** [comment] 2020-12-09 12:49
Duplicate of #655

**Closed by cketti** 2020-12-09 12:49 UTC
