### ISSUE TITLE
Neither list of mails nor view of individual mails show sender address or domain, makes phishing possible

### ISSUE THREAD

**Issue by thfi** [thunderbird/thunderbird-android#5205] opened 2021-03-22 09:58 UTC
An organization was recently subject of a phishing attack were mails were send to many employees. The mail claimed to come from a high-level corporate officer. Let's call him Big Boss with his regular mail address of big.boss@corp.com. The authors of the phishing mail were aware of the corporate officer's name and sent the mail in his name, but with some randomly generate mail address: Big Boss <abc123@google.com>
K-9 Mail, used in version 5.732, shows in the list of all mails (mailbox content) just sender's claimed name ('Big Boss'), subject, and part of the mail body. When opening the mail for reading, still only claimed sender name, subject, mail body and other information is shown, but not the sender's mail address or at least the domain of the email address ('corp.com' vs 'google.com'). A well-crafted phishing mail cannot be discerned from a valid email of the real sender, despite that *it would be really easy to see in this case if the sender's mail address would be visible*.
I know that there is a 'show headers' function which allows you to inspect the underlying data including the sender's email address, but this is quite technical (thus not an option for many laymen) and requires to scroll through a lot of headers to find just the one line you are looking for.

**Comment by njeyaakili** [comment] 2021-03-22 14:41
Under settings - "general settings/display" there is a "show correspondent name" checkbox that determines whether the correspondent name or email address is shown. When unchecked the email address is displayed. I would like to be able to see both the name and the email address, but unchecking that box does address this specific phishing issue.

not being able to see message text parts and so urls is, in my view, a more serious issue.

**Comment by cketti** [comment] 2021-03-22 15:02
As mentioned, you can switch to displaying the email address. There's also a feature request for displaying both the display name and the email address.


Duplicate of #1119

**Closed by cketti** 2021-03-22 15:02 UTC
