### ISSUE TITLE
k9 crashes using wrong signs 

### ISSUE THREAD

**Issue by suuuehgi** [thunderbird/thunderbird-android#724] opened 2015-07-27 18:03 UTC
My k9 crashes when entering different combinations of characters to the recipient field of an email.

Just typing a forward slash `/` to the _To_-field even does it.

**Comment by smoneck** [comment] 2015-07-27 18:06
P.s.: K9 version 5.006 on Android 4.4.4

**Comment by cketti** [comment] 2015-07-27 18:07
Please provide a stacktrace of the crash, e.g. by following these instructions: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by smoneck** [comment] 2015-07-27 18:34
Unfortunately is this page no help to me. I don't have a computer with me and the other program doesn't run with my os-version. *CatLog* works but I don't know how to get it out of there. Furthermore is there no `k9-log.txt` (`find -name "k9-log.text"`).

**Comment by smoneck** [comment] 2015-07-27 18:39
I mean where exactly lies the logfile of k9?

**Comment by smoneck** [comment] 2015-07-27 19:18
Sorry, that was a numb question …

But `logcat -d -v time k9:V '*:S' AndroidRuntime:E` is not giving me anything besides 

> --------- beginning of /dev/log/main

**Comment by ConteDiMonteCristo** [comment] 2015-07-30 15:48
With regard to logcat I had a similar issue and resolved by:
* adb logcat -v time k9:V *:S AndroidRuntime:E > my_log.txt
* run k9 on the device or simulator and reproduce the crash
* stop the adb command piping to the file by Ctrl-C
* read the full log in my_log.txt

I think the -d option dump whatever has been accumulated in the log buffer and might or might not contain your event

Hope it helps

**Comment by smoneck** [comment] 2015-08-02 18:41
Thank you for the help but output does not change. And I have not access to adb since I only use the `terminal emulator`.

**Comment by cketti** [comment] 2016-01-17 08:04
Without a debug log there's no way to know what went wrong. But since most of the code that deals with recipients is now rewritten anyway, this might not be an issue in the next major stable version.

**Closed by cketti** 2016-01-17 08:04 UTC
Labels: status: needs information
