### ISSUE TITLE
Two message lists displayed on top of each other

### ISSUE THREAD

**Issue by saber716rus** [thunderbird/thunderbird-android#5962] opened 2022-03-13 09:37 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

Google Play

### Android version

11

### Device model

Redmi note 8 pro

### Steps to reproduce

1. I enter the letter
2. leave

### Expected behavior

the table of letters does not become a background picture

### Actual behavior

the table of letters becomes a picture

**Comment by saber716rus** [comment] 2022-03-13 09:38
![Screenshot_2022-03-13-12-30-49-187_com fsck k9](https://user-images.githubusercontent.com/22714555/158053658-f591a55c-8ce2-44bf-b42a-acdc25008927.jpg)

**Comment by cketti** [comment] 2022-05-01 17:32
Can you provide more detailed instructions on how to reproduce the error?

**Comment by gunterkoenigsmann** [comment] 2022-05-17 04:52
On my moto G9 play and K9 beta from the play store this is sometimes triggered by tapping on a "new mail" notification in order to open K9 and the pressing the virtual back button of my device in order to go back to the unified inbox (I have two accounts): If I scroll down after that there is a chance that the background of my unified messages view isn't white l, but the unscrolled unified messages view.

An interesting detail: If I delete messages they will be deleted in the unscrolled messages view in the background, too. And if I tap a mail to read it and go back to the unified inbox the problem still persists.

**Comment by cketti** [comment] 2022-07-13 13:51
Duplicate of #4452

**Closed by cketti** 2022-07-13 13:51 UTC
