### ISSUE TITLE
Crash when cutting text from To field

### ISSUE THREAD

**Issue by Slion** [thunderbird/thunderbird-android#5595] opened 2021-08-21 16:14 UTC
**Describe the bug**
Crash when cutting text from To field in new message screen.

**To Reproduce**
1. Create new email
2. Type 'abc' in To field
3. Select the text you just input and long press to bring up the edit menu
4. Select cut
5. App crash

**Expected behavior**
Should not crash.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.804
 - Android version: 9
 - Device: FxTec Pro1
 - Account type: IMAP

**Additional context**
Does not crash if doing cut using keyboard shortcut rather than touch input

**Logs**
Please take some time to [retrieve logs](https://github.com/k9mail/k-9/wiki/LoggingErrors) and attach them here:

**Comment by cketti** [comment] 2021-08-21 19:35
Duplicate of #3951

**Closed by cketti** 2021-08-21 19:35 UTC
