### ISSUE TITLE
Unable to create/rename folders

### ISSUE THREAD

**Issue by tejonaco** [thunderbird/thunderbird-android#7486] opened 2024-01-07 14:34 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I can find anywhere the options to add folders or rename existent folders.

### Suggested solution

Option to add folders and rename it.

**Comment by wmontwe** [comment] 2024-01-11 12:30
This is a duplicate of: #1389

**Closed by wmontwe** 2024-01-11 12:30 UTC
Labels: enhancement, unconfirmed
