### ISSUE TITLE
URL detection not working with special characters

### ISSUE THREAD

**Issue by gitflo** [thunderbird/thunderbird-android#5567] opened 2021-08-12 15:15 UTC
The URL detection, used for creating links out of URLs found in an email, is not working correctly when the URL contains German umlauts. I haven't been testing if further characters may cause that behaviour, too, although being allowed.

Please see the attached screenshots as well as a sample mail.
![screenshot_K-9-Mail_NOK](https://user-images.githubusercontent.com/2064802/129222510-ef891d99-9363-4546-a34c-1bc6689a2a65.png)
![screenshot_Thunderbird_OK](https://user-images.githubusercontent.com/2064802/129222516-3f46abd4-543e-4730-b15b-9cf12c427494.png)
[example-mail.eml.txt](https://github.com/k9mail/k-9/files/6976575/example-mail.eml.txt)

**Environment (please complete the following information):**
 - K-9 Mail version: v5.802

Side note: The bug had already been present before, and the screenshot was taken with the previous version - I just didn't want to open a ticket while the works on the new version were already ongoing.

**Comment by cketti** [comment] 2021-08-12 15:22
Duplicate of #4080

**Closed by cketti** 2021-08-12 15:22 UTC
