### ISSUE TITLE
Last update deleted all my accounts

### ISSUE THREAD

**Issue by Ciapino** [thunderbird/thunderbird-android#2647] opened 2017-07-28 09:51 UTC
This morning I updated K-9 through Google Play: it deleted all my accounts.

### Expected behavior
To see my many accounts set up and running as before

### Actual behavior
K-9 shows as a new install, without any account

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version: 5.207

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2017-07-30 12:38
Duplicate of #750 and closing for the same reason - there's nothing we can do without some kind of debug information.

**Closed by philipwhiuk** 2017-07-30 12:38 UTC
Labels: status: needs information
