### ISSUE TITLE
Search with umlaut characters not working

### ISSUE THREAD

**Issue by kastnerp** [thunderbird/thunderbird-android#3708] opened 2018-11-12 16:04 UTC
### Expected behavior
I am German and, thus, would expect the search to work with umlauts (ä, ö, ü) if those are contained in the header, body, etc. of the message.

### Actual behavior
Search does not yield any results when using umlauts.

### Steps to reproduce
1. Open app
2. Search for mail by word, e.g. "Özbay"
3. Search yields no results

However if you:

2. Search for mail by word, e.g. "Oezbay"
3. Search yields all expected results including "Özbay"

I supposed there might be an easy fix if those characters could be mapped to the corresponding ASCII workaround-characters such as ö->oe, ü->ue, ä->ae, since this seems to be implemented already.

### Environment
K-9 Mail version: 5.600

Android version: 8.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by ckaotik** [comment] 2019-01-26 12:36
This affects only the server search (tested at least with Gmail), local searching works fine. When using characters such as German umlauts (äöüß and so on), the app displays a short popup "search failed" and displays no results. 
Umlauts are quite common, e.g. for street addresses ("Straße").

**Comment by dhebbeker** [comment] 2019-03-02 15:59
I experienced the same issue. Specifically: I tested this with 3 different e-mail providers (all IMAP). One (one.com) worked the other two (Gmail and Outlook) did not succeed to perform a remote search of a word containing an umlaut (error message). Local search always worked.

Also I was not able to find messages by paraphrasing the umlauts (ä :arrow_right: ae). :disappointed: 

### Environment
 
- K-9 Mail version: 5.600
- Android version: 7.0
- Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2020-10-06 21:59
Duplicate of #3607

**Closed by cketti** 2020-10-06 21:59 UTC
