### ISSUE TITLE
'Unified Inbox' string not refreshed after changing language

### ISSUE THREAD

**Issue by iiitomo** [thunderbird/thunderbird-android#5129] opened 2021-02-07 23:32 UTC
**Describe the bug**
Changing language does not work on the 'Unified Inbox' string (top of the default view).

**To Reproduce**
1. Set up at least 2 accounts (so that you have a unified inbox)
2. Go to Settings -> General Settings -> Display -> Language , and change language
3. Go back to your Unified Inbox
4. See that all the UI has switched to the new language, except the 'Unified Inbox' string at the top of the default view. Even after restarting the app.

**Expected behavior**
That string should be refreshed as well.

**Environment:**
 - K-9 Mail version: 5.727
 - Android version: 10
 - Device: Redmi Note 7
 - Account type: IMAP

**Comment by cketti** [comment] 2021-02-07 23:43
Duplicate of #4407

**Closed by cketti** 2021-02-07 23:43 UTC
