### ISSUE TITLE
App crashing and refuse to open

### ISSUE THREAD

**Issue by dausruddin** [thunderbird/thunderbird-android#7953] opened 2024-06-15 11:56 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Google Play

### Android version

14 - Crdroid custom ROM

### Device model

Poco F3

### Steps to reproduce

1. Run K-9 Mail

### Expected behavior

App opens

### Actual behavior

App crashes

### Logs

```
time: 1718452018942
msg: java.lang.IllegalArgumentException: password must not contain line break
stacktrace: java.lang.RuntimeException: Unable to create application app.k9mail.K9App: java.lang.IllegalArgumentException: password must not contain line break
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7314)
	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2337)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8503)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:555)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
Caused by: java.lang.IllegalArgumentException: password must not contain line break
	at com.fsck.k9.mail.ServerSettings.<init>(ServerSettings.kt:26)
	at com.fsck.k9.ServerSettingsAdapter.fromJson(ServerSettingsSerializer.kt:84)
	at com.fsck.k9.ServerSettingsAdapter.fromJson(ServerSettingsSerializer.kt:43)
	at com.squareup.moshi.JsonAdapter.fromJson(JsonAdapter.java:70)
	at com.fsck.k9.ServerSettingsSerializer.deserialize(ServerSettingsSerializer.kt:19)
	at com.fsck.k9.AccountPreferenceSerializer.loadAccount(AccountPreferenceSerializer.kt:33)
	at com.fsck.k9.Preferences.loadAccounts(Preferences.kt:81)
	at com.fsck.k9.Preferences.getAccounts(Preferences.kt:104)
	at com.fsck.k9.Core.setServicesEnabled(Core.kt:48)
	at com.fsck.k9.Core.init(Core.kt:35)
	at com.fsck.k9.CommonApp.onCreate(CommonApp.kt:47)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1385)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7309)
	... 9 more

```

**Comment by cketti** [comment] 2024-06-17 09:55
This bug is already fixed. The fix will be included in the next beta version, K-9 Mail 6.902.

Duplicate of #7855

**Closed by cketti** 2024-06-17 09:55 UTC
