### ISSUE TITLE
Can able to modify the whole mail content after forward or reply using CSS 

### ISSUE THREAD

**Issue by dev-ramkumar** [thunderbird/thunderbird-android#6784] opened 2023-03-25 11:40 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Google Play

### Android version

9

### Device model

Oppo A31

### Steps to reproduce

1. Use any mail client to send HTML email (sample code given below)
2. Open that mail in k-9 mail app
3. Click forward or reply button and add any content in body of email and send
4. Open that forwarded mail
5. you can see that the CSS has access to all the contents of the mail including forward headers and message added by forwarder

#sample html code
```
<html>
  <head>
    <style>
      
* {
border: 1px solid blue !important;
margin: 2px !important;
}
      
    </style>
  </head>
  <body>
    <div id='body'>
      Jerry
    </div>
  </body>
</html>
```

### Expected behavior

CSS should have only access to original mail content not the all content of the mail after reply/forward 

### Actual behavior

After the mail forwarded the CSS has access to all the parts of the mail. so hackers may use this to modify the mail content as per their wish after forwarding.

### Logs

Original mail:
![Screenshot_2023-03-25-17-01-00-03](https://user-images.githubusercontent.com/86308420/227715202-52a8f869-7ff1-4b56-98ef-2ed98c882d59.jpg)

After Forwarded:
![Screenshot_2023-03-25-17-02-32-06](https://user-images.githubusercontent.com/86308420/227715170-f34ecf4f-14a3-4221-bfd2-bb96f9bab1f8.jpg)

**Comment by cketti** [comment] 2023-03-28 09:37
Duplicate of #6784

**Closed by cketti** 2023-03-28 09:37 UTC
