### ISSUE TITLE
Incorrectly shown attachment filename

### ISSUE THREAD

**Issue by anyuta1166** [thunderbird/thunderbird-android#4968] opened 2020-10-02 08:15 UTC
**Describe the bug**
K-9 mail incorrectly shows attachment filename if RFC 5987 encoding is used.

A excerpt from the source code of a mail that I've received:

```
Content-Type: application/vnd.openxmlformats-officedocument.wordprocessingml.document;
 name="=?UTF-8?B?0JrQsNC6INC00L7QsdGA0LDRgtGM0YHRjyDQtNC+INC+0YTQuNGB0LAu?=
 =?UTF-8?Q?docx?="
Content-Transfer-Encoding: base64
Content-Disposition: attachment;
 filename*0*=UTF-8''%D0%9A%D0%B0%D0%BA%20%D0%B4%D0%BE%D0%B1%D1%80%D0%B0;
 filename*1*=%D1%82%D1%8C%D1%81%D1%8F%20%D0%B4%D0%BE%20%D0%BE%D1%84%D0%B8;
 filename*2*=%D1%81%D0%B0%2E%64%6F%63%78
```
The mail was composed by:
```
User-Agent: Mozilla/5.0 (Windows NT 6.3; WOW64; rv:68.0) Gecko/20100101
 Thunderbird/68.12.0
```

K-9 Mail shows attachment filename as "UTF-8''%D0%9A%D0%B0%D0%BA%20%D0%B4%D0%BE%D0%B1%D1%80%D0%B0", while it should be "Как добраться до офиса.docx".

**Screenshots**

![Screenshot_20201002-111151](https://user-images.githubusercontent.com/726409/94902015-35462500-04a0-11eb-836f-50b374727cbb.png)

**Environment (please complete the following information):**
 - K-9 Mail version: [5.600]
 - Android version: [9]
 - Device: [Motorola G7 Plus]
 - Account type: [IMAP]

**Comment by cketti** [comment] 2020-10-02 12:20
This is fixed in 5.7xx beta versions. See [How do I become a beta tester?](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68)

Duplicate of #1466

**Closed by cketti** 2020-10-02 12:20 UTC
