### ISSUE TITLE
App lock feature with pin (etc.)

### ISSUE THREAD

**Issue by Lungenpest** [thunderbird/thunderbird-android#7484] opened 2024-01-06 11:47 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

all?

### Problem you are trying to solve

I would like to have my email app secure with a pin.
It should be a different pin to my screen unlock pin.

### Suggested solution

Implement pin unlock feature for the app.
Best showcase is Nine Email & Calendar, this app have good security features.

Also other possibilities to lock the app would be great for other users (pattern, biometrical, screen unlock pin, ...)

### Screenshots / Drawings / Technical details

![Screenshot_20240106-124403](https://github.com/thunderbird/thunderbird-android/assets/64774660/9902a7d1-fb9d-4b56-badb-45ffc47dc6e7)
Example App Nine Email & Calendar

**Comment by cketti** [comment] 2024-01-16 19:02
Duplicate of #753

**Closed by cketti** 2024-01-16 19:02 UTC
Labels: enhancement, unconfirmed
