### ISSUE TITLE
Add the ability to login to an account once it's already added but not authenticated

### ISSUE THREAD

**Issue by qverkk** [thunderbird/thunderbird-android#8255] opened 2024-10-07 18:13 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b1

### Problem you are trying to solve

After exporting my settings from k9 mail, i imported them to thunderbird but didn't have the time to login to all of the accounts i had. So i just closed the app and decided i'd do it another day. Well, today i've tried to use the app to login to my already existing email profiles within thunderbird, there was no obvious button to login to the already defined profiles/accounts. **I managed to find a not obvious solution: go to account settings -> fetching mail -> incoming server -> click next -> now it lets you login to the account.** I didn't find any easier way for this, it might be a deal breaker for some users if they have for eg. a connection issue and the smtp server doesn't let them sign in and they'll just try in a few hours or days.

### Suggested solution

Detect if the account is logged in, if it's not add a button to the account settings page for a given account, or just show a prompt to let the user know that the acc isn't authenticated and he has to login :smile:

**Comment by cketti** [comment] 2024-10-09 12:43
Duplicate of #6120

**Closed by cketti** 2024-10-09 12:43 UTC
Labels: type: enhancement, unconfirmed
