### ISSUE TITLE
Synchronisation disabled - Android 6.0.1

### ISSUE THREAD

**Issue by Schwefelholz** [thunderbird/thunderbird-android#970] opened 2015-12-21 15:55 UTC
Using two devices with Android 6.0.1 (N5 and N7 (2013)) I'm experiencing the synchronisation getting disabled in (random?) intervalls.
It seems I can get it enabled again by switching WIFI Off and on again.

**Comment by Valodim** [comment] 2015-12-21 18:44
sounds like it might be related to #857

**Comment by Schwefelholz** [comment] 2015-12-21 18:56
That might be. However, I did not experience this with 6.0, but only with 6.0.1.

**Comment by galexmay** [comment] 2015-12-22 05:47
I have a similar problem where the next poll is showing as being 1 hour ago.

**Comment by Jens14L** [comment] 2015-12-26 23:51
I experience no issues of K-9 under [Cataclysm](http://forum.xda-developers.com/google-nexus-5/orig-development/rom-cataclysm-nexus-5-t2518660), Android 6.0.1.

**Comment by osirisinferi** [comment] 2015-12-28 17:52
I'm having the same problem here, Nexus 5X on Android 6.0.1 with K-9 Mail 5.007.

I've set "Background sync" on "Always" now, (was: "When 'Auto-sync' is checked"), as that is suggested in the [FAQ](https://github.com/k9mail/k-9/wiki/FrequentlyAskedQuestions#anchor15). But time will tell if that's gonna work..

**Comment by Schwefelholz** [comment] 2015-12-28 17:58
Background Sync "Always" is set in my N7, but doesn't seem to make a Differenzen.

**Comment by osirisinferi** [comment] 2015-12-28 23:19
Hmm, indeed, that didn't make any difference :sob:

**Comment by cketti** [comment] 2015-12-28 23:36
Please record a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) while this happens.

**Comment by hdbrink** [comment] 2015-12-29 08:49
K-9 Mail 5.007 on Nexus 7 with Android 6.0.1
since the last update syncing keeps disabling itself. I trolled all the settings and tweaked here and there but nothing helps when I look again syncing is disabled. it also does not matter if we set the background sync to Always or when auto sync is enabled. the tablet does not have an auto sync global setting. my LG G3 phone has a global sync button though.running Android 5.0 and seems to work fine. so problem is probably Android 6.0.1?

**Comment by Schwefelholz** [comment] 2015-12-29 17:03
Hello, this is a debug log. Actually, I enabled logging while my N7 was in the state of disabled synchronization. I synced once or twice manually and then switched Wifi off and on again. This enabled the synchronization again. I left logging on and this afternoon I realized that synchronization got disabled again somewhen. Unfortunately, I don't know the exact time. Again I manually synced once or twice and switched Wifi off and on again. Once more, synchronization got enabled afterwards.

Hope this helps debugging the issue.

[k9-log.txt](https://github.com/k9mail/k-9/files/74147/k9-log.txt)
[k9-log_1.txt](https://github.com/k9mail/k-9/files/74148/k9-log_1.txt)

**Comment by lbdroid** [comment] 2015-12-30 15:16
FWIW: It *is* doze that is causing this issue.
The current workaround is to whitelist k9 from doze.

System Settings --> Apps
Hit the "gear" button up beside the menu button, brings you to "configure apps".
Hit "Battery Optimization", choose "all apps" from the spinner, click k9mail, and select "Don't Optimize". That will prevent doze from knocking it out.

**Comment by hdbrink** [comment] 2015-12-31 07:19
Thank you, workaround seems to be working.
Luckily for now it does not seem as if k-9 is using much more battery
without optimization.

**Comment by Schwefelholz** [comment] 2015-12-31 08:56
This workaround seems to be working for me as well. Leaving the issue open though, since there might be a better solution in future. Not sure about the effect on battery usage right now.

**Comment by osirisinferi** [comment] 2016-01-03 16:46
Well, don't know for sure about that "not using much more battery" on my Nexus 5X:

![screenshot_20160103-174028](https://cloud.githubusercontent.com/assets/14792563/12079672/9a008762-b241-11e5-8ad1-c691aad06541.png)

OK, granted, this isn't with much extensive usage (just the occasional WhatsApp/browsing/e-mail), but I thínk K-9 Mail's unoptimized Push mail has quite the impact.

**Comment by lbdroid** [comment] 2016-01-04 19:24
@osirisinferi For what its worth, the power consumed by k9mail can be dramatically impacted by a lot of factors, number of accounts, number of directories being synchronized, configuration of the IMAP server, etc. In the end though, it won't be drawing any more power with this workaround than it did prior to the introduction of doze.

**Comment by yuslepukhin** [comment] 2016-01-11 05:41
Running Android 6.0.1 on Nexus 6.
Have two Google accounts that are accessed through GMail. 

K-9 is used to access two unrelated IMAP accounts.

One of the above Google accounts is not really used on the phone. However, if I completely disable its sync then I notice this K-9 thinks that AutoSync is off system wide even though one if the Google accounts is full sync enabled.

Once I re-enable at least App Data sync on that disabled account K-9 detects that AutoSync is on again with the next sync 3 hours ago.

**Comment by gadgetfan10** [comment] 2016-01-14 17:41
Just as an added data point, I see this happening on my Nexus 7 (2013), but not on my Nexus 9. Both are running 6.0.1. As far as I can tell, K-9 has not been added to the whitelist on the N9 or anything like that.

**Comment by lbdroid** [comment] 2016-01-14 18:14
It *definitely* happens on N9 (we have two N9's). Yours is probably not getting all the way to sleep. Possibly something is holding a wakelock.

**Comment by gadgetfan10** [comment] 2016-01-15 16:05
My mistake. Putting the N7 and N9 next to each other and leaving them both alone for the same amount of time did show that behavior on the N9.

I'll have to do further testing to see if there's something keeping the N9 out of Doze or if it's actually restarting the syncing on its own somehow.  Just odd that this would be the first time I've noticed the problem on the N9.

**Comment by lbdroid** [comment] 2016-01-15 16:09
Just bumping the things around can keep them out of doze. I'm not actually sure if the 7 has a low power motion sensor that it can be used for this purpose, so it could have a greater tendency to go into doze, whereas the 9 will reset its timers by being moved slightly.

**Comment by Rhenania** [comment] 2016-04-15 08:54
Having the same problem with a HTC One M9 since having upgraded to Android 6.0 (the latest version available from HTC). Before updating to Android 6.0, on 5.xx everything was o.k.
As suggested, I tried to disable all 'power saving' functions, no luck...

**Comment by philipwhiuk** [comment] 2016-04-15 10:06
Please record a new debug log if this is still happening with whitelisting disabled @Rhenania

**Comment by Rhenania** [comment] 2016-04-15 11:16
Here‘s the requested bug report with all power saving options disabled.

 

Rgds

**Comment by philipwhiuk** [comment] 2016-04-19 12:05
Debug log as referenced above

[debugLog.txt](https://github.com/k9mail/k-9/files/225816/debugLog.txt)

**Comment by lbdroid** [comment] 2016-04-20 15:41
Why is this bug still labeled as "needs info"? This is a matter of doze kicking in. No info is needed -- the cause is well established.

**Comment by philipwhiuk** [comment] 2016-04-20 17:19
There's a bug for Doze - #857. I believe this bug was for issues despite disabling Doze. We still need to get to the bottom of those.

**Comment by takaox** [comment] 2016-06-07 01:21
In my case, K9's periodical sync works but push doesn't work in Doze on Sony xperia z5 with 6.0 Marshmallow. K9 is whitelisted and notification is set as "High priority" (←GCM setting?).

Though it's Doze caused problem, can next update of K9 solve this???
So far I put "Android system" app into whitelist, then the push seems working fine.
But im not sure if it's just temporal behavior....

**Comment by Rhenania** [comment] 2016-06-07 07:36
About the same symptoms I also observe on my HTC M9. Was waiting for either an Android update or a K9 fix. Being fed up with waiting, now also considering installing an alternative ROM.

**Comment by takaox** [comment] 2016-06-07 08:34
As Rhenania said above, yes, we are waiting for "either an Android update or a K9 fix".
Hope both are aware of this to make out a fix. Whether push works or not, it's very fatal issue for some users.

**Comment by testman86** [comment] 2016-06-07 15:36
I just want to add that I have the same problem with latest OmniROM and had it with CM13. Sometimes push is working, and sometimes not.

**Comment by demure** [comment] 2016-06-07 16:04
On my Nexus 5x (rooted and running 6.0.1), the solution/workaround @lbdroid posted has worked fine since I used it a few months ago.

**Comment by takaox** [comment] 2016-06-08 02:04
All what I have done didn't work, even the way @lbdroid mentioned...
Or if I would root my phone, will there be more options to do?
So far I set K9 poll frequency as every minute.

**Comment by JeppeTh** [comment] 2016-06-14 14:10
Is all info need available? I still get the issue - disabling K-9 in app optimising doesn't help. Nor changing sync to "always". It seems log gets truncated - not sure if there's enough infor here:
[k9-log.txt](https://github.com/k9mail/k-9/files/314111/k9-log.txt)

Please let me know if additional info is required, I gladly try to help out.
I don't want to be forced to abandon this app ;-(

**Comment by JeppeTh** [comment] 2016-06-17 16:06
I realise that if "Power saving mode" is completely disabled syncing works.

**Comment by takaox** [comment] 2016-06-22 01:58
Recently my Xperia Z5 Compact had updated to [Android 6.01 - 32.2.A.0.224].
The doze mode seems to have gone and Sony's Stamina mode is back now.

But point is that no matter whether I use Stamina mode, K9's push got recovered to 
properly work now as it has been on old Android versions except for [6.0]. 
(Of course, if you use Stamina mode on, then K9 still needs to be whitelisted)

Now it's proved that after all the problem was obviously being caused by Doze, 
Doze's [Optimize] even didn't work, it almost has killed core functions.

Not sure how other users with similar phones would be now....?
Hope this update helped many like us.

**Comment by cdmackay** [comment] 2016-07-02 22:25
I believe I have this problem; let me know if a log would be useful.

Samsung Note 4, 6.0.1; global sync enabled. On wifi.

k-9 beta 5.109

IMAP account; polling disabled for all folders. push enabled ("1st class") for one folder (not INBOX).

Background sync when Auto-sync.

After a few hours, k-9 reports "syncing disabled". In settings, that folder is still set to push: 1st class. Changing push to none, then back to 1st class, seems to temporarily sort the issue, for a few hours, then back to "syncing disabled".

I don't think this is Doze, since:

- I have it disabled entirely: Settings - Battery - app power saving - OFF. Assuming that is what Samsung call Doze? Both other power saving modes (regular, and Ultra) are disabled)

- Doze is supposed to kick in after 3 days, minimum, not just a few hours.


are my symptoms in line with this bug, now that Doze is being treated separately?

please let me know if it more data would be helpful, or a log (some have said that the log is truncated and it doesn't happen for several hours).

thanks much.

**Comment by lsk333** [comment] 2016-08-11 14:39
I have a Samsung Galaxy Note 4.  After my phone's last software update, K-9 mail has been so erratic.  Sometimes it works fine and the next thing I know syncing is disabled.  ...or it will tell me the next sync is some hour or more in the past.  I did find that when I turned on WiFi and then turned it off again, syncing was disabled.  Now that I know shutting WiFi off causes K-9 to stop syncing, I can immediately check it to get it started again.  However, I don't know why it decides to stop syncing otherwise.  I went into my settings and made sure that K-9 was not set to doze to save battery life.  That has not helped.  What's more, sometimes it's a crap-shoot whether I can get it to start syncing again.  Frankly, I'm frustrated.  I need my email notifications.  I have a business and I need to know when my clients have sent mail.  This needs to get fixed.

**Comment by schtritoff** [comment] 2016-08-20 04:41
Also having same problem. Syncing disabled shows up if I set Global settings -> Network -> Background sync -> Always. When I set the option to 'When auto-sync is checked' everything worked fine again.
Samsung Galaxy S5, official 6.0 ROM, battery optimization was enabled (default system settings, didn't touch that), K9 5.010

**Comment by AndrueCope** [comment] 2016-09-21 20:25
S7 Edge here and K9 is pretty much incapable of notifying me of new mail. It's configured for IMAP push and is working fine on my old S3 Neo. Setting it to poll doesn't help.

:(

**Comment by LechnerRobert** [comment] 2016-09-26 10:50
same Problem on Nexus 5X Android 7.0

any solution ??

**Comment by AndrueCope** [comment] 2016-09-26 10:54
I have found that white listing the app solved the problem. You have to white list it in the correct place though.

http://www.tech-recipes.com/rx/58206/set-battery-optimization-samsung-galaxy-s7/

While you're there consider white listing GMail, Calendar and Contacts sync since they were suffering as well.

**Comment by LechnerRobert** [comment] 2016-09-26 11:10
i have "white listed" k9mail now, 
thank you for your answer, 
will report if this helps 

found that "tasker" app was  whitlisted automaticaly
maybe k9mail can do this also?

**Comment by atilakiss** [comment] 2016-09-27 10:36
Using IMAP settings for email (yahoo in my case) k-9 working perfect on android 6.0, the same with pop3 settings are not syncing when phone is in standby, otherwise is work fine

**Comment by AndrueCope** [comment] 2016-10-10 20:18
I'm still having occasional issues. Sometimes the idle IMAP connection is being allowed to terminate. Just now I ended up with the draft monitoring still active but my INBOX terminated. I've adjusted the K-9 keep-alive to 12 minutes to see if that helps but obviously that's going to increase battery usage :-/

**Comment by Myjk** [comment] 2016-11-12 13:54
Same here on Nexus 5x with Android 7.0.

**Comment by AndrueCope** [comment] 2016-11-12 21:52
Mine has been a lot better since installing [Disable Doze](https://play.google.com/store/apps/details?id=de.geroo.disabledoze&hl=en_GB).

Curiously the two apps I use to turn things on and off on a schedule sometimes fail to turn wifi on but otherwise my phone is now scheduling events like it should. Battery life isn't much affected either.

**Comment by Myjk** [comment] 2016-11-13 22:24
It's strange, because synchronisation works randomly, and I can't figure out what causing it starts to work again (for some time of course).

**Comment by philipwhiuk** [comment] 2016-11-14 01:06
I've been looking at causes of sync failures recently. I may have some changes to go in for the future surrounding better handling of network disconnection. 

I've been playing around with my device sending it in and out of aeroplane mode and onto a captive portal (which K-9 is not a fan of because it thinks it has a network connection but it doesn't in practice).

Also there's a permanent sync disabling function which prevents sync until the app is actually killed. It was added because of some bad behaviour where we didn't reflect an error case. But I'm no longer convinced that case is justified and if it is we could do better.

I don't want to delay the current stuff though (it's been a large 'merge window'), so I'll work on it and get it ready for a future release after the current (large) release is done.

**Comment by gdt** [comment] 2016-11-14 01:24
syncthing is having similar problems:  https://github.com/syncthing/syncthing-android/issues/543

I have K-9 whitelisted; before that it was not reliable.  For me, the syncthing happens after doze and from the debug logs syncthing thinks it doesn't have working WiFi.  Turning WiFi off/on causes it to get a WiFi OK notification and then things work.   So my theory is that in coming out of doze (probably, or maybe just some othertimes) somehow a notification to the apps about WiFi is wrong/missed.

**Comment by AndrueCope** [comment] 2016-11-14 08:30
One thing that has helped my phone immensely is [Disable Doze](https://play.google.com/store/apps/details?id=de.geroo.disabledoze&hl=en). But I'm still getting times when one of the IMAP connections (usually Inbox) dies and is never recovered. The other one 'drafts' will remain connected.

I don't see anything particularly in my server logs. Just a note that a connection timed out and was closed.

**Comment by AndrueCope** [comment] 2016-11-14 08:35
I put the idle timeout back to the default BTW. 12 minutes didn't help any. Interestingly it _seems_ that the dropped connection only happens on wifi. It also seems to relate to the switch over from data to wifi when I get home. I'm not compeltely sure but I don't think I've ever had the phone lose a connection at work. It seems to always be the evening when I'm at home.
For what it's worth my scheduling app does the following:
2300 - turn off wifi and syncing.
0700 - turn on syncing.
1715 (roughly when I get home) turn on wifi.

**Comment by Myjk** [comment] 2016-11-15 20:22
Indeed,  disconnecting WiFi restores synchronisation in k9. Perhaps programmers of k9 should use this as a solution.

**Comment by kadaj** [comment] 2016-12-08 03:20
I am having the same issue with Samsung Galaxy Note 4. I have power saver on, but whitelisted (turned off) K-9 Mail. But after some time, the sync shows disabled. I have sync always set in global settings. When I turn off power saving it works.

**Comment by nyetwurk** [comment] 2017-01-09 22:14
Same issue, Nexus 5, 7.1.1

**Comment by Bugsbane** [comment] 2017-01-14 18:25
Getting this on Samsung Galaxy S5

**Comment by markusd112** [comment] 2017-02-07 09:27
Same problem with my Samsung Galaxy Tab S2 (Android 6.0.1) and Wileyfox Swift with Lineageos 14.1: sync is disabled and IMAP push doesn't work any longer. In Lineageos 14.1 I can't find any power saving options described as workaround above...

**Comment by AndrueCope** [comment] 2017-02-07 09:30
Did you try installing Disable Doze as per my link above?

This seemed to be the cure for me. At least until the next major release of Android where apparently the Doze functionality is even more aggressive :(

**Comment by markusd112** [comment] 2017-02-07 09:58
On my Samsung Galaxy Tab S2 it works by setting background sync in K9 global settings to "always". 

On my Wileyfox with Lineageos it doesn't work with this setting. Additionally there doesn't exist a doze function to disable (or I cannot find it: it isn't in the app settings menu, nor in the battery settings...).

**Comment by kadaj** [comment] 2017-02-07 10:03
I don't think the Android OS respects the app specific settings if the power saver is turned on with background data restriction enabled. Could be more of an OS behavior than app specific.

**Comment by markusd112** [comment] 2017-02-07 11:37
Yes, you are right: I have completely disabled any power saving function on my Samsung tablet in the menu. Additionally I had to enable the "always" option K9 mail the get push working again. Only to disable the power saving hasn't solved the problem...

On wileyfox with Android 7 (lineageos) I haven't found a solution. With CM13 (Android 6.0.1) it works...

Other apps than K9 are working well in background... How they have solved it? Isn't there any solution to get K9 working again with IMAP push?

**Comment by markusd112** [comment] 2017-02-07 11:48
I have found the energy saving option under lineageos 14. It was my fault, sorry. It's the same way, described in your link. I need some glasses ;-)

**Comment by Bugsbane** [comment] 2017-02-12 07:01
Just thinking about the theory that the os is incorrectly signaling availability of WiFi... I've noticed that a couple of apps will flash up a warning on my phone sometimes (Samsung s6) saying that there's no internet connection, but then proceed to function just fine.

**Comment by cdmackay** [comment] 2017-02-12 19:35
On 12/02/2017 07:01, Bugsbane wrote:
> Just thinking about the theory that the os is incorrectly signaling 
> availability of WiFi... I've noticed that a couple of apps will flash up 
> a warning on my phone sometimes (Samsung s6) saying that there's no 
> internet connection, but then proceed to function just fine.

Yes, my S7e (Nougat) does the same: regularly gets an icon that 
indicates “no internet” despite everything working perfectly. Resolves 
itself after a few minutes, often.

**Comment by nyetwurk** [comment] 2017-02-12 19:38
Can a button be added that manually re-enables sync without having to kill and restart k9 completely?

**Comment by AndrueCope** [comment] 2017-02-13 08:24
The refresh button already does that for me.

**Comment by Bugsbane** [comment] 2017-02-18 12:38
Yeah, I just tap the sync button whenever I want to see new emails.

**Comment by nyetwurk** [comment] 2017-02-20 12:17
Syncing stays disabled if i refresh. I don't see a sync button.

**Comment by Newbie1980** [comment] 2017-03-03 19:11
When "background sync is enable" is selected. This seems to work for me. 

Always on = syncing disabled.

Lineage OS 14.1.

**Comment by Newbie1980** [comment] 2017-03-03 20:22
Edit. Same problem.

**Comment by Newbie1980** [comment] 2017-03-04 13:06
Back on modified stock oneplus 3T rom, no issues .

**Comment by frettloeh** [comment] 2017-03-29 06:30
I can unfortunately confirm the same problem on a Samsung Galaxy S7 with Android 7.0. Prior to Android 7.0 (don't remember the old version) it worked, but since I got the upgrade, K9 disables sync sporadically. It's already whitelisted, but I'll try to switch the setting in K-9 to sync always.

**Comment by frettloeh** [comment] 2017-03-31 22:28
Okay, I did one more debug session and did find this one here, containing a NPE:

```
...
03-31 23:44:10.160 V/k9      (10378): LockableDatabase: Transaction ended, took 40ms / com.fsck.k9.mailstore.LocalFolder.appendMessages(LocalFolder.java:1255)
03-31 23:44:10.166 V/k9      (10378): syncFolder(INBOX) got latch release
03-31 23:44:10.166 I/k9      (10378): About to IDLE for XXX:INBOX/Thread-14
03-31 23:44:10.167 V/k9      (10378): TracingWakeLock for tag ImapFolderPusher XXX:INBOX / id 135 for 60000 ms: acquired
03-31 23:44:10.168 E/k9      (10378): Got exception while closing for exception for XXX:INBOX/Thread-14
03-31 23:44:10.168 E/k9      (10378): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.mail.store.imap.ImapConnection.close()' on a null object reference
03-31 23:44:10.168 E/k9      (10378): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.reacquireWakeLockAndCleanUp(ImapFolderPusher.java:252)
03-31 23:44:10.168 E/k9      (10378): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:202)
03-31 23:44:10.168 E/k9      (10378): 	at java.lang.Thread.run(Thread.java:762)
03-31 23:44:10.168 E/k9      (10378): Failed synchronizing folder XXX:INBOX @ Fri Mar 31 23:44:10 GMT+02:00 2017
03-31 23:44:10.168 I/k9      (10378):  Command 'synchronizeMailbox' completed
03-31 23:44:10.170 E/k9      (10378): Got exception while idling for XXX:INBOX/Thread-14
03-31 23:44:10.170 E/k9      (10378): java.lang.NullPointerException: Attempt to invoke virtual method 'void com.fsck.k9.mail.store.imap.ImapConnection.setReadTimeout(int)' on a null object reference
03-31 23:44:10.170 E/k9      (10378): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.setReadTimeoutForIdle(ImapFolderPusher.java:362)
03-31 23:44:10.170 E/k9      (10378): 	at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:187)
03-31 23:44:10.170 E/k9      (10378): 	at java.lang.Thread.run(Thread.java:762)
03-31 23:44:10.170 D/k9      (10378): SleepService Preparing CountDownLatch with id = 33, thread Thread-14
03-31 23:44:10.171 I/k9      (10378): BootReceiver Got request to schedule alarmedIntent com.fsck.k9.service.SleepService.ALARM_FIRED.33
03-31 23:44:10.176 V/k9      (10378): TracingWakeLock for tag ImapFolderPusher XXX:INBOX / id 135: releasing after 5639 ms, timeout = 60000 ms
03-31 23:44:10.183 E/k9      (10378): Got exception while idling for XXX:Drafts/Thread-13
03-31 23:44:10.183 E/k9      (10378): javax.net.ssl.SSLException: Write error: ssl=0x6fb0beee00: I/O error during system call, Software caused connection abort
03-31 23:44:10.183 E/k9      (10378): 	at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
03-31 23:44:10.183 E/k9      (10378): 	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:824)
...
```

Interesting enough, the same NPE happened later with the DRAFT folder. Perhaps this messes up sync and afterwards it fails?

I could paste more, but somebody needs to hint me into anonymizing these files.

**Comment by drhill** [comment] 2017-04-04 14:37
Something I noticed was when I'm on mobile data (at work or out and about) I get all my work emails via IMAP Idle.  When I get home and my Pixel connects to wifi I stop getting emails.  This was with Doze optimization disabled or enabled.  I also see the inverse when I reboot my phone at home and it starts out with a wifi connection.  It seems as if when switching from mobile to wifi data and vice versa the IMAP idle connection isn't reestablished with the new IP address.

**Comment by Newbie1980** [comment] 2017-04-06 10:53
If this is related to doze, I was reading about disable doze completely through this app and script. 
I am going to try it later when I am at said phone.

"dumpsys deviceidle disable"

https://forum.xda-developers.com/android/apps-games/root-doze-settings-editor-android-t3235130/page138

**Comment by frettloeh** [comment] 2017-04-13 13:29
@cketti does this issue still needs to be labeled with "needs info"? I've posted some debug log entries here. Either remove that label or state what more information you need and how to retrieve it. Thanks!

**Comment by nyetwurk** [comment] 2017-04-15 03:06
Seems pretty obvious; not all of the code in ImapFolderPusher.java checks if connection is null.

**Comment by nyetwurk** [comment] 2017-04-15 03:08
ImapFolderPusher.java

Line 185:
```
                        ImapConnection conn = connection;
                        setReadTimeoutForIdle(conn);
                        sendIdle(conn);
```
Line 249:
```
            try {
                connection.close();
            } catch (Exception me) {
                Timber.e(me, "Got exception while closing for exception for %s", getLogId());
            }
```

**Comment by philipwhiuk** [comment] 2017-04-15 07:21
@nyetwurk

Sure but we catch the exception. It's not the reason.

**Comment by frettloeh** [comment] 2017-04-27 08:47
Any update on this topic? Can I help with any further information you need for analysis?

**Comment by fivemail** [comment] 2017-05-03 00:11
I have a Galaxy S8, running Android 7.0.  Here are the steps I took to solve the K9 app syncing problem:

K9 > Settings > Global Settings > Network > Background sync:  change it  to "When 'Auto-sync' is checked".  It might work with Background sync set to "Always", but I haven't tried it. 

Android Setting > Device Maintenance > Battery, K9 did not appear in the App power monitor section.  If you see K9 here, make sure it is not checked.

Android Setting > Device Maintenance > Battery > Unmonitored apps (at very bottom of Battery screen) add K9 to  "Unmonitored apps" 

Android Setting > Device Maintenance > Battery > Battery Usage (right below "Estimated battery life" at top of screen).  Then click on 3 vertical dots at top right and select "optimize battery usage".   Select "All apps" and  turn off optimization for K9.

**Comment by aronovgj** [comment] 2017-06-29 15:26
@Newbie1980 I have been disabling doze ever since it stopped viber from working properly. Does not help with k9 though

**Comment by drhill** [comment] 2017-07-14 18:23
This issue (for me) seems to be entirely linked from connecting initially to my work mail server (imap idle) on mobile data, which works fine, and then getting home and the phone connects to wifi.  At that point I get no more emails until I leave my home and get back on mobile data.  

It is as if the connection to the mail server needs to be reset when switching from mobile to wifi (or more to the point when the ip address changes).

**Comment by siouxchief** [comment] 2017-10-26 08:23
Just wanted to let people know that fivemail's post 3 above this one fixed the issue for me on my S6. Please try it.

**Comment by WGH-** [comment] 2017-11-21 00:46
FWIW, I also noticed that I sometimes (I haven't figured out exact circumstances) don't receive any notifications on WiFi (and when I checked, it did say "Synchonisation disabled"), but as soon as I go out and switch to mobile connection, K-9 suddenly decides to check e-mail.
Android 7.1.2 (LineageOS 14.1), Redmi Note 4, K-9 5.208.

I've just did the workaround mentioned above, I will update this post if it actually helps.

**Comment by AndrueCope** [comment] 2017-11-21 08:30
I had to switch mine to 'synchronise always' at the weekend because it just couldn't keep a connection at home over wifi. I refreshed it three times and it still kept dropping out. I don't know where that came from as it's been fine since the end of Summer. I've noticed though that the old 'background sync' option seems to have gone from my S7 Edge. I don't know when that happened but it's at least a month since my phone firmware was last updated.

So far 'synchronise always' has solved the problem for me though.

**Comment by dhebbeker** [comment] 2019-01-02 21:31
I can confirm the behavior @WGH- and @drhill have reported: Often e-mails don't get fetched when the device is connected to WiFi, but as soon as it changes to mobile connection e-mails are synchronized again.

I will try the instructions @fivemail has written. The last setting was not set as in the [comment](https://github.com/k9mail/k-9/issues/970#issuecomment-298795561).

- [x] power saving is disabled for that app
- [x] background mobile data is enabled for that app
- [x] background synchronization in K-9 Mail is set to 'always' 
- Android 7.0
- K-9 Mail 5.600

**Comment by cketti** [comment] 2019-03-08 03:24
Duplicate of #3950

**Closed by cketti** 2019-03-08 03:24 UTC

**Comment by dhebbeker** [comment] 2019-03-08 22:28
> I will try the instructions @fivemail has written. The last setting was not set as in the [comment](https://github.com/k9mail/k-9/issues/970#issuecomment-298795561).
> 
>     * [x]  power saving is disabled for that app
> 
>     * [x]  background mobile data is enabled for that app
> 
>     * [x]  background synchronization in K-9 Mail is set to 'always'
> 
>     * Android 7.0
> 
>     * K-9 Mail 5.600

Since I tried the recommendations I did not observe the issue any more.
