### ISSUE TITLE
OpenKeychain should be built into the Thunderbird apk 

### ISSUE THREAD

**Issue by xuenhua** [thunderbird/thunderbird-android#8540] opened 2024-11-09 10:55 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.1

### Problem you are trying to solve

When enable OpenPGP, the OpenKeychain is needed to install. But OpenKeychain can only be downloaded via F-Droid or Google play. 

### Suggested solution

F-Droid  or Google play is not available in some countries. So I suggest to build the openKeychain into Thunderbird apk as the same as K9 mail.

**Comment by kewisch** [comment] 2024-11-12 11:44
Duplicate of #7451

**Closed** 2024-11-12 11:44 UTC
Labels: type: enhancement, unconfirmed
