### ISSUE TITLE
Unable to edit account's server settings / unable to send mails on setting import 

### ISSUE THREAD

**Issue by joni1993** [thunderbird/thunderbird-android#8282] opened 2024-10-09 07:47 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Fairphone 5

### Steps to reproduce

1. Add or import accounts
(I imported settings from K9 in 8.0b1 - sending mails then needs you to reeinter password - which worked in 8.0b1)
2. Try to access the inbox/outgoing settings of that account
3. Account setup dialog appears instead of edit dialog

### Expected behavior

The edit dialog should appear if you try to edit the inbox/outgoing server settings.

### Actual behavior

The "add new account" dialog appears instead.

**Comment by wmontwe** [comment] 2024-10-09 08:26
Duplicate of #8271 and fixed for the next beta.

**Closed by wmontwe** 2024-10-09 08:26 UTC
