### ISSUE TITLE
Force closed after attempt to read or type a mail.

### ISSUE THREAD

**Issue by ahaone** [thunderbird/thunderbird-android#5987] opened 2022-03-26 16:09 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.913

### Android version

Android 9 - custom rom

### Device model

S9 plus

### Steps to reproduce

swipe to refresh for new mail
new mail is loaded correct
then try open the new mail
or
push the button on top to compose a new mail

### Expected behavior

read the contents of the newly received mail 
or 
type new mail.

### Actual behavior

app force closes.

### Logs

[log])

**Comment by cketti** [comment] 2022-03-26 16:24
Looks like you don't have a `WebView` implementation installed on your device.

Duplicate of #5835

**Closed by cketti** 2022-03-26 16:24 UTC

**Comment by ahaone** [comment] 2022-03-26 16:52
Thank you! Just updated the android system webview. All works as intended.
