### ISSUE TITLE
Remote search fails for Persian word

### ISSUE THREAD

**Issue by iriman** [thunderbird/thunderbird-android#4737] opened 2020-05-08 10:36 UTC
### What I want to do
Search remote for "سلام", a Persian word (Also Arabic).

### Expected behavior
I expect some emails with word "سلام". Similar to when I search for an English word like "hello".

### Actual behavior
It finds local messages. Then I choose remote search button and it says "Sending query to server". Just after that, search fails with toast "remote search failed", while for the example search of "hello" results are retrieved without any problem.

### Steps to reproduce
1. Go to Inbox of an account
2. Choose search button (magnifier) and type sth
3. Choose remote search button (magnifier with cloud)

### Environment
K-9 Mail version: 5.710

Android version: 7.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

Retrieve logs and attach them here: [rs.log](https://github.com/k9mail/k-9/files/4598438/rs.log)

**Comment by cketti** [comment] 2020-05-08 14:04
We currently don't specify any text encoding when sending the search text to the IMAP server. Any search term containing non-ASCII characters will most likely lead to this problem.

**Comment by cketti** [comment] 2020-10-06 21:56
Duplicate of #3607

**Closed by cketti** 2020-10-06 21:56 UTC
