### ISSUE TITLE
Not changing star in message view, in split-screen, after swipe

### ISSUE THREAD

**Issue by mhf1998** [thunderbird/thunderbird-android#7108] opened 2023-08-01 11:09 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.707

### Where did you get the app from?

F-Droid

### Android version

10

### Device model

Samsung A6

### Steps to reproduce

1. Go to 'settings'
2. Go to 'General Settings'
3. Go to 'Display'
4. Click on 'Show split-screen'
5. Click on 'when in landscape orientation'
6. Go back to 'General Settings'
7. Go to 'Interaction'
8. Go to 'Swipe Actions'
9. Go to 'right swipe'
10. Click on "Add/Remove Star"
11. Back to the message list
12. Landscape the page orientation
13. Open one of the messages in the right view (message view)
14. Swipe that message to the right (for change star)

### Expected behavior

We expect the star status to change correctly both in the list view and in the message view.

### Actual behavior

We can see that in the message list view, starring or un-starring changes correctly, **but** in the message view (on the right-hand side), starring or un-starring doesn't change.

**Comment by cketti** [comment] 2023-08-02 11:43
This is not exactly the same issue as #6126. But the underlying problem is the same.

Duplicate of #6126

**Closed by cketti** 2023-08-02 11:43 UTC
