### ISSUE TITLE
Failed to export settings

### ISSUE THREAD

**Issue by gitmatt19** [thunderbird/thunderbird-android#1100] opened 2016-02-17 01:34 UTC
### Expected behaviour

Export settings to local file
### Actual behaviour

"Failed to export settings"

02-16 17:18:34.093 I/k9      (10989): Exporting preferences  
02-16 17:18:34.133 W/k9      (10989): Exception during export  
02-16 17:18:34.133 W/k9      (10989): com.fsck.k9.preferences.SettingsImportExportException:  
com.fsck.k9.preferences.SettingsImportExportException: Not a valid transport URI  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.preferences.SettingsExporter.exportToFile(SettingsExporter.java:99)  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.activity.Accounts$ExportAsyncTask.doInBackground(Accounts.java:1949)  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.activity.Accounts$ExportAsyncTask.doInBackground(Accounts.java:1926)  
02-16 17:18:34.133 W/k9      (10989):   at android.os.AsyncTask$2.call(AsyncTask.java:288)  
02-16 17:18:34.133 W/k9      (10989):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)  
02-16 17:18:34.133 W/k9      (10989):   at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)  
02-16 17:18:34.133 W/k9      (10989):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)  
02-16 17:18:34.133 W/k9      (10989):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)  
02-16 17:18:34.133 W/k9      (10989):   at java.lang.Thread.run(Thread.java:841)  
02-16 17:18:34.133 W/k9      (10989): Caused by: com.fsck.k9.preferences.SettingsImportExportException: Not a valid transport URI
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.preferences.SettingsExporter.exportPreferences(SettingsExporter.java:164) 
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.preferences.SettingsExporter.exportToFile(SettingsExporter.java:94)  
02-16 17:18:34.133 W/k9      (10989):   ... 8 more  
02-16 17:18:34.133 W/k9      (10989): Caused by: java.lang.IllegalArgumentException: Not a valid transport URI  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.mail.Transport.decodeTransportUri(Transport.java:43)  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.preferences.SettingsExporter.writeAccount(SettingsExporter.java:257)  
02-16 17:18:34.133 W/k9      (10989):   at com.fsck.k9.preferences.SettingsExporter.exportPreferences(SettingsExporter.java:155) 
02-16 17:18:34.133 W/k9      (10989):   ... 9 more                                                                               
### Steps to reproduce
1. Try to export settings
   2.
   3.
### Environment

K-9 Mail version: 5.008
Android version: Nexus 7 2013  v4.4 / rooted
Account type (IMAP, POP3, WebDAV/Exchange): N/A

**Comment by cketti** [comment] 2016-02-23 20:54
Go to 'Account settings > Sending mail > Outgoing server' and press the "Next" button. Then try again.

**Comment by gitmatt19** [comment] 2016-02-24 01:43
That worked. I have some accounts that dont send email, but I added a fake address and then it saved the file it looks like, thanks.

**Comment by philipwhiuk** [comment] 2016-03-14 16:59
@cketti do we support "accounts that don't send email"? Should we?

In other words which of the three is this bug now:

1. Allow exporting and importing settings without a transport URI - in this case set to the empty string I think)?
2. Support accounts without outgoing server settings (this would seem to be an enhancement)
3. Produce a better error message when attempting to export incompletely configured account

Obviously @gitmatt19 is assuming we already support it and so from his perspective we should either do the remaining work or if it otherwise works, fix this small issue. And there are various scenarios where people use one of their email accounts in a read-only fashion.

But from the code in the Transport class and the usage of it, we never intended to support lack of outgoing server settings.

**Comment by philipwhiuk** [comment] 2016-04-14 21:46
Ok. #728 covers accounts without a SMTP server. So this bug is just fixing the export warning or a dupe of that. On the assumption it's not a dupe, I'll write some code that fixes the NPE pending that enhancement.

**Closed** 2016-04-14 21:50 UTC
