### ISSUE TITLE
Sent emails don't show up in "Sent" folder

### ISSUE THREAD

**Issue by SonOfDiablo** [thunderbird/thunderbird-android#8617] opened 2024-11-27 19:46 UTC
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same bug report.
- [x] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

OnePlus 11

### Steps to reproduce

1. Tap the pencil button to write a new email. 
2. Type out the email.
3. Hit the send button. 

### Expected behavior

Expected behavior is for the sent mail to show up in the "Sent" folder. 

### Actual behavior

Whenever I send a mail from the app the sent mail doesn't show in my "Sent" folder like it does on the windows version (and every other mail app I have tried).

**Comment by kewisch** [comment] 2024-11-27 20:44
Can you check your folder settings to see if you have a Sent folder defined for that account?

**Comment by SonOfDiablo** [comment] 2024-11-27 21:39
> Can you check your folder settings to see if you have a Sent folder defined for that account?

It was set to "automatic" but also said "none" in parenthesis, so I assume it hadn't detected the Sent folder correctly.

As an extra note, I exported my setting from my windows installation, but on windows it works fine.

**Comment by kewisch** [comment] 2024-11-28 15:26
Duplicate of #8383 then, I experienced this as well. Maybe you have time to provide some logs from the setup process?

**Closed by kewisch** 2024-11-28 15:26 UTC

**Comment by cketti** [comment] 2024-11-28 15:38
Special folders configured in Thunderbird for desktop are currently not part of the data exported via the QR code.

**Comment by kewisch** [comment] 2024-11-28 20:53
@cketti but are folders auto-detected after the QR code import? It would be unfortunate if they remained "None" without either auto-detection or the user being able to configure them.

**Comment by cketti** [comment] 2024-11-28 22:58
They are set to "automatic". But that doesn't do anything if the server doesn't support the `SPECIAL-USE` extension or there's no sent folder configured on the server.
