### ISSUE TITLE
Notification spam (one notification per new email)

### ISSUE THREAD

**Issue by frank42hh** [thunderbird/thunderbird-android#5056] opened 2020-11-16 16:30 UTC
**Describe the bug**

When using polling (since IMAP push is not available in current beta) I get notification spamming every time emails are fetched. this is because every new email gets its own notification triggered, so if you get many emails between the polling intervals, you don't get one *ding* per account but one *ding* per email, which can be quite disturbing when you get lots of them.

**To Reproduce**
1. Set your poll interval for example to 30 minutes.
2. poll your emails
3. close K-9
4. send yourself many emails (10 for example) from another device - make sure you have "notifications for own messages" enabled.
5. wait for the next poll
6. Receive 10 times *ding*

**Expected behavior**
Usually there should be one notification stating that there are x new emails.

**Environment (please complete the following information):**
 - K-9 Mail version: 5.724
 - Android version: 11
 - Device: Google Pixel 4a
 - Account type: IMAP

P.S. Of course, having IMAP PUSH back would be much better :-)

**Comment by pejakm** [comment] 2021-05-26 14:02
Seems like another duplicate of #4559

**Closed** 2021-08-07 14:52 UTC
