### ISSUE TITLE
Application Crashes When Inserting Invalid Email Address During Eamil Account Setup

### ISSUE THREAD

**Issue by mwihechi** [thunderbird/thunderbird-android#7243] opened 2023-10-12 07:07 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.711

### Where did you get the app from?

Other

### Android version

13

### Device model

SM-P619

### Steps to reproduce

1. Open the application and click the "Start" button.
2. Enter an invalid email address (e.g., "mwihechi").
3. Click the "Next" button.

### Expected behavior

The expected behavior is for the application to provide clear feedback to the user when they insert an invalid email address during the setup process. This feedback should inform the user that the entered email address is invalid, ensuring a smoother user experience and preventing application crashes.

### Actual behavior

The application crashes, which negatively impacts the user experience.

**Comment by cketti** [comment] 2023-10-12 11:52
Duplicate of #7218

The fix will be included in the next beta version.

**Closed by cketti** 2023-10-12 11:52 UTC
