### ISSUE TITLE
No valid OpenPGP block found

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#1008] opened 2016-01-08 17:42 UTC
Hi!

I am not sure, whether this is an openkeychain issue or a k9 mail issue, that's why I'd like to post it here again: https://github.com/open-keychain/open-keychain/issues/1665

 I use K9 5.007 and OpenKeyChain 3.7 on my Android with CM 12.1.

When I reply a mail, K9 mail adds the old message quoted like this:

> This is the reply mail followed by the quotation of the original mail:
> 
> > -----BEGIN PGP MESSAGE-----
> > Charset: utf-8
> > Version: GnuPG v2
> > 
> > hQIMA324sfl24ltklwqfl2tl2gw

However, K9 mail cannot decrypt my sent message then and Thunderbird tells me that no valid OpenPGP block could be found. This is how the sent mail looks then:

> -----BEGIN PGP MESSAGE-----
> 
> hQIMAypJd8s8JCpBAQ//fWrPkSHfvGyh9YPbIn9OhQCOKCQM2yUusUiGbOxYPxbZ

When I compare it to a working encrypted mail 

> -----END PGP MESSAGE-----

is missing here at the end of the mail. So only a part of the encrypted messages seems to be sent!

**Comment by cketti** [comment] 2016-01-13 07:44
@Valodim Can you please have a look at this?

**Comment by Valodim** [comment] 2016-01-13 10:52
I wasn't able to reproduce this, so it does not seem to be a deterministic issue with replying. Since the actual symptom is that part of the message is missing at the end, my guess is that this is caused by  https://github.com/open-keychain/openpgp-api/pull/3. This is an issue in OpenKeychain, but the fix requires an update of the OpenPgpApi lib to version 0.9 so it's not included in K9 5.007.

**Comment by philipwhiuk** [comment] 2017-02-09 00:12
We're using the IOpenPgpService2 that was merged into K-9 now. So I think we can probably close this one.

**Closed by philipwhiuk** 2017-02-09 00:12 UTC
