### ISSUE TITLE
Re-opening via App-Icon does not remember last state.

### ISSUE THREAD

**Issue by sfadschm** [thunderbird/thunderbird-android#5579] opened 2021-08-16 13:03 UTC
**Describe the bug**
When the app is running open in the background, say with an email opened and one uses the app drawer/home screen icon, the app will open up and return to the start view (inbox of the default account or whatever is set) instead  of  showing the last opened view.

**To Reproduce**
1. Open app and navigate to random view (e.g. open any Email).
2. Go to the android home screen (i.e. minimize K9).
3. Re-open K9 from the "active apps" screen.
4. The app will open with the last state (i.e. the email we opened in 1.).
5. Go to home screen again.
6. Open K9 via home screen or app drawer icon.
7. The app opens with the default start view instead of the previously opened view.

**Expected behavior**
If the app window is already running in the background, I would expect all entry points to show the same app view, which is the currently active view.
The current behaviour in step 6-7 rather resembles a restart of the app then a re-open.
Also, it is quite easy to navigate back to the start page from any point in the app, but can be quite difficult to return to the previously opened mail/view from the start page.

**Environment**
 - K-9 Mail version: 5.8.03
 - Android version: 11
 - Device: Google Pixel 3a (likely all)
 - Account type: all

**Comment by cketti** [comment] 2021-08-16 13:13
Works fine for me. Can you provide more information on when this happens? Does it work when you force stop the app and start with a fresh process as step 0? If so, at what point does it stop working?

> If the app window is already running in the background, I would expect all entry points to show the same app view, which is the currently active view.

That's not the case. There are a bunch of entry points that navigate to specific views, e.g. the "K-9 Accounts" and "K-9 Unread" widgets, notifications, etc.

**Comment by sfadschm** [comment] 2021-08-16 14:35
> That's not the case. There are a bunch of entry points that navigate to specific views, e.g. the "K-9 Accounts" and "K-9 Unread" widgets, notifications, etc.
That is correct and was bad phrasing from my side.

I will do some testing and see if I cam record the actions to reproduce.
One thing to possibly add to the environment: I am using Nova Launcher. Will test with the google launcher later today.

Thanks for the quick reply!

**Comment by sfadschm** [comment] 2021-08-16 16:49
Okay, some more context:

I currently have two entry points to K9:

1. Home Screen Icon which is an `Account` type widget.
2. App Drawer Icon which is just the app icon.

Now there is two (three) scenarios:
1. Open K9 via Drawer to see the default inbox.
2. Navigate to an email and minimize K9.
3. Klick Drawer icon again will bring up the same email we just opened.
4. Klickling the `Account` widget instead will open the linked account.

This is correct behavior. The other scenario:

1. Open K9 via the widget and see the chosen account.
2. Navigate to an email an minimize K9.
3. Klick widget to bring K9 back and it will show the linked account (this is correct behavior).
4. Klick the Drawer icon insteat and the app "restarts" itself and shows the default inbox.

Now here comes an interesting scenario which might be helpful for tracking:
1. Open K9 via the App icon and navigate to an email.
2. Minimize K9 and klick the `Account` widget will take you to the linked account inbox.
3. Navigate to an email and minimize K9 again.
4. Re-open K9 with the App icon will open with the email opened in step 3.

I am not really sure if this is a bug or intended. But it seems that if the app was initially opened from a widget  (i.e. after being force-closed or removed from the running apps list) , it has a different state as when opened from the App icon itself.

I hope this was understandable. If not, I can do some screen recordings.

**Comment by cketti** [comment] 2021-08-16 21:24
Thanks for the details. 

This will be annoying to fix. The problem is how the default launcher action works. It'll launch the start screen. If the app has already been launched it'll bring the task (stack of screens) that contains the start screen to the front, but doesn't change the order of screens. So if you launch the app using the app icon, open settings, press home, then press the app icon again, the settings screen will be displayed, not the start screen.
If you use an account shortcut and there's a task containing the start screen, all screens on top the start screen will be removed and the start screen will be reused to show the account from the account shortcut.
However, if an account shortcut is used, but there's no task containing the start screen, a new screen for the account is launched. (For the launcher) this screen is different from the start screen. So if this task is sent to the background and the app icon is used to bring the app back to the foreground, the default screen is launched on top of the account screen (because the default screen can't be found in the task).

One way to fix this is to use `android:launchMode="singleTask"` for `MessageList`. This has the side-effect of always displaying the message list/view screen and closing all other screens on top when using the app icon. So you couldn't return to say the settings screen using the app icon. Using the app switcher you would still return to the settings screen, though.
This solution should work with existing shortcuts. But we can't use it before #4525 is implemented. Otherwise using the app icon could discard compose screens.

**Comment by cketti** [comment] 2021-08-16 22:16
Maybe not that annoying to fix after all.

When the start screen is launched via the app icon, but there's other screens in the task, we can simply finish the start screen. This has the effect of bringing the last active screen to the foreground.

**Comment by sfadschm** [comment] 2021-08-17 07:15
Oh, great. Nice elaboration.
The fix seems a bit unconventional to me, but as long as it worksI will gladly take it 😆 
Thanks for the quick action!

**Comment by sfadschm** [comment] 2021-08-18 11:39
Can be closed I think?

**Closed** 2021-08-18 11:40 UTC
