### ISSUE TITLE
ThunderBird should add the ability to consolidate multiple emails sent by the same person

### ISSUE THREAD

**Issue by Shura23** [thunderbird/thunderbird-android#8261] opened 2024-10-08 07:22 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

Sometimes there is a large number of emails from the same person, and it is difficult to read the emails sent by other people. Therefore, I want to integrate emails sent by the same person, consolidate them into one record, click on them and then expand all emails

### Suggested solution

You can learn from the chat software, and the interface of the chat software for two people to chat privately is what I wanted. You can think of multiple emails sent as a single record in your chat app

**Comment by cketti** [comment] 2024-10-09 12:41
Duplicate of #1887

**Closed by cketti** 2024-10-09 12:41 UTC
Labels: type: enhancement, unconfirmed
