### ISSUE TITLE
Address field hangs 

### ISSUE THREAD

**Issue by cde1985** [thunderbird/thunderbird-android#6230] opened 2022-08-08 21:22 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

Google Play

### Android version

No

### Device model

Samsung A71

### Steps to reproduce

Write a new mail
In the adress field input a word mark it and select cut. 

### Expected behavior

Empty field

### Actual behavior

Closes the new mail form or hangs.

**Comment by cketti** [comment] 2022-08-08 21:50
Duplicate of #3951

**Closed by cketti** 2022-08-08 21:50 UTC
