### ISSUE TITLE
Synching error...

### ISSUE THREAD

**Issue by Cactus-World** [thunderbird/thunderbird-android#4296] opened 2019-11-27 22:07 UTC
Actual behavior: K-9 removes all already downloaded messages when starting new synching process and starts receiving them again. This uses a lot of bandwidth, time and data plans are easily maxed out.
Expected behavior: Only new messages are downloaded and added to the database as in the previous versions.
Version: K9 5.700 
Environment: Android 9
Account type: IMAP
Steps to reproduce:
1. Create account for IMAP
2. Sync with IMAP server
3. Sync again

The list view and obviously the database is cleared when synching the second time and all messages are downloaded and the displayed again.

**Comment by cketti** [comment] 2019-11-28 18:37
Please provide all the information the issue template asks for. What version are you using? What protocol are you using? Can you please record a [debug log](https://github.com/k9mail/k-9/wiki/LoggingErrors) when syncing.

**Comment by Cactus-World** [comment] 2019-11-28 18:50
Sorry, was writing from phone and forgot to add the info. Edited first post to include it.
Unfortunately I cannot provide you with a debug log as I already removed the new version from phone as it already maxed out my data plan for this month.

**Comment by cketti** [comment] 2019-11-28 19:02
Without a debug log there's little chance we'll find out what's going wrong.

**Comment by DerPate** [comment] 2019-11-29 10:44
Hi There,

can also reproduce the BUG. Will send in debug Log when i'm at home.

**Comment by Bl4d3s** [comment] 2019-12-01 09:44
Hi,

I can also reproduce this behavior. I noticed, sometimes it does not load any messages at all after removing them. Sometimes it does not remove them. This changes when the app is restarted.

I managed to get a log of the following: I started the app, got straight into my first inbox and swiped down to refresh. Then it removed all messages and added them again. This happend in the sort order (sorted from new to old, first new ones get removed, old ones get added first).

[k9-log.txt](https://github.com/k9mail/k-9/files/3908047/k9-log.txt)

**Comment by cketti** [comment] 2019-12-01 14:13
Thanks for the log. I'm not sure exactly what's going on. But the code that seems to be responsible for removing the messages doesn't seem to do anything anymore when it's working as expected. So hopefully getting rid of the code will also get rid of the bug. The change will be included in 5.701.

Once 5.701 has been released please report back on whether or not you're still seeing the reported behavior.

**Comment by Cactus-World** [comment] 2019-12-01 17:38
Okay, we'll see then. If it's still there then I'll send another log. Smiley to your post because I've seen so many code having parts commented with 'it should never get here'

**Comment by Bl4d3s** [comment] 2019-12-03 14:52
I have installed the latest beta and since then could not reproduce this issue anymore.

**Closed** 2019-12-14 13:58 UTC
Labels: status: needs information
