### ISSUE TITLE
IMAP idle breaks phone's deep sleep

### ISSUE THREAD

**Issue by optimumpr** [thunderbird/thunderbird-android#5390] opened 2021-07-08 15:51 UTC
The phone sleeps zero time on Android 11. Once K9 is disabled, deep sleep resumes. The problem started with restoring Push in .735 and persists in all subsequent releases.

Right now, I installed v. 5.600 and both deep sleep and IMAP idle (push) work fine.

Logcat shows no errors regarding K9 (I am a developer). I think you just need to implement wakelock release.

**Comment by cketti** [comment] 2021-07-08 15:56
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

(Next time, please also use the issue templates. https://github.com/k9mail/k-9/issues/new/choose)

**Comment by cketti** [comment] 2021-07-10 13:36
Duplicate of #5397

**Closed by cketti** 2021-07-10 13:36 UTC
Labels: status: needs information
