### ISSUE TITLE
Opening e-mail caused crash that reset all data

### ISSUE THREAD

**Issue by cziegenberg** [thunderbird/thunderbird-android#1039] opened 2016-01-26 16:14 UTC
Today I opened up a mail in K-9 (a spam mail I wanted to mark as spam, but there was nothing special about this mail, simple HTML mail) and it crashed while opening. Then I started K-9 again and it presented the welcome screen - all seetings for five configured accounts are no more available and seem to be completely deleted. Also a restart of the phone didn't change anything - the data seems to be lost forever.

Phone: Nexus 5 (no root)
App Version: 5.007
Android Version: 6.0.1 (Security patch level 1st Jan 2016)

Note: The app still uses more than 300MB for data, so there is something left... but no more accessible)

**Comment by cketti** [comment] 2016-01-26 16:26
Can you provide the email so we have a chance to reproduce the issue?

**Comment by ziege** [comment] 2016-01-26 16:44
Here it is (my e-mail addresses revised with "***email[N]***):
[Uploading crash_spam_email_revised.txt…]()

**Comment by ziege** [comment] 2016-01-26 17:01
Another issue related to this one: After the crash/data deletion and after configuring the first account, the app still uses more than 300MB for data storage, also after selecting "Recreate data" for the newly created account account. So I had to go to the Android app settings, delete the data there and create the account once again.

**Comment by ziege** [comment] 2016-01-26 17:09
I also tried to open the spam mail once again. No problem...

**Comment by ziege** [comment] 2016-01-29 19:34
A minute ago the problem occured again, when trying to open a mail from the new mail notification.

The app crashed. When opening it again I get the welcome screen - all data lost...

I use K-9 for many years now and I never had any serious problems with it. This bug is new, either introduced with the last version or the last Android security patch, I guess.

**Comment by ziege** [comment] 2016-02-12 13:01
The problem occurred again today, with the following updated versions:

App Version: 5.008
Android Version: 6.0.1 (Security patch level 1st Feb 2016)

**Comment by cketti** [comment] 2016-02-12 19:08
Please provide a debug log containing the stack trace of the crash. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by ziege** [comment] 2016-02-13 16:36
Attached the debug log that should contain details about this error. 

Note: You should also find another bug logged in it (Opening a discussion, selecting multiple mails of the same discussion and deleting them results from time to time in a crash - this also occurred while logging).

[k9-log_redacted.txt](https://github.com/k9mail/k-9/files/129251/k9-log_redacted.txt)

**Comment by philipwhiuk** [comment] 2016-03-22 00:49
Plenty of stacktraces but none for K-9 :(

**Comment by fobo66** [comment] 2018-11-16 09:04
I guess, this can be closed as no logs for this issue were provided, and also because of age

**Closed** 2018-11-17 21:08 UTC
Labels: status: needs information
