### ISSUE TITLE
Subject in expanded notifications doesn't take account of dark themes

### ISSUE THREAD

**Issue by Terrance** [thunderbird/thunderbird-android#1418] opened 2016-05-30 10:47 UTC
### Expected behaviour

With a dark theme, all text in notifications should be light coloured.
### Actual behaviour

The subject in the expanded notification appears black, whether a light or dark theme.

![image](https://cloud.githubusercontent.com/assets/4025899/15647525/007a97ce-265c-11e6-9a46-88834678f68d.png)

Collapsed notification displays correctly though.

![image](https://cloud.githubusercontent.com/assets/4025899/15647528/0363fb1a-265c-11e6-87ff-aaddfc039af9.png)
### Environment

K-9 Mail version: v5.010 or v5.109
Android version: 6.0.1 (CyanogenMod 13)

**Comment by OllieTerrance** [comment] 2016-05-30 10:54
Looks like this may be left over from #746?

**Comment by cketti** [comment] 2016-05-30 11:28
Duplicate of #746. But the fix hasn't made it into a stable release yet.

**Comment by OllieTerrance** [comment] 2016-05-30 11:31
It still happens in the 5.109 alpha though?

**Comment by cketti** [comment] 2016-05-30 11:50
:disappointed: 

Reopened. Super-low priority for me. But maybe someone feels inclined to pick this up.

**Comment by philipwhiuk** [comment] 2016-05-30 14:52
That's lame. I thought I fixed all the cases.

**Comment by Valodim** [comment] 2016-06-02 09:00
At the moment, we only set the textcolor for `TextAppearance.StatusBar.EventContent.Emphasized`, but there's some other values like `.Title` and the regular non-emphasized one. I didn't look at this in-depth, is there a problem with just using the default values?

**Closed** 2017-03-26 20:37 UTC
Labels: status: help wanted
