### ISSUE TITLE
Mails not comming in using vpn thunderbird Beta

### ISSUE THREAD

**Issue by ItsMe588** [thunderbird/thunderbird-android#8228] opened 2024-10-03 11:27 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

samsung

### Steps to reproduce

.

### Expected behavior

.

### Actual behavior

Just installed the Beta Thunderbird version of android.
I noticed that mails are not comming in when a vpn is activated.
If the vpn is deactivated they do come in.
Sending mails with activated vpn is no problem.
With K9 i don't have this problem.
I am sure that all setting ( both vpn and thunderbird android )  are okay.
Does anyone else recognise this ?  and maybe have a solution ?

### Logs

.

**Comment by R7010A** [comment] 2024-10-03 16:04
Confirmed, but in another way 
Using wg tunnel, I marked k-9 as an exception for vpn. In wg tunnel it is possibke to define trusted wifi networks to disable vpn when connected.
But even k-9 is excepted from vpn, turning wifi off (vpn is enabled by wg tunnel) and then turning on wifi again (vpn is disabled), a popup says "K-9 was closed multiple times" and it is, the push symbol went away.
Why will K-9 be killed turning vpn on and off though it is marked as an exception?

**Comment by R7010A** [comment] 2024-10-03 16:04
Confirmed, but in another way 
Using wg tunnel, I marked k-9 as an exception for vpn. In wg tunnel it is possibke to define trusted wifi networks to disable vpn when connected.
But even k-9 is excepted from vpn, turning wifi off (vpn is enabled by wg tunnel) and then turning on wifi again (vpn is disabled), a popup says "K-9 was closed multiple times" and it is, the push symbol went away.
Why will K-9 be killed turning vpn on and off though it is marked as an exception?

**Comment by R7010A** [comment] 2024-10-03 16:06
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by R7010A** [comment] 2024-10-03 16:07
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by R7010A** [comment] 2024-10-03 16:07
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by R7010A** [comment] 2024-10-03 16:07
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by R7010A** [comment] 2024-10-03 16:07
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by R7010A** [comment] 2024-10-03 16:07
Cobfirmed.
Turning vpn (Ivam using wg tunnel)  on and off kills K-9, though it is marked as exception.

**Comment by imjuzcy** [comment] 2024-10-04 04:35
Cannot confirm, Thunderbird beta working as expected with always-on VPN (Wireguard).

**Comment by R7010A** [comment] 2024-10-04 07:01
> Cannot confirm, Thunderbird beta working as expected with always-on VPN (Wireguard).
That can be true, but I deliberately don't use always-on-vpn. wg tunnel offers the possibility that vpn is automatically deactivated in a trusted WLAN, because it makes no sense to use vpn in a secure WLAN. And this version of k-9 can't handle that. After turning the WLAN off and on, k-9 is killed. In version 6.804, none of this was a problem. So it must be due to the new version 8.

**Comment by R7010A** [comment] 2024-10-05 09:37
Update:
I installed Thunderbird v8.0b1 over K-9 v8.0b1 and now vpn works as expected.
No more crashes. 👍🏻

**Comment by ItsMe588** [comment] 2024-10-16 07:39
Update : i have added the latest Beta version to the split tunneling of my vpn and it seem to work now.  Remains the question  why i don't have to add K9 to the split tunnel. Of course i would like to have TB also behind a vpn without split tunnel.

**Comment by kewisch** [comment] 2024-11-04 14:02
It looks like this is mostly taken care of? I don't believe we do anything special with connections to avoid VPNs.

**Comment by ItsMe588** [comment] 2024-11-05 18:03
It is all oke now. Problem solved

-------- Oorspronkelijk bericht --------
Op 04-11-2024 15:02, schreef Philipp Kewisch :

**Closed** 2024-11-05 19:33 UTC
