### ISSUE TITLE
No content when sharing 

### ISSUE THREAD

**Issue by muessjoeh** [thunderbird/thunderbird-android#3953] opened 2019-03-08 10:01 UTC
### Expected behavior
When you select 'Share' (in German 'Teilen') on an email, then just its subject and not its content is transmitted to the other program. 

### Actual behavior
Its content should also be transmitted, not just the subject line. 

### Steps to reproduce
1. Select 'Share' on any mail
2. Use a text editor as target 
3. See what is transmitted 

### Environment
K-9 Mail version: 5.600

Android version: 6.0

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by muessjoeh** [comment] 2019-03-08 10:04
'Expected behavior' and 'Actual behavior' should be changed.

**Comment by cketti** [comment] 2019-03-09 19:43
Works for me. 

Does sharing the message to another app (e.g. K-9 Mail itself) work? If so, it's most likely an issue with the text editor. If that doesn't work, the message itself might be causing this. In that case please attach a copy of the message source (feel free to redact the content).

**Comment by muessjoeh** [comment] 2019-03-09 20:40
Strange. Right now it also works for me. Last time I checked it it didn't work. What can be the cause of this strange behavior?

**Comment by cketti** [comment] 2019-03-09 21:49
Closing this issue. Feel free to post again once you can provide steps to reproduce the problem and we'll re-open.

**Closed by cketti** 2019-03-09 21:49 UTC
Labels: status: needs information
