### ISSUE TITLE
'Enable PGP Sign-Only' replace subject with 'Encrypted Message'

### ISSUE THREAD

**Issue by doak** [thunderbird/thunderbird-android#4374] opened 2019-12-14 14:10 UTC
### Expected behavior
Subject should be untouched and readable by any client.

### Actual behavior
Subject of sent message is replaced by *Encrypted Message*. There is a second `Subject:` header containing the original subject, but *K9* does not evaluate it itself, nor most likely any non GPG/PGP-aware client. (Thunderbird does handle it, but I don't know if this is conformant to any RFC.)

### Steps to reproduce
1. Create new message with any subject.
2. Enable option *Enable PGP Sign-Only*
3. Send message
4. Open own message from *Sent* folder.

### Environment
* K-9 Mail version: *v5.700*
* Android version: *Replicant v6.0.1*
* Account type (IMAP, POP3, WebDAV/Exchange): *IMAP*
* Logs: Skipped. I don't expect logs helpful in this case.

**Comment by GNUDimarik** [comment] 2020-09-01 01:30
Could not reproduce it on current master

**Comment by cketti** [comment] 2020-10-11 20:16
Fixed by #4720

**Closed by cketti** 2020-10-11 20:16 UTC
