### ISSUE TITLE
Opening new mail from lock screen notification goes to folder view

### ISSUE THREAD

**Issue by Bubu** [thunderbird/thunderbird-android#1885] opened 2016-12-29 23:25 UTC
### Expected behavior
Double tapping a new mail notification on the lock screen (then unlocking the screen) should open the email that just arrived. Or I guess the new behaviour is to show a list of unread emails if there are multiple unread emails(?).

### Actual behavior
K9-Mail opens but instead of going to a message it opens up the folder listing of the relevant account.

### Steps to reproduce
1. Lock Screen
2. Receive an email
3. Double Tap on Notification
4. Unlock Phone

### Environment
K-9 Mail version: 5.200

Android version: 6.0.1/CM13
Account type: IMAP

This worked as expected before updating to 5.200.
It also works correctly, when clicking on notifications when the phone is unlocked.

**Comment by Bubu** [comment] 2016-12-30 14:30
I'm a bit confused now. Right now it also didn't work correctly on an unlocked phone. But I'm sure I tried it multiple times yesterday and there it worked and only failed from the lock screen.

**Comment by cketti** [comment] 2016-12-30 20:20
Are you maybe clicking on a collapsed notification for multiple new messages?

**Comment by ArchangeGabriel** [comment] 2016-12-31 17:06
I’m having the same issue. Not definitively sure when it does happen on locked phone (didn’t look closely at it), but at least on unlocked phone, when I have a “xx *new* messages” notification then it works OK, but with “yy *unread* messages” it goes to folder view. Not sure also what is responsible of notification type (locking phone after message reception?).

**Comment by cketti** [comment] 2016-12-31 18:43
Make sure 'Global settings > Privacy > Hide subject in notification' is set to 'Never' if you want to see notifications for individual messages.

**Comment by Bubu** [comment] 2016-12-31 20:50
@cketti Can you explain what exactly the difference between 'new' and 'unread' messages is? And what do you mean with collapsed notifications/notifications for individual messages.

I have 'Hide subject in notification' set to 'on lock screen' because I consider this an essential privacy feature.
But from my experiments this does not seem related to the present issue.

After some more testing I don't think it has anything todo with the lock screen, but rather as @ArchangeGabriel said with 'new' vs 'unread' messages. 
At the moment I have a notification on the lock screen saying '1 new mail'. tapping this brings me to the email. When I unlock the phone the notification changes to 1 unread message. This brings me to the folder listing, where I have to press Inbox and then the 1 new mail before I can read it.

Earlier I had 1 new on the lock screen and 3 unread when unlocked.

**Comment by skorokithakis** [comment] 2017-01-01 22:05
I see the same behaviour, every message has a notification that says "1 unread message", pressing it brings me to the account view (not even the inbox), so it requires three taps to read the message I want. K9 used to just take me to the message right away, if there was only one unread message, or to the inbox if there were many, and that behaviour was optimal.

**Comment by ArchangeGabriel** [comment] 2017-01-01 22:15
@cketti This is far from ideal, and even a regression. So to sum up:

1. While unlocked, received messages are added to the notifications, the notifications say “xx new messages”, and you can read their titles and senders. Clicking on the notification goes to Inbox view.

2. Once locked, it only show “xx new messages”. Clicking on notification goes to folder view after unlocking.

3. Once unlocked, it shows “xx unread messages”. Clicking on notification goes to folder view.

In previous version, all where going to Inbox view. There is a regression regarding behaviour after locking.

**Comment by jmlobert** [comment] 2017-01-10 21:10
Same issue here. I follow a top-bar notification icon and it opens in folder view, not in the inbox (or the actual message, if only one new message). Has nothing to do with lock screen. This is a new bug, worked properly before 5.200. Google Nexus 5, Android 6.0.1

**Comment by Bubu** [comment] 2017-01-13 12:04
I haven't experienced this since reinstalling k9 with default settings. I don't know which setting is responsible for this, though.

I have not enabled "Hide subject in notifications." this time but Notifications - "Lock Screen Notifications" - "Unread message count". Which seems to accomplish the same thing but avoids triggering this behaviour.

**Comment by philipwhiuk** [comment] 2017-02-06 23:11
> I follow a top-bar notification icon and it opens in folder view, not in the inbox (or the actual message, if only one new message). Has nothing to do with lock screen. This is a new bug, worked properly before 5.200. Google Nexus 5, Android 6.0.1

The problem here is that everyone has a different definition of properly and it's not really practical to cater to everyone's tastes. There's already a lot of notification settings and configuration.

I can't reproduce the original issue on Android 7.1.1. It's not clear enough how it was configured and whether there were multiple messages.

I don't think this should block 5.204.

**Comment by skorokithakis** [comment] 2017-02-06 23:13
@philipwhiuk What do you mean? What's the second definition for "properly", other than "pressing a notification for '1 message' should open that message directly"?

Basically, pressing the notification should open the highest scope that contains all the arrived messages. If it's just one message, it should open the message. If both messages are in the same folder, it should open that folder. If the messages are in different folders, it should open that account. Notifications are already separated by account, so that's all.

**Comment by jmlobert** [comment] 2017-02-07 04:27
I still have the same issue on Android 711 with the Pixel phone. And @skorokithakis is correct, following the notification should either go to the message (if it's only one) or to the inbox folder where that message is, not to the folder list. This is how it used to behave, we only want it to go back to that behavior.

**Comment by captainepoch** [comment] 2017-02-14 14:50
@skorokithakis has the point in this bug. This is the way notifications were working after the 5.2xx update.

**Comment by Tak-MK** [comment] 2017-04-09 15:00
Is there any progress with this bug? Thank you

**Comment by captainepoch** [comment] 2017-09-27 15:07
@cketti Is this bug fixed in 5.300? It's marked for 5.204 and 5.206 milestones, but it wasn't fixed in them.

**Comment by jmlobert** [comment] 2017-09-27 15:50
It is still the case in 5.208 and I am wondering why such a high level bug doesn't get prioritized over cosmetic changes...

**Comment by skorokithakis** [comment] 2017-09-27 16:14
I'm seeing the same, and I have to tap three times every time I get a "one new message" notification.

**Comment by cketti** [comment] 2021-08-12 14:30
See #5565

**Closed by cketti** 2021-08-12 14:30 UTC
