### ISSUE TITLE
Material you 

### ISSUE THREAD

**Issue by kittenvr** [thunderbird/thunderbird-android#7289] opened 2023-10-25 06:51 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

Version 6.603

### Problem you are trying to solve

I don't like the current color scheme

### Suggested solution

Add the material you color scheme

### Screenshots / Drawings / Technical details

https://source.android.com/docs/core/display/dynamic-color

https://material.io/blog/start-building-with-material-you

**Comment by cketti** [comment] 2023-10-25 08:47
Duplicate of #6617

**Closed by cketti** 2023-10-25 08:47 UTC
Labels: type: enhancement, status: wontfix
