### ISSUE TITLE
App crashes on launch after last update

### ISSUE THREAD

**Issue by hjarnek** [thunderbird/thunderbird-android#7995] opened 2024-06-29 05:57 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.902

### Where did you get the app from?

Google Play

### Android version

Android 12, custom ROM e/OS 1.17

### Device model

Google Pixel 5 (redfin)

### Steps to reproduce

1. Start the app
2. App doesn't start

### Expected behavior

Not crash

### Actual behavior

Crash. Neither force restarting the app nor restarting the phone helps. This happened directly after updating to version 6.902, before that it worked fine.

### Logs

[k9-log.txt](https://github.com/user-attachments/files/16038942/k9-log.txt)

**Comment by zanona** [comment] 2024-06-29 06:56
Same here (f-droid)
Wondering how a pre-release made it to these release channels 🤔

**Comment by shuvashish76** [comment] 2024-06-29 10:13
> Same here (f-droid)
> Wondering how a pre-release made it to these release channels 🤔

Pre-releases are enabled for F-Droid but your client should show stable release as the "Suggested" version to install. Others are mostly targeted for testers.

**Comment by cketti** [comment] 2024-06-29 14:29
Duplicate of #7987

**Closed by cketti** 2024-06-29 14:29 UTC

**Comment by hjarnek** [comment] 2024-06-30 07:54
> Duplicate of #7987

Why has this been marked as a duplicate of #7987 ? This has nothing to do with split screen.

**Comment by cketti** [comment] 2024-06-30 10:10
@hjarnek: Apologies. You are correct. This is a duplicate of #7969. K-9 Mail 6.902 was never available via Google Play or F-Droid. So you probably installed it from GitHub. K-9 Mail 6.904 is already available here and fixes both this crash and the one reported in #7987.

Duplicate of #7969

**Comment by hjarnek** [comment] 2024-06-30 10:39
@cketti 
Thank you, this is correct, since version 6.903 fixes the issue.

Though I didn't get the update from GitHub. I got from the /e/OS official app store called [App Lounge](https://gitlab.e.foundation/e/os/apps), which uses both Google Play and F-Droid as app repositories. Maybe other repositories as well, I'm not sure. Seems like an error on their part most probably, I will ask there instead.
