### ISSUE TITLE
Support Chinese translation

### ISSUE THREAD

**Issue by Shura23** [thunderbird/thunderbird-android#8268] opened 2024-10-08 14:32 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

I want a Chinese translation feature to translate the content of the email, preferably offline, so that privacy can be protected

### Suggested solution

Firefox is now ready to work on Chinese translation, and when Firefox implements Chinese translation, then the Chinese translation function can be ported to thunderbird

**Comment by cketti** [comment] 2024-10-09 12:40
Duplicate of #7482

**Closed by cketti** 2024-10-09 12:40 UTC
Labels: type: enhancement, unconfirmed
