### ISSUE TITLE
Importing multiple accounts via QR fails with a Yahoo account exception

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8286] opened 2024-10-09 09:08 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

Android 14

### Device model

Galaxy Tab A9+

### Steps to reproduce

Pre-requisites:
Have multiple logged accounts in TB Desktop (at least 1 gmail, 1 outlook, 1 yahoo)

Steps:
1. Launch the application (no accounts previously added)
2. Select Import Settings
3. Choose Scan QR code
4. Use the Camera to scan the Generated QR code(s)
5. Select Import 
6. Sign in to all imported accounts.

### Expected behavior

All the imported accounts successfully log in and all emails are properly displayed.

### Actual behavior

With the exception of the Yahoo account, all of the other imported accounts fail to login.
This issue is most definitely related to https://github.com/thunderbird/thunderbird-android/issues/8209

### Logs

Screen Cast of the issue : https://drive.google.com/file/d/1dwpDZk7ILp2HZrDnCXPD0uxltqgGp9hy/view?usp=sharing

**Comment by cketti** [comment] 2024-10-09 11:38
I was able to reproduce this issue with Thunderbird 8.0b2.

**Comment by cketti** [comment] 2024-10-09 11:41
It looks like this was caused by the bug fixed in #8267. I'm not able to reproduce the issue with the fix applied.

**Closed** 2024-10-14 18:30 UTC
