### ISSUE TITLE
Incorrect date shown for an email

### ISSUE THREAD

**Issue by mkende** [thunderbird/thunderbird-android#5526] opened 2021-08-05 21:38 UTC
**Describe the bug**
Unfortunately I’m pretty sure this bug is not easily reproducible, I’m still reporting it in case someone has an idea of what is happening.

I have a phone which had the July 24th version of the app installed (from the Google Play store), which I hadn’t synced for a couple of days. I switched it on, opened K9-Mail and, after a sync, at the top of my message list, there were 3 messages that I had received a couple of days ago, that were shown as if they had just been received at that time I opened the app. These messages were sent at the same time by the same sender a couple of days ago, so there is maybe something in their structure that is causing that.

-   [Screenshot showing one of the message as seen in K9-Mail with the wrong date](https://user-images.githubusercontent.com/3381888/128423294-5a316043-8992-49d6-b519-158a2033ebca.png)
-   [headers of that same email as exported by K9-Mail itself, with the correct date](https://github.com/k9mail/k-9/files/6941766/headers.txt)

I have confirmed in a different email client that the messages are still stored on the IMAP account with their correct date.

I updated the app to the July 27th version and the problem stayed the same (these 3 messages still displayed with the wrong date).

I then took another device with an instance of K9-Mail that was not yet updated to the new UI. I updated it (so directly to the July 27th version 5.802, and it did not displayed this issue (but it had already loaded these messages before the update, as opposed to the other device).

Let me know if I can provide more debugging informations.

**To Reproduce**
1. Open the app (but see above for much more details)

**Expected behavior**
Messages are sorted by date (sent date, received date, server date, I don’t know, but some kind of date).

**Screenshots**
Some messages are displayed as if they had been just received while they are a couple of days old (both the sort order and the displayed date for these messages is wrong).

**Environment (please complete the following information):**
 - K-9 Mail version: 5.802, but maybe caused by the previous version
 - Android version: 11
 - Device: Google Pixel 3
 - Account type: IMAP

**Additional context**

**Logs**
I can’t *trigger* the error so I’m not sure that logs are useful, but let me know if you still want me to generate them.

**Comment by njeyaakili** [comment] 2021-08-06 01:54
Based on the header information you provided, the message appears to be lacking the (user-visible) origination date - "Date:" - field, which is a standards requirement. Because of the way the user-visible fields - Date:/Subject:/To:/From: - are transmitted MTA-to-MTA you will find them clumped together in a header display like the one you provided. When the "Date:" field is missing all bets are off in terms of what date is used.

So, yes there is a bug ... your correspondent's messages are not standards compliant.

**Comment by cketti** [comment] 2021-08-06 15:47
Duplicate of #1356

Not exactly the same. But close enough so we don't need two separate issues.

**Closed by cketti** 2021-08-06 15:47 UTC
