### ISSUE TITLE
Crash when opening any message from a one particular sender

### ISSUE THREAD

**Issue by gh2011** [thunderbird/thunderbird-android#5041] opened 2020-11-04 06:38 UTC
Whenever I open a message from Discover (the credit card company), K9 immediately crashes with the "K-9 mail has stopped" message. This just started happening; it was working fine a couple weeks ago. All messages from other senders open correctly. I've attached a log from the time between launching K9 and right after the crash, and one of the messages that cause this to happen. Thanks for your help!

# Expected behavior

The message displays normally.

# Actual behavior

K9 crashes immediately everytime a message from this sender is opened.

# Environment

Device:  Samsung Galaxy Tab S 8.4 (SM-T700)
Android version:  7.1.2
K9 version name:  5.600
K9 version code:  26000 
Account type:  IMAP

[k9.log](https://github.com/k9mail/k-9/files/5485804/k9.log)
[message.zip](https://github.com/k9mail/k-9/files/5485807/message.zip)

**Comment by cketti** [comment] 2020-11-04 13:37
This is fixed in 5.7xx beta versions.

Duplicate of #3652

**Closed by cketti** 2020-11-04 13:37 UTC
