### ISSUE TITLE
No notification sound / no notification light when new mail arrives

### ISSUE THREAD

**Issue by VRO58** [thunderbird/thunderbird-android#2999] opened 2017-12-29 18:23 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen
Notification Sound / Light should be hearable/visible when new mail arrives

### Actual behavior
Tell us what happens instead
No Notification sound and no Light notification when new mail arrives
(it worked in versions prior 5.400

### Steps to reproduce
1.Send a mail from an external account (not in K9)
2. New Mail arrives (indicated within the K9 account and with a small letter in Notification bar)
3. There is no sound and LED notification light

### Environment
K-9 Mail version: 5.400

Android version: 6.0  (LG G4)

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by hfinp** [comment] 2018-01-01 10:02
Same issue here with an LG L90 yesterday. Today, however, it suddenly worked. Seems to be sort of unstable. (No LED here, just notification sound.)

**Comment by hfinp** [comment] 2018-01-01 11:37
After it did not work later today again, I tried to disable the night-time pause for notifications in global settings. This seems to be a workaround for now until the issue is fixed.

**Comment by Schwefelholz** [comment] 2018-01-01 16:09
We are experiencing this issue as well on Moto G (1st edition) and Moto G4. However, it seems to be working sometimes: Worked on Moto G yesterday, but does not today. No changes to configuration made.
It's not clear to me what causes the effect until now.

**Comment by katonagl** [comment] 2018-01-01 20:37
I have the same problem. It seems that the night-time pause begin and end times are switched. Try switching them, for me it seems to work.

**Comment by gitfve** [comment] 2018-01-03 16:38
**Same here no indication at all! Random working...

->K9 V5.401 / Android 7.0 Huawei P10

**Comment by nathanzachary** [comment] 2018-01-04 03:24
It does seem to be related to Quiet Time settings.  I just had another example of it.  The first email that I received after Quiet Time started produced a notification.  Subsequent ones have not, though.  The same thing happened this morning when Quiet Time ended: first email caused a notification, but all others failed to trigger the notifications (except on-screen).

**Comment by jimimaseye** [comment] 2018-01-04 07:44
I have exactly the same experience.  Randomly, (but more often than not), new email notifications do not occur.  It led me to revert back to 5.208 (Ive learnt to save old APK's of K9 before updating due to recent experiences of it changing/breaking things from what was otherwise a perfectly acceptable client solution).

Could it be related to the same cause of #3022 ?
(Note that I have several accounts running from several different email servers which are RFC compliant and ALL of them never had a problem prior to this latest 5.4.)

**Comment by source-direct** [comment] 2018-01-04 20:13
same experience here, randomly. no notification sound, especially at the first check after deactivating the flight mode if more than one mail have been added.

->K9 V5.401 / Android 7.0 Honor 9

**Comment by katonagl** [comment] 2018-01-05 11:01
Notification is totally random, my previous guess was false. I have reverted back to 5.208 because of this, but strengthened  by the ugly new icon.

**Comment by CandidCamera** [comment] 2018-01-05 18:12
No notification sounds for incoming mail when "Quiet Time" global setting is set.

Notification sounds work when "Quiet Time" is set / turned on.

**Comment by cketti** [comment] 2018-01-05 19:45
The bug is in quiet time handling and will be fixed in the next K-9 Mail version.

**Comment by hfinp** [comment] 2018-01-05 20:01
Cketti: thank you, good 2 know!

**Closed** 2018-01-06 08:00 UTC

**Comment by nyetwurk** [comment] 2018-04-01 01:27
Still not working. Pixel 2 Android 8.1.0 power optimization off, imap push, dovecot.

**Comment by gazzawazza** [comment] 2018-04-03 15:52
I'm getting this too. However, it works sometimes and i think I've worked out when!

**Expected behaviour**
Notification Sound / Light should be audible/visible when new mail arrives

**Actual behaviour**
No Notification sound and no Light notification when new mail arrives
(worked fine on Android Nougat and my current K9 build - 5.403)

**Steps to reproduce**
1. reboot phone
2. volume is active (not muted or vibrate) and levels appropriate
3. no do not disturb, etc
4. check for new mail (K9 sync button - timed polls are disabled)
5. assuming new mail, new mail symbols appear in status bar but no "new mail ringtone" heard or LED seen (though both are configured), on both accounts


**Fix!**
if one chooses mail tone again in K9, after reboot, tone and LED are heard/seen


**Environment**
K-9 Mail version:
5.403

handset:
Samsung S8 (SM-G950F) on O2 (UK carrier)

firmware build:
G950FXXU1CRC7

Android version:
8.0.0 (official O2 build)

Account type (IMAP, POP3, WebDAV/Exchange):
POP3 (2 accounts)
