### ISSUE TITLE
Auto refresh (fetch mail) on app start

### ISSUE THREAD

**Issue by jakariyaa** [thunderbird/thunderbird-android#7645] opened 2024-02-14 20:26 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

Every time I open the app I have to manually pull to refresh the mailbox to fetch the new mail that just came (for example an OTP/Verification mail)

### Suggested solution

The App should automatically refresh (fetch new mails) for one time when it is opened (if connected with the internet). 

_In that way I would not need to do the obvious refreshing manually every time I open the app._

**Comment by cketti** [comment] 2024-12-05 11:41
Duplicate of #7257

**Closed by cketti** 2024-12-05 11:41 UTC
Labels: type: enhancement, unconfirmed
