### ISSUE TITLE
High priority notification even if "do not disturb" enabled

### ISSUE THREAD

**Issue by bkenobi** [thunderbird/thunderbird-android#7581] opened 2024-01-29 15:58 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

Ability to provide a high priority notification if an important email is received.  This could be based on subject or based on sender.  High priority should be able to override "do not disturb" setting if needed and be an option by user for each topic/sender.

### Suggested solution

Example scenarios where immediate attention is required and "do not disturb" should be ignored (by user selection)
- Sensor in home detects water leak and sends email notification which is critical
- Utility notifies of potential water leak
- Important contact (spouse, business associate, etc) sends message that you are waiting for
- Important topic (home purchase details, etc)

There are lots of reasons why an email might be critical to know about as soon as received.  If it comes in at night, it might be important enough to be woken up for.  Push notifications work if both parties are on them but sometimes email is the only mechanism to send such a message.

### Screenshots / Drawings / Technical details

I have been using K9 for years and have never seen this feature though looked in app many times.  I searched the github but found nothing.  The K9 community forum seems to be offline so I don't see any other vehicle to make such a request.

**Comment by cketti** [comment] 2024-02-12 14:31
Duplicate of #5118

**Closed by cketti** 2024-02-12 14:31 UTC
Labels: enhancement, unconfirmed
