### ISSUE TITLE
Double copies of same sent email

### ISSUE THREAD

**Issue by jew4blackberry** [thunderbird/thunderbird-android#8311] opened 2024-10-10 18:45 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Other

### Android version

14

### Device model

Pixel 9 Pro XL

### Steps to reproduce

1. On Office 365/Outlook account, go to sent emails folder and I see duplicates of sent email from the Thunderbird email client

### Expected behavior

Not duplicate the sent email

### Actual behavior

Duplicated the email

**Comment by cketti** [comment] 2024-10-10 19:27
Duplicate of #7134

**Closed by cketti** 2024-10-10 19:27 UTC
