### ISSUE TITLE
Crashes after application was recompiled

### ISSUE THREAD

**Issue by nazar-pc** [thunderbird/thunderbird-android#7579] opened 2024-01-27 23:45 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.712

### Where did you get the app from?

F-Droid

### Android version

Graphene OS (Android 14)

### Device model

Pixel 7 Pro

### Steps to reproduce

1. Update Graphene OS to newer version
2. After reboot and log in OS will optimize/recompile apps in background and will ask to restart them
3. Click restart and see crash report from K9 Mail a moment later

### Expected behavior

Should restart gracefully

### Actual behavior

Get crash report instead, logs look similar to https://github.com/thunderbird/thunderbird-android/issues/7416, but I think circumstances are different. This has been happening for as long as I saw this background recompilation mechanism used in Graphene OS.

### Logs

```
type: crash
osVersion: google/cheetah/cheetah:14/UQ1A.240105.004/2024012600:user/release-keys
package: com.fsck.k9:37012
process: com.fsck.k9
processUptime: 330 + 362 ms
installer: org.fdroid.basic

java.lang.RuntimeException: Unable to start service com.fsck.k9.controller.push.PushService@6147972 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4906)
	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2321)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:294)
	at android.app.ActivityThread.main(ActivityThread.java:8279)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
	at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
	at android.os.Parcel.readParcelableInternal(Parcel.java:4890)
	at android.os.Parcel.readParcelable(Parcel.java:4872)
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3061)
	at android.os.Parcel.createException(Parcel.java:3050)
	at android.os.Parcel.readException(Parcel.java:3026)
	at android.os.Parcel.readException(Parcel.java:2968)
	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6805)
	at android.app.Service.startForeground(Service.java:878)
	at com.fsck.k9.controller.push.PushService$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
	at com.fsck.k9.controller.push.PushService.startForeground(PushService.kt:45)
	at com.fsck.k9.controller.push.PushService.onStartCommand(PushService.kt:28)
	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4888)
	... 11 more
```

**Comment by cketti** [comment] 2024-04-12 13:15
The underlying problem is most likely the same as in issue #7416. So I'm marking this as a duplicate.

Duplicate of #7416

**Closed by cketti** 2024-04-12 13:15 UTC
