### ISSUE TITLE
REGRESSION: forced to recompile all server parameters if certificate is changed

### ISSUE THREAD

**Issue by Ivan-SB** [thunderbird/thunderbird-android#8308] opened 2024-10-10 13:41 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Samsung Galaxy A33 5G

### Steps to reproduce

When a certificate was expiring or simply was changed (certibot/let's encrypt) I was used to go to account setting -> Fetching mail -> Incoming server and simply chose Next (or whatever there was before, I can't check since now it is different) and accept the new certificate.
Same for outgoing email.
Now whenever I go to setting it starts by requiring again the email and make me compile ALL the fields again.

I don't know if this just happens if certificates are expired... or every time you try to change something in the server configuration, but that's very inconvenient.

BTW once there I couldn't find anymore the "Push" settings. It is not clear if it automatically default to Push or it doesn't support Push anymore and now the only option is pooling emails.

thanks

### Expected behavior

a) see the form as it was before
b) provide the choice between wizard (?) and manual setup remembering previous setup

### Actual behavior

REDO all settings

**Comment by cketti** [comment] 2024-10-10 13:44
This is a bug in the navigation. It'll be fixed in 8.0b3.

Duplicate of #8271

**Closed by cketti** 2024-10-10 13:44 UTC
