### ISSUE TITLE
Long URLs are not wrapped, viewport is scaled and the font is then utterly small and hard to read

### ISSUE THREAD

**Issue by dilyanpalauzov** [thunderbird/thunderbird-android#6921] opened 2023-05-24 19:33 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

No custom ROM

### Steps to reproduce

I receive a HTML email with very long URL.  In K9 the HTML message is scaled, so that the whole URL fits on my screen. But then the font is so small, that I cannot read the text.  I cannot also enlarge the font, unless I rotate the device to horizontal mode, which makes the font slightly larger, but this is not ideal.

• In emails URLs shall be wrapped by default at any position, e.g. by implicitly using this CSS style `a {overflow-wrap:anywhere}`.

The other problem is that once I get emails with big embedded images, the email is again scaled, so that the image fits on the screen and the the font is again too small.

All in all, when long URLs or big images are received in HTML mails, the font size shall not be decreased, as this complicates the reading.  And reading is more important than fitting everything, except text worth reading, on the screen.

### Expected behavior

See above.

### Actual behavior

See above.

**Comment by JCGoran** [comment] 2023-05-25 09:08
Pretty sure this is a duplicate of #3172

**Comment by cketti** [comment] 2023-05-25 09:55
Duplicate of #3172

**Closed by cketti** 2023-05-25 09:55 UTC

**Comment by dilyanpalauzov** [comment] 2023-05-28 10:15
https://github.com/thundernest/k-9/issues/3172 is about unnecessary scaling of the font, when there is a long URL included.

This ticket is in addition about unnecessary scaling of the font, when a big image is included in the email.
