### ISSUE TITLE
Notification no longer dismissed by opening inbox

### ISSUE THREAD

**Issue by Pinkyatacme** [thunderbird/thunderbird-android#1921] opened 2017-01-02 17:01 UTC
### Expected behavior
Previously, opening the inbox cleared the notification icon

### Actual behavior
Notification icon remains, and needs to be manually dismissed

### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:
5.201
Android version:
5.0.1
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2017-01-03 01:56
It works for me. Can you provide more information? Does this always happen? Is there something special about the messages? How many accounts do you have set up? Does it happen for all accounts?

**Comment by Pinkyatacme** [comment] 2017-01-03 12:46
It seems to be intermittent. There doesn't appear to be any pattern, but I have noticed this morning that the count on the notification stated 3 messages, but there were 7 (including 3 in a mailing list thread) that had come in. I'll try a day or so with the threading display off to see if that makes a difference.

**Comment by Pinkyatacme** [comment] 2017-01-04 00:35
Sorry to report that switching to non-threaded display had no effect. Just got off a flight, and the notification states 4 new messages, but I have 13, and the notification is still showing after reading all of them. Would the debug logging provide additional details?

**Comment by FoxFR** [comment] 2017-01-06 08:42
I'm also having this issue.  These are the steps to reproduce this issue:

1.  The notification icon always remains when reading mail in K9 itself, not going in via the notification icon.

2.  When going in via the notification icon, it takes you into K9 and the notification icon in this case does disappear as expected, but only the one that was selected.  Reading other mailboxes whilst in K9 does not dismiss the other notification icons.

Previously, the notification icons always disappeared when accessing K9 in both methods described above.
I have multiple mailboxes defined, and the above seems consistent across all accounts.

K-9 Mail version: 5.201
Android version: 5.1

**Comment by FoxFR** [comment] 2017-01-06 09:17
Actually, despite what I wrote in my last post, this is not consistent.

I've just received a number of mails, going into K9 via one of the notifications, and then viewing all other mail, and all the notifications have been dismissed.  

This doesn't always happen, and I'm now not sure how to reproduce this.

**Comment by snmnarum** [comment] 2017-01-07 15:53
I have seen this intermittently (but more often than not) as well. It also no longer clears the notification if I read the mail in another computer like it used to. Prior to the recent updates, reading the email from my computer would result in k9 realising there are no new emails and it would clear the notification.

**Comment by snmnarum** [comment] 2017-01-07 16:00
Additional info: I have 6 accounts set up total, 4 Gmail accounts, 1 IMAP to another provider, and 1 IMAP to MS exchange. All show the issue.

**Comment by lchmiel** [comment] 2017-01-08 13:11
I have exactly the same situation as  FoxFR commented 2 days ago, in his first message. The notifications for the single mailbox disappear only if I enter the message through the notification for this particular inbox. So, the notification disappears only if I enter all the the mailboxes directly from their notifications. (In practice, then, I dismiss all the notifications with the system function.)

I have 7 accounts. Six of them POP, of which one is gmail. One of them is IMAP on gmail. 

Versions:  K-9 5.202 (the bug started from 5.201). Android 6.0.1, from Sony. Phone: Sony Xperia Z3 D6603, not rooted.

I have enabled the debug logging now (without sensitive data) so after a day I can send it in a private message; but to whom?

**Comment by mamoch** [comment] 2017-01-10 17:13
I also have the problem with the symptoms which snmnarum described earlier: reading mails on a PC do not delete corresponding notifications from K-9 on the phone.

I have three IMAP accounts and I use polling every hour to check them, no push service. (I know, that with this configuration only every hour everything gets refreshed. But of course the problem is there _after_ refreshing.)

K-9 Mail Version 5.202
Android 5.0.2
Sony Xperia Z1, stock ROM, rooted

**Comment by Snookoid** [comment] 2017-01-13 08:39
I have also started seeing this issue intermittently for the past week or so, on my Samsung Galaxy S5. I access the same email accounts on my Samsung Galaxy Tab Pro, but haven't seen it on there yet, although I use it less frequently.

**Comment by wedgerage** [comment] 2017-01-31 19:33
When will this be fixed? This problem has been on my phone (Galaxy S6) for a while and it is quite annoying. I have to clear notification manually a lot of times per day to get rid of the notification.

**Comment by FoxFR** [comment] 2017-01-31 22:34
I second that.

It's very annoying to not know if I've got new mail, and having to clear multiple notifications all the time.

**Comment by mamoch** [comment] 2017-02-01 11:11
Two weeks ago I recreated all accounts from scratch as I described above because this issue was quite annoying. And at the beginning everything seemed to work, but after I had set up all three accounts the problem was back. Now not a single notification gets dismissed by opening the inbox.

So reinstalling and setting up again also doesn’t help.

**Comment by ikeeki320** [comment] 2017-02-03 15:55
I too have the same issue and it has been going on for a while. I only have one account set up via IMAP.
K9 5.203
Android 6.0.1
Galaxy S7 on Verizon

**Comment by tomasrudh** [comment] 2017-03-16 20:47
I have seen this problem for quite some time. Is it being worked on? Anything I can do to help?

Samsung Galaxy S5
Android 6.0.1
K-9 Mail version 5.203

**Comment by lchmiel** [comment] 2017-03-17 08:52
Since the problem emerged nothing has changed.

It is difficult for less technical people like my wife or daughter to manually dismiss the notifications each time.

POP accounts: 6, including 1 on gmail. IMAP accout: 1, on gmail.
Versions: K-9: currently 5.203 (the bug started from 5.201). 
Sony Xperia Z3 D6603, not rooted. 
Android 6.0.1, from Sony.

**Comment by philipwhiuk** [comment] 2017-03-17 09:53
A debug log would be useful here.

**Comment by lchmiel** [comment] 2017-03-17 10:24
As I wrote on Jan 8, the debug logging is on, but where can I find the log file? There is none in Android/data/com.fsck.k9, or any other file with "k9" in its name, either on internal or external disk.

**Comment by mamoch** [comment] 2017-03-17 10:48
https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by tomasrudh** [comment] 2017-03-18 13:10
[k9-log.zip](https://github.com/k9mail/k-9/files/852439/k9-log.zip)
I have attached a log file hopefully having some useful info, I opened K-9 at around 14:00 with the notification showing, that did not dismiss.

**Comment by philipwhiuk** [comment] 2017-03-18 13:38
Some interesting and possibly relevant logging

> 03-18 13:57:14.272 W/StatusBar( 3989): removeNotification for unknown key: 0|com.fsck.k9|8|null|10199

> 03-18 13:57:14.352 D/ApplicationPolicy( 1176): isStatusBarNotificationAllowedAsUser: packageName = com.fsck.k9,userId = 0

There's also evidence of #1240 which should be fixed in the next release.

> 
03-18 14:00:50.147 E/Parcel  ( 1176): Class not found when unmarshalling: com.fsck.k9.search.LocalSearch

My question is: The notification you actioned - did the effect happen. If it didn't, then it's possible this will be fixed by #1240. If it did, we need to look at that logging and work out what's happening.

**Comment by tomasrudh** [comment] 2017-03-18 13:50
Not sure what you mean with 'The notification you actioned'. When I saw the K-9 notification I opened the app by clicking the widget, the notification did not get dismissed. When I drew down the curtain the notification said I had two new messages.

**Comment by Jh1440** [comment] 2017-04-08 14:19
I've noticed that the notification seems to be removed by actually downloading a new message in that account (when not launched by the notification itself). For example, I have 3 accts, all with notifications showing. I open k9 via widget, and it shows my universal inbox. It also downloaded a new message in one acct, and only that notification disappeared. The others didn't, even if I manually checked for new messages. Perhaps an additional check for dismissing notifications should be added when an account, or the universal inbox, is opened? Also, it might be appropriate to display new notifications only if the app isn't displayed? 

Thank you.

**Comment by finsterwalder** [comment] 2017-04-25 12:29
Same issue here.
I would say the notification never disappears when opening k9 directly or reading the message with another program. If it ever does, I didn't notice.

IMAP-Account
Android 5.0.2 (LG G2)
K-9 Mail Version: 5.206

**Comment by rogerval** [comment] 2017-05-21 20:43
I too have this issue; it seems that new notifications will disappear when I open the inbox, but old notifications (eg for emails received overnight) won't disappear when I open the inbox.
I've had k-9 logging going for a couple of days, and taken a couple of screen shots showing visible notifications, even though none of my k-9 accounts have unread mail.
I'm currently using k-9 version 5.206
My phone is a stock Samsung Galaxy S2, GT-I9100, android version 4.1.2
Hopefully someone is able to figure out what's going wrong from the info I've provided (and of course I'm happy to provide more if needed.)
Thanks in advance,
Roger V.
(Currently I'm going through the log file to make it more anonymous, as I'm not the only email identity mentioned in there. More info will be provided tomorrow, I hope.)

**Comment by rogerval** [comment] 2017-05-22 01:08
Hi again...
I've finished with the log and the screenshots, so I'll post them.
Thanks for looking at them, and I hope they're useful for debugging the problem (perhaps it's a problem with my old S2...)
[k9-log_170522_edited.zip](https://github.com/k9mail/k-9/files/1017521/k9-log_170522_edited.zip)
![screenshot_2017-05-22-03-52-56 edited](https://cloud.githubusercontent.com/assets/28846333/26289019/ec1627d4-3ede-11e7-84b7-7f6c0c37c62e.png)
![screenshot_2017-05-22-04-29-17 edited](https://cloud.githubusercontent.com/assets/28846333/26289018/ec13a392-3ede-11e7-87b8-2151fe744c2f.png)

**Comment by cketti** [comment] 2021-08-12 14:49
Please create a new issue if this problem is still present in K-9 Mail 5.803 or newer.

**Closed by cketti** 2021-08-12 14:49 UTC
Labels: status: needs information
