### ISSUE TITLE
Ghost message list

### ISSUE THREAD

**Issue by nu-fo** [thunderbird/thunderbird-android#4452] opened 2020-01-15 12:26 UTC
Some times message list is shown incorrectly, with a message list overlayed on another message list.

### Steps to reproduce
1. Have two mail accounts, A and B.
2. Open a message, _which is inside a thread/conversation_, in account A.
3. Wait for new mail notification for B account.
4. Open message list for B account by tapping on new mail notification for B account.
5. Tap the back arrow on top left screen corner.
6. Now there should be two message lists as described above. Of these two, one remains stationary while the other one can be scrolled and tapped to open a message.

### Environment
K-9 Mail version: 5.703, fdroid

Android version: 6.0.1

Edit: _in italics_

**Comment by basilgello** [comment] 2020-01-15 16:57
Got this glitch once, thought it was a hwcomposer bug. Is it reliably reproducible @nhfo ?

**Comment by nhfo** [comment] 2020-01-16 18:59
Yes @basilgello  it happens every time. It is definitely unrelated to hwcomposer because message list should have menu (three horizontal lines) button not the back arrow.

**Comment by cketti** [comment] 2020-01-24 15:23
Issue #4340 contains a screenshot showing the problem. I'm keeping this issue because it contains instructions to reproduce.

**Comment by rdy2go** [comment] 2020-01-31 16:53
in my case, the overlaying message list isn't visible.

But if i tap a message the message that lay's invisible over the tapped one, opens.

Environment:
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by mpas97** [comment] 2020-03-04 11:26
With the newest beta 5.706 I have still multiple lists on top of each other. It happens quite often when I long press a message then select "More from this sender" and if I redo the same and I then go back, there is this overlay.

**Comment by cketti** [comment] 2020-03-04 12:20
@mpas97: Can you please create a new issue with instructions on how to reproduce. I'm guessing this is caused by PR #4581.

**Comment by cketti** [comment] 2020-03-04 12:39
@mpas97: Nevermind. I think I found the bug and created a fix. See PR #4587.

**Comment by ryanleesipes** [comment] 2022-06-17 18:34
This still exists. I apologize for reopening this. The reproduction steps are the same as they originally were. Using Android 12.

**Comment by gunterkoenigsmann** [comment] 2022-06-18 07:11
Had the same phenomenon with K9 beta (6.000) today, too.

**Comment by gunterkoenigsmann** [comment] 2022-06-25 04:35
In 6.1000 the issue is still present, but didn't trigger for days for me so it happens no more reliably for me:
![Screenshot_20220625-063345](https://user-images.githubusercontent.com/5041537/175758130-385927ed-e580-4d87-8983-894b5a1a93ab.png)

**Comment by gdt** [comment] 2022-06-25 11:32
A metoo only because this seems fairly rare: I also had this happen a few days ago, on 6.000 f-droid, which I realize is the old stable not the current beta.  I think I was doing something unusual (maybe clicking on a notification for an inbox message while scrolled deep into inbox).

**Comment by gunterkoenigsmann** [comment] 2022-06-25 17:49
Found a new trigger: Tap on a message notification. Press "back" to get to the unified inbox and tap on the phone's "Back"  button again. If the app doesn't close it shows the ghost message list again.

**Comment by basilgello** [comment] 2022-06-27 11:18
> Found a new trigger:

Can you please reproduce it with painting regions settings on from Develooer settings?

**Comment by gunterkoenigsmann** [comment] 2022-06-29 16:39
There were several of those settings =>
- https://peterpall.de/screen-20220629-125552.mp4
- https://peterpall.de/screen-20220629-125830.mp4
- https://peterpall.de/screen-20220629-125955.mp4

**Comment by cketti** [comment] 2022-07-13 19:07
Steps to reproduce:
1. Open the message list of a thread.
1. Tap the back arrow on top left screen corner.
1. Open the message list of a thread (can be same thread).
1. Go to home screen.
1. Use message list widget to open a message.
1. Tap the back arrow on top left screen corner.
1. Tap the back arrow on top left screen corner.
1. Now there should be two message lists.

**Closed** 2022-07-14 10:41 UTC
