### ISSUE TITLE
Just delete an email without sending it to trash

### ISSUE THREAD

**Issue by gitmatt19** [thunderbird/thunderbird-android#8006] opened 2024-07-09 21:02 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

all

### Problem you are trying to solve

I get a number of emails I read and just want to just delete without sending to trash where things collect.

### Suggested solution

Wish I could select the email(s) and "long press" the trashcan and have it just delete them instead of going to trash. This would allow selective deletes of emails I know I dont care about and will never go hunting for in trash folder.

**Comment by cketti** [comment] 2024-07-15 17:04
Duplicate of #3959

**Closed by cketti** 2024-07-15 17:04 UTC
Labels: type: enhancement, unconfirmed
