### ISSUE TITLE
attached photos are replaced with duplicates

### ISSUE THREAD

**Issue by vn971** [thunderbird/thunderbird-android#749] opened 2015-08-14 08:34 UTC
How was this bug caught:
- started composing a mail
- attached 4 photos using the standard attach feature of K9 (button)
- K-9 showed as if it fully succeeded, a mail was sent and it has 4 photos attached inside.
- The problem: all photos are copies of the last photo. They have identical contets, identical size but not identical names (names are correct).

Expected:
- fail to send the message or send 4 different attachments.

Reproducible? - No. I could not reproduce the problem:
- sending a message with the same 4 photos went OK. Photos have correct contents but the same names as in the first attempt.

Verification, why trust this bug report:
- the _names_ of the attachments are correct, these are 4 different photos. In case of a human mistake (attaching the same photo 4 times) there would be 4 identical names.

**Comment by cketti** [comment] 2015-08-14 17:43
- What version of K-9 Mail were you using?
- Which app did you use to select the images to attach?
- Did you add them one by one? Or did you select all of them in one go?

**Comment by vn971** [comment] 2015-08-14 20:17
* version 5.004. Seems outdated, unfortunately..
* images were chosen using the `Gallery` application.
* images were chosen one-by-one.

**Comment by britiger** [comment] 2015-10-14 07:13
I've found the same Bug:
 - Version 5.006
 - Using Standard Gallery App on Sony Acro S

**Comment by cketti** [comment] 2016-07-17 22:32
Can't reproduce. Chances are this is fixed in the current development version.

**Closed by cketti** 2016-07-17 22:32 UTC
Labels: status: needs information
