### ISSUE TITLE
Can't connect to crypto provider at first when starting from clicking email address in external apps

### ISSUE THREAD

**Issue by UjuiUjuMandan** [thunderbird/thunderbird-android#7503] opened 2024-01-13 15:56 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

CalyxOS 5.2.0, Android 14

### Device model

Google Pixel 5

### Steps to reproduce

1. Set up E2EE.
2. Click one email link form external app, like browser, and if prompted, select K-9 Mail, got into email compse page.
3. Write anything.
4. Click send.

### Expected behavior

Message sent.

### Actual behavior

It says 'Cannot connect to crypto provider'.

https://github.com/thunderbird/thunderbird-android/assets/125150101/42104120-41ca-431a-988b-7620025c53b2

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/13928679/k9mail-logs.txt)

**Comment by criztovyl** [comment] 2024-01-13 18:53
related #7438 ?

**Comment by UjuiUjuMandan** [comment] 2024-01-13 19:07
@criztovyl Not related at all. The point here is: Starting from an external app, if not this, the 'cannot connect' won't occur.

**Comment by cketti** [comment] 2024-01-16 18:56
This is probably a duplicate of #6068. Please install a recent beta version and check if that fixes the problem.

**Closed** 2024-01-16 20:22 UTC
