### ISSUE TITLE
IMAP sync silently failing when Gmail locks account 

### ISSUE THREAD

**Issue by robsmith11** [thunderbird/thunderbird-android#4202] opened 2019-09-23 17:17 UTC
When I travel abroad, Gmail annoyingly locks my account almost every time mu IP address changes and I try to sync with k9.  When this happens, there is no indication that syncing failed except that new emails don't appear. K9 should display some kind of error in these cases.

**Comment by gdt** [comment] 2019-09-23 22:02
I realiize that you realize that you primarily have a google problem vs a k-9 problem, but for k-9 to be improved someone needs to figure out exactly what happens and how it can be recognized, and then decide that should happen and then write a patch.   So if you can run adb and determine how your account behaves when it is in the "locked" state, that would be helpful.  It could be anything from telling you that login failed, to letting you appear to log in but not reporting that new email is present.   Perhaps google support can provide you with a specification.

**Comment by robsmith11** [comment] 2019-09-23 23:15
Shouldn't k9 report any kind of login failure, regardless of the specifics?

I know that a login error message is provided by Gmail because I've had the same issue with OfflineImap (which does properly through an error containing the full message from Gmail).

**Comment by gdt** [comment] 2019-09-23 23:56
To make progress, someone (it could be you) needs to actually obtain the message behavior that results and put it in the issue, and then analyze the code and figure out what to change.   I did not assert that there was no bug -- only that your description is too vague to be actionable.  At this point you should also build the development version at test against that; I know  a lot of things have been improved but I have no idea if this is one of them.

**Comment by dymn** [comment] 2021-03-16 07:25
The problem still here. Very annoying. There is a big risk of not receiving an important message in time and not seeing an error notification about it.

**Comment by robsmith11** [comment] 2021-03-16 08:17
I ended up configuring Gmail to forward all of my mail to a non-Gmail account.  I use that account for reading everything in k9, but can then still use the Gmail account for sending since k9 will show an error whenever sending fails.

Not ideal, but I missed too many emails otherwise

**Comment by dymn** [comment] 2021-03-16 08:22
Gmail is one of the most popular email services. And dropping his normal support is suicide for k-9.

**Comment by poldi171254** [comment] 2021-04-29 00:05
I had a quick look at this and the issue as I see it is that while k-9 logs all coonection failures+reasons, it doesn't let the user know. So for me the easiest/simplest solution would be to pop up a message window with the failure/reason.

Given that this part of the code is still in Java, is there any preference on how to provide this?

**Comment by robsmith11** [comment] 2021-04-29 02:36
I would think any errors that are not just failed to connect because of network issues should be displayed as an Android notification.

Maybe it would also be good to show the last successful sync time for a mail directory in the main UI.

**Comment by poldi171254** [comment] 2021-05-08 03:54
After further investigation I found that a failure to log in logs a notification (see attached)
![Authentication failed](https://user-images.githubusercontent.com/43848359/117525184-5d809e00-b004-11eb-9229-848af034c9de.png)

Given that this approach already works, it could be extended for any other (synchronization) failures.

**Comment by poldi171254** [comment] 2021-05-09 06:41
Unless somebody can post what specifically the issue is, I suggest to close this

**Comment by robsmith11** [comment] 2021-05-09 08:02
> Unless somebody can post what specifically the issue is, I suggest to close this

Isn't the issue already known: there are no notifications for imap sync failures?

I'm assuming the screenshot you posted is for a smtp failure, for which I also get notifications.  They just need to be enabled for imap failures as well.

**Comment by poldi171254** [comment] 2021-05-11 05:11
I have tested this now on one of my gmail accounts; the result is the same (imap sync Failures are notified)
![gmail-fail](https://user-images.githubusercontent.com/43848359/117761651-13e5bc80-b26b-11eb-9d13-99a9a0727fd5.png)

**Closed** 2021-05-11 15:19 UTC

**Comment by robsmith11** [comment] 2021-05-11 15:44
Yeah it's still not working using the latest k9 beta.  I just had failures to sync earlier today when I was using a new wifi connection and didn't get any notifications.  I've only seen notifications on smtp failures and when I set up an imap account incorrectly. 

I'm guessing you're getting a different error message because you're testing by using invalid credentials, not switching IP addresses to another country that triggers Google's silly protection.

I don't have time to figure out how to access the debug logs, so I'll just leave this closed for now.
