### ISSUE TITLE
Error message: "unable to open connection to smtp server"

### ISSUE THREAD

**Issue by Neuwessi11** [thunderbird/thunderbird-android#6358] opened 2022-10-07 10:09 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.202

### Where did you get the app from?

F-Droid

### Android version

9

### Device model

Cat S61

### Steps to reproduce

1. Start a new account and follow the required steps.

### Expected behavior

K-9 Mail should manage to get connection to the SMTP-server as well as to the IMAP-server.

### Actual behavior

After controlling the IMAP settings K-9 Mail starts to control the SMTP settings, and after some seconds it delivers the error message "unable to open connection to smtp server".

No problem at all with Thunderbird (on Laptop).

### Logs

[k9mail-logs[1].txt](https://github.com/thundernest/k-9/files/9732971/k9mail-logs.1.txt)

**Comment by cketti** [comment] 2022-10-07 15:56
I created a fix to make this work. However, you should tell your email provider to make the SMTP service also available over IPv6 since the hostname resolves to an IPv6 address. Otherwise there's a good chance K-9 Mail will first try the IPv6 address and only after the 30 second timeout try the IPv4 address.

**Comment by Neuwessi11** [comment] 2022-10-08 11:36
Thank you for the quick fix!
And I told it to my email provider, who found out that the server software in the default settings only addresses IPv4. He fixed it, too.
So thank you for fixing and helping!
By the way: Do I have to do something to get the fix or will it come automatically?

**Comment by cketti** [comment] 2022-10-08 11:45
If your provider made the service also available over IPv6, you probably don't need the fix for the app to work.

The fix will be included in the next [beta version](https://forum.k9mail.app/t/how-do-i-become-a-beta-tester/68). I don't think the issue is important enough to warrant updating the currently stable version. So it'll only be included in the next stable release (6.4xx).

**Closed** 2022-10-10 13:16 UTC
