### ISSUE TITLE
Missing Message header view

### ISSUE THREAD

**Issue by anton-sutopo** [thunderbird/thunderbird-android#5830] opened 2021-12-17 19:55 UTC
Hi all, 
I using k-9 mail from f-droid version 5.906. Every time i scroll the message, the header is blinking and some times it is blank.
![Screenshot_2021-12-18-02-45-15-51](https://user-images.githubusercontent.com/8575711/146600452-bbbdf099-a883-4861-9740-9fd1190e8bcc.png)

Fyi it is on android 8.1.0
Thank you

**Comment by cketti** [comment] 2022-01-09 07:44
See also https://forum.k9mail.app/t/disappearing-header/3481

I'm not seeing this on any of my devices. Without being able to reproduce the issue, it's very hard to fix a bug. 
As a first step you could install an old K-9 Mail version where things work as expected and then upgrade to the next higher version until the display issue appears. That way we should at least find out which version introduced the issue.

You can find all releases here: https://github.com/k9mail/k-9/releases

Chances are it's a bug in your Android version, not a bug in K-9 Mail. But maybe we can work around the issue.

**Comment by jpopovitch** [comment] 2022-01-09 14:37
@cketti Do you test K9 on Android 8.x ?

**Comment by cketti** [comment] 2022-01-09 16:08
> @cketti Do you test K9 on Android 8.x ?

Of course. But neither my Nexus 6P with Android 8.1 nor an Android 8.x emulator showed the described behavior.

**Comment by jpopovitch** [comment] 2022-01-09 23:17
@anton-sutopo Can you verify that you have "Force GPU rendering" disabled in Developer Options.   I was able to reproduce this problem on Android v8.0.0 if that option is enabled.  Disabling it caused the problem to go away.

**Comment by anton-sutopo** [comment] 2022-01-14 12:45
Hi @jpopovitch , 
I check all option in developer option is disabled by default and still have issues.
![Screenshot_2022-01-14-19-39-17-56](https://user-images.githubusercontent.com/8575711/149517400-e72546de-d1d6-4d21-9889-98affaa0366f.png)

Thank you

**Comment by cketti** [comment] 2022-05-01 16:52
Closing this issue. If someone can provide a way to work around this bug, I'm happy to include it in the app. But until then, there's nothing we can do.

**Closed by cketti** 2022-05-01 16:52 UTC
Labels: status: needs information
