### ISSUE TITLE
Email view does not stay scrolled at top

### ISSUE THREAD

**Issue by edman007** [thunderbird/thunderbird-android#6385] opened 2022-10-12 19:41 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.308

### Where did you get the app from?

Google Play

### Android version

12

### Device model

S10

### Steps to reproduce

1. View inbox, scroll to the top
2. Close k9
3. Get New emails
4. Open k9
5. New emails are not shown

### Expected behavior

If k9 was closed at the top (with the latest email at the top of the window) it should open at the top. The top should be treated like a special position so you see emails as they come in

### Actual behavior

It opens at the last email viewed, not scroll position.  the view is scrolled down to the last seen email, you have to scroll up to see if you got new emails. This is a change from previous versions.

**Comment by cketti** [comment] 2022-10-12 19:43
Duplicate of #6332

**Closed by cketti** 2022-10-12 19:43 UTC
