### ISSUE TITLE
[UX] Make quick actions in push notification configurable

### ISSUE THREAD

**Issue by ypislon** [thunderbird/thunderbird-android#7651] opened 2024-02-17 17:24 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I would like to change the available quick actions in the push notification. Currently, the two visible quick actions for each notification are "mark as read" or "reply". It would be helpful for my workflow with e-mails if I could select which quick actions are shown in the push notification, e.g. "archive", "spam", "delete" or "favorite/star" to immediately choose an appropriate action for new mails without opening the app.

### Suggested solution

I would suggest to add an option to customize the quick actions for all notifications. This could be added in "Settings > General settings > Notifications", with two settings for quick action 1 and quick action 2. 
The available options for each setting could be:
- Mark as read
- Reply
- Archive
- Mark as spam
- Delete
- Favorite/Star

This would cover the existing features. In the future, it would even be helpful to think about options like "Mute this conversation", which would disable further push notifications in the e-mail thread etc

**Comment by cketti** [comment] 2024-02-28 12:15
Duplicate of #3530

**Closed by cketti** 2024-02-28 12:15 UTC
Labels: type: enhancement, unconfirmed
