### ISSUE TITLE
New mail notification icon sometimes does not disappear

### ISSUE THREAD

**Issue by msebald** [thunderbird/thunderbird-android#1273] opened 2016-04-11 12:09 UTC
### Expected behaviour

After entering the account and/or directory the new mail notification icon should disappear from the Android notification bar. Like it was before the new 5.108 alpha version.
### Actual behaviour

Sometimes it disappears, sometimes not. At the moment on my device the icon stays even after I opened the new mail and also marked to as read by opening it.
### Steps to reproduce

see above
### Environment

K-9 Mail version: 5.108

Android version: CM 12.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by philipwhiuk** [comment] 2016-04-11 12:15
I'm not sure we do enough logging in the notifications system to make a debug log useful. This will probably just have to be experimentation to work out where we are not making the right calls:

See also #834 #1245 #1116

**Comment by msebald** [comment] 2016-04-11 12:29
For me the notifications were always working perfect. No issues for me, for years and for different k9/Android versions and different devices. But now starting with 5.108 I have the explained issue. But I guess it is hard to tell what of the many changes caused this, right?

Well, I am ready for experiments. ;-)

**Comment by philipwhiuk** [comment] 2016-04-11 12:53
I'll probably try and have a look what's changed with notifications this evening. But 5.108 includes a lot of changes to the code base - it'll be quite a big release when it drops.

If you can narrow down: "Sometimes it disappears, sometimes not" that would help :)

**Comment by cketti** [comment] 2016-04-11 12:54
The notification code has been completely rewritten.

Instructions on how to reproduce the behavior would be very helpful.

**Comment by msebald** [comment] 2016-04-11 13:25
Well, at the moment, "sometimes it happens, sometimes not" is the best I can give you. But I will take an extra-close look into this from now on. Which means that I will open every new mail on my phone first, then elsewhere and see, what happens.

I have two accounts in k9, maybe this is something which is a bit special, too. Most installations will only have one account I guess.

That everything is rewritten does not make it easier I guess. Also: Why? It worked. ;-)

**Comment by philipwhiuk** [comment] 2016-04-11 13:32
Android Wear support was the driving force. 

Another concern however is that much of the was not designed but just developed and what was designed was not done in a testable way (because in Android pre-history testing was very difficult anyway).

This is problematic because without regression testing it's difficult to avoid reintroducing older bugs to fix newly found ones. It's also harder to add features.

**Comment by msebald** [comment] 2016-04-11 13:37
I see. If it made sense, then it's good. And we have to deal with the issues. ;-) No worries.

Ok, what I can tell after 5 minutes is that clicking onto the notification (which did not dissapear) sent me to that new email and let the notification dissapear. So this seems to work (at least in this case) like I know it. But from my memory from the last weeks this seems to be working ok. The issue was there when I was opening k9 and navigated to the accounts and folders with the new mails and then sometimes the notification icon did not go away.

I'll be back here when I have more. Could take a day or two.

**Comment by msebald** [comment] 2016-04-11 14:11
Ok, two new mails just came in, one per account. The two notification icon dissapeared like I know it from the older k9 versions. Which means that I opened k9, entered the two inboxes and one after the other icon dissapeared.

**Comment by msebald** [comment] 2016-04-11 15:05
Now, after several mails which arrived into my inbox (not a subfolder of the IMAP account) I can say the following: "sometimes" stays... Because for three mails the icon disappeared and now for the forth it stays. I did not click into the message because when I do, the icon might disappear - or not. See above.

**Comment by DrAzraelTod** [comment] 2016-06-14 08:39
i can confirm that notifications are only dismised when i click on them
if i open mails any other way (i.e. i've manually checked k9 for new mails and thus read them directly) then the notification stays even if i read and archived the mail

pretty anoying

**Comment by lobstaj** [comment] 2017-07-09 07:06
I seem to have this issue from time to time. I notice I have new mail from the K9 notification, then I read the mail in my computer's browser, but the K9 notification is never removed.

If I remember correctly, the "read" flag of that new message is synced correctly. So when I open K9, I don't have unread mail, but the notification just was not cancelled.

Since this only happens sometimes, it's maybe not that important, it's just a little annoying to remove the notification manually.

**Comment by ThrashInc** [comment] 2018-08-08 17:49
I have Android 7.1.1 and have had this similar issue ...
I have found, oddly enough, that if I go into my SETTINGS for K9,
then into NOTIFICATIONS and then set OVERRIDE DO NOT DISTURB to
the ON status, oddly enough, I get ALL of my notifications; they ALL stay until
I swipe them, or look at them, and the MAIN/DEFAULT account notification 
doesn't disappear (it does with it off; as do the others ... DEFAULT never showing
otherwise) ...

Just my input; hope it helps someone/developers/whomever ...

-=Dave=-

**Comment by cketti** [comment] 2022-10-09 16:29
This was most likely fixed in 6.200. If not, please create a new issue.

**Closed by cketti** 2022-10-09 16:29 UTC
