### ISSUE TITLE
Adding multiple recipients to To, Cc, Bcc when not in Address Book not obvious or reliable

### ISSUE THREAD

**Issue by stef204** [thunderbird/thunderbird-android#3358] opened 2018-04-24 16:57 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
Tell us what should happen

When trying to add multiple recipients to To, Bcc or Cc fields, provided these are in the Address Book, they are usually recognized and offered for selection by K9.
IOW, when one starts to type the name "bob". K9 offers "bob@example.net" for selection

However, IF one wants to include one or more 3rd parties as recipients but not insert them in one's Address Book (e.g. this is just a "one-time" message), it is not immediately obvious how to get K9 to "detect" and "accept" manually inserted (typed) email addresses.  They appear spelled out but create a "parsing error" message (nice job on K9 giving off a helpful error message btw.)

Desirable: detect that an email address has been inserted manually and "accept" it without undue delays.

### Actual behavior
Tell us what happens instead

I tried to include one or more 3rd parties as recipients (which were not part of my Address Book), K9 did not "detect" and "accept" these manually inserted (typed out) email addresses.  They appeared spelled out but created a "parsing error".

Trying to separate the email addresses with commas or semicolons did not help (same parsing error message). I had to discard the message, start from scratch and this time, K9 detected an email address had been typed manually and as soon as this detection takes place, one can see that K9 formats it as some type of "contact label", with an icon to the left, etc.  I was then able to type yet another recipient (also not included in address book) and then had to change field or do something with cursor so as to "prompt" K9 to detect that additional email address and accept it.

It is not immediately obvious what process to follow.in the above case.  And it does not seem to be robust or 100% reliable since I coudl not get K9 to detect the typed out email addresses the fist time; and on second time, with new message, had to fiddle with cursor to get K9 to detect these email addresses.

Note: K9 is a great email client and this is really _minor_.

### Steps to reproduce
1.start new email
2.add a recipient which is in the address book in the To: field (this step may not be necessary).
3.in the Cc: field type in the email address of someone NOT in the address book (nothing happens). Insert <space> then type in an addtional email address (also of someone not included in address book).
4. nothing happens at times (i.e. K9 does not detect there are additional email addresses inserted which are not part of the address book or does not "parse" them) so one is left wondering how to make K9 detect these manually typed addresses.

### Environment
K-9 Mail version:
5.403
Android version:
7.1
Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by cketti** [comment] 2019-03-07 17:23
I can't reproduce this issue. Can you please provide more detailed information on what text you enter exactly? Either focusing another input field or typing a comma should "complete" the email address.

**Comment by Meteor0id** [comment] 2019-03-08 13:46
When you type a known address, you never need to type a comma. Even when the address 'autocompletes' no comma is added at the end. Subsequently, when you type an unknown address, it is not an intuitive action to type a comma. As a user who doesn't add a lot of manual addresses you might have never seen a comma in this field before. One expects the address to be 'completed' as soon as the spacebar is hit.
Furthermore the comma takes an extra step to switch the keyboard layout on most android keyboards.

The solution is simple: also accept clearspace as a valid separator.

I can see how to cketti a comma is the first thing that comes to mind, but the fact is that to most users that is not the first thing that comes to mind, neither is switching to another field. Most users would expect a clearspace to be sufficient. When that initially doesn't seem to work, (or no visual confirmation is provided that this will work) it leads to confusion and possibly frustration. To a human this looks valid: "why is k9 not confirming it?".

I am not completely sure this is the issue stef204 was reporting, but it is certainly a factor in it.

**Comment by chaserene** [comment] 2021-07-01 19:33
this is still an issue and I consider myself lucky I stumbled upon this issue to find the work-around.

@cketti, it's quite easy to reproduce: copy a mail address and paste it into a to/cc/bcc field that already has recipients. the text will be interpreted as a mail address only if you type a comma (,) after it, focusing on another field won't help. this is something many people won't figure out on their own.

to get an unambiguous UX that's understood by everyone, all of these should trigger a parsing: line break, space, comma, focusing away from the input field.

**Comment by cketti** [comment] 2022-05-01 16:13
I created a new issue for this: #6050

**Closed by cketti** 2022-05-01 16:13 UTC
Labels: status: needs information

**Comment by NotepadPlusUser** [comment] 2023-10-26 06:53
This bug is not quite fixed, unfortunately.  I have a Note10+. 

I use the Texpand app to create 4-character codes to type things that I often use, such as my wife's email address.  (I originally write the codes in AutoHotkey for Windows, then imported them into Texpand.)

* In the Bcc: field  I type any email address.
* Then I type a comma, or semicolon, or space, or comma+space, or semicolon+space (I have tried them all).
* Then I type the code for my wife's email address.
* RESULT:  The dreaded red bang, with the note 'Error parsing address!'

I can also report:
* No such problem in the To: field
* No such problem if I begin to type her address, then select it from the dropdown list.

I use my Texpand codes all the time.  Can this bug also be fixed?
