### ISSUE TITLE
IMAP search with non-ASCII characters returns Remote Search Failed 

### ISSUE THREAD

**Issue by iii00** [thunderbird/thunderbird-android#1140] opened 2016-03-04 08:12 UTC
### Expected behaviour

Tell us what should happen
Search in Russian on IMAP server returns Remote Search Failed 
in English works fine (but should press twice to invoke it, would be better to have one click all mail search option, including old and unsynced) 
### Actual behaviour

Tell us what happens instead
server returns Remote Search Failed 
### Steps to reproduce
1. search in Russian 
   2.
   3.
### Environment

K-9 Mail version:
5.008
Android version:6.0

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by cketti** [comment] 2016-03-04 08:29
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by iii00** [comment] 2016-03-06 12:41
http://paste.debian.net/412392

**Comment by philipwhiuk** [comment] 2016-03-14 07:42
```
Could not complete remote search
03-06 14:36:20.676 E/k9      (6912): com.fsck.k9.mail.store.ImapStore$ImapException: Command: UID SEARCH OR SUBJECT "абвгд" FROM "абвгд"; response: #6# [BAD, Could not parse command]
```

I assume we are not encoding data we should be? Relevant RFC: https://tools.ietf.org/html/rfc3501#section-5.1.3

**Comment by janblau** [comment] 2016-03-29 12:58
On my phone, in k9 mail 5.107, android 4.0.4, IMAP search in French (google account) returns "Remote Search Failed". It works fine with 3 other accounts (not gmail)

**Comment by gloomy-ghost** [comment] 2017-06-25 11:30
#2507 might be a duplicate of this issue

**Comment by cketti** [comment] 2020-10-06 21:58
Duplicate of #3607

**Closed by cketti** 2020-10-06 21:58 UTC

**Comment by floridop** [comment] 2022-05-29 03:23
Hi

I believe this is happening again on Nordic symbols (åäöæø)

This is against a Microsoft exchange server.

I can send the full log but I think the info below is sufficient. The same search with keyword "ake" is successful (but it doesn't find the Nordic string)

```
05-29 05:07:14.552 14150 14311 D RealImapFolder: Got untagged EXISTS with value 13980 for b4456300-254a-49f9-80d8-e2b3cf475297:INBOX/pool-4-thread-1/conn199535455
05-29 05:07:14.552 14150 14311 D RealImapFolder: Got UidNext = 32717 for b4456300-254a-49f9-80d8-e2b3cf475297:INBOX/pool-4-thread-1/conn199535455
05-29 05:07:14.554 14150 14311 V RealImapConnection: conn199535455>>> 6 UID SEARCH OR SUBJECT "åke" FROM "åke"
05-29 05:07:14.582 14150 14311 V ImapResponseParser: conn199535455<<<#6# [BAD, Command Error. 11]
05-29 05:07:14.583 14150 14311 E MessagingController: Could not complete remote search
05-29 05:07:14.583 14150 14311 E MessagingController: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH OR SUBJECT "åke" FROM "åke"; response: #6# [BAD, Command Error. 11]
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:118)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:783)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:769)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:84)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.search(RealImapFolder.kt:1183)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.backend.imap.CommandSearch.search(CommandSearch.kt:17)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.search(ImapBackend.kt:133)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:455)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.lambda$searchRemoteMessages$1(MessagingController.java:426)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$e5ykqKer4DpbXPKcKmKlTRWQWlo(Unknown Source:0)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda28.run(Unknown Source:14)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-29 05:07:14.583 14150 14311 E MessagingController: 	at java.lang.Thread.run(Thread.java:923)
05-29 05:07:14.584 14150 14311 E MessagingController: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH OR SUBJECT "åke" FROM "åke"; response: #6# [BAD, Command Error. 11]
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:118)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:783)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.java:769)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:84)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.mail.store.imap.RealImapFolder.search(RealImapFolder.kt:1183)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.backend.imap.CommandSearch.search(CommandSearch.kt:17)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.backend.imap.ImapBackend.search(ImapBackend.kt:133)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:455)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.lambda$searchRemoteMessages$1(MessagingController.java:426)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController.$r8$lambda$e5ykqKer4DpbXPKcKmKlTRWQWlo(Unknown Source:0)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda28.run(Unknown Source:14)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-29 05:07:14.584 14150 14311 E MessagingController: 	at java.lang.Thread.run(Thread.java:923)
05-29 05:07:14.585 14150 14150 D CompatibilityChangeReporter: Compat change id reported: 147798919; UID 10149; state: ENABLED
```

Thanks for the awesome app!

**Comment by AlexK744** [comment] 2023-11-22 11:05
This problem with searching on the server in Russian has not been resolved. On client 6.603 exactly the same behavior
![photo_2023-11-22_13-49-34](https://github.com/thunderbird/thunderbird-android/assets/150684909/45c2f305-a637-496a-bdb7-3970ab2df449)
![photo_2023-11-22_13-49-41](https://github.com/thunderbird/thunderbird-android/assets/150684909/18d7e029-1636-4e79-b7c3-6f6e4419ee80)
