### ISSUE TITLE
STARTTLS with loopback IP in HELO

### ISSUE THREAD

**Issue by CharlesDelorme** [thunderbird/thunderbird-android#7417] opened 2023-12-06 11:18 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

Google Play

### Android version

13 (fix 23031005)

### Device model

Asus Zenfone 8 

### Steps to reproduce

- have your outgoing server configured with STARTTLS (port 587) using login/pass
- send a mail :-)

### Expected behavior

The SSL connection is established with a client HELO which is "EHLO <hostname>"
<hostname> should be the most accurate possible based on the actual device. It can be the host IP, domain name, FQDN

### Actual behavior

The SSL connection is established with a client HELO which is "EHLO [127.0.0.1]"

Some server refuse to relay with a loopback IP in client HELO (this might referrer to them self thus being some kind of attack)

We encounter the problem on a new secured sendmail/mimedefang configuration. We were able to lower the server security to get around but this might happen for others.

Thank you.

### Logs

This is the extract from the log where the starttls is done. 

12-06 12:08:32.146  6608  6679 V SmtpTransport: SMTP <<< 220 **************.fr ESMTP Wed, 6 Dec 2023 12:08:31 +0100
12-06 12:08:32.146  6608  6679 D SmtpTransport: SMTP >>> EHLO [127.0.0.1]
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-**************.fr Hello lfbn-idf1-1-DD-
CC.wBB-AA.abo.wanadoo.fr [AA.BB.CC.DD], pleased to meet you
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-ENHANCEDSTATUSCODES
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-PIPELINING
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-8BITMIME
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-SIZE 100000000
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-STARTTLS
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250-DELIVERBY
12-06 12:08:32.247  6608  6679 V SmtpTransport: SMTP <<< 250 HELP
12-06 12:08:32.247  6608  6679 D SmtpTransport: SMTP >>> STARTTLS
12-06 12:08:32.264  6608  6679 V SmtpTransport: SMTP <<< 220 2.0.0 Ready to start TLS
12-06 12:08:32.264  6608  6679 D SmtpTransport: SMTP >>> EHLO [127.0.0.1]

I made the K9 capture after lowering server security thus there is no error from the server after that

**Comment by cketti** [comment] 2023-12-06 12:19
See https://github.com/thunderbird/thunderbird-android/issues/4428#issuecomment-571244050

**Comment by mutaunt** [comment] 2023-12-29 04:09
See https://github.com/thunderbird/thunderbird-android/issues/6327#issuecomment-1858969489

**Comment by cketti** [comment] 2024-01-03 15:41
Duplicate of #6327

**Closed by cketti** 2024-01-03 15:41 UTC
