### ISSUE TITLE
Drafts deleted when syncronizing with IMAP server

### ISSUE THREAD

**Issue by JustAnonymous** [thunderbird/thunderbird-android#2164] opened 2017-02-01 07:41 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When "Save as Draft" is selected, draft should be remain saved either locally or on the server for future access. 

### Actual behavior
Either draft is automatically completely deleted and no longer available upon server sync, or the draft remains in the "drafts" folder but when opening the compose window, the text is no longer available. It seems this is dependent on the encryption setting; everytime I re-open the draft I have to re-select "Don't encrypt" because the default is always "encrypt if possible".  The last selection should be remembered. If "encypt if possible" or "encrypt" is selected, the draft is deleted upon sync.  If not, I can often no longer access the draft text. This happens regardless of account, and only started after upgrading to the latest K9 version and adding my keys to OpenKeychain (I was using a much older version of K9 prior to this, not sure which).

### Steps to reproduce
1. Create a draft email with text in the body.
2. Select "don't encrypt"
3. Save draft by selecting either "save draft" or by pressing back and "save draft".
4. Text is gone after server sync.

OR

1. Create a draft email with text in the body.
2. Select "encrypt" or "encrypt if possible".
3. Save draft by selecting either "save draft" or by pressing back and "save draft".
4. Draft is gone after server sync. 

### Environment
K-9 Mail version: 5.203

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by lbort** [comment] 2017-02-28 08:37
I second this. It is really annoying, since writing an email on my phone, and continue writing on my PC does not work anymore. 

**Another way to reproduce:** 

1. Start writing Email, without recipient or encryption setting
2. Leave app by switching to another, triggering a "save as draft"
3. Draft is saved in local draft-folder, but disappears if draftfolder is synced.

 as far as I remember, it used to work recently, i.e. with version 5.202.

I also have errors in the K9mail-errors folder, which seam to be related. See Attached: 
```
K9-Mail version: 5.205
Device make: FP1
Device model: FP1U
Android version: 4.2.2

javax.net.ssl.SSLException: Read error: ssl=0x5deda610: I/O error during system call, Connection timed out
 at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
 at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:662)
 at java.io.InputStream.read(InputStream.java:163)
 at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:200)
 at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:154)
 at java.io.InputStream.read(InputStream.java:163)
 at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
 at java.io.BufferedInputStream.read(BufferedInputStream.java:227)
 at com.fsck.k9.mail.filter.PeekableInputStream.peek(PeekableInputStream.java:36)
 at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:38)
 at com.fsck.k9.mail.store.imap.ImapResponseParser.readResponse(ImapResponseParser.java:30)
 at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:88)
 at com.fsck.k9.mail.store.imap.ImapConnection.readStatusResponse(ImapConnection.java:643)
 at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.sendIdle(ImapFolderPusher.java:310)
 at com.fsck.k9.mail.store.imap.ImapFolderPusher$PushRunnable.run(ImapFolderPusher.java:188)
 at java.lang.Thread.run(Thread.java:838)

```

**Comment by tuliogit** [comment] 2017-03-02 11:45
This seems to be identical to #954 and it affects me too. I have version 5.203

**Comment by lbort** [comment] 2017-03-06 14:18
> This seems to be identical to #954 

It is not entirely identical, this issue here is worse, since right now, it is basically impossible to save drafts using k9mail alone. It is saved locally, but gets deleted as soon as the folder is synched, which means **all** drafts die after 1h in my case. 

Since there is not so much activity in this issue: Is it only me that is completely unable to save any draft permanently? Because if so, please help me getting at least saving drafts locally back to working. If needed, I can test whatever is needed, provide logfiles etc.

**Comment by JustAnonymous** [comment] 2017-03-06 19:47
Ibort, it's definitely not just you, I cannot save any drafts anymore in version 5.203 either. And as significant a bug and as frustrating as it is, I'm also a bit surprised that no one has been working on it.

**Comment by philipwhiuk** [comment] 2017-03-06 20:05
A log file of you creating a draft, saving it and then refreshing your email (to force a sync) would be useful.

**Comment by dwrz** [comment] 2017-03-12 18:00
I can also confirm having this issue.

**Comment by mdkuser** [comment] 2017-03-23 09:17
This bug is still present in current stable release v5.206!
Any chance it will be fixed soon?

**Comment by lbort** [comment] 2017-04-25 22:43
Hi again,
do I understand it correctly that there are basically two conflicting fixes for this, and someone (cketti, since you are assigned to the PRs?) should decide which one to use? If this is the case, I would highly appreciate if this could find its way into a release soon. Also many thanks to Mvishnu9 for actually writing the code!

**Comment by Heineken** [comment] 2017-04-26 11:41
Problem persists for me in v5.207. It happens only for the one account, which has encryption enabled (OpenKeyChain). No matter if the drafted is encrypted or not. Disabling encryption (by unselecting OpenKeyChain) seems to fix the problem.

**Comment by hughbragg** [comment] 2017-08-28 19:08
I had this too.
I can confirm that setting cryptography to none instead of OpenKeyChain works

**Comment by axelsimon** [comment] 2017-10-08 19:00
Just got bit by this.
Almost the same as @KodeToad's situation: I have OpenKeychain set up as cryptography provider, but without a key configured.

k-9 version: 5.208 from Fdroid.

**Comment by fsantiago07044** [comment] 2017-11-04 16:55
This is happening for me too on current rev.

**Comment by hailfinger** [comment] 2017-11-10 12:18
This might be related to #2526.

**Comment by hailfinger** [comment] 2017-11-10 12:26
I'm seeing this as well. Drafts created in K9 version 5.208 (from F-Droid) are saved to the local Drafts folder, but not synchronized via IMAP. Once I synchronize manually, the locally created drafts are deleted. I'm using OpenKeychain, but have no private key configured (OpenKeychain is just there to verify signatures).

Copying a draft to another folder fails with an error message: "Nachrichten, die nicht mit dem Server synchronisiert wurden, können nicht kopiert oder verschoben werden." (move_copy_cannot_copy_unsynced_message)

Once I disable OpenKeychain, saving Drafts to the IMAP server works again.

AFAICS this behaviour is desirable because it prevents accidentally spilling the contents of to-be-encrypted emails in plaintext on the IMAP server. However, for people who only use OpenKeychain for signature verification, giving them the option to save drafts in plain would be appreciated. At the very least, there should be some sort of error message when only saving locally due to missing keys.

**Comment by Avispa** [comment] 2017-11-17 16:30
Same issue here and very annoying: Save draft and after sync they just get deleted from the local cash. In contrast to **hailfinger** I wanna point out that I did not (consciously) set up *OpenKeychain* nor any other security aside of SSL during transmission.[1]

[1] Quick check of the options: the only related setting I could find is *Account settings -> Cryptography = No OpenPGP app installed*

**Comment by deviantollam** [comment] 2017-11-21 07:02
Just stopping by to say that this bug has been burning me HARD ALL YEAR.

How is so utterly fundamental an issue not fixed yet?  Being able to save an email draft is a core functionality of any email client. And it seems as though we are seeing multiple potential solutions... they're just not merged yet?  Can anyone confirm if the work?

**Comment by JustAnonymous** [comment] 2017-11-21 07:13
Agreed. It's been 10 months since I reported this and it seems to be a fundamental issue that is affecting many users. Through multiple versions now I've been afraid to start an email to anyone I know I won't finish immediately for fear that it'll just disappear.  That's a serious issue for users of an otherwise excellent email app, and this has gone on through multiple updates. I get the motivation behind preventing users from accidentally saving sensitive information in unencrypted email drafts, but users should at least have the option whether they want this turned on or not.  Unfortunately there seems to be no communication from anyone who works on updates for K9 regarding this either. Someone obviously implemented this functionality. It would be great if the person/people behind it could pitch in and at least explain their reasoning, and address the issue.

**Comment by Ociramma** [comment] 2017-12-01 20:38
Same, annoying as hell. Typed few hours an email, saves as draft, tried to sync and after few minutes I was ready finish typing but my whole draft dissappeared.

**Comment by deviantollam** [comment] 2017-12-04 09:49
The solution I've hit upon currently (which is totally hacky and stupid so I don't consider it a proper fix) is to create an additional IMAP account.  Use all the exact same details as your main, working email account but for this additional one, do not enable PGP at all.

So whenever I have to compose a message i pull the drop-down "TO:" field and select this alternate account.  Saved drafts work fine and don't ghost on me unexpectedly.

**Comment by alooshu** [comment] 2018-01-03 22:17
I have just posted https://github.com/k9mail/k-9/issues/3031, which is practically identical - it still happens - but I'll keep it there for the while, since my case clearly does **not** involve encryption.

IMO the correct approach would be enforcing that things happen in a certain order when syncing the Drafts folder, namely first isolating all messages in the local Drafts folder which have been written/edited **more recently** than this local folder has been synced last, and making sure these do successfully transfer to the server **before** the server side state of the Drafts folder is getting synced down to the client.

This would still not perfectly catch all possible scenarios, e.g. multiple offline edits from different clients on the same message draft, but it would draw a clear line between **intentional deletions** by the user and **accidental deletions** because a draft hasn't had the time to get synced to the server first.

I can confirm the annoyance factor is extreme, and since arguably, the ability to work offline, reliably, is the main reason for using a client to begin with, rather than a web interface, I'd suggest  giving the bug, under its various appearances and descriptions, a serious priority indeed.

**Closed** 2018-02-17 01:42 UTC

**Comment by planeth44** [comment] 2018-08-31 15:54
This is not Fixed!!!!!

I just lost hours of work.

This is extremely annoying. Especially when you are surprised with this after going back online.

Please at least, have a warning message if the bug is not easily fixed

Thanks
