### ISSUE TITLE
App crashes on replying

### ISSUE THREAD

**Issue by ferrum** [thunderbird/thunderbird-android#7640] opened 2024-02-14 15:48 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

Android 13

### Device model

Xiaomi Redmi Note 11S

### Steps to reproduce

1. Open an e-mail
2. Try to reply by clicking on the reply button
3. Crash

### Expected behavior

The app should not crash

### Actual behavior

The app does crash upon the click on the reply button

### Logs

I am not able to export logs. The app does not allow to export logs if you use a third-party file system explorer.

**Comment by cketti** [comment] 2024-02-14 16:04
This is probably a duplicate of #7622.

> I am not able to export logs. The app does not allow to export logs if you use a third-party file system explorer.

K-9 Mail is using [standard Android SDK functionality](https://developer.android.com/reference/android/content/Intent#ACTION_CREATE_DOCUMENT) to let the user pick a file to save the debug log. If a "third-party file system explorer" breaks this functionality, it should be considered a bug in that app.

**Comment by hurzl** [comment] 2024-02-15 06:42
same here:
```
02-15 07:39:46.489  3768  5237 E AndroidRuntime: Caused by: java.lang.NullPointerException: ResultSet returned null for UserPackets.sq:selectUserIdStatusByEmailLike
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.os.Parcel.createExceptionOrNull(Parcel.java:3017)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2995)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2978)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1219)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1151)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at android.content.ContentResolver.query(ContentResolver.java:1107)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromCryptoProvider(RecipientLoader.java:232)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:202)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
02-15 07:39:46.489  3768  5237 E AndroidRuntime: 	... 3 more
02-15 07:39:46.493  6378  5330 I DropBoxManagerService: add tag=data_app_crash isTagEnabled=true flags=0x2
02-15 07:39:46.494  6378 12053 W ActivityTaskManager:   Force finishing activity com.fsck.k9/.activity.MessageCompose

```

**Comment by xfarrow** [comment] 2024-02-15 07:45
@cketti Thank you, deleting OpenKeychain resolved the problem. Issue closed 👍

**Closed by xfarrow** 2024-02-15 07:45 UTC
