### ISSUE TITLE
Wrong image showing in e-mail body

### ISSUE THREAD

**Issue by gplante** [thunderbird/thunderbird-android#1063] opened 2016-02-02 13:56 UTC
When I look at an e-mail, the image (company logo of the recipient) at the bottom of the body is the wrong one. The image displayed belongs to a completely different e-mail from a completely different sender.

It sounds to me that maybe the image in both e-mails have the same name and for an unknown reason, K9 do not show the correct one.

I'm using K9 version 5.007 on Android version 5.1

**Comment by cketti** [comment] 2016-02-07 14:34
Can you attach a screenshot?

**Comment by gplante** [comment] 2016-02-07 15:52
Hi,

The e-mail is a business related e-mail so I cannot send you a screenshot
(not the complete e-mail) but what I did is that I opened the e-mail with
notepad then remomed sensitive information and I left other e-mail
structure information so that you can look at the e-mail structure and
attachment. So, you will find the epured source e-mail in attachment and
you will see that I replaced sensitive information lines(s) with the string
*xxx-deleted-line(s)-here-xxx*.

For your information, last week, I moved this e-mail in a folder so today,
after I received your e-mail request, I went back to that folder to see the
e-mail again and the proper logo is correctly displayed today. This is
strange. But be sure that last week, it was the wrong logo. Since last
week, I had an Android update. I do not know if it can be related.

Best regards,

Guylain Plante
gplante2@gmail.com


2016-02-07 9:35 GMT-05:00 cketti <notifications@github.com>:

> Can you attach a screenshot?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/k9mail/k-9/issues/1063#issuecomment-181022845>.
>

xxx-deleted-line(s)-here-xxx
Content-Type: multipart/related;
	boundary="_005_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_";
	type="multipart/alternative"
MIME-Version: 1.0
xxx-deleted-line(s)-here-xxx
--_005_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_
Content-Type: multipart/alternative;
	boundary="_000_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_"

--_000_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

Hi,

xxx-deleted-line(s)-here-xxx



--_000_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_
Content-Type: text/html; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable

<html xmlns:v=3D"urn:schemas-microsoft-com:vml" xmlns:o=3D"urn:schemas-micr=
osoft-com:office:office" xmlns:w=3D"urn:schemas-microsoft-com:office:word" =
xmlns:m=3D"http://schemas.microsoft.com/office/2004/12/omml" xmlns=3D"http:=
//www.w3.org/TR/REC-html40">
<head>
<meta http-equiv=3D"Content-Type" content=3D"text/html; charset=3Dus-ascii"=
>
<meta name=3D"Generator" content=3D"Microsoft Word 15 (filtered medium)">
<style></style>
</head>
<body lang=3D"EN-AU" link=3D"blue" vlink=3D"purple">
<div class=3D"WordSection1">
xxx-deleted-line(s)-here-xxx
</div>
</body>
</html>

--_000_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_--

--_005_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_
Content-Type: image/png; name="image001.png"
Content-Description: image001.png
Content-Disposition: inline; filename="image001.png"; size=20954;
	creation-date="Tue, 02 Feb 2016 03:40:08 GMT";
	modification-date="Tue, 02 Feb 2016 03:40:08 GMT"
Content-ID: <image001.png@01D15DC7.9B468460>
Content-Transfer-Encoding: base64

iVBORw0KGgoAAAANSUhEUgAAAKMAAABQCAYAAAB1asU3AAAAAXNSR0IArs4c6QAAAAlwSFlzAAAO
xAAADsQBlSsOGwAAABl0RVh0U29mdHdhcmUATWljcm9zb2Z0IE9mZmljZX/tNXEAAFFaSURBVHhe
7b33c1xXlud5gMyE9wAJEARBgt6TohFFiqK8a0lVqqrurpmu7o2N2Yndjdjd3/aX/UPmp5ndiZnZ
xxx-deleted-line(s)-here-xxx
B3Zl+Qko4BIDLnnBxWxWboOjR6Dp7WUMzyx+c8i7wBtDMW2jHYZrSqHvoWr21CiiikMKKKKACiii
gAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooA//9k=

--_005_ME1PR01MB0020802D6817933E87F0610AE0DF0ME1PR01MB0020ausp_--

**Comment by snedkerdk** [comment] 2016-10-01 06:26
The exact same thing happended to me this week. The logo in a signature file was replaced by a signature logo from a completete different mail thread. I am using Android 6.01. and K9 5.010.

**Comment by cketti** [comment] 2017-11-02 05:42
Duplicate of #2699

**Closed by cketti** 2017-11-02 05:42 UTC
Labels: status: needs information

**Comment by danieltakesphotos** [comment] 2018-09-25 10:29
Just to confirm that this bug still exists: K-9 Mail 5.600 , Android 7.0, Samsung S6, using IMAP
I often send photos from my laptop to the phone by email. Sometimes it shows the attachments thumbnail of an older message, but when I tap open or save the image, the correct image is opened or saved

**Comment by cketti** [comment] 2018-09-26 12:21
@danieltakesphotos Please create a new issue. This one was about inline images, not thumbnails of image attachments.
