### ISSUE TITLE
German translation - Wrong reflexive pronoun

### ISSUE THREAD

**Issue by AS98765** [thunderbird/thunderbird-android#8169] opened 2024-09-25 12:17 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

None

### Android version

GrapheneOS

### Steps to reproduce

Imo not necessary.

### Expected behavior

"mir"

### Actual behavior

"mich"

![Screenshot 2024-09-25 140349 - ss](https://github.com/user-attachments/assets/a37db27b-0ef7-46e9-8628-3a0edbf859bf)

**Comment by cketti** [comment] 2024-09-25 12:19
Duplicate of #7917

**Closed by cketti** 2024-09-25 12:19 UTC
