### ISSUE TITLE
Attached xlsx file cannot be opened by Excel

### ISSUE THREAD

**Issue by stephanewierzbicki** [thunderbird/thunderbird-android#1721] opened 2016-10-17 08:56 UTC
### Expected behavior

Attached xlsx file should be opened by Excel
### Actual behavior

Excel refuse to open the file and tells the user that the file is invalid.
### Workaround

Either use another email client (GMail for example) or save the file on the device storage and open it later with Excel
### Steps to reproduce
1. Open the mail
2. Display attached file
3. Download complete message
4. Open the attached xlsx file
### Environment

K-9 Mail version: 5.010

Android version:
Android 6.01
Samsung S6+ Edge / Sony Z3

Account type (IMAP, POP3, WebDAV/Exchange):
IMAP (Kerio Connect server)

**Comment by philipwhiuk** [comment] 2016-10-18 02:00
Is this reproducible with different XSLX files or is it only a specific file. I don't have Excel right now so I can't test it. It seems very odd that it would only occur with a specific file extension.

**Comment by philipwhiuk** [comment] 2016-11-03 21:39
Probably fixed by #1769 ?

**Comment by Valodim** [comment] 2016-11-06 21:47
Nope actually, since this was reported for version 5.010

**Comment by ar-** [comment] 2016-11-07 15:01
I tested this and it works for me. Since the file could be opened after download with another client: could this be a wrongly declared mime-type?

@stephanewierzbicki Can you reproduce this with other XLSX files? And can you attach a minimal example of a not-working file? What client was used to send the file? Are you able to post the mime-type from the source code of the not-working email?

Mine was sent as
`Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;`

**Comment by ar-** [comment] 2016-11-18 14:56
I have the same issue and can reproduce this with many file types including PDF. The affected PDF is attached (it is a public random pick) and the email source is also attached.

I am using the current alpha release. File comes via IMAP.

I can specify the problem as follows: Opening the attachment in K9 fails (invalid PDF file, with every receiving app). Saving it with K9 and then clicking on the download notification and opening it, also fails with the same error. BUT:

Opening the same file with ES file explorer from the download folder succeeds.

I further verified, that the file is not broken. Therefore I downloaded the from the same IMAP source with thunderbird. Then compared both of them with checksums. They are the same.

So the file attachment is healthy but the sharing with another intent, seems to indicate a wrong mimetype or anything else like that.

[failingpdfatttachment.zip](https://github.com/k9mail/k-9/files/600183/failingpdfatttachment.zip)

**Comment by Valodim** [comment] 2016-11-18 17:01
New alpha out today, please check if the issue persists. Also, what pdf reader do you use? Adobe worked fine for me

**Comment by ar-** [comment] 2016-11-19 05:17
Problem fixed in latest alpha release. Thanks.

Of course it would be good to know, what the problem was (eg. which commit actually fixed it).

I used many different readers including adobe and the one from google drive. All with the same result.

**Comment by philipwhiuk** [comment] 2016-11-19 09:22
It was fixed in #1769

**Comment by stephanewierzbicki** [comment] 2017-01-05 07:55
Problems occurs again.

Now I can't open any office documents : word or excel application are telling me that "file cannot be opened".

I don't have this issue if I use the bundled email client (in my case Samsung mail reader).

**Comment by sabas** [comment] 2017-03-28 09:38
Still applies in the last published version from Play Store.

**Comment by tomgozdek** [comment] 2017-06-06 09:48
The issue always occurs when attachment is identified as application/octet-stream mime type and as result file cannot be determined using Uri for example, having:

`content://com.fsck.k9.tempfileprovider/temp/3ac760f5a0812097540d90237f3dffb9b715f2d2?mime_type=application%2Foctet-stream`

it is impossible to get file name using OpenableColumns.

Are there any plans to solve this bug ?

**Comment by philipwhiuk** [comment] 2017-06-10 14:37
Thanks for looking into why this happens @tomgozdek.

If we were/are losing the MIME type which is provided in the attachment then that would be a bug obviously. 

Given we have the file extension we could **guess** what the mime-type should be and set it properly.

Making K-9 try to do best-effort file-extension/MIME-type decoding itself is somewhat annoying.

**Closed** 2019-02-28 21:13 UTC
