### ISSUE TITLE
Cannot cut/copy recipeients from Reply window

### ISSUE THREAD

**Issue by dabear2** [thunderbird/thunderbird-android#1991] opened 2017-01-06 01:50 UTC
### Expected behavior
When replying to a message that was received, I long press a the "TO" name and it should bring up cut/copy/select menu for the address.  Then I can Cut the address from the TO and paste it into the BCC or CC fields.  This is how it used to be on 5.1

### Actual behavior
Long pressing on the TO in the Reply window does nothing like it used to.  It first brings up the "user name and email address is a big faded (dark theme) box.  Then you have to tap on the TO line somewhere other than on an email address to finally get the Cut/copy/paste menu.  - bug 1.

Then after a Cut or Copy, I expand the menu and try to Paste it into the BCC field.  The only thing that gets pasted is two commas  { ,,  }  without the brackets

### Steps to reproduce
1.   Read an email that is in your inbox and tap Reply
2.    Long press on a TO address (notice no copy/cut menu - bug 1) then tap anywhere in a blank area of the TO and do a Cut.
3.    Select the BCC menu with a long press and paste (bug 2)

### Environment
K-9 Mail version:5.202

Android version:6.0

Account type (IMAP, POP3, WebDAV/Exchange):IMAP

**Comment by philipwhiuk** [comment] 2017-01-10 02:18
The long press functionality was removed from message composition. Long press is fairly ugly from a UX perspective. It's not very intuitive - you have to 'know it's there' or discover it by accident. 

For example, while reading right now:

* You can long-press on the 'To:' address of a message you are reading, to copy it (and the fluff that actually surrounds it underneath). If there's more than one you have to copy them all.
* For the From address tapping on it suggests you add them as a contact. There's no long tap.

The only way you know this is by trial and error or documentation. It's inconsistent, unhelpful and confusing.

If you tap on the letter badge for a contact, you get the contact in a Contacts pop-up. You can copy any of the Contact's information from there, including the email address.

We should probably make it so that you can copy the email out of that drop down.

You can still paste addresses directly into the BCC field.

One other possible improvement might be to allow drag and drop of the completed tokens.

I don't think re-adding long press is good design. If moving from To to CC/BCC is important I think it would be better to look at drag and drop mechanics to move them about

**Comment by dllud** [comment] 2017-01-10 17:48
I have just had a really hard time while trying to move recipients from To to Cc. As happened with @dabear2 pasting just produced some commas. I was forced to type in all the emails from scratch.

With these new tokens I was expecting drag and drop functionality. That was the first thing I tried, thus drag and drop seems the right way to go.

**Comment by DAveShillito** [comment] 2017-10-19 12:25
I was just about to report the same issue.

I had two recipients in the To and wanted to move one of these to the CC.

I tried selecting one of them and they both highlighted in blue, I eventually managed to get just one highlighted and selected copy, then paste into the CC, but I just got four commas ",, ,,".

I tried a long press hoping there would be a pop-up, but got none.

I somehow managed to get the entire panel for a contact to be selected and it followed my finger (I don't know how, I may have had just the one panel highlighted in blue then I held it down for a second, but tbh it was hard to reproduce).  This lead me to believe I could drag and drop, but this time the drop produced two commas ",," leaving the original panel in place.

However if I had both tokens highlighted and I managed to get them to follow my finger, and I dropped them on top of themselves (in the To) they would overwrite the panels and leave four commas.

Since I do not want or need the recipient in my contacts and there seems to be no way of copying the address from the pop up that sometimes appears, the only solution appears to save the mail as a draft and send it from home when I get back to Thunderbird.

It would be very handy if recipients in To, CC & BCC could be moved between fields.

**Comment by richardleger** [comment] 2018-01-05 09:23
Happy new year to K9 dev team! Thanks for great work done on this App.

Have there been any progress on fixing copy/paste (and mive) of recipients in compose window?

Currently using K9 5.402 on Android and in a Imap/Smpt account set in K9, it is still not possible to properly move or copy paste recipients in compose window from To to Bcc for example. When pasting only two commas appear ",,". Any way this behaviour can be fixed in next update of K9, asap?

Being able to rearange recipients in compose window or copy/paste recipient details seemed to be an essential feature of an email client. It was possible previously but since recipient details are converted into tyle objects few months back, it is no longer possible. I was hopping further updates would fix it but that has not been the case yet.

Can the copy/paste issue be set as an urgent bug to fix and have it fixed?

That would be much appreciated by your user base ;-)
Thank you for consideration.
Happy new year to K9 dev team! Thanks for great work done on this App.

Have there been any progress on fixing copy/paste (and mive) of recipients in compose window?

Currently using K9 5.402 on Android and in a Imap/Smpt account set in K9, it is still not possible to properly move or copy paste recipients in compose window from To to Bcc for example. When pasting only two commas appear ",,". Any way this behaviour can be fixed in next update of K9, asap?

Being able to rearange recipients in compose window or copy/paste recipient details seemed to be an essential feature of an email client. It was possible previously but since recipient details are converted into tyle objects few months back, it is no longer possible. I was hopping further updates would fix it but that has not been the case yet.

Can the copy/paste issue be set as an urgent bug to fix and have it fixed?

That would be much appreciated by your user base ;-)
Thank you for consideration.

**Comment by cketti** [comment] 2019-02-28 21:49
Duplicate of #1602

**Closed by cketti** 2019-02-28 21:49 UTC
