### ISSUE TITLE
Have to delete emails twice (IMAP)

### ISSUE THREAD

**Issue by singpolyma** [thunderbird/thunderbird-android#1437] opened 2016-06-05 12:14 UTC
### Expected behaviour

Tell us what should happen

When I delete an email I do not expect to see it again later.
### Actual behaviour

Tell us what happens instead

I do see the email again next time I check email. Second delete works, though.
### Environment

K-9 Mail version: 5.010

Android version: 5.1.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP (dovecot, self-hosted, other clients work)

**Comment by philipwhiuk** [comment] 2016-06-06 08:54
I'm wondering whether this is related to IMAP's delete-purge interaction. Not sure without device logs.

**Comment by cketti** [comment] 2016-06-28 02:54
Please provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by jasom** [comment] 2016-09-08 20:13
I have seen similar behavior that is possibly the same bug.  If I delete an e-mail on the server, push notification does not pick up on it, but if manually refresh (Or whatever the name is for the arrows in a circle icon), the message disappears on k-9.  I confirmed that dovecot sends an EXPUNGE message out.  I'll record a debug log in k-9 next.

**Comment by jasom** [comment] 2016-09-08 20:23
I see nothing logged for k9 trying the instructions on https://github.com/k9mail/k-9/wiki/LoggingErrors Note I also see nothing logged when I get a new push message either though (and that part works for me).

**Comment by jasom** [comment] 2016-09-08 20:26
Just to make sure I'm dumping the right buffer, the lines I do see are of the form:

    W/IInputConnectionWrapper( 4291 ): getTextAfterCursor on inactive InputConnection

**Comment by jasom** [comment] 2016-09-08 20:29
Nevermind, just saw "The app WON'T work with Android 4.1 and newer." which is probably why I'm not seeing anything.  I don't have a micro-usb cable handy so will have to wait until later.

**Comment by Nergal-di-Cuthah** [comment] 2016-09-08 20:41
Jasom, do you mean k9 won't work on newer? Because it works fine on my 4.4,5.0,5.1 and 6.0

**Comment by jasom** [comment] 2016-09-08 20:50
@Nergal-di-Cuthah I mean aLogcat; I don't have a micro-usb cable handy so was trying to use that to dump the logs.

**Comment by Nergal-di-Cuthah** [comment] 2016-09-08 21:01
Yeah, I realized that when I clicked the logging errors link all the way through, what about using "logcat extreme" or "matlog"

**Comment by jasom** [comment] 2016-09-08 21:04
Log attached, showing EXPUNGE message:

[k9-log2.txt](https://github.com/k9mail/k-9/files/462696/k9-log2.txt)

**Comment by davidhedlund** [comment] 2016-10-22 06:45
[mylabel:bug](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Abug%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by davidhedlund** [comment] 2016-10-22 06:45
[mylabel:important](https://github.com/search?utf8=%E2%9C%93&q=commenter%3Adavidhedlund+%22mylabel%3Aimportant%22+in%3Acomments&type=Issues&ref=searchresults)

**Comment by est42** [comment] 2016-12-15 15:30
I have the same issue, when I remove the message I still can see it in webmail until I press expunge. 
I would expect to message be removed after removing message. It's very annoying.

**Comment by bam80** [comment] 2018-01-05 02:32
https://github.com/k9mail/k-9/issues/1437#issuecomment-245725278
>I have seen similar behavior that is possibly the same bug. If I delete an e-mail on the server, push notification does not pick up on it, but if manually refresh (Or whatever the name is for the arrows in a circle icon), the message disappears on k-9

I have such behavior too.
Is it related to this bug indeed, or we should file a separate issue?

**Comment by cketti** [comment] 2020-10-05 00:43
This should be fixed in recent beta versions (5.7xx).

**Closed by cketti** 2020-10-05 00:43 UTC
