### ISSUE TITLE
NPE/Null object reference crash when attempting to decode certain messages

### ISSUE THREAD

**Issue by vt0r** [thunderbird/thunderbird-android#1201] opened 2016-03-22 15:33 UTC
### Expected behaviour

Email should be decoded and displayed properly
### Actual behaviour

K-9 mail crashes, due to an NPE
### Steps to reproduce
1. (Attached email in .eml format) Download attached message to K-9 mail
2. Attempt to view the message
### Environment

K-9 Mail version: 5.108 (build from current master as of 2016-03-22)

Android version: 6.0.1

Device: Nexus 6P

Account type (IMAP, POP3, WebDAV/Exchange): IMAP
### Crash logs

```
03-22 11:02:07.340 E/k9      (20726): Error while decoding message
03-22 11:02:07.340 E/k9      (20726): java.lang.RuntimeException: Not supported
03-22 11:02:07.340 E/k9      (20726):   at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfo(LocalMessageExtractor.java:529)
03-22 11:02:07.340 E/k9      (20726):   at com.fsck.k9.mailstore.LocalMessageExtractor.extractAttachmentInfos(LocalMessageExtractor.java:502)
03-22 11:02:07.340 E/k9      (20726):   at com.fsck.k9.mailstore.LocalMessageExtractor.decodeMessageForView(LocalMessageExtractor.java:444)
03-22 11:02:07.340 E/k9      (20726):   at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:46)
03-22 11:02:07.340 E/k9      (20726):   at com.fsck.k9.ui.message.DecodeMessageLoader.loadInBackground(DecodeMessageLoader.java:15)
03-22 11:02:07.340 E/k9      (20726):   at android.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:312)
03-22 11:02:07.340 E/k9      (20726):   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:69)
03-22 11:02:07.340 E/k9      (20726):   at android.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:66)
03-22 11:02:07.340 E/k9      (20726):   at android.os.AsyncTask$2.call(AsyncTask.java:295)
03-22 11:02:07.340 E/k9      (20726):   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
03-22 11:02:07.340 E/k9      (20726):   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
03-22 11:02:07.340 E/k9      (20726):   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
03-22 11:02:07.340 E/k9      (20726):   at java.lang.Thread.run(Thread.java:818)
03-22 11:02:07.357 E/AndroidRuntime(20726): FATAL EXCEPTION: main
03-22 11:02:07.357 E/AndroidRuntime(20726): Process: com.fsck.k9, PID: 20726
03-22 11:02:07.357 E/AndroidRuntime(20726): java.lang.NullPointerException: Attempt to read from field 'com.fsck.k9.mail.Message com.fsck.k9.mailstore.MessageViewInfo.message' on a null object reference
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageTopView.setMessage(MessageTopView.java:90)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageViewFragment.showMessage(MessageViewFragment.java:281)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageViewFragment.onDecodeMessageFinished(MessageViewFragment.java:276)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageViewFragment.access$1200(MessageViewFragment.java:57)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:755)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.messageview.MessageViewFragment$DecodeMessageLoaderCallback.onLoadFinished(MessageViewFragment.java:745)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.app.LoaderManagerImpl$LoaderInfo.callOnLoadFinished(LoaderManager.java:483)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.app.LoaderManagerImpl$LoaderInfo.onLoadComplete(LoaderManager.java:451)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.content.Loader.deliverResult(Loader.java:144)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:40)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.fsck.k9.ui.message.DecodeMessageLoader.deliverResult(DecodeMessageLoader.java:15)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.content.AsyncTaskLoader.dispatchOnLoadComplete(AsyncTaskLoader.java:265)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.content.AsyncTaskLoader$LoadTask.onPostExecute(AsyncTaskLoader.java:92)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.os.AsyncTask.finish(AsyncTask.java:651)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.os.AsyncTask.-wrap1(AsyncTask.java)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.os.Handler.dispatchMessage(Handler.java:102)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.os.Looper.loop(Looper.java:148)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at android.app.ActivityThread.main(ActivityThread.java:5422)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at java.lang.reflect.Method.invoke(Native Method)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
03-22 11:02:07.357 E/AndroidRuntime(20726):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

[Your PVWC eBill is Ready - Anonymized.eml.txt](https://github.com/k9mail/k-9/files/184412/Your.PVWC.eBill.is.Ready.-.Anonymized.eml.txt)

**Comment by philipwhiuk** [comment] 2016-03-22 20:47
Renaming the file and then sending it to myself in Thunderbird doesn't work as Thunderbird tells K-9 it is text/plain. It looks like it's the actual opening of the attached message itelf.

What's the MIME type of the attachment when it crashes?

**Comment by vt0r** [comment] 2016-03-22 22:32
Ah whoops. Forgot the attachment. I'll take a look when I get home and provide info, plus the attachment itself.

**Comment by philipwhiuk** [comment] 2016-03-23 09:51
I reproduced a similar crash for an SMIME message.

**Comment by vt0r** [comment] 2016-03-24 02:49
Oddly enough, there's no attachment in Thunderbird or any other email client I tested. It seems only K-9 thinks there's an attachment. The format looks like `text/plain`, but it only says `text` in the message source. I'll see if I can find this message in the DB and dump the contents.

**Comment by philipwhiuk** [comment] 2016-03-24 10:58
Maybe that's the issue - K-9 doesn't understand the format so thinks it's an attachment? I'll trawl the codebase...

**Comment by philipwhiuk** [comment] 2016-04-01 12:53
@vt0r This should mean the message can be displayed and work as normal.

**Comment by philipwhiuk** [comment] 2016-04-11 21:01
@cketti (and I agree with him) didn't like the hack for the invalid MIME type. I agree.

I've also been wondering whether it's the right solution. Maybe we should be displaying stuff with invalid MIME types as attachments. After all, if they break the MIME type, all bets are off about what it really is.

This should be fixed along with (or at least taking into account #1261 ) with a rethink of how we handle badly formed messages.

**Comment by vt0r** [comment] 2016-05-11 04:45
Sorry for the super long delay in response here.

I actually like the way Thunderbird handles these cases, which you can see here:

https://github.com/mozilla/releases-comm-central/blob/644b5a1487f60d73010dee11fcc6631cf7cc897f/mailnews/mime/src/mimei.cpp#L676-701

Would love to hear your thoughts on possible issues, but I wonder why we couldn't just default to `text/plain` where it makes sense and all other options have been exhausted.

**Comment by Valodim** [comment] 2016-07-18 18:17
Fixed in a local branch, will push a PR shortly

**Closed** 2016-08-30 02:26 UTC
