### ISSUE TITLE
Modifying Thunderbird's Interface

### ISSUE THREAD

**Issue by Shura23** [thunderbird/thunderbird-android#8318] opened 2024-10-12 04:25 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0b2

### Problem you are trying to solve

When I wanted to change the settings for Thunderbird, I found that I needed to click on "Show Account" before the settings button would appear. Close the software and reopen it, I need to click "Show Settings" again, which is not very convenient, my suggestion is to move the settings button to the first-level menu interface. It is in the same interface as folders such as inbox, outbox, etc.

### Suggested solution

my suggestion is to move the settings button to the first-level menu interface. It is in the same interface as folders such as inbox, outbox, etc.

**Comment by cketti** [comment] 2024-10-14 18:26
Duplicate of #8235

**Closed by cketti** 2024-10-14 18:26 UTC
Labels: type: enhancement, unconfirmed
