### ISSUE TITLE
Failure to save value of 'Bcc all message to'

### ISSUE THREAD

**Issue by EJB4T** [thunderbird/thunderbird-android#8351] opened 2024-10-17 09:34 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

8.0b3

### Where did you get the app from?

Google Play

### Android version

13

### Device model

Fairphone 4

### Steps to reproduce

1. Go to 'Settings'
2. Click the account under 'Accounts'
3. Click 'Sending mail'
4. Click 'Composition defaults'
5. Put cursor in field 'Bcc all messages to'
6. Type desired e-mail address
7. Click 'SAVE' in the right upper corner

### Expected behavior

The typed in e-mail address is stored in the field 'Bcc all messages to' and is used in any new message on the Bcc field. This works on the desktop version of Android and in K-9.

### Actual behavior

When you go back into 'Composition defaults' the field 'Bcc all messages to' is empty and any new message does not have the typed Bcc address on the Bcc line.

### Logs

![Screenshot_20241017-111940~3](https://github.com/user-attachments/assets/a2855e77-736c-41ca-8124-8a40d5060c18)

**Comment by cketti** [comment] 2024-10-17 09:36
Duplicate of #8347

**Closed by cketti** 2024-10-17 09:36 UTC
