### ISSUE TITLE
The K-9 app for Android does not store sent messages in the Sent folder

### ISSUE THREAD

**Issue by Halfspider** [thunderbird/thunderbird-android#8113] opened 2024-09-05 17:13 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

14

### Device model

honor x7a

### Steps to reproduce

1. Writing an email
2. Sending

### Expected behavior

Each message sent via K-9 should be saved in the Sent folder

### Actual behavior

After you type or unsend a message, the message is not saved in the Sent folder. The email is delivered, but there is no information about sending anywhere.

**Comment by gedakc** [comment] 2024-09-17 16:59
Using k9-6.804.apk from github releases I confirm the problem with sent messages not being stored in the sent folder.

My phone is a Motorola Moto G Fast with Android version 11.

I tested multiple email addresses and have additional information that may help triage the issue.

Email Provider | Message Sent Properly | Message stored in Sent Folder
-------------- | --------------------- |------------------------------
gmail.com      | Yes                   | No
hotmail.com    | Yes                   | Yes, but there are two copies
Yahoo.com      | Yes                   | Yes, one copy as expected
nucleus.com[1] | Yes                   | No

1: nucleus.com is a third party ISP providing IMAP email services.

Hopefully this helps to triage this issue.

Regards,
Curtis Gedak

**Comment by gedakc** [comment] 2024-09-25 17:06
The issue with two copies of a sent message appearing in the sent folder for Hotmail (also Microsoft mail) appears to have been reported as follows:

[Mail sent two times with office 365 #7938 ](https://github.com/thunderbird/thunderbird-android/issues/7938#issuecomment-2169421063)

It appears that Microsoft is using non-standard email behaviour and automatically storing a copy of all sent message in the sent folder.

This minor issue can be worked around for Hotmail by de-selecting the option under _Settings → [Account] → Sending mail → Upload sent messages_.

The issue of sent message not appearing in the sent folder remains for gmail and also third party ISP email providers such as nucleus.com.

**Comment by gedakc** [comment] 2024-09-25 17:30
I finally found the solution! 

It involves manually setting the folder for _sent_ for the email account.

Go to _Settings → [Account] → Folders_, and change _Sent folder_ from **Automatic (None)** to **Sent**.

You might wish to do similar actions for folders like Drafts, Spam, and Trash.

See also:  
- [K9 doesn't copy a new sent mail in the sent folder using IMAP #6779 ](https://github.com/thunderbird/thunderbird-android/issues/6779)
- [“Upload sent messages to sent folder after sending” not working with IMAP](https://forum.k9mail.app/t/upload-sent-messages-to-sent-folder-after-sending-not-working-with-imap/5248)

**Comment by gedakc** [comment] 2024-09-25 17:52
There appears to be an enhancement request to notify the user if a sent folder is not automatically detected when k9 email accounts are set up.  See:

[Issue: Warn if Sent folder not found #6276](https://github.com/thunderbird/thunderbird-android/issues/6276)

**Comment by cketti** [comment] 2024-09-25 19:04
As @gedakc mentioned, the folder that messages are uploaded to after sending can be configured under *Settings → [Account] → Folders → Sent folder*. If *Automatic (None)* or *None* are selected, or the setting *Settings → [Account] → Sending mail → Upload sent messages* is unchecked, sent messages won't be uploaded to the Sent folder by the app.

When adding an account, the app asks the user to configure special folders if the server doesn't provide values for all of them.

![image](https://github.com/user-attachments/assets/05116b0a-acc8-4be9-8b9e-9bbccb44b324)

Closing this issue because this is most likely a configuration problem, not a bug.

**Closed by cketti** 2024-09-25 19:04 UTC
