### ISSUE TITLE
Collapse sub-folders

### ISSUE THREAD

**Issue by Sytten** [thunderbird/thunderbird-android#7375] opened 2023-11-23 21:50 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I use a lot of folders and subfolders. They are displayed quite nicely in thunderbird desktop with each folder being able to be collapsed and expanded as need be in a tree structure. In K9, all the subfolders are always shown like `parent/children`. So example I have:
`banks`
`banks/bank 1`
`banks/bank 2`
This is very annoying and it takes a lot of space.

### Suggested solution

It would be super nice to have the same tree structure as on desktop. Ideally the app remembers which folders are expanded. They should also we indented a bit to the right to really see the tree structure (I don't expect people use that much nesting so it should not be too bad).

**Comment by cketti** [comment] 2024-01-03 15:17
Duplicate of #630

**Closed by cketti** 2024-01-03 15:17 UTC
Labels: enhancement, unconfirmed

**Comment by ecxod** [comment] 2024-03-28 15:49
this is not at all completed.

**Comment by macpac59** [comment] 2025-10-23 05:46
I would also like to know when this feature will be really released. 😕
