### ISSUE TITLE
Share attachments with their original file name

### ISSUE THREAD

**Issue by l-mb** [thunderbird/thunderbird-android#2789] opened 2017-09-24 10:19 UTC
### Expected behavior
When sharing an opened attachment file to, say, Google Drive, I would want it under the name of the attachment, such as Contract.pdf

Alternatively, a direct "Share to" button in the browser might work.

### Actual behavior
The file name seems to be a random uuid generated by k9 when saving the attachment locally so it can be opened. When sharing the file then, the original babe is completely lost.

### Steps to reproduce
1. Open an attachment
2. Select share to, say, Google Drive
3. Notice that the file name there is a random uuid

### Environment
K-9 Mail version: 5.208

Android version: Oreo

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Djfe** [comment] 2018-02-01 15:29
This is still happening.
A sharebutton in addition to an open would be nice, since you can't save all file types like this to google drive directly. (some are opened in one app, without my OS offering anything else; like .pkpass with OSMand)

I just noticed (only by looking at the code), that K9 supports sending files to filemanagers, if you long press the save button.
So maybe it could be done that way (though it's unusual for a button to have a long press option :/)

**Comment by Djfe** [comment] 2018-02-01 16:31
I'm wondering whether this is a bug or whether it's done for privacy reasons:
calling
```
String tempFilename = getTempFilenameForUri(uri);
```
creates a kind of random filename based on the Uri of the original file
https://github.com/k9mail/k-9/blob/ad5897125a1a402fe13036d1b5505c1a177f43d5/k9mail/src/main/java/com/fsck/k9/provider/AttachmentTempFileProvider.java#L62

but you're still kind of trying to add the name of the attachment here:
https://github.com/k9mail/k-9/blob/0627ff5f87a855928231eb17c3a22556727ac160/k9mail/src/main/java/com/fsck/k9/ui/messageview/AttachmentController.java#L233

What could fix this (I think):
Changing
```
private static File getTempFileForUri(Uri uri, Context context) {
        Context applicationContext = context.getApplicationContext();

String tempFilename = getTempFilenameForUri(uri);
```
to
```
private static File getTempFileForUri(Context context, Uri uri, String attachmentName) {
        Context applicationContext = context.getApplicationContext();

String tempFilename = attachmentName;
```

of course ```createTempUriForContentUri``` needs to be adjusted as well

and the following line (https://github.com/k9mail/k-9/blob/0627ff5f87a855928231eb17c3a22556727ac160/k9mail/src/main/java/com/fsck/k9/ui/messageview/AttachmentController.java#L183)
intentDataUri = AttachmentTempFileProvider.createTempUriForContentUri(context, attachment.internalUri, attachment.displayName);

so they also include the attachment name.

This is untested code, but it would be nice if the devs could take a look :)

**Comment by woll-knaeuel** [comment] 2023-11-13 13:09
Same request as described in this issue / enhandement. I would like to send attachments to an app without modifiing the original filename. This still seams not to be possible. The workaround (save the file localy and open it from the location with the app and deleting it afterwards) is time consuming and not efficient. So thumbs up for this or at least an option in the settings to choose if you would prefer the privacy (random name) or get original filename when sharing an attachment.

**Comment by fabian-thomas** [comment] 2024-10-18 19:16
https://github.com/thunderbird/thunderbird-android/issues/8045 is a duplicate of this issue and has been fixed in https://github.com/thunderbird/thunderbird-android/pull/8129. So this can be closed. The fix will be included in the next release and is already in the beta channels.

**Comment by fabian-thomas** [comment] 2024-10-18 19:20
@cketti Can you please close this? Thanks.

**Closed** 2024-10-18 19:46 UTC
Labels: type: enhancement

**Comment by Djfe** [comment] 2024-10-18 19:48
awesome thx for letting us know
