### ISSUE TITLE
Repeated headers in Notification drawer

### ISSUE THREAD

**Issue by lewri** [thunderbird/thunderbird-android#6154] opened 2022-07-08 15:58 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.000

### Where did you get the app from?

Google Play

### Android version

11

### Device model

OnePlus Nord

### Steps to reproduce

Not yet known. Appears to happen randomly once you have an array of unread new emails

### Expected behavior

Notification drawer should only show the email header once.

### Actual behavior

It has repeated headers from a random new email

![Screenshot_20220708-164842__01](https://user-images.githubusercontent.com/20030128/178028179-26bce208-5ca2-4f92-8548-3ec211acaab0.jpg)

### Logs

```bash
--------- beginning of system
07-07 16:28:44.580 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
--------- beginning of perf
07-07 16:28:45.035 14207 17795 I 110     : One big frame drop total:96 frameGap:149 delta#0#87#0#79#0#8
07-08 16:41:31.778 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
07-08 16:41:32.401 14207 17795 I 110     : One big frame drop total:83 frameGap:125 delta#0#78#0#71#0#5
--------- beginning of main
07-08 16:47:42.996 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:47:42.997 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:29.832 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:29.832 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:32.980 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:32.980 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:52.093 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:52.094 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:52.904 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:52.907 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:56.444 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:53:56.444 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:12.757 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:12.757 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:25.128 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:54:25.187 14207 14207 I OPFD_Manager: Dark? false, OP Force ? false
07-08 16:54:25.189 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
07-08 16:54:25.189 14207 14207 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
07-08 16:54:25.239 14207 14207 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
07-08 16:54:25.287 14207 14207 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@d82603e[MessageList]
07-08 16:54:25.288 14207 14207 D ViewRootImpl[MessageList]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:54:25.790 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:54:25.791 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:54:25.882 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:54:25.921 14207 14223 I com.fsck.k9: Background young concurrent copying GC freed 396896(16MB) AllocSpace objects, 0(0B) LOS objects, 28% free, 36MB/50MB, paused 329us total 140.079ms
07-08 16:54:25.944 14207 17795 I 110     : One big frame drop total:75 frameGap:148 delta#0#71#0#62#0#3
07-08 16:54:27.116 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:27.116 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:27.124 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:27.124 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:27.124 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:27.124 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:27.125 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:27.125 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:27.125 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:27.126 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:27.126 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:27.126 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:27.126 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:27.127 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:27.127 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:27.127 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:27.127 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:27.127 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:27.128 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:27.128 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:27.128 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:27.128 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:27.129 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:27.129 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:27.130 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:27.130 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:27.138 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:27.138 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:27.138 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:27.138 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:27.139 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:27.140 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:27.141 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:28.928 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:28.929 14207 14207 E com.fsck.k9: Invalid ID 0x00010005.
07-08 16:54:28.931 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:28.932 14207 14207 E com.fsck.k9: Invalid ID 0x00010010.
07-08 16:54:28.932 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:28.932 14207 14207 E com.fsck.k9: Invalid ID 0x0001000f.
07-08 16:54:28.933 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:28.933 14207 14207 E com.fsck.k9: Invalid ID 0x00010001.
07-08 16:54:28.933 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:28.933 14207 14207 E com.fsck.k9: Invalid ID 0x00010008.
07-08 16:54:28.934 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:28.934 14207 14207 E com.fsck.k9: Invalid ID 0x00010004.
07-08 16:54:28.934 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:28.934 14207 14207 E com.fsck.k9: Invalid ID 0x0001000c.
07-08 16:54:28.935 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:28.936 14207 14207 E com.fsck.k9: Invalid ID 0x0001000b.
07-08 16:54:28.936 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:28.936 14207 14207 E com.fsck.k9: Invalid ID 0x00010009.
07-08 16:54:28.936 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:28.936 14207 14207 E com.fsck.k9: Invalid ID 0x00010007.
07-08 16:54:28.937 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:28.937 14207 14207 E com.fsck.k9: Invalid ID 0x00010012.
07-08 16:54:28.938 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:28.938 14207 14207 E com.fsck.k9: Invalid ID 0x00000003.
07-08 16:54:28.938 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:28.939 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:29.758 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:29.758 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:29.837 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
07-08 16:54:29.837 14207 14207 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
07-08 16:54:29.843 14207 14207 D ViewRootImpl[MessageList]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:54:29.857 14207 14207 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
07-08 16:54:29.862 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:29.862 14207 14207 E com.fsck.k9: Invalid ID 0x00000002.
07-08 16:54:29.890 14207 14207 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@8df508c[SettingsActivity]
07-08 16:54:29.891 14207 14207 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:54:33.746 14207 14207 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:54:34.026 14207  8626 E sqlite3_android: [IKR-38846] ONEPLUS_NAME_PARTS_MATCH SQLITE_OK
07-08 16:54:34.040 14207 14289 I WM-WorkerWrapper: Worker result SUCCESS for Work [ id=3c17bb03-c486-4305-8cc8-30cefca78f60, tags={ com.fsck.k9.job.MailSyncWorker, MailSync } ]
07-08 16:54:37.720 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:37.720 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:40.249 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:40.250 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:44.273 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:54:44.273 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:55:34.512 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:55:34.512 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:55:37.687 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:55:37.688 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:03.615 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:03.617 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:14.803 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:14.803 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:38.546 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:38.548 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:42.137 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:42.137 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:44.931 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:44.932 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:46.902 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:46.902 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:54.314 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:56:54.317 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:03.501 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:03.502 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:08.641 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:08.642 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:45.058 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:45.058 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:54.539 14207 17795 W DisplayEventDispatcher: dispatcher 0xb400006fcfd1ad30 ~ ignoring unknown event type 0x6d746f6e
07-08 16:57:54.540 14207 14207 W DisplayEventDispatcher: dispatcher 0xb400006f7fd24f50 ~ ignoring unknown event type 0x6d746f6e
07-08 16:59:31.660 14207 14207 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@8df508c[SettingsActivity]
07-08 16:59:31.661 14207 14207 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:59:41.848 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.855 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
07-08 16:59:41.856 14207 14207 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
07-08 16:59:41.861 14207 14207 D ViewRootImpl[SettingsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:59:41.892 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.894 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 22 lines
07-08 16:59:41.894 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.898 14207 14207 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
07-08 16:59:41.899 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.900 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 10 lines
07-08 16:59:41.900 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.920 14207 14207 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@f78c71c[GeneralSettingsActivity]
07-08 16:59:41.922 14207 14207 D ViewRootImpl[GeneralSettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:59:41.925 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:41.926 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 10 lines
07-08 16:59:41.926 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:42.912 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:42.961 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 9 lines
07-08 16:59:42.961 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.546 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.691 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 54 lines
07-08 16:59:44.691 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.701 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.701 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 1 line
07-08 16:59:44.702 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.702 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.712 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.712 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:44.802 14207 14207 I chatty  : uid=10349(com.fsck.k9) identical 33 lines
07-08 16:59:44.802 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:46.614 14207 14207 E com.fsck.k9: Invalid ID 0x00000000.
07-08 16:59:46.634 14207 14207 D ViewRootImpl: not support adaptive color gamut feature!
07-08 16:59:46.635 14207 14207 V ViewRootImpl: The specified message queue synchronization  barrier token has not been posted or has already been removed
07-08 16:59:46.667 14207 14207 W Choreographer: Already have a pending vsync event.  There should only be one at a time.
07-08 16:59:46.675 14207 14207 D ViewRootImpl[GeneralSettingsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:59:46.692 14207 14207 D ViewRootImpl[PopupWindow:bd42e79]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:59:48.105 14207 14207 D ViewRootImpl[PopupWindow:bd42e79]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:59:48.105 14207 14207 D DecorView: onWindowFocusChangedFromViewRoot hasFocus: true, DecorView@f78c71c[GeneralSettingsActivity]
07-08 16:59:48.106 14207 14207 D ViewRootImpl[GeneralSettingsActivity]: windowFocusChanged hasFocus=true inTouchMode=true
07-08 16:59:48.121 14207 14207 D ViewRootImpl[GeneralSettingsActivity]: windowFocusChanged hasFocus=false inTouchMode=true
07-08 16:59:48.407 14207 17795 D OpenGLRenderer: endAllActiveAnimators on 0xb40000702fed8570 (MenuPopupWindow$MenuDropDownListView) with handle 0xb400006f4fd65b60
```

**Comment by gunterkoenigsmann** [comment] 2022-07-09 10:31
Duplicate of #6077

**Comment by cketti** [comment] 2022-07-09 10:34
Sadly, the log doesn't provide any hints as to what's going on. I'm closing this and we'll be using the older issue to track this bug.

**Closed by cketti** 2022-07-09 10:34 UTC
