### ISSUE TITLE
Cache too large

### ISSUE THREAD

**Issue by PandaGuitar** [thunderbird/thunderbird-android#7464] opened 2023-12-30 05:27 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.713

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Pixel 8 Pro

### Steps to reproduce

After a minimal amount of usage, I check the size of the cache, using the long press on the app icon & tap storage. The cache is always 1.72 GB or above, even though I clear it every day. 
![Screenshot_20231229-231730](https://github.com/thunderbird/thunderbird-android/assets/3621118/912a70ed-efa0-4bea-9100-1b16ef4f072a)

### Expected behavior

I expect a smaller cache

### Actual behavior

Since the latest update, cache is 1.72 GB or more

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/13797159/k9mail-logs.txt)

**Comment by cketti** [comment] 2023-12-30 14:56
This is not a general problem. My K-9 Mail installation is several years old and the cache size is below 50MB. I never manually clear the cache.

Unfortunately, there's no easy way to check what is causing your cache size to blow up like it does. Can you please do some experiments to try to narrow it down? 

I'm guessing it's the WebView component that is caching a lot of data. To test this, clear the cache, open the app and sync your accounts, but don't open any messages for viewing. Then check the cache size.
If the cache size is small, open a message for viewing, then check the cache size again. Repeat, and write down the cache size after each opened message. If there's a message that causes a significant increase, we'd like a (redacted) copy of that message so we can try to reproduce the problem on our test devices.

**Comment by PandaGuitar** [comment] 2023-12-30 18:22
I cleared the cache. I synced my accounts. Cache went up to 1.72 GB without even opening any messages.
Thanks

**Comment by jsinfate** [comment] 2024-01-02 17:41
Hello,
I was just wondering how you are using v6.713 when the version on Google Play and here on Github are both v6.603? I am using this version on Android 14 and my cache is 122MB. 
Could you have downloaded a per-releasve version or something?

**Comment by PandaGuitar** [comment] 2024-01-02 17:51
It's beta. The latest update did this to the cache.

**Comment by cketti** [comment] 2024-01-03 14:37
@PandaGuitar: Can you please clear the cache from the Storage screen, then exit the screen and open it again? Does the cache size actually shrink after "clear cache" was used?

**Comment by PandaGuitar** [comment] 2024-01-03 15:06
When I clear it, it says 0 B. When I close & reopen, it says 2.73 GB, even without opening the app to read messages.

**Comment by cketti** [comment] 2024-01-03 15:07
So at least part of the problem seems to be a bug in Android. Try force stopping the app, then clearing the cache.

**Comment by PandaGuitar** [comment] 2024-01-03 15:18
Same thing happens

**Comment by cketti** [comment] 2024-01-03 15:24
That makes it rather hard to find out what caused the cache to grow that large in the first place. I suggest you open a bug in Android's issue tracker for the cache not actually being deleted. https://issuetracker.google.com

**Comment by PandaGuitar** [comment] 2024-01-03 15:32
OK thanks!

**Comment by cketti** [comment] 2024-01-16 19:24
I'm closing this issue because there's not much we can do without more information. 

Please do post here once your Android version allows you to clear the cache so we can narrow down which part of K-9 Mail is responsible for growing the cache. I'll then re-open the issue.

**Closed by cketti** 2024-01-16 19:24 UTC

**Comment by dewdpol** [comment] 2025-04-27 02:43
Good afternoon, it seems when I manually download additional messages from the server - the cache size increases. After that it is impossible to clear it. Is it possible to add a function to delete downloaded emails from the phone after a certain period of time?
