### ISSUE TITLE
Visual regression from K-9: Unread emails contrast in inbox

### ISSUE THREAD

**Issue by nclm** [thunderbird/thunderbird-android#8234] opened 2024-10-04 05:55 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1 (Thunderbird) vs 6.804 (K-9)

### Where did you get the app from?

None

### Android version

13

### Steps to reproduce

1. Open an inbox with both unread and read emails in Thunderbird 8.0b1
2. Try to recognise which emails are unread and read

### Expected behavior

In K-9, the unread emails vs read emails were very easy to differentiate, using both largely different weights and different text shades:

![k9 screenshot](https://github.com/user-attachments/assets/7baab7e1-1a5f-456d-87ba-77cbfe3c64c1)

### Actual behavior

In Thunderbird, the unread emails vs read emails are only relying on font weight, making it very hard to distinguish which emails are unread:

![thunderbird screenshot](https://github.com/user-attachments/assets/0a7de8b7-6b94-4cb6-9bcb-d7a3a8f7835c)

**Comment by R7010A** [comment] 2024-10-05 09:45
Absolutely right.
It is a mess to recognize read from unread mails in the mail list.
For read mails the letters should be grey and for unread white in dark mode.
Using the grey background for unread mails kills my eyes.😁

**Comment by kewisch** [comment] 2024-10-18 08:17
Duplicate of #7980. I thought we already resolved this, but apparently not :) We can check with design what they'd recommend, I know we talked with them in the past about this but I don't think we've landed on a conclusion.

**Closed by kewisch** 2024-10-18 08:17 UTC

**Comment by nclm** [comment] 2024-10-18 08:22
Thanks for looking into it! I tried but cannot personally switch to Thunderbird until something is changed there, it is too confusing without the distinction between the two states :)

**Comment by nclm** [comment] 2025-05-29 08:16
Oops sorry forgot that was a duplicate of #7980 – will mention it there.
