### ISSUE TITLE
Show next (unread) message after delete doesn't work

### ISSUE THREAD

**Issue by piet85** [thunderbird/thunderbird-android#3263] opened 2018-03-15 19:36 UTC
### Expected behavior
Show next (unread) message.
After deleting the actual shown message, K9 should go to either next unread message or next message in list.

### Actual behavior
K9 shows next read message.
Instead of the expected behaviour, K9 shows the first read message in list and ignores all unread messages which are on higher positions.

### Steps to reproduce
1. check setting "global settings - interaction - Show next message after delete"
2. uncheck setting "global settings - interaction - return to list after delete"
3. get some new unread messages in your inbox and also some read ones
4. go to unified inbox
5. read the first one and delete it
6. K9 will show the first read message instead of next in list (or next unread)

### Environment
K-9 Mail version: 5.403

Android version: 7.1.1

Phone: Xiaomi Mi 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by maidbloke** [comment] 2018-04-23 18:47
I am experiencing exactly this issue. Quite annoying and reduces the usability of K9 for me. It seemed to start this behaviour after a recent update (perhaps in the last 8 weeks).

Thanks for a great app though!

K9 5.403
Samsung Galaxy S7
Android 7.0
POP3

**Comment by piet85** [comment] 2018-04-24 10:25
Good to know that there are other people with other phones with the same issue, so I suggest this bug is present on all android phones and not limited to one special device. I don't know how long this bug persists on my phone, but I suggest it could be some time longer than you said, I suggest it is since the last update on 06.01.18. As a workaround I checked "global settings - interaction - return to list after delete", so it takes me back to list after deleting instead of showing me a wrong message, that saves one additional press on the back button, but is not a fix at all. I hope this bug will be fixed soon.

**Comment by quadrillion** [comment] 2022-04-25 14:08
This appears to be the case if the sort order is "Read/unread". When the order is "Arrival", it seems to work as intended.

**Comment by cketti** [comment] 2022-09-09 17:19
Fixed by #6271

**Closed by cketti** 2022-09-09 17:19 UTC
