### ISSUE TITLE
Compose button broken on 6.900

### ISSUE THREAD

**Issue by MillionsToOne** [thunderbird/thunderbird-android#7846] opened 2024-05-15 16:37 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.900

### Where did you get the app from?

Other

### Android version

LineageOS 21 based on Android 14

### Device model

Oneplus 8T kb2003

### Steps to reproduce

1. Open app
2. Press compose button
3. K9-Mail crashes

### Expected behavior

You should be able to compose an email.

### Actual behavior

It started crashing.

### Logs

[k9mail-logs.txt](https://github.com/thunderbird/thunderbird-android/files/15324457/k9mail-logs.txt)

**Comment by cketti** [comment] 2024-05-15 16:38
Duplicate of #7842

**Closed by cketti** 2024-05-15 16:38 UTC
