### ISSUE TITLE
Save As Draft no longer works properly as of latest update 5.600.

### ISSUE THREAD

**Issue by HerborenInVlammen** [thunderbird/thunderbird-android#3611] opened 2018-09-12 19:38 UTC
Save As Draft no longer works properly as of latest update 5.600.

Expected behavior:  You click 'Save as Draft" and K-9 saves your message in the draft folder.  It saves subject, and message body.

Actual behavior:  If the message body is more than a few words, NONE of the message body is saved; only the subject is saved.  The preview of the saved draft shows the message body, but opening the draft results in all the body being deleted.  Thus rendering Save As Draft useless.

Steps:
1) Create message with subject and body
2) Use Save as Draft from menu or from popup
3) Open draft message and find body of message gone

This is a GO TO feature guys!  When it is broken K-9 is useless as a serious email client.  As a user who handles scores of emails a day, this needs attention yesterday!!

Confirmed on Lollipop (ASUS Zenfone 2), Nougat (Xiomi Redmi Note 4), and Oreo (Oneplus6)

**Comment by cketti** [comment] 2018-09-12 20:41
Works for me. 

Can you provide more detailed information on how this bug can be reproduced? Are you replying to a message? Forwarding a message? Can you provide a sample reply text that triggers the bug for you? What are the values for the following settings (found under 'Account settings > Sending mail'):
* Message Format
* Reply quoting style
* Quote message when replying
* Reply after quoted text
* Quoted text prefix

**Comment by HerborenInVlammen** [comment] 2018-09-13 02:45
Upon review of my bug report I forget to mention that this occurs only when creating a NEW message.  Sorry.  I thought I added that.  When forwarding or replying it works fine.  I should have been more clear.
Steps to recreate:
1) Create a NEW! message.
2) Put in a whole sentence or two (One, maybe two to six words works sometimes.)  Just viewing the preview in the list shows the body of the message.
3) Open the message, and the draft of the body of the message is blank. 

Occurs whether pop3 or IMAP.
Attached is a couple of screencasts of the bug.

    Message Format = **HTML**
    Reply quoting style = **Prefix (Like Gmail)**
    Quote message when replying = **Include the original message in your reply.**
    Reply after quoted text = **The original message will appear above your reply.**
    Quoted text prefix = **>**

[2018_09_12_19_48_09.mp4.zip](https://github.com/k9mail/k-9/files/2377510/2018_09_12_19_48_09.mp4.zip)

**Comment by cketti** [comment] 2019-03-08 03:39
Duplicate of #2581

**Closed by cketti** 2019-03-08 03:39 UTC
Labels: status: needs information
