### ISSUE TITLE
Deleted messages not deleted on server

### ISSUE THREAD

**Issue by Sommergoldhaehnchen** [thunderbird/thunderbird-android#6595] opened 2023-01-20 13:16 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.502

### Where did you get the app from?

F-Droid

### Android version

13

### Device model

OnePlus 8 Pro 5G EU

### Steps to reproduce

1. Delete a spam message in K-9 app
2. Update message list
3. Go to mail provider website in browser and check your mailbox.

### Expected behavior

The deleted spam message should be deleted on the server, too, as the option to delete messages on server if deleted in K-9 is activated.

### Actual behavior

The deleted spam messages in K-9 are still present in GMX online mailbox.
Updating message list in K-9 does not show these apparently deleted messages.

### Logs

[k9mail-logs.txt](https://github.com/thundernest/k-9/files/10466555/k9mail-logs.txt)

**Comment by Sommergoldhaehnchen** [comment] 2023-01-20 13:28
[k9mail-logs_2.txt](https://github.com/thundernest/k-9/files/10466639/k9mail-logs_2.txt)

The deleted spam messages (unread) were deleted in K-9 but in web client (GMX) these spam messages are still there (marked as read).

**Comment by Sommergoldhaehnchen** [comment] 2023-01-20 13:30
The same behaviour in drafts: Drafts folder is empty in K-9 but full in web client, as well after updating.

**Comment by cketti** [comment] 2023-01-20 14:54
Please update to K-9 Mail 6.503.

Duplicate of #6582

**Closed by cketti** 2023-01-20 14:54 UTC
