### ISSUE TITLE
Unable to access email on Office365

### ISSUE THREAD

**Issue by kubuntu-newbie** [thunderbird/thunderbird-android#7270] opened 2023-10-19 21:53 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

Graphene OS / Android 14

### Device model

Pixel 7

### Steps to reproduce

Following the instructions in the link [How do I add an Office365 account? on K-9 Mail forum](https://forum.k9mail.app/t/how-do-i-add-an-office365-account/5072)

incoming server:
outlook.office365.com
SSL/TLS
993
OAuth 2.0

outgoing server
smtp.office365.com
STARTTLS
587
OAuth 2.0

note: my email is not @office365.com or @outlook.com, it's an alias provided by my workplace but authentication appears to work

### Expected behavior

I'm expecting to be able to receive and send emails through my Office365 account

### Actual behavior

During the setup process, after the browser opens and I'm able to login, I don't get request to grant any permissions as described in 8. of the above guide.

When setting up the server while using Auto-detect namespace I get an error:

Setup could not finish
Cannot connect to server
(Command: NAMESPACE; response:
https://github.com/thundernest/k-9/pull/4# [BAD, User is authenticated but not connected.]]

If I turn off auto-detect namespace (tried blank, INBOX. etc) , the app allows creating of the server but I can't get any emails pulled down.

And when setting up smtp.office365 outgoing server:

"Setup could not finish
Cannot connect to server.
(Unable to open connection to SMTP server.)"
@kubuntu-newbie

**Comment by cketti** [comment] 2023-10-19 21:56
See https://forum.k9mail.app/t/outlook-oauth2-cannot-connect-to-server-command-namespace-response-4-bad-user-is-authenticated-but-not-connected/5931

**Comment by kubuntu-newbie** [comment] 2023-10-20 04:09
I saw that and I can't figure out which of the suggestions worked for whom.
In any case, if you are referring to disabling IPv6, I'm connected to the internet through a router that has IPv6 disabled as well as VPN that doesn't support IPv6.
If someone could explain what exactly in that discussion referred to in the link is the solution, I would really appreciate it.

**Comment by cketti** [comment] 2023-10-21 12:33
The takeaway from that thread is that it is unlikely to be a bug in the app, but a problem with Office365. Please contact them for help.

A quick search suggests this could be caused by a connection limit: https://support.getmailbird.com/hc/en-us/articles/16662162740375--User-is-authenticated-but-not-connected-issue-with-Outlook-accounts

This issue is not actionable for us, so I'm closing it. If Microsoft can provide details on what the app could do differently to not run into this error, feel free to open a new issue with that information.

**Closed by cketti** 2023-10-21 12:33 UTC

**Comment by kubuntu-newbie** [comment] 2023-10-22 15:49
same problem happens in Thunderbird (115) on Linux. In Thunderbird if I specify 1 connection instead of default 5 it makes no difference, so I don't think it's a connection limit. In any case it is a bug. how is it "completed"? has anyone event tried to troubleshoot this issue? looking at the logs, returned errors etc? other clients, like Outlook on iOS, Mail in Windows have to problems communicating with Office 365 servers.

at the moment, neither Thunderbird nor K9Mail are capable of talking to Office365
