### ISSUE TITLE
SMTP/IMAP password is stripped when testing the configuration

### ISSUE THREAD

**Issue by kleph** [thunderbird/thunderbird-android#8419] opened 2024-10-27 14:41 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

6.804

### Where did you get the app from?

F-Droid

### Android version

11 (Official OxygenOS 11.0.16)

### Device model

one plus nord N10 5G

### Steps to reproduce

1. Go in Settings
2. tap the user account
3. Sending mail
4. Outgoing server
5. FIll account info, with a password ending with a space character
6. Tap Next

### Expected behavior

The password is sent as written in the field, without stripping the ending space character.

### Actual behavior

The password is stripped before sending it to the server. Thus provoking auth failure and preventing to finish the setup.

Since I'm the email server admin, I set the server to debug mode and observed that the password is really lacking the last space character when sent by the test done at "checking outgoing server settings" time.

I could reproduce this behavior with the incoming server settings.

If the password was already configured in the past (years ago in this case), it's working fine, it is not stripped while being sent to the server.

### Logs

[k9mail-redacted.log](https://github.com/user-attachments/files/17534276/k9mail-redacted.log)

I set up a test account to reproduce the issue.
In the SMTP trace, we can see that the `AUTH PLAIN AHVzZXIAcGFzc3dvcmQ=` decodes to `userpassword` and not `userpassword ` (with ending space) as it should.

**Comment by cketti** [comment] 2024-10-27 15:45
Duplicate of #7774

**Closed by cketti** 2024-10-27 15:45 UTC

**Comment by kleph** [comment] 2024-10-28 00:33
Please allow to skip that check/assistant as it was before.
The UX choice is very sensible, no problem with that, and it's great!

At the very time the assistant check is running, it can fail from numerous reasons, even if it's bug-free, bad user [keyboards] inputs can happen, but a lot of others things(network, other smartphone stuff, ...) can, so many that are not on [y]our hands.

Very please, re-add a way to the bypass the forced assistant, as it was in k9 before, and also with thunderbird on desktop.
Even if it's an obscure check box in an advanced settings menu or whatever, any other path, that do not interfere with the clean UX assistant pattern, no problem!
Just any way where the assistant is not the only, strict, and final decision :pray:
