### ISSUE TITLE
Opening Draft loses Reply-To header

### ISSUE THREAD

**Issue by thtomate** [thunderbird/thunderbird-android#4219] opened 2019-10-13 11:16 UTC
### Expected behavior
If I save a draft with a Reply-To header and open it again, the chosen Reply-To header should still be used.

### Actual behavior
If you open a draft the Reply-To header is lost.

### Steps to reproduce
1. Create a mail with an identity with a Reply-To header
2. Save draft
3. (check headers with other IMAP client, header is still there)
4. Open draft
5. Send/Save again
6. (no Reply-To header in send mail/draft folder anymore)

### Environment
K-9 Mail version: 5.600

Android version: 9

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2019-10-13 12:53
The `Reply-To` value is never copied from a draft. But the app should have figured out which identity was used to create the draft and apply the identity settings on the new message created from the draft.

I can confirm that this is not working as expected. In my test the signature has also been appended even though this was disabled for the identity. So it looks like the identity settings are not properly applied when creating a new message from a draft.

**Comment by cketti** [comment] 2021-08-23 19:58
Related: #5611 (Add support for setting Reply-To header)

**Comment by cketti** [comment] 2021-08-23 20:29
I think this bug should be fixed by using the name + email address from the `From` header field to select the matching identity in the account. If that fails, use the account's default identity.

Use that identity as base when loading data from the identity header in the draft message.

I don't want us to support loading arbitrary Reply-To headers from draft messages before #5611 is implemented and we can display them in the user interface.

**Closed** 2021-09-16 03:46 UTC
