### ISSUE TITLE
No display profile

### ISSUE THREAD

**Issue by BabyOilJohnson** [thunderbird/thunderbird-android#6783] opened 2023-03-24 05:33 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

Other

### Android version

11

### Device model

Samsung A30

### Steps to reproduce

1. Go to side menu.

### Expected behavior

To display profile image from the account.

### Actual behavior

Not showing the profile picture.![Screenshot_20230324-104446_K-9 Mail](https://user-images.githubusercontent.com/101601874/227432759-1a7bcc16-fe4c-43c3-8ebd-564c0c7f24b7.png)

**Comment by cketti** [comment] 2023-03-24 11:03
Duplicate of #5509

**Closed by cketti** 2023-03-24 11:03 UTC
