### ISSUE TITLE
Drafts are deleted when they cannot be sent

### ISSUE THREAD

**Issue by loopsysdev** [thunderbird/thunderbird-android#2616] opened 2017-07-04 15:33 UTC
### Expected behavior

After SMTP failures, drafts should still be available to retry sending later.

### Actual behavior

The draft is gone - it's not in the drafts folder, archive, inbox, sent or trash. This has happened twice in the last few weeks.

### Steps to reproduce
1. Wait for your email provider to become unavailable.
2. Compose and try to send an email
3. Wait

### Environment
K-9 Mail version: 5.207

Android version: 6.0.1

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by AEaut** [comment] 2017-07-29 18:38
hello loopsysdev,

I couldn't/didn't try it out, because all the servers i have access to shut it down for purpose, are in operative service.

from that apart, did u also look in the 'outbox' folder?

i try to remeber, if any other client which i used in my lifetime, ever had the problem of 'definitely' not being able to transmit a message, for whatever reason, within a set limit (limit by a given number of attempts [like with k-9 now] or by a given timeframe, etc), and whether they put the message in the drafts folder, then, or in the trash folder - but i fail in that, because i think none of those clients had such limit, they rather all kept the messages in the outbox folder until they were either finally sent - miraculously - or removed from there manually.

speaking of that, i have assisted way too many users who had complained about being unable to send messages over weeks, to find out the reason was, mostly, one or more messages with ridiculously large (attachments) sizes, congesting the user's dialup capacity or smtp server's acceptance limit, leading to also all newer other messages kept 'waiting' chronologically in the outbox folder.

PS: If you are running the account in question in IMAP mode, then I assume you have set, in k-9's settings for that account, successfully transmitted messages to be saved into the "sent" folder?

**Comment by AEaut** [comment] 2017-07-30 07:30
just saw post #2598 which seems to confirm your reported behavior (with just a different reason of transmission failure, leading to the same result).

**Comment by mueschel** [comment] 2017-08-12 11:26
I can confirm this issue. Under some circumstances, mails that can not be sent are vanishing from the outgoing mail folder.

Expected behavior: Mail that can not be sent is stored in outgoing mail folder and sent at with next sync run. (This happens most of the time)

Faulty behavior:  K9 tries to sent email, reports an error (1). At this point, the mail is still visible in the outgoing mail folder. On the next sync run, the mail just vanishes.

I guess you can reproduce this behavior by blocking the SMTP port in your network. This is what I suspect to be the case in one Hotel WiFi where I lost every mail I was trying to sent. Workaround at this time was to switch to LTE before clicking 'send'.

IMAP-Account, STARTTLS,  Android 4.4 and 6.0.1, latest K9-Mail.

(1) E.g. javax.net.ssl.SSLException: Read error ... Connection timed out
or javax.net.ssl.SSLHandshakeException: SSL handshake aborted

**Comment by superlgn** [comment] 2017-11-08 23:03
I believe I'm experiencing this issue as well, but it may have something to do with a slightly unusual configuration on my work mail server.

I sent a few emails from my phone when I was out running some errands today and after a moment K-9 displayed an error notification about an SMTP delivery failure. I had some idea of what was wrong, as I configured the mail server. The assumption was the Wifi IP I was on had been blacklisted by one or more RBLs. So I connected to my VPN then looked through the folders to see if I could find the messages as to resend them, only nothing was there, so I retyped the messages by hand and they sent out fine. After I got home I started digging into this.

We run Postfix with smtpd_delay_reject=no along with some smtpd_client_restrictions that check an IP blacklist and some RBLs:

smtpd_delay_reject = no
smtpd_client_restrictions = permit_mynetworks,
                            check_client_access cidr:/etc/postfix/blacklist,
                            check_client_access cidr:/etc/postfix/whitelist,
                            reject_rbl_client sbl-xbl.spamhaus.org,
                            reject_rbl_client bl.spamcop.net,
                            reject_rbl_client b.barracudacentral.org,
                            permit

Which (if matched) will cause the SMTP connection to immediately close upon connecting with an error message like:

$ telnet mail.host 25
554 5.7.1 <host.name[a.b.c.d]>: Client host rejected: Access denied
[closed]

The primary reason I disabled the delay is to try and prevent known bad hosts from trying to brute force their way into accounts. If the delay is on, they still have that chance, although the transaction will eventually fail, but only after they've had their crack at and possibly found the password.

http://www.postfix.org/postconf.5.html#smtpd_delay_reject specifically says that some clients can misbehave with this setting disabled. At the time I didn't know exactly what they meant as I didn't encounter any issues in my testing, but perhaps this is it. Normally the setting is on and the transaction is allowed to go RCPT TO: before failing.

So I blacklisted my home IP and saw the same results. An error message from K-9 and no Drafts or messages waiting anywhere for me to retry later. I then turned on smtpd_delay_reject and tried again, and this time my failed message was stuck in Drafts, which I was later able to resend after unblocking myself.

As mentioned, Postfix defaults to the delay, and specifically says that disabling it could cause some problems. So I'm wondering if this might have something to do with it, if K-9 only hangs on to the draft if it's either unable to connect or sees a more typical failure message after possibly authenticating and beginning the SMTP transaction, which wouldn't be happing in this case.

If it's on me and my configuration and there's no interest in changing this possibly non-standard behavior, then I'll either have to live with it or rework my config to something a bit more traditional, but I'd prefer to keep things the way they are, if possible.

Thanks,

Mike

**Comment by smichel17** [comment] 2018-01-09 20:31
I believe I can confirm this issue as well, in a slightly different form:

**Steps to reproduce:**

1. Create a new email and attach a file that is too large to send (or in my case, many files that are too large in total)
2. Send the email.
3. Wait until K9 mail displays a notification that message sending failed.

**Expected behavior:** Message that failed to send should be in the drafts folder with attachments stripped.
**Actual behavior:** Message is not in drafts, outbox, or sent mail.

Note: this was actually a reply, and while the message does not show up anywhere, the "you have replied to this message" arrow *does* still appear.

**Comment by cketti** [comment] 2020-10-05 01:37
This should be fixed in K-9 Mail 5.7xx.

**Closed by cketti** 2020-10-05 01:37 UTC
