### ISSUE TITLE
Crash during compose or reply when entering recipient (OpenKeychain 6.0.0)

### ISSUE THREAD

**Issue by benkibbey** [thunderbird/thunderbird-android#7622] opened 2024-02-11 02:31 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.716-snapshot

### Where did you get the app from?

Other

### Android version

14 (Graphene OS)

### Steps to reproduce

1. Select compose icon to compose a new email
2. Begin typing in the recipient field.
3. Crash

or

1. Select an email.
2. Select the reply icon
3. Crash

### Expected behavior

Typing in the recipient field should not result in a crash.

### Actual behavior

When composing a new email or replying to an email a crash occurs. It seems to be an issue with autofill in the recipient field. This also happens in stable version 6.715.

### Logs

[k9.log](https://github.com/thunderbird/thunderbird-android/files/14231120/k9.log)

**Comment by cketti** [comment] 2024-02-11 03:17
This seems to be a problem in OpenKeychain (that K-9 Mail doesn't properly handle). 

As a work-around try disabling OpenPGP support in K-9 Mail and/or reinstalling OpenKeychain.

**Comment by benkibbey** [comment] 2024-02-11 03:36
Reinstalling OpenKeychain didn't help but disabling it in K-9 did.
Thanks.

**Comment by vdbhb59** [comment] 2024-02-12 03:29
Agreed. But then the OPGPK integration should be fixed please. I have encryption that needs to be used.
Also, confirmed, this does work if the disabling is done in K-9.

**Comment by cketti** [comment] 2024-02-12 12:04
Can one of you provide instructions on how to configure K-9 Mail and OpenKeychain to trigger this bug?

**Comment by cketti** [comment] 2024-02-12 12:20
Nevermind. I can reproduce this with OpenKeychain 6.0.0. See also: https://github.com/open-keychain/open-keychain/issues/2881

**Closed** 2024-02-12 13:22 UTC

**Comment by marek22k** [comment] 2024-02-14 21:44
Maybe a new version can be released in F-Droid with this bug fix?

I also get this error when trying to report a error in NewPipe via E-Mail:
```
FATAL EXCEPTION: ModernAsyncTask #4
Process: com.fsck.k9, PID: 10848
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.NullPointerException: ResultSet returned null for UserPackets.sq:selectUserIdStatusByEmailLike
	at android.os.Parcel.createExceptionOrNull(Parcel.java:3063)
	at android.os.Parcel.createException(Parcel.java:3041)
	at android.os.Parcel.readException(Parcel.java:3024)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:495)
	at android.content.ContentResolver.query(ContentResolver.java:1229)
	at android.content.ContentResolver.query(ContentResolver.java:1161)
	at android.content.ContentResolver.query(ContentResolver.java:1117)
	at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromCryptoProvider(RecipientLoader.java:230)
	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:200)
	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by spaetz** [comment] 2024-02-15 06:09
Just to let people know who might also suffer from this: all versions from 6.603 - 6.715 are affected (and yes, I understand that this seems to be Openkeychain's problem more than a k9 issue)
