### ISSUE TITLE
Option to configure an email account to receive only/add an option to disable mail sending

### ISSUE THREAD

**Issue by Peter0** [thunderbird/thunderbird-android#7673] opened 2024-02-26 21:33 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.714

### Problem you are trying to solve

I am using K-9 with multiple email accounts. Among them there is one, which I don’t want to use to send messages. In order to prevent according mistakes, my idea was to configure no (or an invalid) outgoing mail server. But it seems that K-9 is smart enough to not accept such habits.

### Suggested solution

Accept an empty field for "outgping mail ser er"

In properties, add an option to disable sending for specific accounts.

**Comment by cketti** [comment] 2024-02-26 23:29
Duplicate of #7524

**Closed by cketti** 2024-02-26 23:29 UTC
Labels: type: enhancement, unconfirmed
