### ISSUE TITLE
Passwords with Umlaut letters not working

### ISSUE THREAD

**Issue by dvzrv** [thunderbird/thunderbird-android#1673] opened 2016-10-05 22:51 UTC
### Expected behavior

Client authentication to IMAP (dovecot)/ SMTP (postfix) on new account setup.
### Actual behavior

Client fails to authenticate.
### Steps to reproduce
1. Setup mail account with Umlaut (ä,ö,ü) in password
2. Try to test the server connection
### Environment

K-9 Mail version: 5.111

Android version: 4.4.4

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

I know this is ugly, but some people actually seem to use Umlaut letters in passwords...
Webmail frontends such as roundcube don't suffer from the issue, but luckily let the account owner reset their password to something more sane (after which the authentication works).
Nonetheless, this might happen.

**Comment by philipwhiuk** [comment] 2016-10-06 00:12
For amusement: equivalent Thunderbird bug is I think https://bugzilla.mozilla.org/show_bug.cgi?id=312593

Are you using the plain authentication or encrypted authentication option? (You can check in the Account Settings -> Fetching mail screen).

**Comment by dvzrv** [comment] 2016-10-06 10:18
It was plain authentication in that case.

**Comment by philipwhiuk** [comment] 2016-10-06 20:03
Related Dovecot bug: http://www.dovecot.org/list/dovecot/2008-November/035271.html

The thing is, we already try AUTH PLAIN first, not LOGIN.

I am considering the best strategy on this.

1) If it contains non-ASCII characters, try multiple encodings
2) Restrict passwords to 7-bits and get the users to change them

I will probably change my password to use an umlaut and see what happens.

**Comment by cketti** [comment] 2019-02-28 21:11
Duplicate of #1015

**Closed by cketti** 2019-02-28 21:11 UTC
