### ISSUE TITLE
Feature Request: Support for HTML signatures

### ISSUE THREAD

**Issue by nose-gnome** [thunderbird/thunderbird-android#7684] opened 2024-03-03 19:58 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.717

### Problem you are trying to solve

I want to be able to have the HTML formatted signatures, so I can havecustom colour and font, along with including a hyperlink, hyperlink phone number and hyperlink email.

This would allow me to have a consistent signature emails sent from Thunderbird desktop

### Suggested solution

Add HTML support for signatures.

**Comment by cketti** [comment] 2024-03-04 13:45
Duplicate of #794

**Closed by cketti** 2024-03-04 13:45 UTC
Labels: type: enhancement, unconfirmed
