### ISSUE TITLE
It is hard to star a mail in the main screen without scrolling down

### ISSUE THREAD

**Issue by Massedil** [thunderbird/thunderbird-android#5052] opened 2020-11-14 09:54 UTC
**Describe the bug**

It is hard to star a mail in the main screen without scrolling down. 

**To Reproduce**
1. Go to the main screen
2. Click on the star icon to star an email

**Expected behavior**
The email is starred. 

**Actual behaviour**
It often scroll down instead of starring the email because the star icon is near the right border of the screen. 

**Environment (please complete the following information):**
 - K-9 Mail version: [e.g. 5.724]
 - Android version: 9
 - Device: Galaxy S5
 - Account type: IMAP

**Comment by cketti** [comment] 2020-11-14 19:18
Duplicate of #894

**Closed by cketti** 2020-11-14 19:18 UTC
