### ISSUE TITLE
S/MIME not just PGP support

### ISSUE THREAD

**Issue by MANICX100** [thunderbird/thunderbird-android#8559] opened 2024-11-13 10:34 UTC
### Checklist

- [x] I have used the search function to see if someone else has already submitted the same feature request.
- [x] I will describe the problem with as much detail as possible.
- [x] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.1

### Problem you are trying to solve

I always digitally sign (Not encrypt) by messages using my S/MIME Certificate. This workflow doesnt appear to be supported in the current android build but is on desktop.

### Suggested solution

Same support as desktop for unencrypted but signed emails

**Comment by cketti** [comment] 2024-11-13 10:42
Duplicate of #1003

**Closed by cketti** 2024-11-13 10:42 UTC
Labels: type: enhancement, unconfirmed
