### ISSUE TITLE
Custom From Address like in Thunderbird.

### ISSUE THREAD

**Issue by cobordism** [thunderbird/thunderbird-android#7352] opened 2023-11-13 13:47 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

As a user with a catch-all email address - i.e. ANYTHING@my.domain works - I routinely use new addresses for new purposes. 
This helps in terms of organisation / filtering and in terms of security - identifying phishing.

On Thunderbird I can always type my "From" address by selecting "Custom Sender" in the pull-down.

In K9mail I have to save the email as draft. Navigate to settings. Composing/Sending. Manage Identities. Create new Identity etc etc.. navigate back to my draft and select the new identity from the pull-down and hit send.

This is an incredibly painful workflow.

Feature Request: Allow me to type the From Address manually ad-hoc without going through the whole Identity Creation workflow.

### Suggested solution

As in Thunderbird, the From field allows you to click "custom" and then type the desired alias.

**Comment by Cwpute** [comment] 2023-12-15 21:10
I routinely use aliases as well, but with a plus sign `+` in them: `johndoe+ANYTHING@my.domain`.It's also called email subadressing.
I'd also like to be able to send mails from my subadresses more easily, not for privacy reasons, but because some websites require you reply to their mail with the exact adresg they sent their mail to (which is understandable). For example: Gitlab issue replies that get sert by replying to an email notification.

**Comment by Cwpute** [comment] 2023-12-15 21:18
Probably a duplicate of #935 though :x

**Comment by tamirat67** [comment] 2023-12-16 16:08
Hello everyone, first of all, I would like to express my appreciation to
the Thunderbird/K-9 developers. However, there are still some bulky
incoming and outgoing server settings, and recently, you added a folder
filter option. Please consider removing the extra configurations.

**Comment by cketti** [comment] 2024-01-03 15:03
Duplicate of #935

**Closed by cketti** 2024-01-03 15:03 UTC
Labels: enhancement, unconfirmed
