### ISSUE TITLE
Empty message body when opening mail from server search results

### ISSUE THREAD

**Issue by 36bits** [thunderbird/thunderbird-android#3111] opened 2018-01-18 21:07 UTC
Please search to check for an existing issue (including closed issues, for which the fix may not have yet been released) before opening a new issue: https://github.com/k9mail/k-9/issues?q=is%3Aissue

### Expected behavior
When I open a mail from the server search results list I expect to see the content of the message.

### Actual behavior
No content is displayed, just the sender, recipient and timestamp. In addition, selecting 'Show headers' from the menu displays the headers for a fraction of a second and then they disappear.

### Steps to reproduce
1. Run a search from the message list
2. Press 'Search messages on server'
3. Select a message from the server results list

### Environment
K-9 Mail version:
5.403
Android version:
7.0
Account type (IMAP, POP3, WebDAV/Exchange):
IMAP

**Comment by philipwhiuk** [comment] 2018-01-18 22:08
I can't reproduce this against my mail server - can you provide a debug log?

**Comment by 36bits** [comment] 2018-01-19 20:23
Here's the debug log. The search is at 01-19 20:01:20.734

[k9-log.txt](https://github.com/k9mail/k-9/files/1647831/k9-log.txt)

**Comment by philipwhiuk** [comment] 2018-01-19 20:49
Thanks, that's very useful. It's clearly skipping it due to age when it shouldn't be.

**Comment by philipwhiuk** [comment] 2018-01-19 21:04
Here's the relevant log snippet.

```
01-19 20:01:31.490 V/ImapConnection(24400): conn28255846>>> 7 UID SEARCH 1065
01-19 20:01:31.494 V/ImapResponseParser(24400): conn28255846<<<#null# [SEARCH, 2707]
01-19 20:01:31.496 V/ImapResponseParser(24400): conn28255846<<<#7# [OK, Search completed (0.000 secs).]
01-19 20:01:31.497 I/MessagingController(24400): Got new pushed email messages for account jonathan@s10, folder INBOX
01-19 20:01:31.653 V/MessagingController(24400): Message with uid 2707 is present in the local store
01-19 20:01:31.653 V/MessagingController(24400): Message with uid 2707 is not downloaded, even partially; trying again
01-19 20:01:31.653 D/MessagingController(24400): SYNC: Have 1 unsynced messages
01-19 20:01:31.653 D/MessagingController(24400): SYNC: About to fetch 1 unsynced messages for folder INBOX
01-19 20:01:31.660 V/ImapFolder(24400): Stored uid '2707' for msgSeq 1065 into map
01-19 20:01:31.662 D/MessagingController(24400): Newly downloaded message 2707 is older than Tue Dec 19 00:00:00 GMT+00:00 2017, skipping
01-19 20:01:31.662 V/ImapConnection(24400): conn179947654<<<#118# [OK, Fetch completed.]
01-19 20:01:31.679 D/MessagingController(24400): SYNC: Synced unsynced messages for folder INBOX
01-19 20:01:31.679 D/MessagingController(24400): SYNC: Have 0 large messages and 0 small messages out of 1 unsynced messages
01-19 20:01:31.680 D/MessagingController(24400): SYNC: Fetching 0 small messages for folder INBOX
01-19 20:01:31.680 D/MessagingController(24400): SYNC: Done fetching small messages for folder INBOX
01-19 20:01:31.681 D/MessagingController(24400): SYNC: Fetching large messages for folder INBOX
01-19 20:01:31.681 D/MessagingController(24400): SYNC: Done fetching large messages for folder INBOX
01-19 20:01:31.682 D/MessagingController(24400): SYNC: About to sync flags for 0 remote messages for folder INBOX
01-19 20:01:31.682 D/MessagingController(24400): SYNC: Synced remote messages for folder INBOX, 0 new messages
```

The call path is as follows:

downloadCompleteMessage / onLoadMessageFromDatabaseFinished
startDownloadingMessageBody
loadMessageRemotePartial / loadMessageRemote
loadMessageRemoteSynchronous
downloadMessages
fetchUnsyncedMessages

The bug is that fetchUnsyncedMessages does not take into account the `purgeToVisibleLimit` parameter in the `downloadMessages` function.

**Comment by procyon12lotor** [comment] 2018-04-03 23:17
I've also been experiencing this. I am using mailbox.org as a backend, and it happens for all emails not currently synced to my phone.

**Comment by morckx** [comment] 2018-07-14 17:01
@dgrabla : See my comment [here ](https://github.com/k9mail/k-9/issues/3254#issuecomment-398661631)

**Comment by dgrabla** [comment] 2018-07-15 05:45
My error, K9 can download server emails when it is allowed on the account configuration to get messages no matter how old - the whole collection. Maybe an error message indicating the email was not downloaded because it is older than what k9 on the settings is allowed to retrieve will be useful.

**Comment by morckx** [comment] 2018-07-15 06:30
Sorry, yes, this is indeed an issue on its own. However, with current builds, the fetching of the found messages was not possible due to two additional bugs that are not circumventable by the right settings (provisionally fixed in #3501) .

**Comment by istenrot** [comment] 2019-01-11 11:58
Any progress on this issue recently?

**Comment by renanito** [comment] 2019-01-28 16:03
Actually it's possible to change the setting : in the account setting, change the sync history to 1 year.

**Comment by DerGuteWolf** [comment] 2019-01-28 17:33
@renanito : but this not help for even older messages or when one year is too much data...

**Comment by Cactus-World** [comment] 2019-12-03 00:25
Still not working correctly in version 5.701...

**Closed** 2019-12-17 16:47 UTC

**Comment by Wolf35978** [comment] 2020-05-09 09:29
Hi there, the issue persists. I tried a few moments ago. Can you please check for this? What do you need from me to fix?
regards Wolf
