### ISSUE TITLE
Special folders names are not localized according to their mapping in Settings but keep the IMAP name

### ISSUE THREAD

**Issue by NicolasWeb** [thunderbird/thunderbird-android#8279] opened 2024-10-08 19:34 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b2

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Xiaomi Note 10 Pro

### Steps to reproduce

1. Use a localized version of Thunderbird for Android
2. Set an IMAP account
3. Go to hamburger menu
4. Check the names of the special folders (Inbox, Draft, Sent, Spam, Trash, ...) and their icons
5. Go to Settings/Account/<Account name>/Folders
6. Check that the names of each setting (not the values!) for special folders are translated in the UI

### Expected behavior

Step 4 : Special folders displayed names are localized as they are in their own settings titles in Folders mapping (squared in blue in the screenshot)

### Actual behavior

Special folders displayed names are NOT localized in the folders tree.
Maybe they stay in EN-US. Maybe they keep the IMAP name.

### Logs

![IMG_20241008_205823](https://github.com/user-attachments/assets/20b1864c-d521-4189-a2eb-349363b472de)
![IMG_20241008_213155](https://github.com/user-attachments/assets/43ac5cd3-9289-401d-a087-cf522c80af56)

**Comment by NicolasWeb** [comment] 2024-10-08 19:42
If you go to `Settings/Manage folders` you will notice that only `Inbox` and `Outbox` use their translated special names

**Comment by cketti** [comment] 2024-10-09 12:34
Duplicate of #6799

**Closed by cketti** 2024-10-09 12:34 UTC
