### ISSUE TITLE
Attachment symbol shown when there is no attachment

### ISSUE THREAD

**Issue by bypear** [thunderbird/thunderbird-android#7609] opened 2024-02-07 19:01 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.715

### Where did you get the app from?

Other

### Android version

14

### Device model

Pixel 5a

### Steps to reproduce

Hello!

First, I love this app! To all contributors: Thank you so much for all the work done.

As for the issue:

It happens with some of my emails that k9 shows an attachment symbol in the subject line (for example in the inbox view where all the emails are listed) next to the time/date.

However, this email doesn't have an attachment. If I view the header, there's also no attachment listed. If I sort emails with attachments, then those emails are sorted too. As if they have an attachment, but they don't.

I couldn't find any bug report about it but please close my report if it is a duplicate.

### Expected behavior

K9 should not show an attachment symbol when there is no attachment.

### Actual behavior

K9 shows an attachment symbol when there is no attachment.

### Logs

I'd rather not provide logs of my emails/k9 setup. But maybe it's not necessary to have logs here.

**Comment by cketti** [comment] 2024-02-12 14:08
Please provide the source of such a message. Feel free to redact the contents. The important thing is the MIME structure.

**Comment by cketti** [comment] 2024-02-12 18:21
Thanks. Apparently we display the attachment indicator when a message contains inline images.

Duplicate of #3405

**Closed by cketti** 2024-02-12 18:21 UTC
