### ISSUE TITLE
Schedule send email

### ISSUE THREAD

**Issue by paniash** [thunderbird/thunderbird-android#7492] opened 2024-01-10 22:18 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

I would like to send an email at a later time automatically. Such a feature exists on gmail, where you can specify the date and time of sending. The only difference is that the email scheduled to be sent later is stored on google's servers and only at the specified time does it get sent from the server to the recipient.

### Suggested solution

K-9 being an IMAP client on android could fulfill such a feature by running in the background or make period time checks. When the time-check is at the specified scheduled time, the email gets sent from the client to the recipient.

**Comment by njeyaakili** [comment] 2024-01-10 23:31
this is really a server-side capacity - which is how outlook and, as you note, gmail handles this option. trying to do this from this client-side is very unreliable as it assumes the device is on, has connectivity and the app is running at the specified time(s).

**Comment by cketti** [comment] 2024-01-11 10:20
Duplicate of #688

**Closed by cketti** 2024-01-11 10:20 UTC
Labels: enhancement, unconfirmed
