### ISSUE TITLE
Case sensitivity problem in account>folders settings

### ISSUE THREAD

**Issue by stenyak** [thunderbird/thunderbird-android#632] opened 2015-04-29 10:52 UTC
I have an IMAP account with two directories, one named "Spam", and other named "spam".

In K9Mail I go to Account Preferences, Folders, Spam folder, and try to choose the lower case "spam".

After that, marking a message as spam, K9Mail will still move it to the "Spam" folder, instead of "spam".

I suppose the problem is case sensitivity?

**Comment by cketti** [comment] 2015-04-30 01:52
I was wondering when someone would stumble upon this. Sadly, far too many folder name comparisons are case-insensitive. But the only folder that must be compared case-insensitive is Inbox.

This should be easy to fix, though. Even for someone unfamiliar with the code base. Any takers?

**Comment by jkdf2** [comment] 2015-06-19 23:37
I cannot reproduce this bug, either. I followed the steps outlined and K9 moved it to the "spam" folder as expected.

**Comment by swapsmagic** [comment] 2015-12-26 23:21
I don't know how you can have two folders with "Spam" and "spam" as name. I trying creating label "spam" using gmail and folder "spam" in yahoo account but none of them allowed it. Can someone explain to create such Folders and i can work on it if it's still an issue.

**Comment by GoneUp** [comment] 2017-01-13 16:55
Could not reproduce it either. Time to close it?

**Comment by Pritom14** [comment] 2017-02-28 19:34
If suppose we there are two lists "spam" and "Spam", after marking a message as spam we want the message to go in "spam" and not in "Spam". We can do something like this,

```
if(message.markedSpam()){
    spam.add(message);}
```
where, `markedSpam()` is a function which decides whether a message is marked as spam or not. 
I am new to this, so it's just an idea. Please guide me further.

**Comment by getsanjeev** [comment] 2017-02-28 22:29
@cketti I do not think the problem can be replicated. 
Moreover I am not being able to see the new folders in the app ; created through browser.  I have tried with both gmail and outlook.

**Comment by philipwhiuk** [comment] 2017-02-28 23:45
Nope there's definitely work to be done here. `ImapFolder` violates the contract for hashCode. The following test fails because `ImapFolder.equals()` ignores the case for getName().

```
    @Test
    public void equals_returnsFalse_whenHashCodeIsDifferent() {
        ImapFolder imapFolder = createFolder("Folder");
        ImapFolder imapFolder2 = createFolder("folder");
        assertNotEquals(imapFolder.hashCode(), imapFolder2.hashCode());

        assertFalse(imapFolder.equals(imapFolder2));
    }
```

This means the behaviour of putting and retrieving ImapFolders from collections will have problems which is probably the cause.

This is not that simple to fix because we want to retain the behaviour surrounding INBOX being equal to Inbox - just not Spam being equal to spam.

**Comment by AnirudhBadri** [comment] 2017-03-01 10:18
I am new to open-source and would like to work on this. I think my first step here would be to replicate the problem. Any suggestions regarding what else I should do to start?

**Comment by danwain** [comment] 2017-03-01 11:46
A solution would be to change it to only do case insensitivity on the inbox folder eg
```java
            if (otherFolder.getName().equalsIgnoreCase("inbox"))
                return otherFolder.getName().equalsIgnoreCase(getName());
            else
                return otherFolder.getName().equals(getName());
```
However this could be an issue when creating folders in K9 with servers that are case sensitive.
I'm not families with the code base so I'm not sure on what ramifications this would have. Anyone have any suggestions.

**Comment by philipwhiuk** [comment] 2017-03-07 17:38
This probably needs more thought than a beginner task.

**Comment by cketti** [comment] 2017-03-26 04:58
The case-insensitive comparison for INBOX is an IMAP-only thing. I think the best way to deal with it is to normalize the Inbox folder name returned by the LIST command to "INBOX". Then all other folder comparisons inside K-9 Mail can be case-sensitive. The server has to treat the Inbox folder name case-insensitive so it doesn't care if the Inbox name we send is not exactly like that in the LIST response. And by normalizing the name from the LIST response we protect ourselves from the server changing the case of the Inbox folder name in a subsequent LIST response.

**Closed** 2018-02-27 18:55 UTC
Labels: type: architecture
