### ISSUE TITLE
Auto-sync after starting the app

### ISSUE THREAD

**Issue by AS98765** [thunderbird/thunderbird-android#8214] opened 2024-10-01 13:52 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.804

### Problem you are trying to solve

No auto-sync after starting the app (POP3).

### Suggested solution

Auto-sync after starting the app.

**Comment by au7oma7** [comment] 2024-10-02 15:15
I second that request.

I am currently using version 8.0b1 on android phone with one pop3 account and the app doesn't fetch new messages upon start,
manual refresh is needed to initate message sync.

**Comment by ssaring** [comment] 2024-11-17 12:32
I'm also missing the feature that Thunderbird (up to current version 8,1) fetches automatically for new mails when starting the app.
All my email accounts in Thunderbird are configured for manual query of new mails (no periodic fetch), because I don't want to get notified automatically and I don't want to have resource consuming background activities. Instead I want just to open the Thunderbird app where the manual query for new mail would be started automatically.

This is how all the other mail apps are working (e.g. GMail or Mail on iOS). Would be great to have this (default?) behavior in Thunderbird as well. Otherwise the user always needs to trigger manually the upload in addition when opening the app, although it's clear that the user wants to check for new mails.

**Comment by cketti** [comment] 2024-12-05 11:32
Duplicate of #7257

**Closed by cketti** 2024-12-05 11:32 UTC
Labels: type: enhancement, unconfirmed
