### ISSUE TITLE
attached images cannot be displayed (but can be saved)

### ISSUE THREAD

**Issue by gdt** [thunderbird/thunderbird-android#1644] opened 2016-09-28 23:01 UTC
### Expected behavior

After receiving a message with an attached image, I see a line for the attached part (jpg) with two buttons: "Open" and "Save".   Whether or not the image has been downloaded, I expect that pushing "Open" leads to seeing the picture full screen.
### Actual behavior

I see a black screen with "No thumbnail" in really really small white type in the middle.  The menu shows "Set picture as" and "Print".

After doing this, or maybe just after downloading, I see a preview in the message.  I have done "save" and verified that I can then use gallery to see the image from the sd card.
### Steps to reproduce
1. Set up openkeychain and generate a key
2. get frustrated with clicking on approve for messages signed  by weak keys (but not unsigned messages) and set provider to none  (I have no idea if 1/2 are necessary; still fails with it turned back on)
3. Get an email with an attached image in INBOX.   So far  any sending MUA works, and in all cases other clients view the image fine.
4. Click "open"
### Environment

K-9 Mail version: 5.111 (git master 5.111-15-gf388fe4
 f388fe41b8992d8f80548e6c8124189895ae81f5)

Android version: CM 13

Account type (IMAP, POP3, WebDAV/Exchange):  IMAP
### adb logcat

```
09-27 19:16:55.377 6264-7884/com.fsck.k9.debug E/OpenPgp API: IOException when writing to out
    java.io.IOException: write failed: EPIPE (Broken pipe)
    at libcore.io.IoBridge.write(IoBridge.java:498)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at org.openintents.openpgp.util.ParcelFileDescriptorUtil$TransferThread.run(ParcelFileDescriptorUtil.java:78)
    Caused by: android.system.ErrnoException: write failed: EPIPE (Broken pipe)
    at libcore.io.Posix.writeBytes(Native Method)
    at libcore.io.Posix.write(Posix.java:271)
    at libcore.io.BlockGuardOs.write(BlockGuardOs.java:313)
    at libcore.io.IoBridge.write(IoBridge.java:493)
    at java.io.FileOutputStream.write(FileOutputStream.java:186)
    at org.openintents.openpgp.util.ParcelFileDescriptorUtil$TransferThread.run(ParcelFileDescriptorUtil.java:78)
p
```

**Comment by gdt** [comment] 2016-09-28 23:04
After uninstalling openkeychain and force-close and restart k-9, I still get the black/no-thumbnail display.

**Comment by jotwewe** [comment] 2016-10-14 17:52
I experience the same, however it has nothing to do with openkeychain (I have never used it). It worked as expected with version 5.010 from f-droid, the bug is there since 5.113 f-droid. Well, if I remember correctly there also was 5.111 on f-droid, which showed the bug, too, but was replaced some days later due to the dark theme fix.

**Comment by lbdroid** [comment] 2016-10-18 18:21
Same thing here. Android 7 on Nexus 6. Cannot open an attached image.

**Comment by cketti** [comment] 2016-10-18 18:48
Works for me. What app is used to open the image?

**Comment by jotwewe** [comment] 2016-10-18 18:59
It is cyanogenmods standard gallery-app 'com.android.gallery3d'.

Because of your question I just installed 'leafpic' from the f-droid
store -- now android asks which app to use in order to display the
attached image. After chosing leafpic, no picture is displayed. I have
to use the save/download workaround when using leafpic, too.

**Comment by lbdroid** [comment] 2016-10-18 20:13
@cketti : I've been running a custom modified com.android.gallery3d that I forked from AOSP. Turns out that it *does* work with google photos...

**Comment by gdt** [comment] 2016-10-19 12:26
I have been using the cyanogenmod gallery app, stock from CM 13.

**Comment by philipwhiuk** [comment] 2016-10-19 12:39
So there's two options here:

1. There's a bug in how we are dispatching content to image viewers that Google Photos is able to work-around
2. There's a bug in the AOSP/CM gallery app. It sounds like they use much of the same underlying code base

I'm not sure which is more likely right now.

**Comment by lbdroid** [comment] 2016-10-19 12:58
Well, what I can say, is that it **used to work**.
It also continues to work from other applications. For instance, if I use Amaze file manager, and select an image, open with gallery3d, then it loads the image as expected. Of course, it is *probably* dispatching the data in a different manner -- URI to filesystem vs. ???.

**Comment by jotwewe** [comment] 2016-10-19 17:53
I want to repeat my statement in a somewhat clearer fashion: my system
(cyanogenmod 12.1) has NOT changed; I have NOT changed the app
used to view images. Opening attached images from k9mail worked when
using 5.010 from f-droid, but not with 5.111 and 5.113 from f-droid.
It seems like k9mail makes the difference.

**Comment by zoff99** [comment] 2016-10-19 17:54
+1 i have the same issue

i do not use CM and i use quickpic as gallery app

**Comment by philipwhiuk** [comment] 2016-10-19 22:12
Thanks to both of you. I'll try and reproduce this with the quickpic app and look at what's changed.

**Comment by philipwhiuk** [comment] 2016-10-20 01:12
Here's the debug trace for QuickPic

```
10-20 01:40:05.510 892-29388/? I/PackageManager: Setting last chosen activity com.alensw.PicFolder/.GalleryActivity for user 0:
10-20 01:40:05.511 892-29388/? I/PackageManager:   Action: "android.intent.action.VIEW"
10-20 01:40:05.511 892-29388/? I/PackageManager:   Category: "android.intent.category.DEFAULT"
10-20 01:40:05.511 892-29388/? I/PackageManager:   Type: "image/jpeg"
10-20 01:40:05.511 892-29388/? I/PackageManager:   AutoVerify=false
10-20 01:40:05.515 892-4637/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.debug.attachmentprovider/e4cc752c-2b4c-4efb-bd57-4adb84e7340e/40208/image/jpeg typ=image/jpeg flg=0x13080001 cmp=com.alensw.PicFolder/.GalleryActivity} from uid 10119 on display 0
```
vs (working) for Google Photos.

```
10-20 01:41:33.186 892-2892/? I/PackageManager: Setting last chosen activity com.google.android.apps.photos/.pager.HostPhotoPagerActivity for user 0:
10-20 01:41:33.186 892-2892/? I/PackageManager:   Action: "android.intent.action.VIEW"
10-20 01:41:33.186 892-2892/? I/PackageManager:   Category: "android.intent.category.DEFAULT"
10-20 01:41:33.186 892-2892/? I/PackageManager:   Type: "image/jpeg"
10-20 01:41:33.186 892-2892/? I/PackageManager:   AutoVerify=false
10-20 01:41:33.187 892-5724/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.debug.attachmentprovider/e4cc752c-2b4c-4efb-bd57-4adb84e7340e/40208/image/jpeg typ=image/jpeg flg=0x13080001 cmp=com.google.android.apps.photos/.pager.HostPhotoPagerActivity} from uid 10119 on display 0
```

As you can see we are using a perfectly normal ACTION_VIEW_INTENT with a content URI. 

The behaviour of Google Photos is to display the file. The behaviour of QuickPic is to close the activity immediately.

After leaving it idle for a bit QuickPic crashed with an NPE:

```
Process: com.alensw.PicFolder, PID: 9595
java.lang.NullPointerException: Attempt to read from field 'com.alensw.b.v com.alensw.b.x.c' on a null object reference
at com.alensw.b.w.b(Unknown Source)
at com.alensw.c.k.h.run(Unknown Source)
```

I've uninstalled it again (I'm not a fan of Cheetah Mobile) because I'm not likely to learn more from a closed source app.

So I tried another one: Image Viewer by Byte Mobile.

```
10-20 02:06:54.399 892-3738/? I/ActivityManager: START u0 {act=android.intent.action.VIEW dat=content://com.fsck.k9.debug.attachmentprovider/e4cc752c-2b4c-4efb-bd57-4adb84e7340e/40208/image/jpeg typ=image/jpeg flg=0x13080001 cmp=com.pcvirt.ImageViewer/.PreviewActivity} from uid 10119 on display 0
...
10-20 02:06:54.735 12086-12086/? E/BitmapFactory: Unable to decode stream: java.io.FileNotFoundException: content:/com.fsck.k9.debug.attachmentprovider/e4cc752c-2b4c-4efb-bd57-4adb84e7340e/40208/image%2Fjpeg (No such file or directory)
10-20 02:06:54.865 12086-12398/? W/System.err: java.io.FileNotFoundException: /content:/com.fsck.k9.debug.attachmentprovider/e4cc752c-2b4c-4efb-bd57-4adb84e7340e/40208/image%2Fjpeg (No such file or directory)
10-20 02:06:54.865 12086-12398/? W/System.err:     at java.io.FileInputStream.open(Native Method)
10-20 02:06:54.865 12086-12398/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:146)
10-20 02:06:54.865 12086-12398/? W/System.err:     at java.io.FileInputStream.<init>(FileInputStream.java:99)
10-20 02:06:54.865 12086-12398/? W/System.err:     at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
10-20 02:06:54.865 12086-12398/? W/System.err:     at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
10-20 02:06:54.865 12086-12398/? W/System.err:     at com.pcvirt.ImageSearchActivity.search.providers.AbstractPagedImageSearch$Result.getFile(AbstractPagedImageSearch.java:411)
10-20 02:06:54.866 12086-12398/? W/System.err:     at com.pcvirt.ImageSearchActivity.search.providers.AbstractPagedImageSearch$Result.getImageFile(AbstractPagedImageSearch.java:457)
10-20 02:06:54.866 12086-12398/? W/System.err:     at com.pcvirt.ImageSearchActivity.helpers.SearchHelper.getItemShareUri(SearchHelper.java:180)
10-20 02:06:54.866 12086-12398/? W/System.err:     at com.pcvirt.ImageSearchActivity.helpers.SearchHelper.setIntentItems(SearchHelper.java:158)
10-20 02:06:54.866 12086-12398/? W/System.err:     at com.pcvirt.ImageSearchActivity.helpers.SearchHelper.getItemsShareIntent(SearchHelper.java:146)
10-20 02:06:54.866 12086-12398/? W/System.err:     at com.oajoo.bitmapviewer.BVPreviewFragment$17.run(BVPreviewFragment.java:762)
10-20 02:06:54.866 12086-12398/? W/System.err:     at java.lang.Thread.run(Thread.java:761)
```

Thank you Byte Mobile.

But why can Google Photos find the file....

Regression testing time...

**Comment by maulwuff** [comment] 2016-10-26 21:25
The same is true for wav attachments. Before joining beta test I was able to 
- open images with QuickPic and 
- wav files with FX media player. 

Now with 5.114 (and previous version) this doesn't work anymore. 
- QuickPic (4.5.2 neutered before cheetah kicked in)  stays empty,
- FX media player says it can't open the file. VLC on the opposite is able to open it.

**Comment by Valodim** [comment] 2016-10-27 18:26
The Byte Mobile thing doesn't support content uris, so that's not relevant for our case.

Spent pretty much all day chasing this, here's what I think is happening in the gallery app:

First, a file descriptor is obtained in [openOrDownloadInner](https://android.googlesource.com/platform/packages/apps/Gallery2/+/jb-dev/src/com/android/gallery3d/data/UriImage.java#103) from the contentresolver, nothing magic there. This FD is passed in [createBitmapRegionDecoder](https://android.googlesource.com/platform/packages/apps/Gallery2/+/jb-dev/src/com/android/gallery3d/data/UriImage.java#171) to [BitmapRegionDecoder](https://chromium.googlesource.com/android_tools/+/18728e9dd5dd66d4f5edf1b792e77e2b544a1cb0/sdk/sources/android-19/android/graphics/BitmapRegionDecoder.java) and from there into a native interface that ends up in [nativeNewInstanceFromFileDescriptor](https://android.googlesource.com/platform/frameworks/base.git/+/android-4.3_r3.1/core/jni/android/graphics/BitmapRegionDecoder.cpp#109). My guess is that the [SkFDStream](https://android.googlesource.com/platform/external/skia/+/eclair-release/src/images/SkFDStream.cpp#32) used in there makes calls to [lseek](http://man7.org/linux/man-pages/man2/lseek.2.html), which are unsupported by the FD we pass because it's not backed by a file.

From what I can tell, there might not be a way around file-backed filedescriptors :(

**Comment by Valodim** [comment] 2016-10-27 19:13
I created a PoC fix for this, which does solve the problem 4aceb251491832e7900a9fc987fa9e26d446b9c7

There are a couple of options here, the easiest way seems to be integrating a simple caching layer into either AttachmentController or AttachmentProvider

**Comment by morckx** [comment] 2016-10-27 19:23
A popular bug on the side of attachment viewer apps seems to be calling InputStream.available()
in order to get the content size. For MuPDF  I sent a corresponding patch:

http://bugs.ghostscript.com/show_bug.cgi?id=696662

which is merged by now. For my personal MuPDF I also added some intent filters so that I can also view jpg, png, tiff, ....

**Comment by gdt** [comment] 2016-11-04 19:44
I built from the attachment-ninjabranch fix.   Now I can click open on images and it works normally, like it used to.   With git master from a few days ago (d0b3caf9768bc6710d9e0702de260a6b73b72995), I still had the bug.

**Closed** 2016-11-08 10:21 UTC
