### ISSUE TITLE
F-Droid: old version suggested

### ISSUE THREAD

**Issue by criwe** [thunderbird/thunderbird-android#5422] opened 2021-07-21 08:23 UTC
**Describe the bug**
On F-Droid an old version (2018) is suggested

**To Reproduce**

Use the app oder visit https://f-droid.org/en/packages/com.fsck.k9/index.html

**Expected behavior**

Newest version should recommended

**Screenshots**
![fdroid](https://user-images.githubusercontent.com/7531138/126455947-20bca9f7-84ff-4cbe-ba68-dad5b0c6ffb2.jpg)

**Comment by cketti** [comment] 2021-07-21 10:40
Duplicate of #4784

**Closed by cketti** 2021-07-21 10:40 UTC
