### ISSUE TITLE
new dark theme is brownish and not black (harder to read)

### ISSUE THREAD

**Issue by ghost** [thunderbird/thunderbird-android#7864] opened 2024-05-22 05:36 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.901

### Where did you get the app from?

Other

### Android version

12

### Device model

samsung a52q

### Steps to reproduce

Old dark theme wasn't pure black and did not support amoled feature, but at least it were easier to read. The new even has even less contrast between the background and the text, making it harder to read.

# new dark theme
![Imagepipe_1](https://github.com/thunderbird/thunderbird-android/assets/15078341/5b3df6fe-7359-44c2-9e2c-fc0c884778ee)

I put the screenshot of the left pane, but the same goes for the messages list and message UI

# old dark theme
![Imagepipe_0](https://github.com/thunderbird/thunderbird-android/assets/15078341/af0566c5-a669-4e6d-ba06-8fd7004735ce)

### Expected behavior

dark theme is close to black

### Actual behavior

Dark theme is brownish

**Comment by wmontwe** [comment] 2024-05-22 12:44
There are some known contrast issues with the new dark color scheme and we're working on a fix.

**Comment by pwd-github** [comment] 2024-05-29 10:14
It should probably be noted that black doesn't fair well with user experience research

**Comment by cketti** [comment] 2024-05-29 10:21
I think it would be helpful to anyone reading this if you provided links to relevant user experience research.

**Comment by pwd-github** [comment] 2024-05-29 10:25
> I think it would be helpful to anyone reading this if you provided links to relevant user experience research.

https://tatham.blog/2008/10/13/why-light-text-on-dark-background-is-a-bad-idea/

https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/

**Comment by MillionsToOne** [comment] 2024-06-05 17:39
That is just pure propaganda from light mode users. Even common sense should tell you to not be on a computer all the time.

**Comment by baccyflap** [comment] 2024-06-06 20:13
The idea that white-on-not-quite-black (or gray-on-white) is somehow more legible than black-and-white is a pervasive one. [This NN article](https://www.nngroup.com/articles/low-contrast/) is the closest thing I could find to a reliable source, though it doesn't explicitly discuss dark mode - it just recommends high contrast overall, much like W3C.

There are some inconclusive small-scale studies which seem to be mostly [from the 90s](http://www.mmeissner.de/AHNCUR.html) and early 2000s, when displays looked rather different. All the rest seems to be down to preference and UX fairystories - talk of 'cool blacks' and 'warm grays', that sort of thing.

**Comment by MillionsToOne** [comment] 2024-07-01 12:09
> > > I think it would be helpful to anyone reading this if you provided links to relevant user experience research.
> > 
> > https://tatham.blog/2008/10/13/why-light-text-on-dark-background-is-a-bad-idea/
> > 
> > https://uxmovement.com/content/why-you-should-never-use-pure-black-for-text-or-backgrounds/
> 
> Pissing off your user base by suddenly changing the look and feel they've used for years also creates a bad user experience. Not everyone will necessarily want to use the "super ergonomic better for your eyes solarized IDE" style option and that's okay, even if using something like the current existing dark mode is slightly more eye straining for them. That is of course even assuming this research is accurate, if I'm recalling correctly a lot of human factors research on eye strain was done during the CRT era, and I'm sure some was done during the LCD era, and now we're split between those and OLEDs so it's not even universal at the moment. It's also worth keeping in mind that most UX research is best practices or guidelines at best, it's rarely by any means definitive so you should always take it with a grain of salt and not try to wield it like a big stick.
> 
> Given that the point of free software is user choice, leaving the traditional dark mode as an option along with one or more ergonomic/accessibility style themes seems like a pretty reasonable middle ground.

All I can say is "Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied."

**Comment by baccyflap** [comment] 2024-07-01 17:40
I'd be interested in an update on this bug, if it's available; the inexplicable brown colouration is driving me a little nuts.

**Comment by MillionsToOne** [comment] 2024-07-01 18:30
> I'd be interested in an update on this bug, if it's available; the inexplicable brown colouration is driving me a little nuts.

It isn't a bug. MD3 and MY is a work-in-progress, so MY colors haven't been merged yet. Otherwise it would use wallpaper colors. You can stay on latest stable release if colors bother you.

**Comment by baccyflap** [comment] 2024-07-01 18:53
Yes sorry, an issue rather than a bug. So once that's finished, it'll use wallpaper colours? That'd solve the issue for everyone, I imagine.

**Comment by MillionsToOne** [comment] 2024-07-01 19:00
> Yes sorry, an issue rather than a bug. So once that's finished, it'll use wallpaper colours? That'd solve the issue for everyone, I imagine.

https://github.com/orgs/thunderbird/projects/4/views/7

In the MD3 section.

**Comment by MillionsToOne** [comment] 2024-07-01 19:01
> Yes sorry, an issue rather than a bug. So once that's finished, it'll use wallpaper colours? That'd solve the issue for everyone, I imagine.

https://github.com/thunderbird/thunderbird-android/issues/6617#issuecomment-2149405793

**Comment by marek22k** [comment] 2024-10-02 09:18
Is there a workaround to remove these ugly sand colors?

**Comment by marek22k** [comment] 2024-10-02 10:51
I use 6.904 from F-Droid. There doesn't seem a new version available.

**Comment by MillionsToOne** [comment] 2024-10-02 13:29
> I use 6.904 from F-Droid. There doesn't seem a new version available.

Use Github releases

**Comment by marek22k** [comment] 2024-10-02 17:19
There is a possibility, but there is a reason why I use F-Droid and not GitHub releases. If you want to deliver updates faster in F-Droid, maybe use reproducible builds.

**Comment by MillionsToOne** [comment] 2024-10-04 08:54
> There is a possibility, but there is a reason why I use F-Droid and not GitHub releases. If you want to deliver updates faster in F-Droid, maybe use reproducible builds.

They're working on Thunderbird also.

**Closed** 2024-10-16 10:57 UTC
Labels: type: UI/UX, tb-team

**Comment by Akselmo** [comment] 2024-10-27 02:16
Any possibility for full-black background color? I find it very helpful on OLED screen because it helps with readability, i tend to need a very high contrast at times.
