### ISSUE TITLE
"reply below quoted text" is visually confusing

### ISSUE THREAD

**Issue by DerDakon** [thunderbird/thunderbird-android#5914] opened 2022-02-13 19:35 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.807

### Where did you get the app from?

F-Droid

### Android version

11

### Device model

Xperia 10 II

### Steps to reproduce

1. Enable "reply below quoted text"
2. Reply to an email

### Expected behavior

The entered "message text" should be below the quoted text.

### Actual behavior

The "message text" is displayed above the quoted text. Everything that is entered there at the end ends below the text. While it makes the editing on mobile screens easier this is confusing.

Editing anything inside the quote works, it is placed there. And then the text entered above the quote is put below the remainder of the quote.

**Comment by cketti** [comment] 2022-02-21 17:09
Duplicate of #2212

**Closed by cketti** 2022-02-21 17:09 UTC
