### ISSUE TITLE
export/import of settings not working (v5.800 and above)

### ISSUE THREAD

**Issue by supervisitor** [thunderbird/thunderbird-android#5602] opened 2021-08-22 13:24 UTC
this is an extension of: https://github.com/k9mail/k-9/issues/4138

**Describe the bug:**
import of settings file (default name: k9_settings_export_202\*-\*\*-\*\*.k9s) is not working

**To Reproduce:**
the way I transfer my settings is:
1. open K-9 (old device Motorola)
2. export setting
3. compress with Amaze
4. send with Blitz Mail
5. save it from desktop Client to disk
6. upload ZIP to web server
7. download it with Lightning Browser to device (new Samsung)
8. extract it with Amaze
9. check file with Acode
10. open K-9 and want import settings
11. not working, get error message:  "Failed to read settings file"

I update the App (from F-Droid) in small steps, to check different verions:
```
source Moto	| destination Sams	| result	| settings file
5.800		| 5.800			| reading error	| "settings5800.k9s"
5.800		| 5.801			| reading error	| same from above
5.801		| 5.801			| reading error	| "settings5801.k9s"
5.801		| 5.802			| reading error	| same from above
5.802		| 5.802			| reading error	| "settings5802.k9s"
5.802		| 5.803			| reading error	| same from above
5.803		| 5.803			| reading error	| "settings5803.k9s"
5.803		| 5.804			| reading error	| same from above
5.804		| 5.804			| reading error	| "settings5804.k9s"
```

**Expected behavior:**
 - all settings importing
 - asking for password of accounts....

**Environment:**
 - K-9 Mail version: 5.800 - 5.804
 - Android version: 6.01
 - Device: source Moto E 2nd Gen LTE, destination Galaxy S5 mini
 - Account type: 9x IMAP

**Logs:**
 - at this point I'm not able to enable logging

**Comment by cketti** [comment] 2021-08-22 13:32
What error message are you seeing exactly?

Developers need to be able to reproduce the error in order to fix it. Your "steps to reproduce" are not helping with that.
We need either a debug log or your settings file. You could manually edit the settings file and remove any privacy-sensitive information. After editing make sure the resulting file still fails to import. If it does, attach the file to this issue.

**Comment by supervisitor** [comment] 2021-08-22 15:06
sorry...  I get every time the error message: "Failed to read settings file"

**Comment by supervisitor** [comment] 2021-08-22 23:27
??? it was in any case more a coincidence than intent!
- I opened out of frustration and boredom "Open Mail" (v5.503), installed sometime ago, I do not remember when it was
- the first start dialog reminded me to K-9 Mail?!
- I decided to press "IMPORT SETTING
- chose the last exported K-9 settings file: "settings5804.k9s"
... worked?!

But why this, OMv5.503 writes k9s file settings v49, K9v5.804 writes file settings v74?
And of course I immediately tried to import the exported v49 configuration file into K-9 Mail v5.804... also no success.

**Comment by supervisitor** [comment] 2021-08-23 00:31
I check some older version of K-9 Mail from F-Droid. The archived version 5.600 can import my "settings5804.k9s" settings file, the next version 5.700 can not. (error message: "Failed to read settings file")

Now my work around is:
 - install v5.600
 - start App and import my last settings file from old device
 - complete all accounts with password
 - now update to v5.700
 - start App and check mails
 - now update to v5.710, v5.721, v5.730, v5.740, v5.800, 5.804 and check mail (I do this in some more smaller steps, because I don't read the change-log/ don't know any about the changes in detail)

It looks like there are some changes at import function since v5.700 which are not working well?!

**Comment by cketti** [comment] 2021-08-23 13:41
The changes between 5.600 and 5.700 contain over one year of development. This doesn't narrow down the list of changes enough to be useful.

Again, we need to be able to tell what's going wrong exactly. K-9 Mail 5.8xx should be able to produce a log that contains enough information to figure out what went wrong (https://github.com/k9mail/k-9/wiki/LoggingErrors). The other option is to send us your settings file, so we can reproduce the bug ourselves.

**Comment by cketti** [comment] 2021-10-05 15:10
Closing this issue because I can't reproduce the problem with the information provided.

If you're reading this because you experience the same bug, please open a new issue and don't forget to provide the requested information (settings file or debug log).

**Closed by cketti** 2021-10-05 15:10 UTC

**Comment by supervisitor** [comment] 2021-10-14 11:07
Sorry, I was not connected to the internet too often for surfing, satellite connection is much more expensive than over broadband... 😇  but one more piece of information: this week I reinstalled K-9 (F-Droid Version 5.904 (29004) 2021-10-09) on another device. I used the file "settings5804.k9s"... and it worked without any problem.

Thanks for everything, K-9, your time... and stay healthy! 😉
