### ISSUE TITLE
Problems opening an email

### ISSUE THREAD

**Issue by lesliepear** [thunderbird/thunderbird-android#1628] opened 2016-09-22 19:35 UTC
### Expected behavior

Able to read an email
### Actual behavior

It showas up as download entire message enabled but clicking on it shows nothing, no matter how big I make the message size. Can't forward it or reply to it either, k9 mail crashes
### Steps to reproduce

1.open this email
2.
3.
### Environment

K-9 Mail version:
5.111
Android version:
6.0
Account type (IMAP, POP3, WebDAV/Exchange):
Imap

**Comment by philipwhiuk** [comment] 2016-09-24 13:03
Please provide the email itself and a debug log.

**Comment by philipwhiuk** [comment] 2016-09-24 13:07
Probable duplicate of #1243

**Comment by lesliepear** [comment] 2016-09-25 11:18
Not sure how to do provide a debug log. I reported it via google play. I also can't get the email easily.

On September 24, 2016 9:03:11 AM EDT, Philip <notifications@github.com> wrote:
>Please provide the email itself and a debug log.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/k9mail/k-9/issues/1628#issuecomment-249363777

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2019-02-28 20:53 UTC
Labels: status: needs information
