### ISSUE TITLE
Crash when completing some addresses

### ISSUE THREAD

**Issue by qwerty287** [thunderbird/thunderbird-android#7671] opened 2024-02-25 18:49 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.603

### Where did you get the app from?

F-Droid

### Android version

12

### Steps to reproduce

1. Write new e-mail
2. Enter some address
3. Searching for some e-mail addresses crashes the app

The addresses that lead to a crash:
- The addresses that lead to a crash: have private keys (they're mine) in openkeychain
- but some addresses with private keys work flawlessly
- disabling e2e doesn't fix the issue
- it always crashes if these addresses would be displayed, i.e. when searching for parts of them
- similar to https://github.com/thunderbird/thunderbird-android/issues/7622, but I have openkeychain 6.0.2

### Expected behavior

No crash, just displaying the addresses

### Actual behavior

Crash

### Logs

```
FATAL EXCEPTION: ModernAsyncTask #1
Process: com.fsck.k9, PID: 2585
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at androidx.loader.content.ModernAsyncTask$3.done(ModernAsyncTask.java:164)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
	at java.util.concurrent.FutureTask.run(FutureTask.java:269)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.lang.IllegalStateException: ResultSet returned more than 1 row for UserPackets.sq:selectUserIdStatusByEmailLike
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2434)
	at android.os.Parcel.createException(Parcel.java:2410)
	at android.os.Parcel.readException(Parcel.java:2393)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:190)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:142)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:481)
	at android.content.ContentResolver.query(ContentResolver.java:1221)
	at android.content.ContentResolver.query(ContentResolver.java:1152)
	at android.content.ContentResolver.query(ContentResolver.java:1108)
	at com.fsck.k9.activity.compose.RecipientLoader.fillContactDataFromCryptoProvider(RecipientLoader.java:232)
	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:202)
	at com.fsck.k9.activity.compose.RecipientLoader.loadInBackground(RecipientLoader.java:37)
	at androidx.loader.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:307)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:60)
	at androidx.loader.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:48)
	at androidx.loader.content.ModernAsyncTask$2.call(ModernAsyncTask.java:141)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	... 3 more
```

**Comment by cketti** [comment] 2024-02-25 21:49
From K-9 Mail's perspective this is a duplicate of #7622. The fix for that issue (currently available in beta) prevents K-9 Mail from crashing in this case, too.

**Closed by cketti** 2024-02-25 21:49 UTC
