### ISSUE TITLE
Cannot configure an email account

### ISSUE THREAD

**Issue by liar666** [thunderbird/thunderbird-android#1658] opened 2016-10-03 09:47 UTC
### Expected behavior

I should be able to enter my username+password and access my emails
### Actual behavior

K9 was installed and working fine. I just "emptied" the application's data to save some space.
Now, K9 starts as if it were freshly installed and asks agains for account configuration. Entering username and password results in application crash.
Even when cleaning data again, removing totally the app and reinstalling it, it still crashes.
Entering a false username/password tuple results in a message "cannot contact server" with a dialog showing options "continue/modify configuration". Both options results in app crash...
### Steps to reproduce
1. clear app data from the android OS menus
2. try to configure an email account
### Environment

K-9 Mail version: latest from PlayStore as of today (2016/10/03)

Android version: 4.4.2

Account type (IMAP, POP3, WebDAV/Exchange):
GMail

**Comment by philipwhiuk** [comment] 2016-10-03 11:27
If you reported the crash then @cketti ought to be able to see a crash log in Google Play.

If not we need the logs to diagnose this.

**Comment by liar666** [comment] 2016-10-03 12:11
I had the crash at least 10 times, I tried twice to report it (I clicked on "report" in the dialog that said "K9-MAil application has stopped / report / close" ; however, I was oriented to a page that asked for a single line of feedback ; not sure if this is what you call a "report")

Otherwise how can I find the logs (NOTE: I removed the app since it is useless to me for the moment)?

**Comment by philipwhiuk** [comment] 2016-10-03 16:15
> I was oriented to a page that asked for a single line of feedback ; not sure if this is what you call a "report"

The line is just extra notes - if you send it we get technical information - i.e. the device logs and basic phone info.

**Comment by liar666** [comment] 2016-10-14 09:06
i still cannot configure an account. I've sent another report this day.... you should now have all the necessary info.

**Comment by liar666** [comment] 2016-10-20 15:48
Tried again today, still not working....

Would it be possible to have at least some feedback: did you receive the reports? Is there anything suspicious in them? What info can I sent to help you find the problem?

Can at least _one_ person just try the reproduce the steps and confirm the bug?
- install k9
- configure an account
- receive/send some mails
- clear app data
(- enventually try to reconfigure an account here => did not work for me; k9 chrashes)
- uninstall app
- reinstall app
- try to configure again the email account (still does not work => k9 crashes)

**Comment by philipwhiuk** [comment] 2016-10-20 16:13
I can't reproduce this in the beta version (5.113). So I expect it will be fixed in the next stable release which will likely be soon.

I have no idea why it would break after installing and re-installing - there is literally no data left following an uninstall.

Regardless, closing as can't reproduce in latest build.

**Closed by philipwhiuk** 2016-10-20 16:13 UTC
Labels: status: needs information

**Comment by liar666** [comment] 2016-10-26 13:00
Just tried with latest version: 5.114, still crashes without possibility to create an account.

I even changed my password to something simpler (only lower case letters & numbers) but still doesn't work.

Have you tried the exact process I have provided (i.e. with cleaning cache and app data, not just reinstalling)?
Have you tried with a gmail account?

Is it possible that OAuth2/(lack of)authorization token from google would be causing the trouble?

**Comment by philipwhiuk** [comment] 2016-10-26 13:31
> Is it possible that OAuth2/(lack of)authorization token from google would be causing the trouble?

This may prevent you signing in, but it shouldn't crash. And yes I tested by clearing cache and app data.

@cketti - have we any crash logs in Google Play?

**Comment by cketti** [comment] 2016-10-26 13:35
@philipwhiuk: Nothing relevant to account setup. But I just noticed that 5.114 wasn't available on Google Play yet. So @liar666 must have sideloaded the APK. In that case crashes wouldn't have been reported to Google Play anyway.

@liar666: Please try to record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors
