### ISSUE TITLE
IMAP Unable to Check the email

### ISSUE THREAD

**Issue by Bob0111** [thunderbird/thunderbird-android#6519] opened 2022-12-09 01:50 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

Lineage OS 19, Android 12

### Device model

Pixel 4

### Steps to reproduce

1. Add an IMAP email account from 126.
2.  Provide correct username and password.
3. Check the email.
4. Nothing happens.

### Expected behavior

Check the email normally.

### Actual behavior

Just blank, nothing happens.

### Logs

12-04 14:40:26.252 7651 7671 E RealImapFolder: Unable to open connection for 51cb515b-4adb-4d70-8256-cbd026613e83:INBOX/MessagingController/conn223192082
12-04 14:40:26.252 7651 7671 E RealImapFolder: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE “INBOX”; response: #6# [NO, EXAMINE Unsafe Login. Please contact [kefu@188.com](mailto:kefu@188.com) for help]
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:119)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:697)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:683)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:84)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:118)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:89)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:81)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:616)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:556)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:528)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
12-04 14:40:26.252 7651 7671 E RealImapFolder: at java.lang.Thread.run(Thread.java:920)
12-04 14:40:26.252 7651 7671 E ImapSync: synchronizeMailbox
12-04 14:40:26.252 7651 7671 E ImapSync: com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: EXAMINE “INBOX”; response: #6# [NO, EXAMINE Unsafe Login. Please contact [kefu@188.com](mailto:kefu@188.com) for help]
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:119)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:697)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.RealImapConnection.executeSimpleCommand(RealImapConnection.kt:683)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.RealImapFolder.executeSimpleCommand(RealImapFolder.kt:84)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.RealImapFolder.internalOpen(RealImapFolder.kt:118)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.mail.store.imap.RealImapFolder.open(RealImapFolder.kt:89)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.backend.imap.ImapSync.synchronizeMailboxSynchronous(ImapSync.kt:81)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.backend.imap.ImapSync.sync(ImapSync.kt:34)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.backend.imap.ImapBackend.sync(ImapBackend.kt:55)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.syncFolder(MessagingController.java:616)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:556)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.lambda$synchronizeMailbox$3(MessagingController.java:528)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.$r8$lambda$ar_6eNiqt1c67rfo1nCyGoIX3Sg(Unknown Source:0)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController$$ExternalSyntheticLambda20.run(Unknown Source:10)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.runInBackground(MessagingController.java:222)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController.access$000(MessagingController.java:108)
12-04 14:40:26.252 7651 7671 E ImapSync: at com.fsck.k9.controller.MessagingController$1.run(MessagingController.java:163)
12-04 14:40:26.252 7651 7671 E ImapSync: at java.lang.Thread.run(Thread.java:920)
12-04 14:40:26.256 7651 7671 E ImapSync: Failed synchronizing folder ybx333@126.com:INBOX @ 周日 12月 04 14:40:26 GMT+08:00 2022

**Comment by Bob0111** [comment] 2022-12-09 01:52
I contact their consumer support, and they say that they will check IMAP id and you should include that in your software.They give an example of the code:
Properties props = new Properties();
props.setProperty(“mail.store.protocol”, “imap”);
props.setProperty(“mail.imap.host”, “[imap.163.com](http://imap.163.com/)”);
props.setProperty(“mail.imap.port”, “143”); HashMap IAM = new HashMap
();
//Provide IMAP ID information, which is consist of key and value，such as name，version，vendor，support-email, etc…
IAM.put(“name”,“myname”);
IAM.put(“version”,“1.0.0”);
IAM.put(“vendor”,“myclient”);
IAM.put(“[support-email","testmail@test.com](mailto:support-email%22,%22testmail@test.com)”);

Session session = Session.getInstance(props);
IMAPStore store = (IMAPStore) session.getStore(“imap”);

**Comment by cketti** [comment] 2022-12-09 10:27
Duplicate of #5089

**Closed by cketti** 2022-12-09 10:27 UTC
