### ISSUE TITLE
Multiple message notification is unreadable when Night Mode active

### ISSUE THREAD

**Issue by robpridham** [thunderbird/thunderbird-android#4079] opened 2019-05-30 10:25 UTC
On my Samsung S9 running Android P, I have enabled Night Mode.

When multiple new emails arrive, and the notification represents them together, the background to the notification and the text on it are both white. Therefore it's unreadable.

This is a recently introduced problem, either from an update to K-9 or a system update on the S9.

### Steps to reproduce
1. Enable Night Mode
2. Receive multiple new emails at once
3. Observe the notification

### Environment
K-9 Mail version: 5.600

Android version: Pie

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![image](https://user-images.githubusercontent.com/26543551/58626802-8bfc8700-82cd-11e9-9758-7ec2b81e94f6.png)

Single notifications still appear OK:

![image](https://user-images.githubusercontent.com/26543551/58626931-dda51180-82cd-11e9-9832-52f2dc780ff7.png)

**Comment by VilleW** [comment] 2019-05-30 10:40
Same problem here. I also have Galaxy S9 running android P. Hope this is fixed soon and the background for multiple emails is changed to dark. It looks better that way.

**Comment by robpridham-bbc** [comment] 2019-05-30 17:05
I tested this against https://github.com/k9mail/k-9/pull/4073 and it still occurs.

**Comment by robpridham-bbc** [comment] 2019-05-30 18:18
I also tested that it wasn't the platform/device, using a quick demo app - `NotificationCompat` and a very similar setup to K9. The grouped notifications appeared correctly, respecting dark mode.

I have briefly looked through the K9 source (I'm a professional Android developer) and I can't see any easy answer to why it appears white.

**Comment by VilleW** [comment] 2019-05-30 19:09
I don't know anything about making apps for android so I can't really help.. I will leave it to those who know how to do it.

**Comment by dannyauble** [comment] 2019-08-19 20:58
I have this problem as well.  I would love it to get fixed :).  I am running on a Galaxy S10+.  When the phone was new this problem didn't exist, but then after a firmware update it started doing it.

**Comment by Maetts** [comment] 2019-11-01 20:46
The issue is still here. Will there be an update soon? I have it on a s10+ too.

**Comment by robpridham-bbc** [comment] 2019-11-02 11:17
@cketti What if anything can I do to support or provide more info into this issue? As above, I'm a professional Android dev.

**Comment by cketti** [comment] 2019-11-02 12:55
@robpridham-bbc: Figure out the problem and propose a fix? I don't have any more information on this than you have, and I can't reproduce it on my devices. From the comments it seems like it's specific to Samsung devices.

**Comment by Maetts** [comment] 2019-11-02 13:14
Let me know what Info you need - I will provide it.

**Comment by robpridham-bbc** [comment] 2019-11-02 14:22
I've tried it from master today, and as expected the fault persists.

I think this is fundamentally a Samsung bug - AFAIK we're all running their version of Pie/9, which has Dark Mode support provided early by bolting it on, rather than the true support in Q/10. What I didn't (and still don't completely) understand is what the difference could be between K9 and other apps that display correctly.

However I have made it work by raising the k9mail targetSdkVersion from 23 to 29.

**Comment by robpridham-bbc** [comment] 2019-11-02 14:31
I incrementally reduced it back down and it only broke when back on 23, at least on my S9, so hopefully that helps you reduce the change impact.

@cketti is this something you think you can action?

**Comment by cketti** [comment] 2019-11-02 15:27
We'll have to raise the targetSdkVersion to 29 anyway to be able to release an update on Google Play. If this will fix the issue, then there's nothing else you need to do. Thanks for investigating this :+1:

**Comment by dannyauble** [comment] 2019-11-02 18:17
This is fantastic news. I can also confirm on the s10+ with beta Android 10 the problem currently goes away without any fix.

**Comment by Maetts** [comment] 2019-11-09 08:07
Thanks for the good news. Since Samsung's release of Android 10 will traditionally take more time - do you have a schedule for the K9 update?

**Comment by oliv3** [comment] 2019-11-30 15:37
I also have this issue with 5.600, Samsung Galaxy A10 with Android Pie.

**Comment by Tobias-B-Besemer** [comment] 2019-12-17 04:44
The issue is now fixed for me on my Samsung Galaxy S9 with K-9 v5.702. Just FYI...

**Comment by robpridham-bbc** [comment] 2019-12-17 11:37
I raised this and I'm also happy to confirm it's fixed for me, as expected since the target version has changed. Thanks for the work.

**Closed** 2019-12-17 12:49 UTC
Labels: status: needs information
