### ISSUE TITLE
k9-mail 5.70x: imap flags not applied for posteo.de accounts (star, deleted etc)

### ISSUE THREAD

**Issue by m1027** [thunderbird/thunderbird-android#4420] opened 2020-01-02 21:03 UTC
Using several IMAP accounts with K-9 5.70x up to 5.703 reveal an issue with
posteo.de accounts only, not the with over providers: You can e.g.  star /
delete / flag mail read but this is not updated to the server. So with each
pull these flags get reverted (thus, no star, not deleted, unread again etc).

This issue was not present in 5.6xx.

**Comment by cketti** [comment] 2020-01-02 21:29
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by m1027** [comment] 2020-01-05 15:47
Voila the log file. To reproduce the issue I did this:

- I starred an unstarred mail (account called 'posteo')
- The mail received a star as expected
- I dragged the mail list to trigger a fresh mail pull
- The starred mail was unstarred again

I see just one potentially important error message:

01-05 16:35:52.849  9037  9059 E MessagingController: Root cause failure in posteo:INBOX was 'NumberFormatException: For input string: "K9LOCAL:8fa1ea34-7c4c-4ffd-8ef8-98eff99be845"'

Thank you so much



[k9-log.txt](https://github.com/k9mail/k-9/files/4023546/k9-log.txt)

**Comment by cketti** [comment] 2020-01-08 00:34
Unfortunately, the most interesting part was not logged. Can you please try to get a complete log of a sync of that folder.

**Comment by m1027** [comment] 2020-01-17 13:56
[k9-log1.txt](https://github.com/k9mail/k-9/files/4077097/k9-log1.txt)
[k9-log2.txt](https://github.com/k9mail/k-9/files/4077098/k9-log2.txt)

I am still on 5.703. And I am on LineageOS, too, as in #4436.

Voila log files again as requested. I wonder though whether they contain more
than the previous log. So, this time, I created two log files like so:

- k9 started
- adb: get pid
- activate star on an email
- wait some seconds
- create log1
- pull mail account for new mail (dragging list downwards)
- wait until completed: no new mail but star removed (=the issue)
- wait some seconds
- create log2

Note: Although the timestamps of log1 overlap log2, log2 does not contain the
content of log1 at that time. Don't know whether that's normal behaviour.

**Comment by m1027** [comment] 2020-01-17 14:02
Mistake: I am on 5.704, not 5.703.

**Comment by cketti** [comment] 2020-01-24 15:57
Again, the interesting part is missing. Try using the following command:

```shell
adb logcat -pid=[PID] > k9-log.txt
```

Do this before you perform any actions inside the app. This will continuously write the log to the file. After some time you can interrupt the logging using CTRL+C.

**Comment by m1027** [comment] 2020-01-25 10:54
This log should probably catch it all now.

What I did as always:

- k9 started
- got pid via adb
- started log as above
- enabled a star on an email (k9 enabled the star and sorted mail to top then)
- dragged list to pull new mail
- result: mail with star lost the star (this is the issue)

As mentioned initially: Other mail accounts on this phone do not have that issue.

[k9-log.txt](https://github.com/k9mail/k-9/files/4111943/k9-log.txt)

**Comment by cketti** [comment] 2020-01-25 18:06
Thanks. Now the log contains the full stack trace.

This is similar to #4436 in that there's a command stuck in the command queue. In this case the data describing the command seems to contain a local UID (which it shouldn't).  I don't know how this happened. There's code in place to prevent exactly that.

For now there's no way to remove the command from the queue. Please remove the account from K-9 Mail and add it again. You can use the import/export functionality for this.

Closing this issue because I can't reproduce it. We'll add more checks in the future to catch cases like this before inserting commands into the queue. Hopefully that will point to the source of the problem when this happens again.

**Closed by cketti** 2020-01-25 18:06 UTC
Labels: status: needs information

**Comment by m1027** [comment] 2020-01-25 20:12
Hoooray, fixed! Thank you so much
