### ISSUE TITLE
Change initials

### ISSUE THREAD

**Issue by UserX404** [thunderbird/thunderbird-android#8550] opened 2024-11-11 16:15 UTC
Is it possible to change the acounts initials at the overview.
I have multible acounts from the same domain and it's hard to differ.
![Screenshot_20241111-170944_K-9 Mail](https://github.com/user-attachments/assets/c86ca6d9-4506-47f8-ad9a-5a898cd31e08)

**Comment by kewisch** [comment] 2024-11-12 11:42
Duplicate of #8381

**Closed by kewisch** 2024-11-12 11:42 UTC
