### ISSUE TITLE
windows 1252 encoding issue?

### ISSUE THREAD

**Issue by RenaldoB** [thunderbird/thunderbird-android#2090] opened 2017-01-18 13:54 UTC
### Expected behavior
moving from gmail to k9 v5.202 we expected to and from addresses to render correctly.

### Actual behavior
some addresses in the to and from fields of a given mail are rendered as if they havent been decoded i.e. 
"=?Windows-1252?Q?insertnamehere?....".
pressing show headers shows what appears to be valid information however when replying to these mails sending fails due to an invalid address.
Connecting to the same IMAP service via gmail does not cause the same issue.
### Steps to reproduce
1.
2.
3.

### Environment
K-9 Mail version:5.202

Android version: various versions of 6

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by Valodim** [comment] 2017-01-18 14:02
This is caused by missing support for RFC 2231, see #1466. These are fairly rare in my perception which is why we havn't assigned this very high priority. Can you say which mail client produces these values?

**Comment by RenaldoB** [comment] 2017-01-18 14:19
The crux of the issue is that we provide an IMAP service to certain clients and while we haven't made explicit changes to the encoding they are asserting that the version update has caused this to start occurring with "all" of their incoming mails.

**Comment by Valodim** [comment] 2017-01-18 14:27
It seems I mixed this up, this is actually just RFC 2047 encoding, and we should have support for that. We'll look into it, thanks for reporting!

**Comment by Valodim** [comment] 2017-01-18 19:55
I tested with this exact mail:

```
From: =?Windows-1252?Q?Keith_=97_Moore?= <moore@cs.utk.edu>
To: =?ISO-8859-1?Q?Keld_J=F8rn_Simonsen?= <keld@dkuug.dk>
CC: =?ISO-8859-1?Q?Andr=E9?= Pirard <PIRARD@vm1.ulg.ac.be>
Subject: =?ISO-8859-1?B?SWYgeW91IGNhbiByZWFkIHRoaXMgeW8=?=
    =?ISO-8859-2?B?dSB1bmRlcnN0YW5kIHRoZSBleGFtcGxlLg==?=
```

and it all looked just fine for me, reply and everything also worked. Can you provide me with an email that exhibits the problematic behavior?

**Comment by RenaldoB** [comment] 2017-01-19 09:18
I am conferring with my superiors on that for you, I have included a
screenshot in the mean time if that helps. Also, some of the fields
displaying like this appear to be utf-8.

Thanks,
Renaldo Beck

**Comment by Valodim** [comment] 2017-01-19 11:45
Screenshots attached to mails are not shown on github, please try again through the web interface

**Comment by cketti** [comment] 2017-02-06 04:22
No additional information provided.

**Closed by cketti** 2017-02-06 04:22 UTC
Labels: status: needs information
