### ISSUE TITLE
Unable to attach a file with v6.701

### ISSUE THREAD

**Issue by franco27** [thunderbird/thunderbird-android#6865] opened 2023-05-01 22:23 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

v6.701

### Where did you get the app from?

Other

### Android version

10

### Steps to reproduce

1. I click on the button to write a new message.
2. I write my message.
3. I want to attach a PDF file or image file
4. After selecting the file in Android file manager, when I go back to your app, the message I was writing is gone
In the "draft" folder, the message is not there.

This situation repeats itself every time. And I can't send message with attached file. Because after selecting the file, when I return to your application, the message is lost or no longer displayed.

I specify that with the previous versions, I did not have this problem. This problem also occurs on my two Android phones.

Thanks in advance for fixing this big problem.
I find your app excellent. Thanks for developing it.

### Expected behavior

Normally after selecting the file, I have to go back to the message I was writing and see the addition of the selected file

In order to be able to send the message.
Currently, with v6.701, I return to your application but the message is no longer displayed.
The message is lost.

### Actual behavior

Currently, with v6.701, I return to your application but the message is no longer displayed.
The message is lost.

**Comment by cketti** [comment] 2023-05-02 09:36
Duplicate of #6863

**Closed by cketti** 2023-05-02 09:36 UTC

**Comment by franco27** [comment] 2023-05-02 09:57
The app is still open. (It does not close). I have no app crashes. It is only the message editing window that is no longer displayed.

**Comment by cketti** [comment] 2023-05-02 09:58
Modern Android versions automatically restart the app after a crash. So it looks like the app didn't crash, but it did.
