### ISSUE TITLE
Grouped folders

### ISSUE THREAD

**Issue by galantra** [thunderbird/thunderbird-android#4603] opened 2020-03-11 12:35 UTC
### Expected behavior
There should be groups for all folder categories – i.e., archive, trash, drafts, inbox. Like with the Thunderbird add-on Group Folders

### Actual behavior
There is a common view only for the inboxes.

### Environment
K-9 Mail version: 5.705

Account type: IMAP

PS: I like the latest redesign A LOT

**Comment by ivnmad** [comment] 2023-11-13 23:09
Add more unified folders https://github.com/thunderbird/thunderbird-android/issues/6596

**Comment by cketti** [comment] 2024-06-17 09:59
We'll be using #6596 to track this feature request.

Duplicate of #6596

**Closed by cketti** 2024-06-17 09:59 UTC
Labels: type: enhancement
