### ISSUE TITLE
Notification twice

### ISSUE THREAD

**Issue by phramusca** [thunderbird/thunderbird-android#6539] opened 2022-12-23 18:20 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Moto g50

### Steps to reproduce

Configure a mailbox
Receive some email
Get a notification
Remove notification

### Expected behavior

No more notification for this e-mail 

### Actual behavior

Same notification pops again

**Comment by cketti** [comment] 2022-12-23 19:16
Duplicate of #6426

**Closed by cketti** 2022-12-23 19:16 UTC
