### ISSUE TITLE
Support text formatting

### ISSUE THREAD

**Issue by fallsdevil** [thunderbird/thunderbird-android#7247] opened 2023-10-12 19:28 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.602

### Problem you are trying to solve

I went to respond to an email and I wanted to add a list of simple topics, and since I didn't find that option, I added the format: *

- to stay in this format;
- example.

so it would be cool if it at least supported this simple topic formatting, italics, bold, I couldn't find it so I don't think it exists, plus the email I sent was badly formatted, as the * remained that way, and did not become a list of topics.

![Screenshot_20231012_162346](https://github.com/thundernest/k-9/assets/142761950/3362e735-c6fa-4fe5-843d-3d2f0504f411)

### Suggested solution

markdown support OR a toolbar with these features with a preview of what the final message would look like.

### Screenshots / Drawings / Technical details

As an example of a "toolbar" I will leave this screenshot of an app, which specifically has these options that I mentioned previously.

![Screenshot_20231012_162614](https://github.com/thundernest/k-9/assets/142761950/cbc28af7-d02a-4ef6-af33-945c27b807bf)

**Comment by cketti** [comment] 2024-01-03 14:40
Duplicate of #1745

**Closed by cketti** 2024-01-03 14:40 UTC
Labels: enhancement, unconfirmed
