### ISSUE TITLE
Background Mail Check NOT WORKING

### ISSUE THREAD

**Issue by jorgevierag** [thunderbird/thunderbird-android#7201] opened 2023-09-27 01:45 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

Google Play

### Android version

13

### Device model

M62

### Steps to reproduce

Close app, or not even opening it

### Expected behavior

Should check for emails every 15mins (IT IS CONFIGURED).

### Actual behavior

Absolutetly NO notifications. I have to open the app and manually refresh to get the emails.

**Comment by cketti** [comment] 2023-09-27 12:04
I'm sorry that checking mail in the background is not working for you. But it is very unlikely that this is a bug in the app. The functionality works for most users. When it doesn't, it's usually a configuration issue with the Android version on the device.

Many device vendors use very aggressive energy saving measures that might prevent an app from accessing the network in the background or even running in the background. You might have to specifically allow K-9 Mail to run in the background. See https://dontkillmyapp.com/ for more information.

In case you're manually force stopping the app, don't. This will prevent the app from running (in the background) until you manually start the app again.

You could try using Push to check for new messages. That will start a foreground service which is usually enough to prevent most Android variants from killing the app. See https://forum.k9mail.app/t/how-to-configure-push/1102

In the future please use the [forum](https://forum.k9mail.app/) for reports like this. Closing this issue because it doesn't contain any actionable steps that could be used to reproduce the problem.

**Closed by cketti** 2023-09-27 12:04 UTC

**Comment by HumanMus1c** [comment] 2024-01-11 07:59
> I'm sorry that checking mail in the background is not working for you. But it is very unlikely that this is a bug in the app. The functionality works for most users. When it doesn't, it's usually a configuration issue with the Android version on the device.我很抱歉在后台查收邮件对你不起作用。但这不太可能是应用程序中的一个 bug。该功能对大多数用户都适用。如果没有，通常是设备上 Android 版本的配置问题。
> 
> Many device vendors use very aggressive energy saving measures that might prevent an app from accessing the network in the background or even running in the background. You might have to specifically allow K-9 Mail to run in the background. See https://dontkillmyapp.com/ for more information.许多设备供应商使用非常积极的节能措施，可能会阻止应用程序在后台访问网络，甚至在后台运行。您可能必须特别允许 K-9邮件在后台运行。更多信息见 https://dontkillmyapp.com/。
> 
> In case you're manually force stopping the app, don't. This will prevent the app from running (in the background) until you manually start the app again.如果你手动强制停止应用程序，不要。这将阻止应用程序运行(在后台) ，直到您手动重新启动应用程序。
> 
> You could try using Push to check for new messages. That will start a foreground service which is usually enough to prevent most Android variants from killing the app. See https://forum.k9mail.app/t/how-to-configure-push/1102您可以尝试使用 Push 来检查新消息。这将启动一个前台服务，这通常足以防止大多数 Android 变体杀死应用程序。Https://forum.k9mail.app/t/how-to-configure-push/1102
> 
> In the future please use the [forum](https://forum.k9mail.app/) for reports like this. Closing this issue because it doesn't contain any actionable steps that could be used to reproduce the problem.以后这样的报道请使用论坛。关闭此问题是因为它不包含任何可用于重现问题的可操作步骤。

Not working on HarmonyOS4. Still couldn't receive new email notification from background.
