### ISSUE TITLE
Gmail fails to properly login after importing from a file when alongside a Outlook account

### ISSUE THREAD

**Issue by VladLucaci** [thunderbird/thunderbird-android#8209] opened 2024-10-01 13:10 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

8.0b1

### Where did you get the app from?

Google Play

### Android version

14

### Device model

Galaxy Fold 4

### Steps to reproduce

1. Launch the application (no accounts previously added)
2. Select Import Settings
3. Choose Select File
4. Pick the desired import file
5. Choose a Google and a Microsoft account
6. Sign into selected Google account
7. Select OK(after going through Google permissions)
8. Allow everything on the Contacts/Notifications screen

### Expected behavior

All of the emails and folders from both accounts are properly loaded and displayed.

### Actual behavior

Only the Microsoft account emails and folders are displayed.

### Logs

[k9mail-accounts.txt](https://github.com/user-attachments/files/17209836/k9mail-accounts.txt)

https://github.com/user-attachments/assets/8fe48a09-ed2c-48c5-9f25-f06d82852f06

**Comment by nekoedges** [comment] 2024-10-03 15:16
Same issue

**Comment by imjuzcy** [comment] 2024-10-04 04:32
Have you tried the steps I posted on #8194? Sounds like it's the same issue.

**Comment by nekoedges** [comment] 2024-10-04 16:32
It doesn't help, looks like the problem is with google auth

**Comment by derkrasseleo** [comment] 2024-10-16 18:43
I also get constant "Authentication failed" notifications for my gmail accounts

**Comment by cketti** [comment] 2024-10-16 19:08
This should be fixed in 8.0b3. If it's not, please create a new issue with detailed steps on how to reproduce.

**Closed by cketti** 2024-10-16 19:08 UTC
