### ISSUE TITLE
Encryption provider not found

### ISSUE THREAD

**Issue by roelfrenkema** [thunderbird/thunderbird-android#6818] opened 2023-04-13 10:57 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.400

### Where did you get the app from?

F-Droid

### Android version

12 stock

### Device model

Motorola edge

### Steps to reproduce

Write mail from account with key. Press send

### Expected behavior

Sending signed mail

### Actual behavior

Giving an error saying encryption provider not found.
if I go to setting and choose openpgp again then it will sent

**Comment by life777eternal** [comment] 2023-04-17 22:25
Is this similar to the toast message that appears saying, "Cannot connect to crypto provider..." ?

I've noticed this appear after opening a new email by hitting an email link on Google play to contact the developer. Then the email can't be saved. 


![obscura1681769829915_1](https://user-images.githubusercontent.com/25623649/232623409-42ffae4c-e38c-437d-8619-e97e99ebdac3.jpg)

**Comment by williamdes** [comment] 2023-04-24 22:46
I have the same issue, previously while replying to an email I would copy the text, abort the email and do reply paste and send it with success. 
I found another less complicated workaround, remove the receiver email (J on the screenshot), and add it back.

Its been quite some versions since it occurs, I am always on the latest one and it still exists. 

![Screenshot_2023-04-25-00-39-39-984_com fsck k9](https://user-images.githubusercontent.com/7784660/234132030-cf78c14e-bc94-4148-98e3-dbcb2ecd4eef.jpg)

**Comment by cketti** [comment] 2023-04-25 13:05
Duplicate of #6068

**Closed by cketti** 2023-04-25 13:05 UTC
