### ISSUE TITLE
Non-existent folder in PendingMoveOrCopy

### ISSUE THREAD

**Issue by larjona** [thunderbird/thunderbird-android#4436] opened 2020-01-10 11:36 UTC
Note: maybe related or duplicated with #4420 , but opening a new issue since I'm not sure.

Hello,
Thanks for working and offering k-9 mail, it's very useful piece of software.
I use the F-Droid version and recently upgraded from 5.600 to 5.700 (and then the next ones. Currently I'm using 5.703).

I use K-9 in telephone with Lineage 14 (Android 7.1.2), and I have several IMAP accounts configured.
For one of them, I'm experiencing an issue: when I mark as read a message, or I open to read it, it appears as "read" in K-9, but it seems that such status does not propagate to the server: when I refresh or obtain new mail, the messages that I've read in K-9 become "unread" again.

If I do the opposite (mark a read message as "not read"), when I refresh, the message becomes "read" again.

The same happens when I star/unstar a message.

I'm attaching a log of the action of reading several mails, and then, refreshing to receive new mail if available.

[k9-log-failure.txt](https://github.com/k9mail/k-9/files/4045387/k9-log-failure.txt)

The strange thing is that this happens only with this account (which receives dozens of mails daily). I have another account configured with much less traffic (1-2 mails each several days) and I cannot reproduce the problem in this second account. Both accounts are from the same provider (Gandi).

I have tried to uninstall K-9 and install again, and configure the account manually, but the problem persist. I have reviewed all the settings (general and account settings) to try to figure out if it was some setting by mistake, but I cannot find anything related to the issue.

Thanks!

**Comment by cketti** [comment] 2020-01-11 17:27
There's a command repeatedly failing and blocking the queue of remote operations to perform. The command is referencing a non-existent folder. We need to find out how that happened.

The other bug is that we don't remove the failing command from the queue. That's bad because it leads to the behavior you're observing. On the other hand, it's probably the only way we learn about the bug that caused this situation in the first place.

Can you please post a screenshot of 'Settings > [affected account] > Folders' (scrolled down so the special folders are visible).

**Comment by larjona** [comment] 2020-01-11 20:22
Attached you can find my settings.

I have tried to change Drafts and Spam to "Automatic (none)" and then marked some messages as read, refreshed, and they turned to be unread (so the issue persists).

Kind regards
Laura Arjona Reina
https://wiki.debian.org/LauraArjona
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by cketti** [comment] 2020-01-12 12:22
You need to use GitHub's web UI in order to add attachments.

**Comment by larjona** [comment] 2020-01-13 14:37
Apologies, I didn't know. Trying again...

**Comment by larjona** [comment] 2020-01-13 14:38
![Screenshot_20200111-211559](https://user-images.githubusercontent.com/1420240/72264246-b3188680-361a-11ea-820a-ab482e66c52f.png)
![Screenshot_20200111-211550](https://user-images.githubusercontent.com/1420240/72264266-bc095800-361a-11ea-9e4a-124dd0a68df9.png)
Apologies, I didn't know. Trying again...

**Comment by cketti** [comment] 2020-01-13 15:10
Thanks.

Steps to reproduce:
1. Set 'When I delete a message' to 'Delete from server' (this is the default)
2. Set 'Trash folder' to 'None' (this might happen automatically if there's no Trash folder on the server)
3. Delete a message

**Comment by larjona** [comment] 2020-01-14 07:00
Hello



El 13 de enero de 2020 16:10:53 CET, cketti <notifications@github.com> escribió:
>Thanks.
>
>Steps to reproduce:
>1. Set 'When I delete a message' to 'Delete from server' (this is the default)

This was my configuration.

>2. Set 'Trash folder' to 'None' (this might happen automatically if there's no Trash folder on the server)

I've done this (in fact, I've set all the folders to the default)


>3. Delete a message
>

Deleting a message works (it was working before, too). But 'read' messages become 'unread'.

I'll configure 'another' account with all the default settings, pointing to the same mailbox, and see what happens.

Kind regards

Laura Arjona Reina
https://wiki.debian.org/LauraArjona
-- 
Enviado desde mi dispositivo Android con K-9 Mail. Por favor, disculpa mi brevedad.

**Comment by larjona** [comment] 2020-01-14 13:39
When I configured another account in K-9 pointing to the problematic mailbox, and synced, the deleted messages were downloaded. So yes, there was indeed an issue with the deleted messages.
However, I indeed have a "Trash" folder in my inbox in my server. I logged in using the webmail service from account provider and I can see "Trash" (with the icon of the Trash bin) and another folder called "Papelera" (Trash bin in Spanish). From the webmail, when I delete a message, it's moved to the Trash folder. I have synced then my K-9 account and I can see the message I deleted from the webmail.
Now, if I delete a message from the Inbox in K-9, it disappears from inbox but it goes "nowhere" (I cannot see the message in Trash nor in Papelera). And it's not synced with the server.

If I go in K-9 to settings, manage folders and assign Trash to the Trash folder (instead of "Automatic(none)"), when I delete a message from K-9 it goes to the trash folder, but it's not synced with the server. When I delete a message in Webmail, it comes to the Trash folder in K-9 too, though.

HTH

**Comment by ByteHamster** [comment] 2020-01-14 13:46
> The other bug is that we don't remove the failing command from the queue. That's bad because it leads to the behavior you're observing. On the other hand, it's probably the only way we learn about the bug that caused this situation in the first place.

What about storing the number of failures together with a command? If a command fails many times, force a full sync and display a notification with the bug description. I somehow got into the same situation running an earlier version of the "mark as read when deleting" PR. I was quite confused for a week because the behavior felt really random. I fear that most users would go and look for another email app instead of reporting the bug if they faced this behavior.

**Comment by cketti** [comment] 2020-01-14 15:00
@ByteHamster: I created issue #4450 for this. Please add your comments there.

@larjona: The fix in #4447 will be included in the next beta version. It will prevent inserting the particular command that is blocking your command queue forever (see #4450 if you're interested in more details on the pending command queue).
However, it will not fix your current account. You'll have to remove the account and set it up again in order to get rid of the command stuck in the queue.

> Now, if I delete a message from the Inbox in K-9, it disappears from inbox but it goes "nowhere"

If K-9 Mail doesn't detect a Trash folder and isn't configured to use one manually, deleting a message in K-9 Mail will remove it from the server.

> If I go in K-9 to settings, manage folders and assign Trash to the Trash folder (instead of "Automatic(none)"), when I delete a message from K-9 it goes to the trash folder, but it's not synced with the server.

This should work if there's not already a command stuck in the pending command queue.

**Closed** 2020-01-14 15:10 UTC
