### ISSUE TITLE
Crash viewing an application/pgp message

### ISSUE THREAD

**Issue by norbusan** [thunderbird/thunderbird-android#1271] opened 2016-04-11 08:08 UTC
Hi Philip,

as discussed on the mailing list, here a crash log. To repeat: I have a message with

```
Content-Type: application/pgp; format=text; x-action=encrypt
```

where opening the message consistenly crashes K9, version 5.108

Hope the log helps, let me know if you need any testing.

Norbert

[k9-crash-log.txt](https://github.com/k9mail/k-9/files/212533/k9-crash-log.txt)

**Comment by philipwhiuk** [comment] 2016-04-11 08:58
So from the stacktraces:

The message is badly parsed/unsupported. Why this is I'm not sure off the top of my head - maybe @Valodim might know if we support this content-type. We definitely want to I think.

**Supporting this content-type should be the focus for the issue.**

But this puts us in the situation fixed by #1205 which causes the actual crash - we'll show a blank message and a toast in the next release.

Interestingly we then see a database error: 

```
java.lang.IllegalStateException: attempt to re-open an already-closed object: 
SQLiteQuery: SELECT m.id AS id,uid,internal_date,subject,date,sender_list,to_list,
cc_list,read,flagged,answered,forwarded,attachment_count,folder_id,preview_type,
preview,root,name 
FROM threads t JOIN messages m ON (m.id = t.message_id) 
LEFT JOIN folders f ON (m.folder_id = f.id) 
WHERE root = ? AND deleted = 0 AND empty = 0 
ORDER BY date DESC, m.id DESC
```

I might open a separate issue for that one.

We also hit #1245 and see another crash in the AccountSettings (that's probably another new issue).

Thanks for the log!

**Comment by norbusan** [comment] 2016-04-11 09:01
If you are interested I can put up the email including headers, slightly edited only.

**Comment by philipwhiuk** [comment] 2016-04-11 12:12
I'm not sure we'll learn much more from the headers. I think I'm not going to worry too much about the SQL error - I assume it's caused by the prior crash.

**Comment by Valodim** [comment] 2016-05-13 13:17
Can reproduce the crash on v5.108, but on current master it already gets a more correct "Unable to read message" toast. For the record, where it crashed was [here](https://github.com/k9mail/k-9/blob/5.108/k9mail/src/main/java/com/fsck/k9/mailstore/LocalMessageExtractor.java#L529).

**Comment by Valodim** [comment] 2016-05-13 22:02
Simple fix to treat this type of message as text for pgp/inline purposes.

One design decision might be relevant here: Should I also check for the format=text parameter? This seems to be a mutt-specific deal and the parameter is always there for those. Is there a case where anything application/pgp should *not* be checked if it's pgp content, i.e. treated as pgp data iff it begins with `-----BEGIN PGP MESSAGE-----`?

**Closed** 2016-07-01 08:30 UTC
