### ISSUE TITLE
Attachment Location Is Horrible User Experience

### ISSUE THREAD

**Issue by DPineault** [thunderbird/thunderbird-android#8523] opened 2024-11-06 16:06 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.0

### Problem you are trying to solve

Having the attachments at the bottom is an absolute horrible user experience.

When dealing with long threads, having to scroll, and scroll, and scroll some more is just tedious.

It is so annoying that I have reverted back to my previous e-mail client and will wait and see if this gets addressed or not.

### Suggested solution

Attachments should be located at the top above the actual message body.  Perhaps some accordion style area with a drop-down arrow.

**Comment by kewisch** [comment] 2024-11-06 19:29
Duplicate of #7364

**Closed by kewisch** 2024-11-06 19:29 UTC
Labels: type: enhancement, unconfirmed

**Comment by DPineault** [comment] 2024-11-06 22:05
Sad.  UI/User Experience should be the main focus of any app and this is a MAJOR problem which could easily be addressed.

I was seriously happy to see an android version of Thunderbird, but this is a deal breaker and there are a few other issues, but this one is big.

Uninstalled.
