### ISSUE TITLE
Deleted emails not deleting from server

### ISSUE THREAD

**Issue by ARenko12** [thunderbird/thunderbird-android#8389] opened 2024-10-22 17:51 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

Thunderbird for Android

### App version

6.804

### Where did you get the app from?

Google Play

### Android version

Android Version 14

### Device model

Google Pixel 7

### Steps to reproduce

Delete email from inbox

### Expected behavior

I expected the email will delete from my server (earthlink.net)

### Actual behavior

The emails are not deleting from the server - they are remaining in the earthlink webmail inbox.

This used to work fine when I used POP3, but I changed to IMAP in order to create some folders.  Since then the emails do not delete from the server.

### Logs

[k9mail-logs.txt](https://github.com/user-attachments/files/17480279/k9mail-logs.txt)

**Comment by christiancabrero** [comment] 2024-10-24 12:16
I confirm it. It happens with Gmail, Outlook and third party servers. Does not delete or sync read emails.
Version 8.0b4 play store, Android 14, Xiaomi Mix Fold 4.

**Comment by cketti** [comment] 2024-10-24 12:29
The log from the original report suggests this is a duplicate of #7818.

@christiancabrero: What you're experiencing is probably a different problem. Please create a new issue and include a debug log.

Duplicate of #7818

**Closed by cketti** 2024-10-24 12:29 UTC

**Comment by ARenko12** [comment] 2024-10-24 13:37
I don't get it. I just signed 2 days ago. I didn't even know how to create a log before. This is not a duplicate post.

**Comment by cketti** [comment] 2024-10-24 13:59
"Duplicate" as in "this problem was reported before" (by someone else). Please read the comments in issue #7818. The problem should no longer be present in recent beta versions.

**Comment by ARenko12** [comment] 2024-10-24 14:20
Ok. I misread that you were telling christiancabrero he had a different problem and submit a new log. Thought that was meant for me and got confused. Thanks for your help.

**Comment by ARenko12** [comment] 2024-10-24 17:16
One more question...

I signed up on Google Play to be a beta tester. It says future updates will include beta versions. How do I get the current beta version? Google Play says go to for you and apps in development to get it, but I can't find apps in development.
