### ISSUE TITLE
tree folder view

### ISSUE THREAD

**Issue by 532910** [thunderbird/thunderbird-android#5011] opened 2020-10-16 07:31 UTC
The current flat folders view looks ugly and uninformative:

![image](https://user-images.githubusercontent.com/14617699/96226097-cc2fd880-0f9a-11eb-9a1a-f7d8ec8bbc66.png)

Compare with thunderbird for example:
![image](https://user-images.githubusercontent.com/14617699/96225911-79562100-0f9a-11eb-8fb2-887c0d875a20.png)

**Comment by cketti** [comment] 2020-10-16 10:24
Duplicate of #630

**Closed by cketti** 2020-10-16 10:24 UTC

**Comment by 532910** [comment] 2020-10-16 10:56
Sorry, I missed it.
