### ISSUE TITLE
Bars disappear

### ISSUE THREAD

**Issue by levinuss** [thunderbird/thunderbird-android#1671] opened 2016-10-05 18:16 UTC
### Expected behavior

When I open a mail the action bar, the 'header', the navigation bar at the bottom of the screen and the mail content should be loaded.
### Actual behavior

The header and the content loads but the action bar and the navigation bar are buggy. They disappear and instead, there is some part of the mail content shown. (see picture).
The Buttons are klickable but invisible.
This behavior doesn't appear in every mail I open, but after opening 5-7 mail I got every time one thats buggy. It seems to be independently from the mail content, if I re-open a buggy mail the behavior isn't the same.
Some times it happens instantly after opening the mail, some times after scrolling.
Some times only the action bar disappears.
[Here's the debug log.](http://pastebin.com/PZ0Yfiu1) In my view there is nothing helpful documented. What you can see is, that I try to open some mails, and that's it, actually.
The screenshot is taken from the german version of the "New twitter ToS" mail.
### Steps to reproduce
1. Open some mails
2. scroll through them and wait for it.
### Environment

K-9 Mail version: 5.111 (screens from 5.111, logs from 5.112, but behavior exactly the same)

Android version: 7.0 on Nexus 5X

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

![k9 screen](https://cloud.githubusercontent.com/assets/12646813/19125703/5e2e3984-8b38-11e6-976d-e175df2886e7.jpg)

**Comment by philipwhiuk** [comment] 2016-10-06 00:03
I've seen this. I'm suspicious it might be a Nougat bug but we should look at it anyway.

**Comment by cketti** [comment] 2016-10-06 00:14
I've seen this on Android 6.0, too. Maybe a WebView bug?

**Comment by webratte** [comment] 2016-10-06 04:24
Android 6.0.1
Also to me.

In Mail view window it not happens if I set in settings "show pitures" to "always" or click the butten "show pictures" in the Mail view.

I have tested it with notification Mails from Github.

**Comment by levinus** [comment] 2016-10-06 05:12
I can confirm that the bug only appears when there are external images that aren't loaded (In my test just now). If I load them through the button the bars are back as usual.

**Comment by gadgetfan10** [comment] 2016-10-06 22:47
On Android 6.0, too. I'd hoped the latest beta would fix it, but no such luck.

Thanks, @levinus for connecting this to loading of external images. I hadn't made that connection, but it seems to be legitimate.

**Comment by werano** [comment] 2016-10-07 09:49
the V5.113 still has the problem

**Comment by Ketrel** [comment] 2016-10-07 13:47
Can also confirm with 5.113 on Nexus 5 with Android 6.0.1

**Comment by levinus** [comment] 2016-10-14 14:37
I've got the bug also in a mail without external images.
[Screenshot is here](https://cloud.githubusercontent.com/assets/12646813/19391251/0e3d2e1c-922c-11e6-971e-17ff8575c022.jpg), sorry that I had to censor so much, but I think you can see what the problem is.
It seems that the action bar shows somethink from the header of the mail, the bottom is empty.

**Comment by werano** [comment] 2016-10-14 15:40
the bug is still present, also in the v5.114

**Comment by philipwhiuk** [comment] 2016-10-14 19:36
Yeah we've not really investigated this one yet. I've seen it myself but it's difficult to determine why :(

**Comment by webratte** [comment] 2016-10-28 16:14
I'm not sure.
But it seems this problem is fixed in K-9 Mail Version: 5.114.

Mayby by chance?

Since I have isntalled the current Version it's not happens anymore for me.

Can someone confirm that?

**Comment by Ketrel** [comment] 2016-10-28 16:38
It still occurs on 5.114

It's just sporadic.

**Comment by moshpirit** [comment] 2016-12-08 12:54
Also is present on 5.115 (F-Droid) on my Android 6.0.1 (Official ROM)

**Comment by duncan-SF** [comment] 2017-02-15 22:36
I recently updated from K-9 Mail_5.006.apk to K-9 Mail_5.203.apk and see this new bug too on my Samsung (Unlocked/T-Mobile) Tab3 running KitKat [4.4.4].  Another device running K9v5.010 on 4.4.2 does not show this bug.

I have one message which seems to trigger this bug reliably.  The sequence appears to be:
1. The message is drawn as it should be when I tap it on the message list.
2. A scroll bar appears.
3. The scroll bar, message header and message toobar all go away.
4. One, both or neither of the message header and toolbar may reappear.

A workaround is to switch to another app (long-press Home) and switch back.
Another workaround is to press the button you want during the fraction of a second before it goes away.
As noted above, the invisible action buttons are still pressable, which can be destructive depending on what I might have in that bar.

Tried to submit screenshots of a message with either or both parts missing.  "Something went really wrong, and we can't process that file."  Haven't been able to read Android logs since my 2.3.4 handset died.  Hopefully the event sequence described above is helpful.

**Comment by philipwhiuk** [comment] 2017-02-16 10:54
This has probably become more common but clearly has existed for a long time. I've closed the other one as dupe (though it may have useful information to a developer trying to fix it).

**Comment by JDJADU** [comment] 2017-03-07 06:49
In the Release  notes 5.204:
* Improved support for messages that didn't display correctly

Why this release and/or the following release 5.205 is still missing on Google Play?

**Comment by cketti** [comment] 2017-03-11 13:02
This bug is still open. Neither 5.204 nor 5.205 will fix it.

**Comment by amunizp** [comment] 2017-03-24 09:48
f-droid 5.206 has it in my Motorola G Phone running 4.4.4  but I have never seen it in tablet Samsung galaxy 3 might be due to form factor?

**Comment by moshpirit** [comment] 2017-03-24 10:29
Asked on GNU social and got a similar response,I think it's an Android 5+ issue.

**Comment by ssb22** [comment] 2017-12-29 21:27
Sorry to say this issue is still present in K9 5.400 on Android 4.4.

**Comment by JDJADU** [comment] 2017-12-30 07:02
Yes I must confirm that the bar is still disappearing. The bug is repeatable I don't know why it's not corrected. 
Jan Dudek 


-------- Původní zpráva --------
Odesílatel: "Silas S. Brown" <notifications@github.com>
Odesláno: 29. prosince 2017 22:27:10 CET
Komu: k9mail/k-9 <k-9@noreply.github.com>
Kopie: JDJADU <dudek@jadu.cz>, Comment <comment@noreply.github.com>
Předmět: Re: [k9mail/k-9] Bars disappear (#1671)

Sorry to say this issue is still present in K9 5.400 on Android 4.4.

**Comment by amunizp** [comment] 2018-02-12 01:18
I have now changed to lineageOS android 7.1.2 and k9 5.403.

I can no longer replicate the issue.

**Comment by JDJADU** [comment] 2018-02-12 06:08
I think that this problem is only on Android 4.4


Od: "Andres Muniz Piniella" notifications@github.com
Komu: "k9mail/k-9" k-9@noreply.github.com
Kopie: "JDJADU" dudek@jadu.cz,"Comment" comment@noreply.github.com
Datum: Sun, 11 Feb 2018 17:18:11 -0800
Předmet: Re: [k9mail/k-9] Bars disappear (#1671)


I have now changed to lineageOS android 7.1.2 and k9 5.403.
I can no longer replicate the issue.

**Comment by ssb22** [comment] 2018-02-12 07:53
Reproduced on Android 4.4 (Xperia Z Ultra) and Android 4.1 (Galaxy S2).  I have not been able to test on Android 5 or later.

**Closed** 2019-02-28 21:10 UTC
