### ISSUE TITLE
Cancelling Compose window not always requesting 'Save As Draft' option

### ISSUE THREAD

**Issue by jimimaseye** [thunderbird/thunderbird-android#2433] opened 2017-03-23 17:26 UTC
THIS IS THE SAME AS #2120 (for v5.203) but that is closed and I dont know how to append/reopen.  This now applies to v5.206.

I confirm that the problem now resides on **5.206** despite supposed fix being 'applied' in 5.204.

"Save As Draft" offering is inconsistent.

### Expected behavior
When browsing, for example the GALLERY on the device, and choosing a picture to 'share' through K9, a new email is generated with the photo attachment.  If the 'return'/back out button is pressed on the device, K9 prompts "Save as Draft or Discard" (allowing saving as draft).

### Actual behavior
If a fresh email is composed **from WITHIN** K9, and the  'return'/back out button is pressed, the email is unceremoniously discarded and no option to Save As Draft is offered.

### Steps to reproduce
As above

### Environment
K-9 Mail version: 5.206

Android version:  4.2.1

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by philipwhiuk** [comment] 2017-03-23 18:07
Your expected behaviour and actual behaviour contain different reproduction steps. Please clarify the steps being done where the bug occurs.

**Comment by jimimaseye** [comment] 2017-03-23 19:34
Sorry, yeah, I can see the confusion.

EXPECTED BEHAVIOUR:

new email
add gallery photo as attachment
press back
Expect "Save As Draft" option.  (as it does When creating an email with a SHARE WITH k9 against a gallery picture).

ACTUAL BEHAVIOUR:
new email
add gallery photo as attachment
press back
Email is simply discarded! No warning.

**Comment by NGimhana** [comment] 2017-03-25 02:15
I am not sure on this bug. When proceeding above steps the actual behavior is already there I think. Not just discarding at once.

**Comment by majeedk526** [comment] 2017-03-25 09:00
The issue persists in the released version of 5.206. However, this seems to have been fixed now. There has been onAttachmentAdded() method implemented int the MessageCompose.java file which takes care of this issue.

**Comment by philipwhiuk** [comment] 2017-03-25 10:28
Closing as duplicate because this is not a new bug it's just the fix hasn't been released.

**Closed by philipwhiuk** 2017-03-25 10:28 UTC
