### ISSUE TITLE
New feature proposal: Show new mail instead of unread mail (notification)

### ISSUE THREAD

**Issue by ProfPh** [thunderbird/thunderbird-android#2414] opened 2017-03-20 23:23 UTC
### Expected behavior
If I have K9mail check for new messages every 60 mins, it comes back every 60 mins saying 100 unread messages. I would have thought the expected/desired behaviour is to say 1 new message (since last sync) or don't notify if 0 new messages since last sync.

### Actual behavior
There is no such button.

### Environment
K-9 Mail version: 5.203

Android version: 6.0.1

**Comment by rishsethia** [comment] 2017-03-23 07:39
Hi , I want to work on this !

**Comment by ProfPh** [comment] 2017-04-11 18:33
@rishsethia great!

**Comment by cketti** [comment] 2019-02-28 23:16
Duplicate of #2018

**Closed by cketti** 2019-02-28 23:16 UTC
Labels: type: enhancement
