### ISSUE TITLE
K9 Mail won't delete messages on the server

### ISSUE THREAD

**Issue by TristanYoung** [thunderbird/thunderbird-android#1748] opened 2016-10-24 15:44 UTC
I've been having issues with K9 Mail deleting messages from the server.  K9 won't delete messages.  After I delete them and perform a refresh, they are re-fetched.  The behavior is not correct.

I have K9 configured to delete the message on the server when I delete the message on the phone.

I have reset my K9 configuration and started from scratch - uninstalled and then re-installed K9, and rewrote all my settings manually.
### Expected behavior

Delete the message on the server when I delete the message on the phone
### Actual behavior

The message is not deleted on the server.  Re-freshing (fetch email) re-downloads the emails I thought I deleted.
### Steps to reproduce
1.  Delete message
2.  Fetch email
3.  Pull hair out
### Environment

K-9 Mail version:
This was happening on v5.010, and again on the latest alpha

Android version:
6.0.1

Account type (IMAP, POP3, WebDAV/Exchange):
POP3

**Comment by cketti** [comment] 2016-10-24 16:45
Please record a debug log while trying to delete a message.
https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by trmidas** [comment] 2016-10-25 22:10
Same issue with my Zuk-Z1

LoggingErrors dump below.

Thank you for looking into it.

Sent: October 25, 2016 10:45:54 PM GMT+01:00
Subject: SocketTimeoutException: failed to connect to trmail.triumf.ca/142.90.100.150 (port 993) after 30000ms

K9-Mail version: 5.010
Device make: Zuk
Device model: Z1
Android version: 5.1.1

com.fsck.k9.mail.MessagingException: IO Error
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.ioExceptionHandler(ImapStore.java:2208)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:947)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.open(ImapStore.java:867)
	at com.fsck.k9.controller.MessagingController.processPendingMoveOrCopy(MessagingController.java:2309)
	at com.fsck.k9.controller.MessagingController.processPendingCommandsSynchronous(MessagingController.java:1997)
	at com.fsck.k9.controller.MessagingController.synchronizeMailboxSynchronous(MessagingController.java:975)
	at com.fsck.k9.controller.MessagingController.access$400(MessagingController.java:111)
	at com.fsck.k9.controller.MessagingController$8.run(MessagingController.java:934)
	at com.fsck.k9.controller.MessagingController.run(MessagingController.java:435)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.net.SocketTimeoutException: failed to connect to trmail.triumf.ca/142.90.100.150 (port 993) after 30000ms
	at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
	at libcore.io.IoBridge.connect(IoBridge.java:122)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
	at java.net.Socket.connect(Socket.java:882)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.open(ImapStore.java:2445)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.sendCommand(ImapStore.java:2872)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2921)
	at com.fsck.k9.mail.store.ImapStore$ImapConnection.executeSimpleCommand(ImapStore.java:2902)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.executeSimpleCommand(ImapStore.java:858)
	at com.fsck.k9.mail.store.ImapStore$ImapFolder.internalOpen(ImapStore.java:904)
	... 8 more

-- 
Sent from my Android device with K-9 Mail.

**Comment by philipwhiuk** [comment] 2016-11-06 10:50
Nah, it's trimming the Exception message - the 't' is just the first character from "**t**he bind value at index 1 is null"

Anyway, I said I would have a look at our database code - this looks like a fine place to start...

**Comment by philipwhiuk** [comment] 2016-11-06 16:07
In 5.010 - MessagingController

```
if (!localUidMap.isEmpty() && remoteUidMap != null && !remoteUidMap.isEmpty()) {
  for (Map.Entry<String, String> entry : remoteUidMap.entrySet()) {
    String remoteSrcUid = entry.getKey();
    String localDestUid = localUidMap.get(remoteSrcUid);
    String newUid = entry.getValue();
    //Line - 2355
    Message localDestMessage = localDestFolder.getMessage(localDestUid); 
```

This still exists in master: 

https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L2095

I think the problem is that localDestUid is null because it's not present in the map for some reason.

We should do one of two things:

1. Check for null before calling getMessage() and add a @NotNull anotation to that method.
2. Mark getMessage as @Nullable and check for null before trying to query.

That moves the problem back and gets us closer to the root cause.

Next we need to work out why it's not in the map. I think this might have been refactored though - it's possible the cause of @trmidas 's issue was fixed by the changes to the MessagingController.

Basically the causal tree of this is (for @trmidas)

1. We process sync commands in order
2, We have a pending move/copy that is outstanding before we process the deletes
3. We have a bug in the move/copy code that means the message isn't being properly fetched from the DB

Whether the same points 2 & 3 are true for @TristanYoung is impossible to know without logs.

Regardless the approach should be:

* Make the code more resilient in move/copy by handling the null-case as outlined above.
* If possible, diagnose the reason it's not in the map (may not be possible)
* Rework sync code.

The first is trivial, the second requires some more analysis. The third is a larger planned enhancement I discussed briefly with cketti - it requires us to chain offline actions in a better way (so that failure on one action doesn't block everything). It's a large project though.

**Comment by trmidas** [comment] 2016-11-07 00:00
Hi,  I  have to add that since my last msg,  I reinstalled the app and the problem is gone.  So I  guess some local var retain the wrong information. 

On November 6, 2016 8:08:05 AM PST, Philip <notifications@github.com> wrote:
>In 5.010 - MessagingController
>
>```
>if (!localUidMap.isEmpty() && remoteUidMap != null &&
>!remoteUidMap.isEmpty()) {
>  for (Map.Entry<String, String> entry : remoteUidMap.entrySet()) {
>    String remoteSrcUid = entry.getKey();
>    String localDestUid = localUidMap.get(remoteSrcUid);
>    String newUid = entry.getValue();
>    //Line - 2355
>  Message localDestMessage = localDestFolder.getMessage(localDestUid); 
>```
>
>This still exists in master: 
>
>https://github.com/k9mail/k-9/blob/master/k9mail/src/main/java/com/fsck/k9/controller/MessagingController.java#L2095
>
>I think the problem is that localDestUid is null because it's not
>present in the map for some reason.
>
>We should do one of two things:
>
>1. Check for null before calling getMessage() and add a @NotNull
>anotation to that method.
>2. Mark getMessage as @Nullable and check for null before trying to
>query.
>
>That moves the problem back and gets us closer to the root cause.
>
>Next we need to work out why it's not in the map. I think this might
>have been refactored though - it's possible the cause of @trmidas 's
>issue was fixed by the changes to the MessagingController.
>
>Basically the causal tree of this is (for @trmidas)
>
>1. We process sync commands in order
>2, We have a pending move/copy that is outstanding before we process
>the deletes
>3. We have a bug in the move/copy code that means the message isn't
>being properly fetched from the DB
>
>Whether the same points 2 & 3 are true for @TristanYoung is impossible
>to know without logs.
>
>Regardless the approach should be:
>
>* Make the code more resilient in move/copy by handling the null-case
>as outlined above.
>* If possible, diagnose the reason it's not in the map (may not be
>possible)
>* Rework sync code.
>
>The first is trivial, the second requires some more analysis. The third
>is a larger planned enhancement I discussed briefly with cketti - it
>requires us to chain offline actions in a better way (so that failure
>on one action doesn't block everything). It's a large project though.

-- 
Cheers, PAA

**Comment by TristanYoung** [comment] 2016-11-07 14:12
Sorry for the lack of a log on my part.  The problem isn't cropping up at the moment.  Instead I'm dealing with a flood of spam filling my K9 inbox, so it has really put a damper on my use and testing of K9.

I can't remember if I downgraded K9 or what, I'll have to get on my phone and find out what's going on.

**Comment by bobmseagithub** [comment] 2017-07-26 21:24
I have this problem too.  Messages never get deleted from the server.  Log attached.  K-9 Mail Version: 5.206
[k9-log.txt](https://github.com/k9mail/k-9/files/1178116/k9-log.txt)

**Comment by bouncinglime** [comment] 2017-08-21 16:20
I'm also having this issue, with a gmail account.

DETAILS :
Device : Samsung Galaxy S5 Mini (SM-G800F)
OS : Android 6.0.1
K-9 : 5.207

STR :
1. Open any folder (Inbox or other) in K-9.
2. Using the selection boxes on the left, select and delete a message (read or unread).
3. Sync account. [See Result 1.]
4. Open gmail account in any other way (app, browsers, etc.). (See Result 2.)

RESULTS :
1. Message is removed from K-9.
2. Message is still present in the same location in gmail.

I also get a message in the K9mail-errors folder, which is attached. The subject line indicates that it's looking for a folder titled "[Google Mail]/Trash" which is what I have selected in the account settings for trash. It also seems to have renamed the Trash folder in my gmail account, as it now shows up in the list in gmail-in-the-browser as "[Google Mail]/Trash".

I was really hoping that I could use K-9 as a full gmail-app replacement, but until deleting works properly I'll have to treat it as a read-only option. It would be nice to have my old gmail Trash folder back, too!

[bouncinglime_gmail-trash-error_2017-08-21.txt](https://github.com/k9mail/k-9/files/1239482/bouncinglime_gmail-trash-error_2017-08-21.txt)

**Comment by fik236** [comment] 2017-09-21 05:59
I have similar problem in version K9-mail 5.208.
in phone is message deleted (and no more downloaded) - but if I check server - the message is still there.

android: 6.0
phone: cubot echo.

if you need some log - please help me where can i find it.

**Comment by bam80** [comment] 2018-01-05 00:25
Does it occur only for POP3 accounts?

**Comment by bouncinglime** [comment] 2018-01-05 10:31
I think I've solved the issue with my gmail account! It seems that K-9 had created the "[Google Mail]/Trash" folder and was using it for deleted messages, instead of using the existing gmail trash folder. (I'm localized for UK, so the correct one is "[Google Mail]/Bin".)

Solution :
1. Open gmail Account Settings.
2. Tap "Folders".
3. Scroll down to the bottom and tap "Trash folder".
4. Select the correct trash folder (on the server) from the list available.

I've gone through and done this for Sent, Drafts, and Trash on all of my accounts and everything is working properly now. Yay! (I was also not getting my sent mail synced across other accounts, so I decided to try it.)

It's a little frustrating that K-9 doesn't identify them correctly automatically, but at least there's a way to fix it.

**Comment by fik236** [comment] 2018-03-01 09:47
Hello,
I have still this problem.
version of k9: 5.403
android 6.0

Maybe this is problem of specific server.
I have conected several servers to k-9 and only one does not work.

But at PC with thunderbird it works.
I have checked that folder for thrash is setted correctly.
I am using imap/smtp.

Please could any body advice me what sould I try do?

**Comment by terr72** [comment] 2018-04-25 06:11
I just realised that I might have created a report for the same bug.
Feel free to mark it as duplicate. It would be great to have it fixed.
Thank you for your great work!

**Comment by fik236** [comment] 2018-05-07 07:17
when I delete message trough K9 mail - it look like that it is deleted (in phone), but when i look to mail trough its web-interface or trough thunderbird - the message is still there.

trough thunderbird I can delete message.

In K9 is option  "if delete message" so i have it setted to "delete it in server"
I have also experimented with setting of trash-folder but no succed.

I am not sure if imap or smtp are responsible for deleting messages so here is both wariants of server:
imap.centrum.cz and smtp.centrum.cz

if you need some log, please describe mi how to create this log or, where can i find it.
Thank you.

**Comment by cketti** [comment] 2019-02-28 21:18
Please create a new issue with an attached debug log if this is still a problem with the latest K-9 Mail version.

**Closed by cketti** 2019-02-28 21:18 UTC

**Comment by gorky** [comment] 2019-03-10 00:17
Fix confirmed.  THANKS!
