### ISSUE TITLE
IMAP search in Japanese returns Remote Search Failed 

### ISSUE THREAD

**Issue by aliceinwire** [thunderbird/thunderbird-android#2507] opened 2017-04-20 06:35 UTC
### Expected behavior
Searching with Japanese works

### Actual behavior
Remote search failed
```

I/k9      (27782): Running command 'getFolderUnread:XXXX XXXXXXXXXX:INBOX', seq = 24(foregroundpriority)
I/k9      (27782):  Command 'getFolderUnread:XXXX XXXXXXXXXXX:INBOX' completed
I/ActivityManager(  719): START u0 {act=android.intent.action.SEARCH flg=0x10000000 cmp=com.fsck.k9/.activity.Search (has extras)} from uid 10127 on display 0
I/ActivityManager(  719): Displayed com.fsck.k9/.activity.Search: +202ms
I/k9      (27782): searchRemoteMessages (acct=9c5a069f-8738-4ad2-9112-c696f6a77f9d, folderName = INBOX, query = 会員)
V/k9      (27782): conn230882607>>> 18 NOOP
V/k9      (27782): conn230882607<<<#18# [OK, Success]
V/k9      (27782): conn230882607>>> 19 UID SEARCH OR SUBJECT "会員" FROM "会員"
V/k9      (27782): conn230882607<<<#19# [BAD, Could not parse command]
E/k9      (27782): Could not complete remote search
E/k9      (27782): com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH OR SUBJECT "会員" FROM "会員"; response: #19# [BAD, Could not parse command]
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:121)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:620)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapFolder.access$000(ImapFolder.java:42)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapFolder$5.search(ImapFolder.java:1493)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:621)
E/k9      (27782): 	at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:1503)
E/k9      (27782): 	at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:610)
E/k9      (27782): 	at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:581)
E/k9      (27782): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
E/k9      (27782): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
E/k9      (27782): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
E/k9      (27782): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
E/k9      (27782): 	at java.lang.Thread.run(Thread.java:818)
V/k9      (27782): LockableDatabase: Transaction ended, took 24ms / 

```
### Steps to reproduce
1. search with Japanese
2. return search failed

### Environment
K-9 Mail version:
5.207
Android version:
6.0.1
Account type:
IMAP

**Comment by gloomy-ghost** [comment] 2017-06-25 11:25
Searching in Chinese fails as well. Error message:

```
K9-Mail version: 5.207
Device make: LGE
Device model: Nexus 5X
Android version: 7.1.2

com.fsck.k9.mail.store.imap.NegativeImapResponseException: Command: UID SEARCH OR SUBJECT "测试" FROM "测试"; response: #12# [BAD, Could not parse command]
at com.fsck.k9.mail.store.imap.ImapResponseParser.readStatusResponse(ImapResponseParser.java:121)
at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:634)
at com.fsck.k9.mail.store.imap.ImapConnection.executeSimpleCommand(ImapConnection.java:620)
at com.fsck.k9.mail.store.imap.ImapFolder.executeSimpleCommand(ImapFolder.java:109)
at com.fsck.k9.mail.store.imap.ImapFolder.access$000(ImapFolder.java:42)
at com.fsck.k9.mail.store.imap.ImapFolder$5.search(ImapFolder.java:1493)
at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:621)
at com.fsck.k9.mail.store.imap.ImapFolder.search(ImapFolder.java:1503)
at com.fsck.k9.controller.MessagingController.searchRemoteMessagesSynchronous(MessagingController.java:610)
at com.fsck.k9.controller.MessagingController$7.run(MessagingController.java:581)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

**Comment by philipwhiuk** [comment] 2017-06-26 12:46
Duplicate of #1140

**Closed by philipwhiuk** 2017-06-26 12:46 UTC
