### ISSUE TITLE
Crash a K-9 Mail V6.500/6.501

### ISSUE THREAD

**Issue by testac0123** [thunderbird/thunderbird-android#6566] opened 2023-01-10 08:57 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.500/6.501

### Where did you get the app from?

Other

### Android version

6.0(EMUI4.0.3)

### Device model

HUAWEI M2-802L

#### Email account set up

Crashes when started.

#### Mail account not configured

Crashes when OK is pressed on the last screen of the initial setup screen (sync interval, number of receipts, notifications)

#### Mail account configured

Crashes when OK is pressed at the last screen of registering additional mail accounts (sync interval, number of receipts, notifications)

#### Email account not configured
Crashes when OK is pressed on the last screen of the initialization screen (sync interval, number of receipts, whether or not to notify)

### Expected behavior

Go to the Mail List screen

### Actual behavior

クラッシュして強制終了

### Logs

Could not record due to crash

**Comment by cketti** [comment] 2023-01-10 10:14
https://github.com/thundernest/k-9/wiki/LoggingErrors also contains instructions on how to record a debug log when the app is crashing. In that case the device has to be connected to a PC. Without this debug log there's not a lot we can do.

Duplicate of #6558

**Closed by cketti** 2023-01-10 10:14 UTC
