### ISSUE TITLE
Unread email counter display wrong information in notifications

### ISSUE THREAD

**Issue by PhilesFogg92** [thunderbird/thunderbird-android#5732] opened 2021-10-10 20:23 UTC
Hi,

Even if I enable notification for new emails only for first class folders (in which I have only inbox folder), when I receive a new email, the counter on Icon app and status bar display the number of all unread messages including unread messages of each archives and trash folders.

It's a problem because when you manage your emails with many other devices, they don't automatically unread the messages that you delete (and thus you send in the trash) or that you quickly move in an archive folder without fully opening it.
So, with the time, you naturally have more and more unread messages in trash and archives folders, and currently when you just receive a really new one in the inbox, the K-9 client count all these old messages as unread to display the result in the notifications of status bar and icon app.

The easy fix would be to only count unread messages in the class of folders I select.
A second and easier option would be to only count the unread messages of inbox folder.
A third option would be to not display the counter of unread message in the status bar and on the the icon app, but just a message in status bar and an overlay on icon app saying that there is new email.

Hoping it could be solved.

Best regards

Philippe

**Comment by cketti** [comment] 2021-10-11 12:22
Duplicate of #2018

**Closed by cketti** 2021-10-11 12:22 UTC
