### ISSUE TITLE
Suggest Mail Address from a list of former recipients and recenty received mails

### ISSUE THREAD

**Issue by githubandispensing** [thunderbird/thunderbird-android#7450] opened 2023-12-20 12:08 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

6.603

### Problem you are trying to solve

when starting to write a mail address a list of similar mails address recently used and known recipients is very helpful.

A full address book is not what i want. 

### Suggested solution

Copied from outlook:

![address_suggestions_Screenshot_20231220-125851](https://github.com/thunderbird/thunderbird-android/assets/154430417/c55bba2a-cc4e-40a0-959c-57806480b5fb)

The list should show addresses from all accounts.

**Comment by cketti** [comment] 2024-01-03 17:02
Duplicate of #1006

**Closed by cketti** 2024-01-03 17:02 UTC
Labels: enhancement, unconfirmed
