### ISSUE TITLE
Attachment deleted when opening draft from IMAP

### ISSUE THREAD

**Issue by anderoox** [thunderbird/thunderbird-android#1566] opened 2016-08-16 01:29 UTC
### Expected behavior

Attachments should be preserved even if not explicitly shown
### Actual behavior

When opening a message from a IMAP draft folder, there is no indication of whether there are attachments. In the event the email does have attachments, those are silently deleted when the draft is saved back to the server.
### Steps to reproduce
1. On PC, create a draft message with an attachment and save to IMAP draft folder
2. In K9, open this draft message then save
3. On PC, reopen the message - attachment is gone
### Environment

K-9 Mail version: 5.010

Android version:

Account type (IMAP, POP3, WebDAV/Exchange):

**Comment by chrisrapson** [comment] 2018-02-24 22:49
Is this a duplicate of [#954](https://github.com/k9mail/k-9/issues/954) and [#2547](https://github.com/k9mail/k-9/issues/2547)?

I would also say it is related to [#2485](https://github.com/k9mail/k-9/issues/2485), which is a duplicate of [#3110](https://github.com/k9mail/k-9/issues/3110).

**Comment by cketti** [comment] 2019-02-28 20:41
Duplicate of #954

**Closed by cketti** 2019-02-28 20:41 UTC
