### ISSUE TITLE
F-Droid client(s) suggested version stuck on 6.603

### ISSUE THREAD

**Issue by Gravemind2015** [thunderbird/thunderbird-android#7706] opened 2024-03-08 14:40 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.717

### Where did you get the app from?

F-Droid

### Android version

12

### Device model

Samsung M51

### Steps to reproduce

Both official F-Droid client and Droid-ify have been showing version 6.303 as suggested version. Even though newer versions get populated on the releases list, they are therefore never recommended as updates.

I can successfully reproduce it on fresh install of both Droid-ify and official F-Droid client on two devices (Samsung M51, OneUI 4.1 Android12 stock and Moto G84, Android 13 stock).

Apologies in advanced if this is something beyond k-9/thunderbird teams' reach, I decided to post here as the issue tracker on f-droid page for k-9 leads here.

### Expected behavior

Latest version should be marked as suggested
![Screenshot_20240308-144729](https://github.com/thunderbird/thunderbird-android/assets/116586720/0d306958-e3f7-4a6e-9dfc-c0422552ec2a)
![Screenshot_20240308-144707](https://github.com/thunderbird/thunderbird-android/assets/116586720/c64d1259-34bb-411a-9732-49f003353bc7)
.

### Actual behavior

Suggested version is stuck on 6.603.

Edit: oops, somehow missed that closed issue, maybe because I searched for suggested and not recommended 😅

**Comment by cketti** [comment] 2024-03-08 16:37
Duplicate of #7441

**Closed by cketti** 2024-03-08 16:37 UTC
