### ISSUE TITLE
Unable to execute POP3 command

### ISSUE THREAD

**Issue by File4mat** [thunderbird/thunderbird-android#5880] opened 2022-01-25 16:07 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.806

### Where did you get the app from?

Google Play

### Android version

12

### Device model

Pixel 6 Pro

### Steps to reproduce

Add new POP account
Enter credentials
Tap next on the Incoming server settings screen.
Error unable to execute pop3 command

### Expected behavior

Log in to pop server

### Actual behavior

Cant connect to pop server. Error: **Unable to execute POP3 command**
There is a forum thread about this issue [located here](https://forum.k9mail.app/t/no-pop3-email-from-ionos-unable-to-execute-pop3-command/4017)

### Logs

[k9-log.txt](https://github.com/k9mail/k-9/files/7935142/k9-log.txt)

**Comment by cketti** [comment] 2022-01-25 16:11
Thanks.

Duplicate of #5879

**Closed by cketti** 2022-01-25 16:11 UTC
