### ISSUE TITLE
K-9 Mail listing on f-droid is incorrect (shows Thunderbird Beta for Testers)

### ISSUE THREAD

**Issue by VictorVow** [thunderbird/thunderbird-android#8478] opened 2024-11-03 12:26 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App

K-9 Mail

### App version

8.0

### Where did you get the app from?

F-Droid

### Android version

14

### Steps to reproduce

I've used K-9 Mail from F-Droid for years and enjoyed the experience. Today I see K-9 Mail updated to Thunderbird - which I'm fine with, I expected the rebranding. 

### Expected behavior

However I did not expect the app to become Thunderbird Beta for Testers - I need a stable client and am not interested in being on the cutting-edge branch. Why has K-9 Mail been changed to the Beta branch instead of the Stable version? Is there a way I can one-click change to the Stable version?

### Actual behavior

.

**Comment by Sunsper** [comment] 2024-11-03 13:23
What's more weird is that now if you search for Thunderbird on F-Droid, you'll discover that there are TWO "Thunderbird Beta for Testers". The branding of the installed app is untouched tho.

Was K-9 Mail unintentionally renamed or something?

**Comment by wsmwk** [comment] 2024-11-03 13:49
There is an error in the metadata that will be corrected, which may take some hours.

**Comment by wiltet** [comment] 2024-11-03 14:53
Why not call it by its name? Poor old and stable K-9.

**Comment by goodevilgenius** [comment] 2024-11-03 22:35
> There is an error in the metadata that will be corrected, which may take some hours.

To be clear, this is only a metadata issue, right? If I upgrade, I'll still be using K-9, and not Thunderbird?

I know there's some migration steps needed to switch from K-9 to Thunderbird, and I don't want to upgrade and lose my data.

**Comment by je-vv** [comment] 2024-11-04 04:01
I'm wondering if it would be simpler and easier to just replace k9 with thrunderbird-beta at once, when upgrading k9, without user intervention, and keeping all settings, accounts, encryption keys configs and so on.  I believe by now people already know K9 is Thunderbird.

In my case, I'll stay K9, but I'm hoping for what I mentioned, a f-droid automatic replacement.  I'm sort of afraid of K9 at some point getting stalled and TB-beta progressing.  But we'll see.

Many thanks !

**Comment by bodograumann** [comment] 2024-11-04 06:26
> I'm wondering if it would be simpler and easier to just replace k9 with thrunderbird-beta at once, when upgrading k9, without user intervention, and keeping all settings, accounts, encryption keys configs and so on. I believe by now people already know K9 is Thunderbird.
> 
> In my case, I'll stay K9, but I'm hoping for what I mentioned, a f-droid automatic replacement. I'm sort of afraid of K9 at some point getting stalled and TB-beta progressing. But we'll see.

I hope there won't be an automatic replacement.

First of all I think this was a faux-pas to break the metadata. I was not aware of the fact that K9 is now part of the thunderbird project and so it shocked me to find that FDroid had installed an unknown app without my explicit go-ahead.
Secondly I feel sentimental and would like to keep the K9 branding. In their blog they actually [promised this](https://k9mail.app/2023/12/28/When-will-Thunderbird-for-Android-be-released) and said it would not be difficult to publish two app versions that differ just in color theme, icon and naming.

**Comment by TheR0cketMan** [comment] 2024-11-04 09:36
To make it more confusing the app icon is still K-9 and when you search install apps on Android, Thunderbird doesn't even show up. I even tried scrolling in alphabetical order & it's just non existent but yet on F-Droid it says K-9 is now Thunderbird. I'm so confused right now & it makes the app look dodgily suspicious.

**Comment by RoestVrijStaal** [comment] 2024-11-04 09:52
Yikes, I feel K9-mail is hijacked by Mozilla.

I don't want Mozilla. Fuck Mozilla.

Is there a clean fork?

**Comment by Sunsper** [comment] 2024-11-04 10:09
> To make it more confusing the app icon is still K-9 and when you search install apps on Android, Thunderbird doesn't even show up. I even tried scrolling in alphabetical order & it's just non existent but yet on F-Droid it says K-9 is now Thunderbird. I'm so confused right now & it makes the app look dodgily suspicious.

> Yikes, I feel K9-mail is hijacked by Mozilla.
> 
> I don't want Mozilla. Fuck Mozilla with their commercial shit.
> 
> Is there a clean, true FOSS fork like it happened with those Simple* apps?

Have any on you tried to actually read comments under this here issue? This is just metadata error, nothing actually changed. The error WILL be fixed.

Also on that note, K-9 and Thunderbird Android are basically the same app anyways.
If you don't like the fact that Mozilla "hijacked" the K9 Mail project, even though not a lot has changed in terms of how the application operates, I don't know what to tell you.

**Comment by TheR0cketMan** [comment] 2024-11-04 10:15
> > To make it more confusing the app icon is still K-9 and when you search install apps on Android, Thunderbird doesn't even show up. I even tried scrolling in alphabetical order & it's just non existent but yet on F-Droid it says K-9 is now Thunderbird. I'm so confused right now & it makes the app look dodgily suspicious.
> 
> > Yikes, I feel K9-mail is hijacked by Mozilla.
> > 
> > I don't want Mozilla. Fuck Mozilla with their commercial shit.
> > 
> > Is there a clean, true FOSS fork like it happened with those Simple* apps?
> 
> Have any on you tried to actually read comments under this here issue? This is just metadata error, nothing actually changed. The error WILL be fixed.
> 
> Also on that note, K-9 and Thunderbird Android are basically the same app anyways.
> If you don't like the fact that Mozilla "hijacked" the K9 Mail project, even though not a lot has changed in terms of how the application operates, I don't know what to tell you.

Firstly, you don't need to be rude, secondly, we have every right to be suspicious with what's put in front of us when we were hardly told about K-9 joining forces with Thunderbird. It's a good thing to be dubious sometimes, it's how we keep ourselves safe from potential threats. The PR hasn't been handled well from either side so it's no surprise people are getting confused & even more so with this "bug".

**Comment by kewisch** [comment] 2024-11-04 10:47
Hi folks. The fact that K-9 has become a part of the Thunderbird family is more than 2 years old, we originally blogged about it here https://blog.thunderbird.net/2022/06/revealed-thunderbird-on-android-plans-k9/  and it was also on the K-9 Mail blog: https://k9mail.app/2022/06/13/K-9-Mail-and-Thunderbird.html . Everyone is entitled to their opinion about Mozilla, but for the sake of this issue let's keep it professional. We also have a little information at https://support.mozilla.org/en-US/kb/thunderbird-android-8-faq#w_what-is-happening-with-k-9 . If there is anything you think would be useful to mention to better explain the situation please let us know and I'll be happy to expand the messaging.

The f-droid listing was updated over the weekend after we triggered a metadata update during the week. Unfortunately, the symlink that is responsible for pointing to the right metadata was not updated, leading f-droid's automation to take the listing metadata from Thunderbird Beta.

I can confirm that it was just the listing metadata that has changed, you'll continue to have K-9 Mail (com.fsck.k9) installed. Note however that K-9 Mail and Thunderbird are on the same code base, so you won't see a major difference in functionality or looks at the moment. There are a few common complaints you might point out that are covered in other issues that we'll be working on smoothing out shortly.

Going back to the core of this issue, we did an emergency build yesterday to trigger an f-droid update, and the f-droid team graciously restarted the build cycle for us. Once the cycle is through (max 2-3 days), K-9 will be restored to its original listing. I'll leave this open and pinned until the listing is finally updated.

**Comment by scollovati** [comment] 2024-11-04 10:48
> we were hardly told about K-9 joining forces with Thunderbird

This has been extensively communicated for more than 2 years: 

- https://k9mail.app/2022/06/13/K-9-Mail-and-Thunderbird.html
- https://blog.thunderbird.net/2022/06/faq-thunderbird-mobile-and-k-9-mail/
- almost monthly projects reports: https://blog.thunderbird.net/category/mobile-news/

**Comment by RoestVrijStaal** [comment] 2024-11-04 13:57
> There will not be an automatic replacement from K-9 Mail to Thunderbird, the actual Thunderbird applications are under completely different application ids (net.thunderbird.android).

You're lying. 
I've updated the repositories in my F-Droid app and I get this:
![d4c273f7-037c-4f09-af1b-44e8a510e4c4](https://github.com/user-attachments/assets/c2d42339-0362-45c4-84b2-e0259fc189a5)

Even worse: The pre-Mozilla versions are not choosable anymore. Only the 8.x versions are present.

**Comment by librelegal** [comment] 2024-11-04 14:00
Dear RoestVrijStaal, your aggression is not necessary, please tune down and [read this](https://forum.f-droid.org/t/k-9-to-thunderbird-update/28973/36)

**Comment by mahdi921** [comment] 2024-11-04 15:56
Time for migration has come for me. I never used thunderbird nor I'm using it from now on. You could've made a separate repo for thundebird and left k9 alone. But you decided to hijack k9. There's no guarantee that you will continue k9 from now on and not implement Mozilla's tracking and call to home s*it into k9, too; which is why i left firefox many years ago.

Wish you all the best.

**Comment by RoestVrijStaal** [comment] 2024-11-04 16:40
> Dear RoestVrijStaal, your aggression is not necessary, please tune down and [read this](https://forum.f-droid.org/t/k-9-to-thunderbird-update/28973/36)

Which is a blatant lie:
> Additionally, we plan to continue maintaining and releasing K-9 Mail for approximately one year after the release of Thunderbird for Android. 

Because K9 doesn't exist anymore already.

**Comment by goodevilgenius** [comment] 2024-11-04 16:53
@RoestVrijStaal , you really need to calm down here. This is a bug report about the wrong metadata showing in F-Droid. It's not a forum for you to air your grievances about something that has been in the pipeline, and highly publicized for two years now.

GitHub just is not the place for these particular comments. Take them to Reddit if you must.

**Comment by TheR0cketMan** [comment] 2024-11-04 17:02
> @RoestVrijStaal , you really need to calm down here. This is a bug report about the wrong metadata showing in F-Droid. It's not a forum for you to air your grievances about something that has been in the pipeline, and highly publicized for two years now.
> 
> GitHub just is not the place for these particular comments. Take them to Reddit if you must.

"Highly publicised" next joke 🤣 I agree with the rest though. This is a buf report not a forum.

**Comment by RoestVrijStaal** [comment] 2024-11-04 17:10
> GitHub just is not the place for these particular comments. Take them to Reddit if you must.

...Which won't be read by the developers when posting those there or on a different website.

Now they do.

**Comment by Sunsper** [comment] 2024-11-04 19:30
> Firstly, you don't need to be rude, secondly, we have every right to be suspicious with what's put in front of us when we were hardly told about K-9 joining forces with Thunderbird. It's a good thing to be dubious sometimes, it's how we keep ourselves safe from potential threats. The PR hasn't been handled well from either side so it's no surprise people are getting confused & even more so with this "bug".

Yes, I don't have to be rude, though I'm being barely rude at all in my last comment, at least to my own judgment.
Yes, it is a right thing to do to exercise a healthy bit of skepticism towards free and open-source programs and applications we all use on a daily basis.

You want to know what the problem is?
Looking at comments in this issue, including those that came in the meantime between my last comment and now, time and time again I get reassured that apparently a lot of people in this community don't actually know what **healthy amount of skepticism** is, have severe paranoia and frequently get explosive meltdowns over very insignificant changes and/or errors. Including errors as small as "Guys, we messed up metadata in the F-Droid repo a bit. Will be fixed very soon, sorry for the confusion."
And it makes me very sad that because of this people are willing to bring forums or X (Twitter) type of discussion where it doesn't belong.

Also I'm not sure where you get news about anything open-source, but personally I knew about K9 becoming Thunderbird Mobile for a very long time, long before the first public beta of Thunderbird Android appeared and I've been waiting for this. So yeah, "highly publicized" is actually a true statement, both K9 and Mozilla have been very vocal about this.

**Comment by kewisch** [comment] 2024-11-04 19:51
I want to thank everyone who has stepped in to help keep the conversation constructive and on-topic—it really means a lot. I also understand that people care deeply about these issues, and having some level of skepticism is certainly important these days. I've collapsed a few comments (and those in reply, sorry) so we can focus on any further issues that might arise from the f-droid build that brings back the original listing. Again, changing the listing was a simple mistake, and the fact that f-droid indicated there is "an update" to Thunderbird is just because the listing was wrong. Everything should be back to normal soon.

**Comment by scollovati** [comment] 2024-11-06 08:19
In the Android client now it shows up properly (icon, name, description). Instead in the website it still shows as "Thunderbird Beta for Testers", but the logo is the right one: https://f-droid.org/en/packages/com.fsck.k9/

![image](https://github.com/user-attachments/assets/430c0ca6-f639-4253-9250-732e5681d377)

<img width="657" alt="image" src="https://github.com/user-attachments/assets/2f541584-be93-4b8f-93e7-b0dcd4e0caf1">

**Comment by je-vv** [comment] 2024-11-06 09:40
Many thanks !  This helped me try Thunderbird from F-Droid BTW, :)

**Comment by kewisch** [comment] 2024-11-06 12:24
There is some caching going on and it needs to go out to all the mirrors. I've seen the f-droid devs chatting about this a bit. It looks good on my end now.

**Comment by TheR0cketMan** [comment] 2024-11-06 15:00
> There is some caching going on and it needs to go out to all the mirrors. I've seen the f-droid devs chatting about this a bit. It looks good on my end now.

Hopefully in time it will. However, I've just checked on both F-Droid and Droidify (fork of F-Droid) and it displays like this for ms at least still.

![Screenshot_2024-11-06-14-58-39-966_org.fdroid.fdroid.jpg](https://github.com/user-attachments/assets/d98758a7-270f-47d6-a527-8d97b8ac98c4)

![Screenshot_2024-11-06-14-58-50-157_com.looker.droidify.jpg](https://github.com/user-attachments/assets/0b94f800-87b3-47eb-883b-2c97c0e6ec77)

**Comment by kewisch** [comment] 2024-11-08 19:25
This has been resolved as far as we're able to, anything that shows up now will likely be mirrors that need updating. Closing out this issue.

**Closed by kewisch** 2024-11-08 19:25 UTC
