### ISSUE TITLE
Failed to start push service

### ISSUE THREAD

**Issue by p-fruck** [thunderbird/thunderbird-android#7857] opened 2024-05-19 18:43 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.803

### Where did you get the app from?

F-Droid

### Android version

14

### Device model

Pixel 6a

### Steps to reproduce

Cannot reproduce, happened randomly after reboot

### Expected behavior

App should auto-start

### Actual behavior

App crashed, failed to start push service. Poll based notifications still work

### Logs

```
type: crash
osVersion: google/bluejay/bluejay:14/AP1A.240505.004/2024051500:user/release-keys
package: com.fsck.k9:38003
process: com.fsck.k9
processUptime: 197 + 369 ms
installer: org.fdroid.fdroid

java.lang.RuntimeException: Unable to start service com.fsck.k9.controller.push.PushService@4677c25 with null: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5079)
at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2397)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8532)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ExecInit.main(ExecInit.java:50)
at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:359)
Caused by: android.app.ForegroundServiceStartNotAllowedException: Service.startForeground() not allowed due to mAllowStartForeground false: service com.fsck.k9/.controller.push.PushService
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:54)
at android.app.ForegroundServiceStartNotAllowedException$1.createFromParcel(ForegroundServiceStartNotAllowedException.java:50)
at android.os.Parcel.readParcelableInternal(Parcel.java:5035)
at android.os.Parcel.readParcelable(Parcel.java:5017)
at android.os.Parcel.createExceptionOrNull(Parcel.java:3186)
at android.os.Parcel.createException(Parcel.java:3175)
at android.os.Parcel.readException(Parcel.java:3151)
at android.os.Parcel.readException(Parcel.java:3093)
at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6876)
at android.app.Service.startForeground(Service.java:878)
at com.fsck.k9.controller.push.PushService$$ExternalSyntheticApiModelOutline0.m(R8$$SyntheticClass:0)
at com.fsck.k9.controller.push.PushService.startForeground(PushService.kt:45)
at com.fsck.k9.controller.push.PushService.onStartCommand(PushService.kt:28)
at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5061)
... 11 more
```

**Comment by p-fruck** [comment] 2024-05-19 18:46
Might be related to https://github.com/thunderbird/thunderbird-android/issues/7725 / https://github.com/thunderbird/thunderbird-android/issues/7363 ? Push notifications have not been working for a while now, but this random crash could not be reproduced

**Comment by cketti** [comment] 2024-05-21 08:56
Duplicate of #7416

**Closed by cketti** 2024-05-21 08:56 UTC
