### ISSUE TITLE
read and unread messages are not distinguishable in dark mode

### ISSUE THREAD

**Issue by b-glawe** [thunderbird/thunderbird-android#8403] opened 2024-10-24 10:04 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same feature request.
- [X] I will describe the problem with as much detail as possible.
- [X] This issue only contains a request for one single feature, **not** multiple (related) features.

### App version

8.04b

### Problem you are trying to solve

I want to distinguish unread  from read messages at a glancein the mailbox listing (Inbox etc. ) in dark mode. Currently thunderbird draws headers of unread messages actually with almost the same boldness, color and size. Thus I cannot see whether messages in the list are read or unread. Issue affects only dark mode. 
I have not customized any fonts anywhere. Setting thunderbird to dark mode in thunderbird's setting menu is the only customization, that I've applied. 

### Suggested solution

Highlight unread messages with higher font size , lighter colors, modified background, additional markers - whatever appears useful to you UI/UX experts. 

Quick filters for unread messages would also support. They would however not solve the above mentioned uiI/UX issue. 

A possible emergency exit: Do not offer dark mode which would be a pity.

**Comment by cketti** [comment] 2024-10-24 10:35
Duplicate of #7980

**Closed by cketti** 2024-10-24 10:35 UTC
Labels: type: enhancement, unconfirmed
