### ISSUE TITLE
K9 crashes when 15+ folders exist

### ISSUE THREAD

**Issue by k9fmrowner** [thunderbird/thunderbird-android#1065] opened 2016-02-03 19:19 UTC
I have a Samsung Galaxy Note 3, running Android 5.0 and K9 5.007. If I set K9 to pull my IMAP folder list, just 1st class standard folders, everything is fine. If I have it set to 1st and 2nd, which loads between. 15 and 20 folders, K9 always crashes. It's not even downloading the folders' contents, just the folder names themselves at that point.

**Comment by cketti** [comment] 2016-02-03 19:32
Please provide a debug log: https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by rls73** [comment] 2016-03-07 23:16
I have a Samsung Galaxy Note 3, running Android 5.1.1 and K9 5.008.  I have at least two IMAP accounts with greater than 15 folders in them.  I have not experienced this while using both 1st and 2nd class folders.  I will have to see if I can get mine to crash.

**Comment by philipwhiuk** [comment] 2016-04-12 21:32
I have way, way more than 15 folders and can't reproduce this on master. Closing, pending a debug log.

**Closed by philipwhiuk** 2016-04-12 21:32 UTC
Labels: status: needs information
