### ISSUE TITLE
search box closes automatically

### ISSUE THREAD

**Issue by THardi** [thunderbird/thunderbird-android#5967] opened 2022-03-16 10:03 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

5.913

### Where did you get the app from?

Google Play

### Android version

9

### Device model

BV9900

### Steps to reproduce

1. Click on search-button at shared inbox or single inbox
2. search box Is going on
3. search box closes
4. Click on search-button at shared inbox or single inbox
5. search box stays

### Expected behavior

Klick and stays.

### Actual behavior

the search field closes automatically with the first click, after the second click it remains and you can search.

**Comment by cketti** [comment] 2022-05-01 17:31
I can't reproduce this. It might be a bug in the Android version of your device.

**Comment by qd-rwsoft** [comment] 2022-05-12 14:50
I got the some issue. I got a OnePlus 8 with Android 11.
I do the some steps like @THardi

**Comment by sfadschm** [comment] 2022-08-25 06:35
Same issue here with

Google Pixel 3a on Android 12
Google Pixel 6a on Android 12/13

I found the behavior to be quite random. Sometimes I can search multiple times without issue, then suddenly the search bar closes. Sometimes it closes after a few ms, sometimes after 0.5-2s.

Restarting the app and/or phone does not solve this issue. Instead, it will usually work again after 2-5mins of waiting time.

The problem with this is, that if one clicks the search icon and enters the search term, but the search bar closes, all input will be interpreted and executed as hotkeys by K-9.

I can send a screen video if that helps.

**Comment by truh** [comment] 2022-08-26 12:26
I think this is a better explanation for the observations I made here  https://github.com/thundernest/k-9/issues/5967

**Closed** 2022-09-12 11:03 UTC
