### ISSUE TITLE
Password not escaped correctly

### ISSUE THREAD

**Issue by drohhyn** [thunderbird/thunderbird-android#1015] opened 2016-01-10 16:22 UTC
Hallo,

I've justed change the password for an IMAP Mail already used in k-9. My new password was generated by a password manager and contained several special characters. Updating it in k-9 led to errors - both in incoming and outgoing mails. After trying different new password, it seems like "§" is the one char which causes problems.

Kind regards,
  drohhyn

---
### Expected behaviour

Password is updated and login to server is possible.
### Actual behaviour

Password is updated and login is not possible (Auth failed)
### Steps to reproduce
1. Change password on existing account with a password containing "§".
### Environment

K-9 Mail version: 5.007 (James Bond Version :D)

Android version: 6.0.1
Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2016-01-13 07:47
Are you sure it's an encoding issue in K-9 Mail? Does the password containing "§" work with other IMAP/SMTP clients? Maybe it's a server issue.

If you're sure it's an issue with K-9 Mail please let us know what authentication mechanism you are using. It would also be helpful to know what software the mail servers are running.

**Comment by drohhyn** [comment] 2016-01-18 11:14
Not absolutely sure, but the password worked with Thunderbird without problems. I've tried several passwords, only those with "§" where rejected.

The settings in K-9 are:
Security: SSL/TLS (STARTTLS for smtp)
Port: 993
Auth: Password, normal

I don't know the server's software as the system is not hosted by myself.

**Comment by icbator** [comment] 2016-09-20 21:48
I have the same issue with special characters, can't figure it out why I get "authentication failed"
with #$% in the password

k9 5.010
Android 4.4.2

**Comment by snackiz** [comment] 2017-01-25 11:59
I have the same problem with passwords containing swedish characters, such as Å, Ä, Ö, å, ä, ö.

**Comment by yankee42** [comment] 2021-05-12 08:00
Same here. With K-9 Mail Office365 would not work. I had "$" and German Umlauts "ä" and "ö" in my password. The password was working absolutely fine with Thunderbird. However with K-9 Mail I always got `response: #3# [NO, LOGIN failes.]`. After numerous attempts and trying to Google something I eventuelly just tried to change the password so it does not contain special chars. Who knows, maybe it is an encoding problem... And this indeed fixed the problem.

**Comment by cketti** [comment] 2021-05-14 22:19
@yankee42: Which authentication mechanism did you use? "Normal password" or "Encrypted password"?

**Comment by yankee42** [comment] 2021-05-15 12:31
> @yankee42: Which authentication mechanism did you use? "Normal password" or "Encrypted password"?

"Normal Password"

**Comment by DC7IA** [comment] 2022-02-02 17:43
I have issues with a password containing ASCII characters (no control characters, though, lol) which works on other clients, but K-9 mail seems to do weird things and then tells me the password is wrong. It definitely isn't. I've checked 17 times.

**Comment by cketti** [comment] 2022-02-02 20:05
Please enable "log sensitive information" and record a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**IMPORTANT**: This log will include your password. Please change it before attaching the log to this issue. Otherwise people will be able to extract your password from the log and connect to your server to read/delete/change your emails.

**Comment by DC7IA** [comment] 2022-02-15 11:56
> it seems like "§" is the one char which causes problems.

Yup. Seems like that's the problem.

**Comment by cketti** [comment] 2022-02-15 14:36
With sensitive debug logging enabled the command used for authentication together with an encoded version of your username/password is logged. Of course this won't fix your problem. But if you post that part of the log here, I have a chance to check whether or not K-9 Mail is properly encoding your password. And if it is not, I can see what went wrong exactly.

**Comment by DC7IA** [comment] 2022-02-17 15:19
As I said, the log does contain exactly the same as any other attempt at a connection. The only difference that I get told that the "Authentication failed".

**Comment by cketti** [comment] 2022-04-30 22:33
Closing this because nobody provided the information necessary to diagnose the problem. If anyone else encounters this behavior, please open a new issue and make sure to provide a debug log with sensitive logging enabled. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**IMPORTANT:** Enabling *General settings → Logging → Log sensitive information* in K-9 Mail will include your password in the log. Please change it before attaching the log to this issue. Otherwise people will be able to extract your password from the log and connect to your server to read/delete/change your emails.

**Closed by cketti** 2022-04-30 22:33 UTC
Labels: status: needs information

**Comment by cketti** [comment] 2022-05-02 14:30
I've detailed in a comment why the log is important. You've decided the log doesn't contain any important information to diagnose the error and didn't provide the information I asked for. If you're so sure of your capabilities why not provide a fix? We happily accept pull requests that fix bugs.

**Comment by ErikKrause** [comment] 2022-10-16 19:01
> You've decided the log doesn't contain any important information to diagnose the error and didn't provide the information I asked for.

@cketti 
Here is a log which contains the auth error from the password `12praxis§` (test account, already deleted)
[k9mail-logs-1.txt](https://github.com/thundernest/k-9/files/9795465/k9mail-logs-1.txt)

Please re-open the issue, now you have the requested log.

**Comment by cketti** [comment] 2022-10-16 19:22
@ErikKrause: The password that was sent to the server was "12praxis12". That certainly explains why it didn't work for you. However, I can't reproduce this behavior. When I enter "12praxis§" as a password, it is properly encoded and the expected data is sent to the server. It is not transmitted as "12praxis12" for me.

**Comment by ErikKrause** [comment] 2022-10-16 19:46
12praxis12 was the first attempt (to verify the mail server works), see the second attempt at 10-16 20:50:35.487

**Comment by cketti** [comment] 2022-10-16 19:59
Apologies. In the second attempt everything looks like it should.

```shell
$ echo "AHRlc3RAbXVlaGxiYWNoLXByYXhpcy11bWtpcmNoLmRlADEycHJheGlzwqc=" | base64 -d | hexdump -C
00000000  00 74 65 73 74 40 6d 75  65 68 6c 62 61 63 68 2d  |.test@muehlbach-|
00000010  70 72 61 78 69 73 2d 75  6d 6b 69 72 63 68 2e 64  |praxis-umkirch.d|
00000020  65 00 31 32 70 72 61 78  69 73 c2 a7              |e.12praxis..|
0000002c
```

The password is correctly encoded using UTF-8. If your provider doesn't accept this, it's most likely a bug on their end.

**Comment by ErikKrause** [comment] 2022-10-16 20:02
Well, why then does it work with thunderbird? I contacted the mail provider, and they said the mail server is well capable of accepting UTF-8 encoded special characters, including the §

**Comment by drohhyn** [comment] 2022-10-16 20:07
> The password is correctly encoded using UTF-8. If your provider doesn't accept this, it's most likely a bug on their end.
Hm, that was already stated in the second comment: works with thunderbird (or evolution mail) without problems. So the mail server is capable of handling the request.

**Comment by cketti** [comment] 2022-10-16 20:34
If someone can provide the network traffic from an app where authentication works, we might have a chance to figure out what's going on.

**Comment by ErikKrause** [comment] 2022-10-16 21:09
Just a wild guess: Could it be the §-character needs to be escaped? See https://www.ndchost.com/wiki/mail/test-smtp-auth-telnet

**Comment by cketti** [comment] 2022-10-16 21:14
K-9 Mail is using `AUTH PLAIN` when possible (that's also what your log contains). The relevant specification is [RFC 4616](https://www.rfc-editor.org/rfc/rfc4616).

**Comment by yankee42** [comment] 2022-10-17 16:39
I tested like this:
```bash
swaks -raw --to sometest@cipher-code.de --from sometest@cipher-code.de --auth PLAIN --auth-user sometest@cipher-code.de --auth-password "12praxis§" --server mail.cipher-code.de:587
```
What I believe is the relavant section of the output:
```
<~  250-PIPELINING
<~  250-8BITMIME
<~  250-SMTPUTF8
<~  250-SIZE 26214400
<~  250 AUTH PLAIN LOGIN
 ~> AUTH PLAIN AHNvbWV0ZXN0QGNpcGhlci1jb2RlLmRlADEycHJheGlzwqc=
  > 0000: 41 55 54 48  20 50 4C 41  49 4E 20 41  48 4E 76 62    AUTH.PLAIN.AHNvb
  > 0016: 57 56 30 5A  58 4E 30 51  47 4E 70 63  47 68 6C 63    WV0ZXN0QGNpcGhlc
  > 0032: 69 31 6A 62  32 52 6C 4C  6D 52 6C 41  44 45 79 63    i1jb2RlLmRlADEyc
  > 0048: 48 4A 68 65  47 6C 7A 77  71 63 3D 0D  0A             HJheGlzwqc=..   
<   0000: 32 33 35 20  32 2E 37 2E  30 20 41 75  74 68 65 6E    235.2.7.0.Authen
<   0016: 74 69 63 61  74 69 6F 6E  20 73 75 63  63 65 73 73    tication.success
<   0032: 66 75 6C 0D  0A                                       ful..           
```

**Comment by cketti** [comment] 2022-10-17 16:44
```shell
$ echo "AHNvbWV0ZXN0QGNpcGhlci1jb2RlLmRlADEycHJheGlzwqc=" | base64 -d | hexdump -C
00000000  00 73 6f 6d 65 74 65 73  74 40 63 69 70 68 65 72  |.sometest@cipher|
00000010  2d 63 6f 64 65 2e 64 65  00 31 32 70 72 61 78 69  |-code.de.12praxi|
00000020  73 c2 a7                                          |s..|
00000023
```

That looks identical to what K-9 Mail is doing.

**Comment by yankee42** [comment] 2022-10-17 16:53
> That looks identical to what K-9 Mail is doing.

It is. Yes. I posted to fast, sorry. Unfortunately I have no SMTP Access to office365 anymore, so I cannot test there. So I just made this test with another mail server expecting it would be the same. However you are right. I just also tested this with K-9 mail and there it works fine, too!

So it is obviously Server dependent. However, maybe someone else who has access to such a broken server can test with swaks as well...

**Comment by cketti** [comment] 2022-10-17 17:03
This should no longer be an issue with Office365 since they stopped supporting password authentication. See https://learn.microsoft.com/en-us/exchange/clients-and-mobile-in-exchange-online/deprecation-of-basic-authentication-exchange-online
