### ISSUE TITLE
sslhandshakeexception 0x7dbd768006  I/O error

### ISSUE THREAD

**Issue by liar666** [thunderbird/thunderbird-android#7208] opened 2023-09-29 15:26 UTC
### Checklist

- [X] I have used the search function to see if someone else has already submitted the same bug report.
- [X] I will describe the problem with as much detail as possible.

### App version

6.602

### Where did you get the app from?

Google Play

### Android version

8.1.0

### Device model

N10

### Steps to reproduce

Hi,

Starting a few days ago, I started to get strange errors when sending email for one (of the 3) accounts I have configured in K9.

The error I get is:
```
SSLHandshakeException: SSL handshake aborted: ssl=0x7dbd768006:  I/O error during system call, Connection reset by peer
```
Sometimes the value is `0x7dc19decc0`.

It happens when I'm connected through my 4G connection, but works perfectly with a Wifi connection. 

So I thought it was a problem with my operator(*). But then I tried with another account (which has the same SSL/TLS/port config), and I can send email with this other account.

So I'm quite lost... Since I upgraded K9 and changed operator almost at the same time a few weeks ago, I'm not sure where the problem is...

### Expected behavior

Email shoul be sent lawlessly

### Actual behavior

With one of the accounts, email show an Exception.

### Logs

The error I get is:
```
SSLHandshakeException: SSL handshake aborted: ssl=0x7dbd768006:  I/O error during system call, Connection reset by peer
```
Sometimes the value is `0x7dc19decc0`.

**Comment by cketti** [comment] 2023-10-01 15:08
It's unlikely that this is a bug in K-9 Mail because we use the TLS implementation provided by the Android version on the device. However, if it works on one network but not another, it's probably not a bug in your Android version either.

It's possible that your mobile network provider is somehow filtering the network traffic. It's also possible that the email provider is blocking connections from the mobile network.

I don't think there's a change we can make to K-9 Mail to make it easier to track down these kind of errors. So I'm closing this issue.

**Closed by cketti** 2023-10-01 15:08 UTC
