### ISSUE TITLE
K9 crashes on start after Androidupdate

### ISSUE THREAD

**Issue by HDValentin** [thunderbird/thunderbird-android#4592] opened 2020-03-06 12:02 UTC
### Expected behavior
The app should work as before.

### Actual behavior
When I open the app it crashes and closes several times.

### What changed?
I've installed the security update for my shiftphone.
It is the security update for the wireless lan chip issue.

### Steps to reproduce
1. Open the app
2. crashes
3. reopen it, and it crashes again

### Environment
K-9 Mail version: 5.705 and 5.600 happens on both 

Android version: 8.0.0
Shiftphone SHIFT6M.SOS.1.1.G.20200214

Account type (IMAP, POP3, WebDAV/Exchange): IMAP

**Comment by cketti** [comment] 2020-03-06 14:21
Please provide a debug log. See https://github.com/k9mail/k-9/wiki/LoggingErrors

**Comment by HDValentin** [comment] 2020-03-08 14:48
Today it happens no more.
This is a bit crazy.

**Comment by HDValentin** [comment] 2020-03-09 06:05
If it workes today also, I am going to close this issue.

**Comment by HDValentin** [comment] 2020-03-11 13:20
The problem is back since yesterday. I can't enable debugging, because because the app crashes on everey start. should I log via MTK logging?

**Comment by cketti** [comment] 2020-03-11 14:54
Quote from https://github.com/k9mail/k-9/wiki/LoggingErrors
> If K-9 is crashing or you otherwise can't get to the settings screen, don't worry about about enabling debug logs.

**Comment by BernhardWerder** [comment] 2020-03-17 09:04
I have exactly the same problem as HDValentin. Whenever I try to open the K9 app since the Shiftphone Update, I get the message that the app has been closed. The first time it gets reopened, but then it closes once again. I simply can't acces it any more, so debugging is also not possible.
Is there going to be an update to K9 soon or does it make sense to try newer beta versions?

**Comment by BernhardWerder** [comment] 2020-03-18 18:52
Meanwhile I also tried the most recent Beta version, but the crash happens in the same way; no difference unfortunately.

**Comment by Rubylion** [comment] 2020-03-19 10:08
Same Problem. App can't be opened. crashes

Hi. I'm on:
LineageOS 14.1 (Android7.1 respectivetly)

K9 5.600 works without problems. But 5.7x crashes imideatley after openening the app. Bug report says: can't access SQL library.
I checked about permissions in app-settings and the permissiom for accessing the storage is gone. So I think this could be the cause of the problem.
Here's the bug report: 

android.database.sqlite.SQLiteCantOpenDatabaseException: unknown error (code 14): Could not open database
	at android.database.sqlite.SQLiteConnection.nativeOpen(Native Method)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:209)
	at android.database.sqlite.SQLiteConnection.open(SQLiteConnection.java:193)
	at android.database.sqlite.SQLiteConnectionPool.openConnectionLocked(SQLiteConnectionPool.java:463)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:185)
	at android.database.sqlite.SQLiteConnectionPool.open(SQLiteConnectionPool.java:177)
	at android.database.sqlite.SQLiteDatabase.openInner(SQLiteDatabase.java:808)
	at android.database.sqlite.SQLiteDatabase.open(SQLiteDatabase.java:793)
	at android.database.sqlite.SQLiteDatabase.openDatabase(SQLiteDatabase.java:696)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:711)
	at android.database.sqlite.SQLiteDatabase.openOrCreateDatabase(SQLiteDatabase.java:704)
	at com.fsck.k9.mailstore.LockableDatabase.doOpenOrCreateDb(LockableDatabase.java:400)
	at com.fsck.k9.mailstore.LockableDatabase.openOrCreateDataspace(LockableDatabase.java:380)
	at com.fsck.k9.mailstore.LockableDatabase.open(LockableDatabase.java:356)
	at com.fsck.k9.mailstore.LocalStore.<init>(LocalStore.java:213)
	at com.fsck.k9.mailstore.LocalStore.createInstance(LocalStore.java:187)
	at com.fsck.k9.mailstore.LocalStoreProvider.getInstance(LocalStoreProvider.kt:22)
	at com.fsck.k9.provider.EmailProvider.getDatabase(EmailProvider.java:535)
	at com.fsck.k9.provider.EmailProvider.getThreadedMessages(EmailProvider.java:340)
	at com.fsck.k9.provider.EmailProvider.query(EmailProvider.java:237)
	at android.content.ContentProvider.query(ContentProvider.java:1020)
	at android.content.ContentProvider$Transport.query(ContentProvider.java:239)
	at android.content.ContentResolver.query(ContentResolver.java:534)
	at android.content.ContentResolver.query(ContentResolver.java:475)
	at com.fsck.k9.ui.messagelist.MessageListLoader.loadMessageListForAccount(MessageListLoader.kt:114)
	at com.fsck.k9.ui.messagelist.MessageListLoader.getMessageList(MessageListLoader.kt:41)
	at com.fsck.k9.ui.messagelist.MessageListLiveData$loadMessageListAsync$1$1.invokeSuspend(MessageListLiveData.kt:33)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)

**Comment by cketti** [comment] 2020-03-20 23:56
@Rubylion: This is odd. I'm blaming LineageOS. Try uninstalling, then reinstalling.

Closing this issue, since no actionable information was provided on the original bug.

**Closed by cketti** 2020-03-20 23:56 UTC
Labels: status: needs information
