### ISSUE TITLE
Message are not marked as read on the server.

### ISSUE THREAD

**Issue by layus** [thunderbird/thunderbird-android#4842] opened 2020-06-19 14:31 UTC
Similar to #3516, which was closed without further info from the OP.

### Expected behavior
The message should be marked as read in the server when read in k9.

### Actual behavior
It does not work. Actually, the read status seams read-only in k9. Curiously, they are marked as read in k9 for some time, but get back to their (server-side) status of unread after a while. Marking a read email as unread does not work either.

### Steps to reproduce
1. Open an unread message.
2. Come back later (or use a different client)
3. The email is not marked as read.
4. also works when explicitly marking message as read/unread with the button on top of the email.

### Environment
K-9 Mail version: 5.716 (f-droid)

Android version: 9

Account type: IMAP

Logs: https://gist.github.com/layus/b7e955818fb3fa6cd0961f0ff5388902
In the two trials, I took the log right after opening an unread email (which should mark it as read) then marked it as unread, then read again using the ad-hoc button at the top of the interface.

**Comment by cketti** [comment] 2020-06-19 17:17
There's a failing command stuck in the "pending commands" queue (see #4450). It prevents further commands (like "mark as read") from being sent to the server. The local change will be overwritten once the folder is synced with the server.

In your case this is caused by failing to upload a message that is too large. Presumably you tried to send it and after getting an error notification deleted it from K-9 Mail's Outbox folder. This will attempt to upload the message to the Trash folder.

```
>>> 41 APPEND "[Gmail]/Corbeille" (\Seen) {54434552}
<<<#41# [BAD, [TOOBIG], Message too large. https://support.google.com/mail/answer/6584#limit]
```

Duplicate of #4622

**Closed by cketti** 2020-06-19 17:17 UTC

**Comment by layus** [comment] 2020-06-19 19:59
Whoaaa. Quick reply and easy fix ! Thanks :-).

**Comment by cketti** [comment] 2020-06-19 20:44
K-9 Mail 5.717 contains a fix for this.

**Comment by layus** [comment] 2020-06-19 21:02
An a release :-). Thank you so much !
